### ISSUE TITLE
opensuse TW - ERROR: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

### ISSUE THREAD

**Issue by Soyasi** [waydroid/waydroid#1046]
**Describe the bug**
ERROR: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

**General information (please complete the following information):**
 [waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1691212643
vendor_datetime = 1691234448
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = anbox-binder
vndbinder = anbox-vndbinder
hwbinder = anbox-hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3
[properties]

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 20.04 x64]
 - GPU: [ Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    driver: amdgpu v: kernel]
 - Kernel version: [ 6.4.8-1-default]
 - Host mesa version: [ API: OpenGL v: 4.6 Mesa 23.1.5 renderer: AMD Radeon RX 580 Series
    (polaris10 LLVM 16.0.6 DRM 3.52 6.4.8-1-default)]
 - Desktop: [plasma 5.27.7 Xwayland]

**Additional context**

**Logs (please upload as file)**
/var/lib/waydroid/**waydroid_base.prop**
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=radeon
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.1
ro.vndk.lite=true

/var/lib/waydroid/**waydroid.prop**
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=radeon
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.1
ro.vndk.lite=true
waydroid.host.user=soyasi
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/soyasi/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-0
waydroid.background_start=false
waydroid.stub_sensors_hal=1

**waydroid log**
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(008424) [00:26:04] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(008424) [00:26:04] *** output passed to waydroid stdout, not to this log ***
(009491) [00:40:37] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(017039) [00:40:37] Waiting for binder Service Manager...
(017039) [00:41:37] Service Manager never appeared
(017039) [00:41:37] Failed to access IPlatform service
(018349) [00:43:21] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(018349) [00:43:21] WayDroid container is STOPPED
(019793) [00:46:03] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(019793) [00:46:03] WayDroid container is STOPPED
(025598) [00:54:03] Starting waydroid session
(025598) [00:54:03] ERROR: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
(025598) [00:54:03] See also: <https://github.com/waydroid>
(025598) [00:54:03] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 64, in maybeLaunchLater
    tools.helpers.ipc.DBusSessionService()
  File "/usr/lib/waydroid/tools/helpers/ipc.py", line 44, in DBusSessionService
    return dbus.Interface(dbus.SessionBus().get_object("id.waydro.Session", object_path), intf)
                          ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/_dbus.py", line 209, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/_dbus.py", line 99, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 120, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 130, in main
    actions.app_manager.showFullUI(args)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 132, in showFullUI
    maybeLaunchLater(args, justShow)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 72, in maybeLaunchLater
    tools.actions.session_manager.start(args, launchNow, background=False)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
                                                     ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/_dbus.py", line 209, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/_dbus.py", line 99, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 120, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.

(029422) [01:01:35] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(029422) [01:01:35] *** output passed to waydroid stdout, not to this log ***

**waydroid logcat**
[01:03:47] WayDroid container is STOPPED

 - Output of `**dmesg**`
[ 8970.767003] binder_linux: 13152:13621 transaction failed 29189/-22, size 0-0 line 2987
[ 8971.533137] binder_linux: 9491:9491 transaction failed 29189/-22, size 0-0 line 2987
[ 8971.768045] binder_linux: 13152:13621 transaction failed 29189/-22, size 0-0 line 2987
[ 8972.534175] binder_linux: 9491:9491 transaction failed 29189/-22, size 0-0 line 2987
[ 8972.768763] binder_linux: 13152:13621 transaction failed 29189/-22, size 0-0 line 2987
[ 8973.535213] binder_linux: 9491:9491 transaction failed 29189/-22, size 0-0 line 2987
[ 8973.769807] binder_linux: 13152:13621 transaction failed 29189/-22, size 0-0 line 2987
[ 8974.535427] binder_linux: 9491:9491 transaction failed 29189/-22, size 0-0 line 2987

**systemctl status waydroid-container**
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled; preset: disabled)
     Active: active (running) since Wed 2023-08-09 23:32:22 WEST; 1h 35min ago
   Main PID: 9491 (waydroid)
      Tasks: 5 (limit: 4915)
        CPU: 538ms
     CGroup: /system.slice/waydroid-container.service
             └─9491 /usr/bin/python3 /usr/bin/waydroid -w container start

ago 09 23:34:59 localhost.localdomain dnsmasq[13207]: opciones de compilación: IPv6 GNU-getopt DBus no-UBus i18n IDN2 DHCP DHCPv6 Lua TFTP conntrack ipset no-nftset auth cryptohash DNSSEC loop-detect inotify dumpfile
ago 09 23:34:59 localhost.localdomain dnsmasq-dhcp[13207]: DHCP, IP range 192.168.240.2 -- 192.168.240.254, tiempo de concesión1h
ago 09 23:34:59 localhost.localdomain dnsmasq-dhcp[13207]: DHCP, sockets bound exclusively to interface waydroid0
ago 09 23:34:59 localhost.localdomain dnsmasq[13207]: leyendo /etc/resolv.conf
ago 09 23:34:59 localhost.localdomain dnsmasq[13207]: usando nombre de servidor 8.8.8.8#53
ago 09 23:34:59 localhost.localdomain dnsmasq[13207]: usando nombre de servidor 8.8.4.4#53
ago 09 23:34:59 localhost.localdomain dnsmasq[13207]: read /etc/hosts - 10 names
ago 09 23:34:59 localhost.localdomain waydroid[9491]: [23:34:59] waiting 10 seconds for container to start...
ago 09 23:35:00 localhost.localdomain waydroid[9491]: [23:35:00] waiting 9 seconds for container to start...
ago 10 00:39:01 localhost.localdomain systemd[1]: Started Waydroid Container.

**waydroid first-launch**
[01:08:37] Starting waydroid session
[01:08:37] ERROR: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
[01:08:37] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.

I think it's the same problem that's described here.
[https://github.com/waydroid/waydroid/issues/854]

**Comment by xSavian** [comment]
Hello. Have you solved this issue? I have similar issue

**Comment by TomuraCreator** [comment]
Hi. Me too

**Comment by Thiago-Mota-Santos** [comment]
me too lol

**Comment by dontknowhy** [comment]
![image](https://github.com/waydroid/waydroid/assets/85813508/d2b49ab9-5ba9-467d-8adf-ef03f2d5ee4c)
lol, A Chinese website tells us that we can't run this as root.
Are you rooted?

**Comment by bastian-zab** [comment]
How do I solve this without restarting

**Comment by Alexandr71001** [comment]
`export $(dbus-launch)` worked for me

**Comment by caoanhhao** [comment]
> export $(dbus-launch)

worked for me too. thanks [Alexandr71001](https://github.com/Alexandr71001).
