### ISSUE TITLE
Apps being killed immediately if executing `waydroid app launch` before starting a session

### ISSUE THREAD

**Issue by w568w** [waydroid/waydroid#1066]
**Describe the bug**
Most apps being killed immediately if I execute `waydroid app launch <PKG_NAME>` before starting a session manually with `waydroid session start`.

To be exact:

1. Run `waydroid session stop` to ensure that the session had been killed;
2. Run `waydroid app launch com.hypergryph.arknights`;
3. In several seconds, a window shows up, but then disappear after ~100ms;
4. Nothing happens after that. `waydroid status` says:
```
$ waydroid status
Session:        RUNNING
Container:      FROZEN
Vendor type:    MAINLINE
IP address:     192.168.240.112
Session user:   w568w(1000)
Wayland display:        wayland-0
```

On the other hand:

1. Run `waydroid session start` to ensure that the session had been started up; **wait until `Android with user 0 is ready` printed**;
2. Run `waydroid app launch com.hypergryph.arknights`;
3. A window shows up, and the app runs normally.

**General information (please complete the following information):**
 - Waydroid tools Version 1.4.1
 - Waydroid Images Version `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`: 1692422331 / 1692444077

**Desktop (please complete the following information):**
 - OS: Archlinux x86_64
 - GPU: AMD Ryzen 7 4800H with iGPU
 - Kernel version: 6.4.12-x64v2-xanmod1-1 (it happens on Linux mainline kernel 6.4.12 with binder patches, too)
 - Host mesa version: mesa 23.1.6
 - Desktop: KDE Plasma 5.27.7

**Additional context**
I can confirm that the application had been killed by `ActivityManager` as soon as the app initializes, which claimed that the app had started up too many empty processes without components:

```
08-26 15:15:17.252   272   735 I ActivityManager: Killing 1071:com.hypergryph.arknights/u0a140 (adj 985): empty #17
```

I compared two logcat files, and found that an exception only occurs when killing:

```
08-26 15:15:16.286   489   700 W PluginManagerImpl: Cannot get class loader for non-whitelisted plugin. Src:/system/app/BoringdroidSystemUIApk/BoringdroidSystemUIApk.apk, pkg: com.boringdroid.systemui
08-26 15:15:16.287   272   650 E BoringdroidConfig: Don't save package windowing mode when pc mode disabled
08-26 15:15:16.290   272   649 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10134; state: DISABLED
08-26 15:15:16.291   489   700 W PluginInstanceManager: Couldn't load plugin: com.boringdroid.systemui
08-26 15:15:16.291   489   700 W PluginInstanceManager: java.lang.ClassNotFoundException: com.boringdroid.systemui.SystemUIOverlay
08-26 15:15:16.291   489   700 W PluginInstanceManager: 	at java.lang.Class.classForName(Native Method)
08-26 15:15:16.291   489   700 W PluginInstanceManager: 	at java.lang.Class.forName(Class.java:454)
08-26 15:15:16.291   489   700 W PluginInstanceManager: 	at com.android.systemui.shared.plugins.PluginInstanceManager$PluginHandler.handleLoadPlugin(PluginInstanceManager.java:350)
08-26 15:15:16.291   489   700 W PluginInstanceManager: 	at com.android.systemui.shared.plugins.PluginInstanceManager$PluginHandler.handleQueryPlugins(PluginInstanceManager.java:315)
08-26 15:15:16.291   489   700 W PluginInstanceManager: 	at com.android.systemui.shared.plugins.PluginInstanceManager$PluginHandler.handleMessage(PluginInstanceManager.java:264)
08-26 15:15:16.291   489   700 W PluginInstanceManager: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-26 15:15:16.291   489   700 W PluginInstanceManager: 	at android.os.Looper.loop(Looper.java:223)
08-26 15:15:16.291   489   700 W PluginInstanceManager: 	at android.os.HandlerThread.run(HandlerThread.java:67)
08-26 15:15:16.291   489   700 W PluginInstanceManager: Caused by: java.lang.ClassNotFoundException: com.boringdroid.systemui.SystemUIOverlay
08-26 15:15:16.291   489   700 W PluginInstanceManager: 	... 8 more
```

I cleaned the logcat outputs by hand and these two logs should be more readable:

[readable_logcat_good.log](https://github.com/waydroid/waydroid/files/12444829/readable_logcat_good.log)
[readable_logcat_killed.log](https://github.com/waydroid/waydroid/files/12444830/readable_logcat_killed.log)

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`: [waydroid.prop.txt](https://github.com/waydroid/waydroid/files/12444825/waydroid.prop.txt)
 - Log file, located at `/var/lib/waydroid/waydroid.log`: TOO BIG TO UPLOAD (~0.5 GB!)
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running: [logcat_killed.log](https://github.com/waydroid/waydroid/files/12444826/logcat_killed.log) [logcat_not_killed.log](https://github.com/waydroid/waydroid/files/12444827/logcat_good.log) 
 - Output of `dmesg`: [dmesg.log](https://github.com/waydroid/waydroid/files/12444833/dmesg.log)

**Comment by TriMoon** [comment]
> TOO BIG TO UPLOAD (~0.5 GB!)

You should be able to upload a `gzip` version of the logs...
But better would be to just `truncate -s0 /var/lib/waydroid/waydroid.log` and then reproduce to get fresh logs and upload those, i think it will be much smaller that way :wink:

**Comment by w568w** [comment]
> But better would be to just truncate -s0 /var/lib/waydroid/waydroid.log and then reproduce to get fresh logs and upload those, i think it will be much smaller that way 😉

Thanks! I have uploaded the fresh log.

**Comment by XilinJia** [comment]
On Waydroid 1.4.2 on Manjaro KDE Wayland.  

In my case, if I start an app before starting Waydroid session, a full-screen window shows up with some telltale, then the window disappears without starting the app.  I checked with ps and found the Waydroid session has indeed been started.  If I start the app again, it starts.

**Comment by sertonix** [comment]
This line silently fails since `status` isn't checked

https://github.com/waydroid/waydroid/blob/2be58d19ad233e61d5ce1d3c3fbbe38261f783e6/tools/interfaces/IPlatform.py#L184

Adding a 1 second delay works but it's only a hack:
```patch
diff --git a/tools/services/user_manager.py b/tools/services/user_manager.py
index 83a50cc..bd845a6 100644
--- a/tools/services/user_manager.py
+++ b/tools/services/user_manager.py
@@ -3,6 +3,7 @@
 import logging
 import os
 import threading
+import time
 import tools.config
 import tools.helpers.net
 from tools.interfaces import IUserMonitor
@@ -83,6 +84,9 @@ NoDisplay={str(hide).lower()}
                 makeDesktopFile(app)
             multiwin = platformService.getprop("persist.waydroid.multi_windows", "false")
             makeWaydroidDesktopFile(multiwin == "true")
+
+        # HACK: Applications are killed when they are started too early
+        time.sleep(1)
         if unlocked_cb:
             unlocked_cb()
 
```

**Comment by Cornelius-Figgle** [comment]
Any update? I have the same issue where running `waydroid app launch com.mojang.minecraftpe` (with the system service running) opens the LineageOS loading screen, this then disappears and the terminal just says "Android with user 0 is ready". However, if I run `waydroid session start`, wait for the "Android with user 0 is ready" message to appear, and then run the app launch from another terminal it opens Minecraft straight away

**Comment by TobiKuik** [comment]
Exact same issue here.

**Comment by toazd** [comment]
This is still a problem almost 2yrs later. The app opens up normally if `waydroid session start` is run before launching the app. Not sure what to do about it. I'm using waydroid on a 2-in-1 touchscreen and when in tablet mode I have to launch the app twice to get it to work as expected. I don't always want the waydroid session running or else I would launch it at startup after the container service.

@sertonix 's hack above still works fine (thank you!) but I'm guessing I'll have to redo the hack every time waydroid updates.

And here is a brief recording of what it looks like:
https://github.com/user-attachments/assets/f56005eb-1959-4afa-8c3a-1cb1aa19e5fa

Here is what `waydroid.log` looks like after running `waydroid session stop; sudo systemctl restart waydroid-container; sudo truncate -s0 /var/lib/waydroid/waydroid.log` and then attempting to launch an app via `waydroid app launch` (the session starts, the app opens and then immediately closes):

> (072691) [14:53:40] Starting waydroid session
(072597) [14:53:40] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(072597) [14:53:40] % systemctl is-active -q nfcd
(072597) [14:53:40] % chmod 777 -R /dev/dri/renderD128
(072597) [14:53:40] % chmod 777 -R /dev/fb0
(072597) [14:53:40] % chmod 777 -R /dev/video3
(072597) [14:53:40] % chmod 777 -R /dev/video2
(072597) [14:53:40] % chmod 777 -R /dev/video1
(072597) [14:53:40] % chmod 777 -R /dev/video0
(072597) [14:53:40] % chmod 777 -R /dev/dma_heap/system
(072597) [14:53:40] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(072597) [14:53:40] % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(072597) [14:53:40] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(072597) [14:53:40] % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(072597) [14:53:40] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(072597) [14:53:40] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(072597) [14:53:40] Save config: /var/lib/waydroid/waydroid.cfg
(072597) [14:53:40] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(072597) [14:53:40] New background process: pid=72737, output=background
(072597) [14:53:40] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(072691) [14:53:49] waydroidusermonitor: Received transaction: 1
(072691) [14:53:49] Android with user 0 is ready
