### ISSUE TITLE
Container fails to start (lxc-start: Out of memory)

### ISSUE THREAD

**Issue by CybergoreDali** [waydroid/waydroid#108]
When i start the waydroid container, it exits with a message about running out of memory. 

I'm trying to run waydroid on postmarketOS on the pinephone, it is running the wayland version of sxmo (swmo).

```
$ uname -a
Linux hostname 5.14.1 #2-postmarketos-allwinner SMP PREEMPT Mon Sep 13 18:40:42 UTC 20 aarch64 GNU/Linux
```

I followed the instructions for installing and running Waydroid from [the pmOS wiki](https://wiki.postmarketos.org/index.php?title=Waydroid).

For debugging purposes, I removed the rc-service from the default runlevel and [started the container and session manually](https://docs.waydro.id/usage/install-on-desktops#manually-starting-waydroid) with `sudo waydroid container start` and `waydroid session start`.
Once I start the session I get the following output from `waydroid log`:

```
$ waydroid log
(003837) [13:02:09] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(003837) [13:02:09] *** output passed to waydroid stdout, not to this log ***
(004081) [13:02:48] % sudo chmod 666 -R /dev/binder
(004081) [13:02:48] % sudo chmod 666 -R /dev/vndbinder
(004081) [13:02:48] % sudo chmod 666 -R /dev/hwbinder
(004081) [13:02:48] Container manager is waiting for session to load
(004081) [13:02:48] % sudo /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(004081) [13:02:48] % sudo waydroid-sensord /dev/hwbinder
(004081) [13:02:48] New background process: pid=4148, output=background
(004081) [13:02:48] % sudo mount /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
sudo: waydroid-sensord: command not found
(004081) [13:02:48] % sudo mount -o remount,ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(004081) [13:02:48] % sudo mount /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(004081) [13:02:49] % sudo mount -o remount,ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(004081) [13:02:49] % sudo mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(004081) [13:02:49] % sudo mount -o bind /home/max/waydroid/data /var/lib/waydroid/data
(004081) [13:02:49] % sudo chmod 777 -R /dev/ashmem
(004081) [13:02:49] % sudo chmod 777 -R /dev/dri
(004081) [13:02:49] % sudo chmod 777 -R /dev/fb0
(004081) [13:02:49] % sudo lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(004081) [13:02:49] New background process: pid=4201, output=background
lxc-start: waydroid: cgroups/cgfsng.c: initialize_cgroups: 3381 Out of memory - Failed to initialize cgroups
lxc-start: waydroid: cgroups/cgroup.c: cgroup_init: 35 Bad file descriptor - Failed to initialize cgroup driver
lxc-start: waydroid: start.c: lxc_init: 872 Failed to initialize cgroup driver
lxc-start: waydroid: start.c: __lxc_start: 1987 Failed to initialize container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 996 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and
--logpriority options
(004081) [13:02:49] waiting 10 seconds for container to start...
(004081) [13:02:50] waiting 9 seconds for container to start...
(004081) [13:02:51] waiting 8 seconds for container to start...
(004081) [13:02:52] waiting 7 seconds for container to start...
(004081) [13:02:53] waiting 6 seconds for container to start...
(004081) [13:02:54] waiting 5 seconds for container to start...
(004081) [13:02:55] waiting 4 seconds for container to start...
(004081) [13:02:56] waiting 3 seconds for container to start...
(004081) [13:02:57] waiting 2 seconds for container to start...
(004081) [13:02:58] waiting 1 seconds for container to start...
(004081) [13:02:59] ERROR: container failed to start
(004081) [13:02:59] See also: <https://github.com/waydroid>
(004081) [13:02:59] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 158, in start
    raise OSError("container failed to start")
OSError: container failed to start
```

```
$ waydroid status
Session:        RUNNING
Container:      STOPPED
Vendor type:    MAINLINE
Session user:   max(10001)
Wayland display:        wayland-1
```

```
$ dmesg
...
[Sep27 13:02] Module has invalid ELF structures
[  +0.004479] Module has invalid ELF structures
[  +0.020228] Module has invalid ELF structures
[  +0.044347] bridge: filtering via arp/ip/ip6tables is no longer available by default. Update your scripts to load br_netfilter if you need this.
[  +0.127218] Module has invalid ELF structures
[  +0.111029] Module has invalid ELF structures
[  +0.078977] loop0: detected capacity change from 0 to 2894088
[  +0.148925] EXT4-fs (loop0): mounted filesystem without journal. Opts: (null). Quota mode: none.
[  +0.050845] EXT4-fs (loop0): re-mounted. Opts: (null). Quota mode: none.
[  +0.045636] loop1: detected capacity change from 0 to 256784
[  +0.149884] EXT4-fs (loop1): mounted filesystem without journal. Opts: (null). Quota mode: none.
[  +0.031994] EXT4-fs (loop1): re-mounted. Opts: (null). Quota mode: none.
```

The output of `free` on the host machine:
``` 
$ free
              total        used        free      shared  buff/cache   available
Mem:        3067056      142624     2716844       15468      207588     2840320
Swap:       2097148           0     2097148
```
It seems like there should be enough free memory for the container to start.

I've tried reinstalled waydroid following [these instructions](https://docs.waydro.id/usage/install-on-desktops#reinstalling-waydroid) and have also tried rebooting.

Ideas? Thanks!

EDIT: Added output of `waydroid status`.

**Comment by clangdo** [comment]
I too get an error like this, mine is very similar, but not quite the same. My hardware is also the PP, and I'm also running postmarketOS (edge).

The one difference for me is the line number for the error's origin, which in my case is 3359, not 3381. This difference in line number may be a question of version, mines `1.2.0`, my package on postmarketOS is marked as `waydroid-1.2.0-r3`.

Note that postmarketOS is based on alpine and is therefore probably linking against the musl libc in this case, so there could be problems there. I've looked over the function where the error is thrown, but it's quite a long and highly nested implementation function for doing cgroup init, so it's a little above my head.

My logs are here.
```
(013236) [13:44:18] Save session config: /var/lib/waydroid/session.cfg
(013236) [13:44:18] UserMonitor service is not even started
(013236) [13:44:18] Clipboard service is not even started
(013236) [13:44:26] UserMonitor service is not even started
(013236) [13:44:26] Clipboard service is not even started
(013316) [13:44:34] Save session config: /var/lib/waydroid/session.cfg
(013316) [13:44:34] UserMonitor service is not even started
(013316) [13:44:34] Clipboard service is not even started
(013383) [13:44:39] % chmod 666 -R /dev/binder
(013383) [13:44:39] % chmod 666 -R /dev/vndbinder
(013383) [13:44:39] % chmod 666 -R /dev/hwbinder
(013383) [13:44:39] Container manager is waiting for session to load
(013383) [13:44:39] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
waydroid-net is already running
(013383) [13:44:39] % mount /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(013383) [13:44:39] % mount -o remount,ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(013383) [13:44:39] % mount /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(013383) [13:44:39] % mount -o remount,ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(013383) [13:44:39] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(013383) [13:44:39] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(013383) [13:44:39] % chmod 777 -R /dev/ashmem
(013383) [13:44:39] % chmod 777 -R /dev/dri
(013383) [13:44:39] % chmod 777 -R /dev/fb0
(013383) [13:44:39] % chmod 777 -R /dev/video2
(013383) [13:44:39] % chmod 777 -R /dev/video1
(013383) [13:44:39] % chmod 777 -R /dev/video0
(013383) [13:44:39] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(013383) [13:44:39] New background process: pid=13411, output=background
lxc-start: waydroid: cgroups/cgfsng.c: initialize_cgroups: 3359 Out of memory - Failed to initialize cgroups
lxc-start: waydroid: cgroups/cgroup.c: cgroup_init: 33 Bad file descriptor - Failed to initialize cgroup driver
lxc-start: waydroid: start.c: lxc_init: 864 Failed to initialize cgroup driver
lxc-start: waydroid: start.c: __lxc_start: 2002 Failed to initialize container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 987 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 306 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options
(013383) [13:44:39] waiting 10 seconds for container to start...
(013383) [13:44:40] waiting 9 seconds for container to start...
(013383) [13:44:41] waiting 8 seconds for container to start...
(013383) [13:44:42] waiting 7 seconds for container to start...
(013383) [13:44:43] waiting 6 seconds for container to start...
(013383) [13:44:44] waiting 5 seconds for container to start...
(013383) [13:44:45] waiting 4 seconds for container to start...
(013383) [13:44:46] waiting 3 seconds for container to start...
(013383) [13:44:47] waiting 2 seconds for container to start...
(013383) [13:44:48] waiting 1 seconds for container to start...
(013383) [13:44:49] ERROR: container failed to start
(013383) [13:44:49] See also: <https://github.com/waydroid>
(013383) [13:44:49] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 163, in start
    raise OSError("container failed to start")
OSError: container failed to start
```

**Comment by somefoo** [comment]
Same problem here, same system and log as above :P

**Comment by ktprograms** [comment]
Try these two steps:

1. `service cgroups start`
2. `apk add iptables dnsmasq`

**Comment by clangdo** [comment]
Wow, I had no idea a cgroups service was required to get cgroups working...seems like a silly mistake but now I have completely different problems, I'm not the OP, but for me @ktprograms' suggestion fixed this issue.

**Comment by ktprograms** [comment]
@clangdo By completely different problems do you mean that `waydroid show-full-ui` repeatedly outputs `Failed to get service waydroidplatform, trying again...`?

(Which is the problem I'm having now but I can't find a solution)

**Comment by CybergoreDali** [comment]
Can't reproduce in the current state of my device, closing the issue for now.

**Comment by zpeterg** [comment]
@ktprograms , did you find a solution? I'm getting the same message now...

**Comment by clangdo** [comment]
I don't get this message reliably, though I have gotten the message in the past. As I recall it generally happened when I tried to start a second session while the other one was starting.

Right now it seems like my main problem is that my session repeatedly crashes during initialization due to some graphics initialization issue. I can see this through `waydroid logcat`.
