### ISSUE TITLE
[BUG] can't start session 

### ISSUE THREAD

**Issue by Bogdan-Torkhov** [waydroid/waydroid#1089]
### Describe the bug

[gbinder] WARNING: Service manager /dev/anbox-binder has died
have these bug

### Waydroid version

1.4.1

### Device

Linux Desktop

### Operating System

Arch adm64

### Kernel version

6.4.15-lqx1-2-lqx

### Desktop Environment

Gnome 44.4

### GPU

Intel TigerLake-LP GT2 [Iris Xe Graphics]

### Logs

/var/lib/waydroid/waydroid.cfg:
```
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1693618252
vendor_datetime = 1693653750
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = anbox-binder
vndbinder = anbox-vndbinder
hwbinder = anbox-hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3

[properties]
```
/var/lib/waydroid/waydroid.prop:
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.1
ro.vndk.lite=true
waydroid.host.user=deusbog
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/deusbog/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-0
waydroid.background_start=true
waydroid.stub_sensors_hal=1
```
/var/lib/waydroid/waydroid_base.prop:
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.1
ro.vndk.lite=true
```
/var/lib/waydroid/waydroid.log:
```
(056238) [18:04:42] % mkdir -p /dev/binderfs
(056238) [18:04:42] % mount -t binder binder /dev/binderfs
(056238) [18:04:42] % ln -s /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/features /dev/binderfs/binder-control /dev/
(056238) [18:04:42] Save config: /var/lib/waydroid/waydroid.cfg
(056238) [18:04:42] % mkdir -p /var/lib/waydroid/cache_http
(056238) [18:04:42] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20230902-GAPPS-waydroid_x86_64-system.zip/download
(056238) [18:04:42] Validating system image
(056238) [18:04:42] ERROR: Downloaded system image hash doesn't match, expected: 00726c5177c71c1c885120f4f5271b66f5adfc7dc05f131e65df4b0d991d39de
(056238) [18:04:42] See also: <https://github.com/waydroid>
(056238) [18:04:42] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 124, in init
    helpers.images.get(args)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 44, in get
    raise ValueError("Downloaded system image hash doesn't match, expected: {}".format(
ValueError: Downloaded system image hash doesn't match, expected: 00726c5177c71c1c885120f4f5271b66f5adfc7dc05f131e65df4b0d991d39de

(056338) [18:04:58] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(056338) [18:04:58] *** output passed to waydroid stdout, not to this log ***
(056433) [18:05:19] Save config: /var/lib/waydroid/waydroid.cfg
(056433) [18:05:19] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20230902-GAPPS-waydroid_x86_64-system.zip/download
(056433) [18:05:19] Validating system image
(056433) [18:05:19] ERROR: Downloaded system image hash doesn't match, expected: 00726c5177c71c1c885120f4f5271b66f5adfc7dc05f131e65df4b0d991d39de
(056433) [18:05:19] See also: <https://github.com/waydroid>
(056433) [18:05:19] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 124, in init
    helpers.images.get(args)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 44, in get
    raise ValueError("Downloaded system image hash doesn't match, expected: {}".format(
ValueError: Downloaded system image hash doesn't match, expected: 00726c5177c71c1c885120f4f5271b66f5adfc7dc05f131e65df4b0d991d39de

(005530) [11:01:06] ERROR: Action "init" needs root access
(005530) [11:01:06] See also: <https://github.com/waydroid>
(005530) [11:01:06] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 63, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "init" needs root access

(005628) [11:01:23] % mkdir -p /dev/binderfs
(005628) [11:01:23] % mount -t binder binder /dev/binderfs
(005628) [11:01:23] % ln -s /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/features /dev/binderfs/binder-control /dev/
(005628) [11:01:23] Save config: /var/lib/waydroid/waydroid.cfg
(005628) [11:01:23] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20230902-GAPPS-waydroid_x86_64-system.zip/download
(005628) [11:04:31] Validating system image
(005628) [11:04:32] Extracting to /var/lib/waydroid/images
(005628) [11:04:39] Save config: /var/lib/waydroid/waydroid.cfg
(005628) [11:04:39] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-18.1-20230902-MAINLINE-waydroid_x86_64-vendor.zip/download
(005628) [11:05:11] Validating vendor image
(005628) [11:05:11] Extracting to /var/lib/waydroid/images
(005628) [11:05:12] Save config: /var/lib/waydroid/waydroid.cfg
(005628) [11:05:12] % modprobe -q ashmem_linux
(005628) [11:05:12] % lxc-info --version
5.0.3
(005628) [11:05:12] % mkdir -p /var/lib/waydroid/lxc/waydroid
(005628) [11:05:12] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(005628) [11:05:12] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(005628) [11:05:12] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(005628) [11:05:12] % systemctl is-active -q apparmor
(005628) [11:05:12] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(005629) [11:05:12] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(005629) [11:05:12] % modprobe -q ashmem_linux
(005629) [11:05:12] % chmod 666 -R /dev/anbox-binder
(005629) [11:05:12] % chmod 666 -R /dev/anbox-vndbinder
(005629) [11:05:12] % chmod 666 -R /dev/anbox-hwbinder
(006516) [11:06:50] ERROR: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
(006516) [11:06:50] See also: <https://github.com/waydroid>
(006516) [11:06:50] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
                                                     ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/_dbus.py", line 209, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/_dbus.py", line 99, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 120, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

(006989) [11:11:49] ERROR: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
(006989) [11:11:49] See also: <https://github.com/waydroid>
(006989) [11:11:49] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
                                                     ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/_dbus.py", line 209, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/_dbus.py", line 99, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 120, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

(005629) [11:12:14] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(005629) [11:12:14] % systemctl is-active -q nfcd
(005629) [11:12:14] % chmod 777 -R /dev/dri
(005629) [11:12:14] % chmod 777 -R /dev/fb0
(005629) [11:12:14] % chmod 777 -R /dev/video1
(005629) [11:12:14] % chmod 777 -R /dev/video0
(005629) [11:12:14] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(005629) [11:12:14] % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(005629) [11:12:14] % mkdir -p /var/lib/waydroid/overlay_work/system
(005629) [11:12:14] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(005629) [11:12:14] % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(005629) [11:12:14] % mkdir -p /var/lib/waydroid/overlay_work/vendor
(005629) [11:12:14] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(005629) [11:12:14] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(005629) [11:12:14] Save config: /var/lib/waydroid/waydroid.cfg
(005629) [11:12:14] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(005629) [11:12:14] New background process: pid=7259, output=background
(005629) [11:12:14] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(005629) [11:12:14] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(005629) [11:12:14] waiting 10 seconds for container to start...
(007193) [11:12:15] Failed to start Clipboard manager service, check logs
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
(005629) [11:12:48] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(008432) [11:12:48] Waiting for binder Service Manager...
(008432) [11:13:48] Service Manager never appeared
(008432) [11:13:48] Failed to access IPlatform service
(007193) [11:14:33] Clipboard service is not even started
(005629) [11:14:33] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(005629) [11:14:33] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(005629) [11:14:33] % systemctl is-enabled -q nfcd
(005629) [11:14:33] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(005629) [11:14:33] % umount /var/lib/waydroid/rootfs/vendor
(005629) [11:14:33] % umount /var/lib/waydroid/rootfs/vendor
(005629) [11:14:33] % umount /var/lib/waydroid/rootfs
(005629) [11:14:33] % umount /var/lib/waydroid/rootfs
(005629) [11:19:26] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(005629) [11:19:26] % systemctl is-active -q nfcd
(005629) [11:19:26] % chmod 777 -R /dev/dri
(005629) [11:19:26] % chmod 777 -R /dev/fb0
(005629) [11:19:26] % chmod 777 -R /dev/video1
(005629) [11:19:26] % chmod 777 -R /dev/video0
(005629) [11:19:26] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(005629) [11:19:26] % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(005629) [11:19:26] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(005629) [11:19:26] % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(005629) [11:19:26] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(005629) [11:19:26] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(005629) [11:19:26] Save config: /var/lib/waydroid/waydroid.cfg
(005629) [11:19:26] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(005629) [11:19:26] New background process: pid=9769, output=background
(005629) [11:19:26] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(005629) [11:19:26] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(005629) [11:19:26] waiting 10 seconds for container to start...
(009714) [11:19:27] Failed to start Clipboard manager service, check logs
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
(009714) [11:22:29] Clipboard service is not even started
(005629) [11:22:29] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(005629) [11:22:29] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(005629) [11:22:29] % systemctl is-enabled -q nfcd
(005629) [11:22:29] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(005629) [11:22:29] % umount /var/lib/waydroid/rootfs/vendor
(005629) [11:22:29] % umount /var/lib/waydroid/rootfs/vendor
(005629) [11:22:29] % umount /var/lib/waydroid/rootfs
(005629) [11:22:29] % umount /var/lib/waydroid/rootfs
(005629) [11:28:44] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(005629) [11:28:45] % systemctl is-active -q nfcd
(005629) [11:28:45] % chmod 777 -R /dev/dri
(005629) [11:28:45] % chmod 777 -R /dev/fb0
(005629) [11:28:45] % chmod 777 -R /dev/video1
(005629) [11:28:45] % chmod 777 -R /dev/video0
(005629) [11:28:45] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(005629) [11:28:45] % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(005629) [11:28:45] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(005629) [11:28:45] % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(005629) [11:28:45] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(005629) [11:28:45] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(005629) [11:28:45] Save config: /var/lib/waydroid/waydroid.cfg
(005629) [11:28:45] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(005629) [11:28:45] New background process: pid=15689, output=background
(005629) [11:28:45] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
(005629) [11:32:24] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(005629) [11:32:24] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(005629) [11:32:24] % systemctl is-enabled -q nfcd
(005629) [11:32:24] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(005629) [11:32:24] % umount /var/lib/waydroid/rootfs/vendor
(005629) [11:32:24] % umount /var/lib/waydroid/rootfs/vendor
(005629) [11:32:24] % umount /var/lib/waydroid/rootfs
(005629) [11:32:24] % umount /var/lib/waydroid/rootfs
(000575) [11:33:49] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000575) [11:33:49] % mkdir -p /dev/binderfs
(000575) [11:33:49] % mount -t binder binder /dev/binderfs
(000575) [11:33:49] % ln -s /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/features /dev/binderfs/binder-control /dev/
(000575) [11:33:49] % modprobe -q ashmem_linux
(000575) [11:33:49] % chmod 666 -R /dev/anbox-binder
(000575) [11:33:49] % chmod 666 -R /dev/anbox-vndbinder
(000575) [11:33:49] % chmod 666 -R /dev/anbox-hwbinder
(000575) [11:34:19] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(000575) [11:34:19] % systemctl is-active -q nfcd
(000575) [11:34:19] % chmod 777 -R /dev/dri
(000575) [11:34:19] % chmod 777 -R /dev/fb0
(000575) [11:34:19] % chmod 777 -R /dev/video1
(000575) [11:34:19] % chmod 777 -R /dev/video0
(000575) [11:34:19] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(000575) [11:34:19] % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(000575) [11:34:19] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000575) [11:34:19] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(004053) [11:34:19] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 174, in do_start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"], session)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 143, in mount_rootfs
    helpers.mount.mount(args, images_dir + "/system.img",
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 148, in mount
    tools.helpers.run.user(args, ["mount", *extra_args, source, destination])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs

(004053) [11:34:19] RuntimeError: Command failed: % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(000543) [11:37:51] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000543) [11:37:51] % mkdir -p /dev/binderfs
(000543) [11:37:51] % mount -t binder binder /dev/binderfs
(000543) [11:37:51] % ln -s /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/features /dev/binderfs/binder-control /dev/
(000543) [11:37:51] % modprobe -q ashmem_linux
(000543) [11:37:51] % chmod 666 -R /dev/anbox-binder
(000543) [11:37:51] % chmod 666 -R /dev/anbox-vndbinder
(000543) [11:37:51] % chmod 666 -R /dev/anbox-hwbinder
(000543) [19:02:19] Hardware service is not even started
(000543) [19:02:19] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000543) [19:02:19] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(000543) [19:02:19] % systemctl is-enabled -q nfcd
(000673) [19:03:07] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000673) [19:03:07] % mkdir -p /dev/binderfs
(000673) [19:03:07] % mount -t binder binder /dev/binderfs
(000673) [19:03:07] % ln -s /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/features /dev/binderfs/binder-control /dev/
(000673) [19:03:07] % modprobe -q ashmem_linux
(000673) [19:03:07] % chmod 666 -R /dev/anbox-binder
(000673) [19:03:07] % chmod 666 -R /dev/anbox-vndbinder
(000673) [19:03:07] % chmod 666 -R /dev/anbox-hwbinder
(000673) [19:24:24] Hardware service is not even started
(000673) [19:24:24] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000673) [19:24:24] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(000673) [19:24:24] % systemctl is-enabled -q nfcd
(000518) [19:31:37] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000518) [19:31:37] % mkdir -p /dev/binderfs
(000518) [19:31:37] % mount -t binder binder /dev/binderfs
(000518) [19:31:37] % ln -s /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/features /dev/binderfs/binder-control /dev/
(000518) [19:31:37] % modprobe -q ashmem_linux
(000518) [19:31:37] % chmod 666 -R /dev/anbox-binder
(000518) [19:31:37] % chmod 666 -R /dev/anbox-vndbinder
(000518) [19:31:37] % chmod 666 -R /dev/anbox-hwbinder
(000518) [12:41:55] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(000518) [12:41:55] % systemctl is-active -q nfcd
(000518) [12:41:55] % chmod 777 -R /dev/dri
(000518) [12:41:55] % chmod 777 -R /dev/fb0
(000518) [12:41:55] % chmod 777 -R /dev/video1
(000518) [12:41:55] % chmod 777 -R /dev/video0
(000518) [12:41:55] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(000518) [12:41:55] % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(000518) [12:41:55] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(000518) [12:41:55] % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(000518) [12:41:55] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(000518) [12:41:55] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(000518) [12:41:55] Save config: /var/lib/waydroid/waydroid.cfg
(000518) [12:41:55] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(000518) [12:41:55] New background process: pid=16332, output=background
(000518) [12:41:55] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000518) [12:41:55] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(000518) [12:41:55] waiting 10 seconds for container to start...
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
(000518) [12:43:43] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000518) [12:43:43] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(000518) [12:43:43] % systemctl is-enabled -q nfcd
(000518) [12:43:43] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(000518) [12:43:43] % umount /var/lib/waydroid/rootfs/vendor
(000518) [12:43:43] % umount /var/lib/waydroid/rootfs/vendor
(000518) [12:43:43] % umount /var/lib/waydroid/rootfs
(000518) [12:43:43] % umount /var/lib/waydroid/rootfs
(018913) [12:50:47] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(018913) [12:50:47] WayDroid container is STOPPED
```
`sudo waydroid shell -- logcat -d | tee logcat.txt`:
```
[13:07:06] WayDroid container is STOPPED
```
`sudo dmesg | tee dmesg.txt`:
```
https://pastebin.com/sEp6YUua
```

**Comment by Bogdan-Torkhov** [comment]
?

**Comment by kir68k** [comment]
Same as #631, I don't know why this happens, though.

**Comment by kir68k** [comment]
Found a fix described in https://github.com/waydroid/waydroid/issues/631#issuecomment-1757385842
