### ISSUE TITLE
[BUG]waydroid not initialize

### ISSUE THREAD

**Issue by Sheepmister** [waydroid/waydroid#1132]
### Describe the bug

i tried running as root then type waydroid init but still not fix the issue

dream@debian:~/Downloads$ cd
dream@debian:~$ waydroid session start
ERROR: WayDroid is not initialized, run "waydroid init"
dream@debian:~$ sudo waydroid container start
[sudo] password for dream: 
ERROR: WayDroid is not initialized, run "waydroid init"
dream@debian:~$ su
Password: 
root@debian:/home/dream# waydroid init
[00:48:42] ERROR: [Errno 2] No such file or directory: 'modprobe'
[00:48:42] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
root@debian:/home/dream#

and heres the log

root@debian:/home/dream# waydroid log
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 75, in setup_config
    vendor_request = helpers.http.retrieve(vendor_ota)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/http.py", line 143, in retrieve
    with urllib.request.urlopen(req) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 104] Connection reset by peer>

(006372) [00:48:42] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(006372) [00:48:42] ERROR: [Errno 2] No such file or directory: 'modprobe'
(006372) [00:48:42] See also: <https://github.com/waydroid>
(006372) [00:48:42] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 97, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 128, in setupBinderNodes
    probeBinderDriver(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 95, in probeBinderDriver
    output = tools.helpers.run.user(args, command, check=False, output_return=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 335, in core
    (code, output_after_run) = foreground_pipe(args, cmd, working_dir,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 147, in foreground_pipe
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'modprobe'

(006392) [00:50:39] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(006392) [00:50:39] *** output passed to waydroid stdout, not to this log ***

### Waydroid version

latest version

### Device

Linux Desktop

### Operating System

debian 12 bookworm

### Kernel version

latest kernel

### Desktop Environment

latest genom

### GPU

intel hd 4600

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by erenerturk1** [comment]
I get the same issue on Debian 12 as well, but I'm running it in an accelarated vm. 
![image](https://github.com/waydroid/waydroid/assets/61586104/f3604daa-5772-4e53-aeae-c60960296128)

**Comment by erenerturk1** [comment]
Okay I found a fix and it proves this isn't a waydroid bug. If you `echo $PATH` you'll see that `/sbin` is not in your path, that why waydroid can't find `modprobe` because it is located at `/sbin/modprobe`. Now it works for me with no problems. Again, THIS IS FULLY A DEBIAN ISSUE.

**Comment by Sheepmister** [comment]
> Okay I found a fix and it proves this isn't a waydroid bug. If you `echo $PATH` you'll see that `/sbin` is not in your path, that why waydroid can't find `modprobe` because it is located at `/sbin/modprobe`. Now it works for me with no problems. Again, THIS IS FULLY A DEBIAN ISSUE.

how to fix it then

**Comment by YJJjun** [comment]
run  "export  PATH=$PATH:/sbin"  at  the  terminal   ，then   run  your  command  follow  it   at  the same terminal to  try

**Comment by Sheepmister** [comment]
dubrik@mint:~$ waydroid session start
[23:44:06] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
[23:44:06] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?
dubrik@mint:~$ 
 got this error

**Comment by YJJjun** [comment]
Does  the   result   of   "echo   $XDG_SESSION_TYPE"  is   x11 ？what  is  your  system  version  ? ubuntu22.04?
