### ISSUE TITLE
[Feature] Please Bring Call of Duty Mobile Support to Waydroid

### ISSUE THREAD

**Issue by NeuHix** [waydroid/waydroid#1146]
### Is your feature request related to a problem? Please describe.

I have dual-booted windows entirely for this single reason.
My phone is not so powerful but my pc is enough to play that game.
I installed the game, hoping I can get it to work. The game starts and shows "ACTIVISION" and then closes itself.
I checked the logs from the point where I started the game.
But I didn't understood them.

### Describe the solution you'd like.

1. I want Call of Duty Mobile to be playable on waydroid.
2. It should have keyboard or gamepad mappings. 
3. And CODM should be able to detect that an external controller is connected.
    so, it matches me against the same kind of players.

**Although, 3 is not so important, if it's really hard to implement.**

### Describe alternatives you've considered.

Gameloop on Windows.
But Windows is heavy on resources.

### Additional context

- **Here's `sudo systemctl status waydroid-container.service`**
```
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Sun 2023-10-29 02:59:13 IST; 2h 31min ago
    Process: 951 ExecStartPre=/usr/bin/ln -sf /dev/binderfs/binder /dev/binderfs/vndbinder /dev/binderfs/hwbinder /dev/ (code=exited, status=0/SUCCESS)
   Main PID: 993 (waydroid)
      Tasks: 6 (limit: 16586)
     Memory: 2.3G
        CPU: 14.456s
     CGroup: /system.slice/waydroid-container.service
             ├─  993 /usr/bin/python3 /usr/bin/waydroid -w container start
             └─13389 dnsmasq --conf-file=/dev/null -u dnsmasq --strict-order --bind-interfaces --pid-file=/run/waydroid-lxc/dnsmasq.pid --listen-address 192.168.240.1 --dhcp-range 192.168.240.2,192.168.240.254 >

Oct 29 05:21:48 fedora dnsmasq-dhcp[13389]: DHCPREQUEST(waydroid0) 192.168.240.112 00:16:3e:f9:d3:03
Oct 29 05:21:48 fedora dnsmasq-dhcp[13389]: DHCPACK(waydroid0) 192.168.240.112 00:16:3e:f9:d3:03 WayDroid-x86-64-Device
Oct 29 05:29:01 fedora dnsmasq-dhcp[13389]: DHCPDISCOVER(waydroid0) 00:16:3e:f9:d3:03
Oct 29 05:29:01 fedora dnsmasq-dhcp[13389]: DHCPOFFER(waydroid0) 192.168.240.112 00:16:3e:f9:d3:03
Oct 29 05:29:01 fedora dnsmasq-dhcp[13389]: DHCPREQUEST(waydroid0) 192.168.240.112 00:16:3e:f9:d3:03
Oct 29 05:29:01 fedora dnsmasq-dhcp[13389]: DHCPACK(waydroid0) 192.168.240.112 00:16:3e:f9:d3:03 WayDroid-x86-64-Device
Oct 29 05:29:48 fedora dnsmasq-dhcp[13389]: DHCPDISCOVER(waydroid0) 00:16:3e:f9:d3:03
Oct 29 05:29:48 fedora dnsmasq-dhcp[13389]: DHCPOFFER(waydroid0) 192.168.240.112 00:16:3e:f9:d3:03
Oct 29 05:29:48 fedora dnsmasq-dhcp[13389]: DHCPREQUEST(waydroid0) 192.168.240.112 00:16:3e:f9:d3:03
Oct 29 05:29:48 fedora dnsmasq-dhcp[13389]: DHCPACK(waydroid0) 192.168.240.112 00:16:3e:f9:d3:03 WayDroid-x86-64-Device

```
- **Here's `waydroid log`**
```
    raise RuntimeError(
RuntimeError: Action "container" needs root access

(000993) [05:28:29] waydroidhardware: Received transaction: 3
(000993) [05:28:29] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(000993) [05:28:29] % lxc-freeze -P /var/lib/waydroid/lxc -n waydroid
(000993) [05:28:29] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
FROZEN
(051939) [05:28:35] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
FROZEN
(051939) [05:28:35] WayDroid container is FROZEN
(052376) [05:28:48] ERROR: Action "container" needs root access
(052376) [05:28:48] See also: <https://github.com/waydroid>
(052376) [05:28:48] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 77, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "container" needs root access

(052605) [05:28:54] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
FROZEN
(052605) [05:28:54] % lxc-unfreeze -P /var/lib/waydroid/lxc -n waydroid
(052605) [05:28:54] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(052711) [05:28:57] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(052711) [05:28:57] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(052711) [05:28:57] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(052711) [05:28:57] New background process: pid=52736, output=background
(052711) [05:28:57] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(013338) [05:29:08] waydroidusermonitor: Received transaction: 1
(013338) [05:29:08] Android with user 0 is ready
(013338) [05:29:08] % adb start-server
(013338) [05:29:08] % adb connect 192.168.240.112
already connected to 192.168.240.112:5555
(013338) [05:29:08] Established ADB connection to Waydroid device at 192.168.240.112.
(000993) [05:29:41] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(056979) [05:29:44] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(056979) [05:29:44] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(056979) [05:29:45] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(056979) [05:29:45] New background process: pid=57001, output=background
(056979) [05:29:45] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(013338) [05:29:55] waydroidusermonitor: Received transaction: 1
(013338) [05:29:55] Android with user 0 is ready
(013338) [05:29:55] % adb start-server
(013338) [05:29:55] % adb connect 192.168.240.112
already connected to 192.168.240.112:5555
(013338) [05:29:55] Established ADB connection to Waydroid device at 192.168.240.112.
(068357) [05:34:30] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(068357) [05:34:30] *** output passed to waydroid stdout, not to this log ***

```

- **Here's `waydroid logcat`**
_the call of duty mobile logs start at 10-29 05:30:02.069_
[waydroid-logcat.txt](https://github.com/waydroid/waydroid/files/13196971/waydroid-logcat.txt)

- **Here's my OS info**

  - OS: Fedora Linux 38 (Thirty Eight) x86_64 
  - Kernel: 6.4.12-200.fc38.x86_64 
  - Shell: fish 3.6.1 
  - Resolution: 1920x1080 
  - DE: GNOME 44.4 
  - CPU: AMD Athlon 3000G (4) @ 3.500GHz 
  - GPU: AMD ATI Radeon Vega Series / Radeon Vega Mobil 
  - Memory: 2566MiB / 13880MiB

**Comment by gaetan1903** [comment]
need this features too

not need to use WIndows anymore to play CODM on PC

**Comment by Lolo58ulti** [comment]
I’m not one of their dev but i can give you an awnser.
Waydroid is a compatility layer for android on linux, even if they add support to play call of duty mobile it will be useless because their anti cheat will detect waydroid as an unauthorized emulator so they will ban ur account.
The only way for them is to make an huge work on that and edit a massive amount of files and codes just for that, this can lead to instability, possibly make some apps unusable and maybe virtualisation support needed. So if you still want to play on ur pc i recommand to install gameloop emulator on windows, it their official emulator from tencent.
Have a great day.

**Comment by KillerBorn10** [comment]
Yo quisiera poder jugar el juego en mi mobil pero le cuesta a mi equipo correr juego y después de no mas de 10 minutos se sale solo y tarda en volver a conectarse ya intente una vpn si de alguna manera el juego va un poco mejor incluso ya libere el almacenamiento del equipo y tampoco que podrían aconsejarme se los agradecería muchísimo

**Comment by G-Titan** [comment]
> I’m not one of their dev but i can give you an awnser. Waydroid is a compatility layer for android on linux, even if they add support to play call of duty mobile it will be useless because their anti cheat will detect waydroid as an unauthorized emulator so they will ban ur account. The only way for them is to make an huge work on that and edit a massive amount of files and codes just for that, this can lead to instability, possibly make some apps unusable and maybe virtualisation support needed. So if you still want to play on ur pc i recommand to install gameloop emulator on windows, it their official emulator from tencent. Have a great day.

I'm upset
