### ISSUE TITLE
[BUG] Android is NOT hardware accelerated on the Pinephone

### ISSUE THREAD

**Issue by AdolfRoxler** [waydroid/waydroid#1172]
### Describe the bug

Hello. I am unsure if it's LineageOS being retarded or it's a rare Waydroid bug.

Whatever's going on, it's not HW accelerated as shown here: https://www.mediafire.com/file/ybk1g0bfhwmsg8s

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

PostmarketOS edge [19/11/2023]

### Kernel version

6.6.0

### Desktop Environment

SXMO

### GPU

Mali 400

### Logs

/var/lib/waydroid/waydroid.cfg
```
[waydroid]
arch = arm64
vendor_type = MAINLINE
system_datetime = 1700244220
vendor_datetime = 1700261635
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_arm64/VANILLA.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_arm64/MAINLINE.json
binder = binder
vndbinder = vndbinder
hwbinder = hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3

[properties]
```
/var/lib/waydroid/waydroid.prop
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_arm64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_arm64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
ro.product.waydroid.model=Pine64 PinePhone (1.2)
waydroid.host.user=snoopdogg
waydroid.host.uid=10000
waydroid.host.gid=10000
waydroid.host_data_path=/home/snoopdogg/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/dev/shm/user/10000
waydroid.pulse_runtime_path=/dev/shm/user/10000/pulse
waydroid.wayland_display=wayland-1
waydroid.background_start=false
waydroid.stub_sensors_hal=1
```
/var/lib/waydroid/waydroid_base.prop
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_arm64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_arm64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
ro.product.waydroid.model=Pine64 PinePhone (1.2)
```
/var/lib/waydroid/waydroid.log
```
(016874) [12:53:53] Save config: /var/lib/waydroid/waydroid.cfg
(016874) [12:53:54] % mkdir -p /var/lib/waydroid/cache_http
(016874) [12:53:54] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_arm64/lineage-18.1-20231118-VANILLA-waydroid_arm64-system.zip/download
(023685) [13:06:15] Save config: /var/lib/waydroid/waydroid.cfg
(023685) [13:06:15] % rm /var/lib/waydroid/cache_http/lineage-18.1-20231118-VANILLA-waydroid_arm64-system.zip_94ff16309946492fde7ef441a1f4d87325de1c969e198d483724cddfb615034b
(023685) [13:06:15] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_arm64/lineage-18.1-20231118-VANILLA-waydroid_arm64-system.zip/download
(024331) [13:07:30] Save config: /var/lib/waydroid/waydroid.cfg
(024331) [13:07:31] % rm /var/lib/waydroid/cache_http/lineage-18.1-20231118-VANILLA-waydroid_arm64-system.zip_94ff16309946492fde7ef441a1f4d87325de1c969e198d483724cddfb615034b
(024331) [13:07:31] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_arm64/lineage-18.1-20231118-VANILLA-waydroid_arm64-system.zip/download
(024331) [13:12:14] Validating system image
(024331) [13:12:15] ERROR: Downloaded system image hash doesn't match, expected: b8c2818433b429cf7924a3a873b39406e2a9e3ec350857ea9e532cc7bcea33bb
(024331) [13:12:15] See also: <https://github.com/waydroid>
(024331) [13:12:15] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 124, in init
    helpers.images.get(args)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 44, in get
    raise ValueError("Downloaded system image hash doesn't match, expected: {}".format(
ValueError: Downloaded system image hash doesn't match, expected: b8c2818433b429cf7924a3a873b39406e2a9e3ec350857ea9e532cc7bcea33bb

(013241) [13:13:41] Save config: /var/lib/waydroid/waydroid.cfg
(013241) [13:13:41] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_arm64/lineage-18.1-20231118-VANILLA-waydroid_arm64-system.zip/download
(017102) [13:14:49] Save config: /var/lib/waydroid/waydroid.cfg
(017102) [13:14:49] % rm /var/lib/waydroid/cache_http/lineage-18.1-20231118-VANILLA-waydroid_arm64-system.zip_94ff16309946492fde7ef441a1f4d87325de1c969e198d483724cddfb615034b
(017102) [13:14:49] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_arm64/lineage-18.1-20231118-VANILLA-waydroid_arm64-system.zip/download
(017102) [13:17:00] Validating system image
(017102) [13:17:03] Extracting to /var/lib/waydroid/images
(017102) [13:18:34] Save config: /var/lib/waydroid/waydroid.cfg
(017102) [13:18:43] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_arm64/lineage-18.1-20231118-MAINLINE-waydroid_arm64-vendor.zip/download
(017102) [13:22:49] Validating vendor image
(017102) [13:22:49] Extracting to /var/lib/waydroid/images
(017102) [13:23:02] Save config: /var/lib/waydroid/waydroid.cfg
(017102) [13:23:05] % modprobe -q ashmem_linux
(017102) [13:23:05] % lxc-info --version
5.0.3
(017102) [13:23:15] % mkdir -p /var/lib/waydroid/lxc/waydroid
(017102) [13:23:15] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(017102) [13:23:15] % sed -i s/LXCARCH/aarch64/ /var/lib/waydroid/lxc/waydroid/config
(017102) [13:23:15] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(017102) [13:23:15] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(016876) [13:23:15] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(016876) [13:23:15] % modprobe -q ashmem_linux
(016876) [13:23:15] ERROR: [Errno 2] No such file or directory: 'modprobe'
(016876) [13:23:15] See also: <https://github.com/waydroid>
(016876) [13:23:15] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 85, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 111, in start
    helpers.drivers.probeAshmemDriver(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 116, in probeAshmemDriver
    tools.helpers.run.user(args, command, check=False)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 335, in core
    (code, output_after_run) = foreground_pipe(args, cmd, working_dir,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 147, in foreground_pipe
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'modprobe'

(010065) [13:24:42] Already initialized
(025168) [13:38:24] Starting waydroid session
(025175) [13:38:25] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(025175) [13:38:25] % modprobe -q ashmem_linux
(025175) [13:38:25] ERROR: [Errno 2] No such file or directory: 'modprobe'
(025175) [13:38:25] See also: <https://github.com/waydroid>
(025175) [13:38:25] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 85, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 111, in start
    helpers.drivers.probeAshmemDriver(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 116, in probeAshmemDriver
    tools.helpers.run.user(args, command, check=False)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 335, in core
    (code, output_after_run) = foreground_pipe(args, cmd, working_dir,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 147, in foreground_pipe
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'modprobe'

(025168) [13:38:26] Introspect error on :1.652:/ContainerManager: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
(025168) [13:38:26] Executing introspect queue due to error
(025168) [13:38:26] org.freedesktop.DBus.Error.ServiceUnknown: The name :1.652 was not provided by any .service files
(025168) [13:38:26] WayDroid container is not listening
(025449) [13:38:40] Starting waydroid session
(025456) [13:38:41] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(025456) [13:38:41] % modprobe -q ashmem_linux
(025456) [13:38:41] ERROR: [Errno 2] No such file or directory: 'modprobe'
(025456) [13:38:41] See also: <https://github.com/waydroid>
(025456) [13:38:41] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 85, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 111, in start
    helpers.drivers.probeAshmemDriver(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 116, in probeAshmemDriver
    tools.helpers.run.user(args, command, check=False)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 335, in core
    (code, output_after_run) = foreground_pipe(args, cmd, working_dir,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 147, in foreground_pipe
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'modprobe'

(025449) [13:38:41] Introspect error on :1.656:/ContainerManager: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
(025449) [13:38:41] Executing introspect queue due to error
(025449) [13:38:41] org.freedesktop.DBus.Error.ServiceUnknown: The name :1.656 was not provided by any .service files
(025449) [13:38:41] WayDroid container is not listening
(025459) [13:38:42] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(025459) [13:38:42] *** output passed to waydroid stdout, not to this log ***
(004196) [13:45:59] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(004196) [13:46:00] % modprobe -q ashmem_linux
(004196) [13:46:00] % chmod 666 -R /dev/binder
(004196) [13:46:00] % chmod 666 -R /dev/vndbinder
(004196) [13:46:00] % chmod 666 -R /dev/hwbinder
(006653) [13:47:46] Starting waydroid session
(004196) [13:47:46] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(004196) [13:47:46] % chmod 777 -R /dev/dri
(004196) [13:47:46] % chmod 777 -R /dev/fb0
(004196) [13:47:46] % chmod 777 -R /dev/video0
(004196) [13:47:46] % chmod 777 -R /dev/video1
(004196) [13:47:46] % chmod 777 -R /dev/video2
(004196) [13:47:46] % chmod 777 -R /dev/video3
(004196) [13:47:47] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(004196) [13:47:47] % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(004196) [13:47:47] % mkdir -p /var/lib/waydroid/overlay_work/system
(004196) [13:47:47] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(004196) [13:47:47] % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(004196) [13:47:47] % mkdir -p /var/lib/waydroid/overlay_work/vendor
(004196) [13:47:47] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(004196) [13:47:47] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(004196) [13:47:47] Save config: /var/lib/waydroid/waydroid.cfg
(004196) [13:47:47] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(004196) [13:47:47] New background process: pid=6802, output=background
(004196) [13:47:47] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(004196) [13:47:47] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(004196) [13:47:47] waiting 10 seconds for container to start...
(004196) [13:47:48] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(004196) [13:47:48] waiting 9 seconds for container to start...
(004196) [13:47:56] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(007471) [13:47:56] Failed to get service waydroidplatform, trying again...
(007471) [13:47:57] Failed to get service waydroidplatform, trying again...
(007471) [13:47:58] Failed to get service waydroidplatform, trying again...
(007471) [13:47:59] Failed to get service waydroidplatform, trying again...
(007471) [13:48:00] Failed to get service waydroidplatform, trying again...
(007471) [13:48:01] Failed to get service waydroidplatform, trying again...
(007471) [13:48:02] Failed to get service waydroidplatform, trying again...
(007471) [13:48:03] Failed to get service waydroidplatform, trying again...
(007471) [13:48:04] Failed to get service waydroidplatform, trying again...
(007471) [13:48:05] Failed to get service waydroidplatform, trying again...
(007471) [13:48:06] Failed to get service waydroidplatform, trying again...
(007471) [13:48:07] Failed to get service waydroidplatform, trying again...
(007471) [13:48:08] Failed to get service waydroidplatform, trying again...
(007471) [13:48:09] Failed to get service waydroidplatform, trying again...
(007471) [13:48:10] Failed to get service waydroidplatform, trying again...
(007471) [13:48:11] Failed to get service waydroidplatform, trying again...
(007471) [13:48:12] Failed to get service waydroidplatform, trying again...
(007471) [13:48:13] Failed to get service waydroidplatform, trying again...
(007471) [13:48:14] Failed to get service waydroidplatform, trying again...
(007471) [13:48:15] Failed to get service waydroidplatform, trying again...
(007471) [13:48:16] Failed to get service waydroidplatform, trying again...
(007471) [13:48:17] Failed to get service waydroidplatform, trying again...
(007471) [13:48:18] Failed to get service waydroidplatform, trying again...
(007471) [13:48:19] Failed to get service waydroidplatform, trying again...
(007471) [13:48:20] Failed to get service waydroidplatform, trying again...
(007471) [13:48:21] Failed to get service waydroidplatform, trying again...
(007471) [13:48:22] Failed to get service waydroidplatform, trying again...
(007471) [13:48:23] Failed to get service waydroidplatform, trying again...
(007471) [13:48:24] Failed to get service waydroidplatform, trying again...
(007471) [13:48:25] Failed to get service waydroidplatform, trying again...
(007471) [13:48:26] Failed to get service waydroidplatform, trying again...
(007471) [13:48:27] Failed to get service waydroidplatform, trying again...
(007471) [13:48:28] Failed to get service waydroidplatform, trying again...
(007471) [13:48:29] Failed to get service waydroidplatform, trying again...
(007471) [13:48:30] Failed to get service waydroidplatform, trying again...
(007471) [13:48:31] Failed to get service waydroidplatform, trying again...
(007471) [13:48:32] Failed to get service waydroidplatform, trying again...
(007471) [13:48:33] Failed to get service waydroidplatform, trying again...
(007471) [13:48:34] Failed to get service waydroidplatform, trying again...
(007471) [13:48:35] Failed to get service waydroidplatform, trying again...
(007471) [13:48:36] Failed to get service waydroidplatform, trying again...
(007471) [13:48:37] Failed to get service waydroidplatform, trying again...
(007471) [13:48:38] Failed to get service waydroidplatform, trying again...
(007471) [13:48:39] Failed to get service waydroidplatform, trying again...
(007471) [13:48:40] Failed to get service waydroidplatform, trying again...
(007471) [13:48:41] Failed to get service waydroidplatform, trying again...
(007471) [13:48:42] Failed to get service waydroidplatform, trying again...
(007471) [13:48:43] Failed to get service waydroidplatform, trying again...
(007471) [13:48:44] Failed to get service waydroidplatform, trying again...
(007471) [13:48:45] Failed to get service waydroidplatform, trying again...
(007471) [13:48:46] Failed to get service waydroidplatform, trying again...
(007471) [13:48:47] Failed to get service waydroidplatform, trying again...
(007471) [13:48:48] Failed to get service waydroidplatform, trying again...
(007471) [13:48:49] Failed to get service waydroidplatform, trying again...
(007471) [13:48:50] Failed to get service waydroidplatform, trying again...
(007471) [13:48:51] Failed to get service waydroidplatform, trying again...
(007471) [13:48:52] Failed to get service waydroidplatform, trying again...
(007471) [13:48:53] Failed to get service waydroidplatform, trying again...
(007471) [13:48:54] Failed to get service waydroidplatform, trying again...
(007471) [13:48:55] Failed to get service waydroidplatform, trying again...
(007471) [13:48:56] Failed to get service waydroidplatform, trying again...
(007471) [13:48:57] Failed to get service waydroidplatform, trying again...
(007471) [13:48:58] Failed to get service waydroidplatform, trying again...
(007471) [13:48:59] Failed to get service waydroidplatform, trying again...
(007471) [13:49:00] Failed to get service waydroidplatform, trying again...
(007471) [13:49:01] Failed to get service waydroidplatform, trying again...
(007471) [13:49:02] Failed to get service waydroidplatform, trying again...
(007471) [13:49:03] Failed to get service waydroidplatform, trying again...
(007471) [13:49:04] Failed to get service waydroidplatform, trying again...
(006653) [13:49:34] waydroidusermonitor: Received transaction: 1
(006653) [13:49:34] Android with user 0 is ready
(006653) [14:23:11] waydroidusermonitor: Received transaction: 2
```
`sudo waydroid shell -- logcat -d | tee logcat.txt`
[logcat.txt](https://github.com/waydroid/waydroid/files/13403488/logcat.txt)
`sudo dmesg | tee dmesg.txt`
[dmesg.txt](https://github.com/waydroid/waydroid/files/13403487/dmesg.txt)

**Comment by Djhg2000** [comment]
Looks hardware accelerated to me, the Allwinner A64 (or more specifically the Mali 400) in the PinePhone is just really slow and even the vanilla LineageOS version of Android without GApps is a fairly heavy load for the SoC as a whole. The 3GB of RAM doesn't help either but it's manageable with zRAM and swap. The CPU load pattern you're seeing is probably the input handling (like the touch extrapolation Android uses to improve momentum) and vsync related tasks.

For reference I got 1-2 FPS with forced software rendering even on my PinePhone Pro a while back, and the Rockchip RK3399 is way more powerful than the Allwinner A64. I upgraded to a PinePhone Pro from a regular PinePhone specifically because Waydroid (or more accurately Android) was too much for my PinePhone to handle with the apps I needed.

I'm sorry I don't have better news for you but we really are pushing the A64 to its limits with Waydroid on top of a real Linux desktop (SXMO is a really light weight one but it's still a full featured Wayland desktop). The best advice I can give you is to disable as many animations as you can in Android as it will make it feel faster and waste less resources on eye candy, and to keep memory usage to a minimum both in Android and in PostmarketOS to make the system swap less things in and out of RAM.

If you are fine with spending time to tweak things you can have a look at https://source.android.com/docs/core/perf/lmkd , I remember trying `ro.config.low_ram=true` at some point on my PinePhone but any difference was hard to perceive in my case. I didn't have time to play around with any of the other values to there might still be some performance left to be found there, but I wouldn't get my hopes up too much.

**Comment by AdolfRoxler** [comment]
I have tried the PP on GloDroid. I don't know what the guys did in order to get it to not be a PowerPoint slideshow. CPU usage was also low there

**Comment by Djhg2000** [comment]
GloDroid runs bare metal, which means it would not have any layers in between to slow things down and it would be able to manage all of the system resources by itself. One example would be the process scheduler where I know Android does some funky things to make the system feel more responsive when a finger is touching the screen.

I watched your video again and I still think it looks pretty smooth for a PinePhone. Last time I tried GloDroid was a very long time ago so I might have to try that again and compare, but I won't have the time to do that for a while.

**Comment by AdolfRoxler** [comment]
Do you think compiling GloDroid for Waydroid would help?

**Comment by Djhg2000** [comment]
Waydroid requires patches to Android in order to work, but if you're up to the task there might be some relevant patches in GloDroid. I'm not familiar enough with the codebase to determine what's useful to Waydroid, there might be some generic performance patches which would be useful. I'm not sure if Waydroid would want to introduce a low performance build but I'm sure it could be useful for custom builds.

**Comment by aleasto** [comment]
What is you wayland compositor, and does it support the [dmabuf wayland protocol](https://wayland.app/protocols/linux-dmabuf-unstable-v1)?
Otherwise the cpu is doing a lot of copying buffers

**Comment by AdolfRoxler** [comment]
I am using sway
