### ISSUE TITLE
[BUG] dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch

### ISSUE THREAD

**Issue by ghost** [waydroid/waydroid#1195]
### Describe the bug

```
Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 130, in main
    actions.app_manager.showFullUI(args)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 132, in showFullUI
    maybeLaunchLater(args, justShow)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 72, in maybeLaunchLater
    tools.actions.session_manager.start(args, launchNow, background=False)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

```

My Ubuntu doesn't have `/usr/bin/dbus-launch`. I re-insatlled _dbus_ and there's still error

```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Ubuntu 22.04.3 LTS amd64

### Kernel version

6.2.0-39-generic

### Desktop Environment

GNOME Shell 42.9

### GPU

[AMD/ATI] Picasso/Raven 2 [Radeon Vega Series / Radeon Vega Mobile Series] (rev c2)

### Logs

```
(005253) [05:10:40] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(005253) [05:10:40] *** output passed to waydroid stdout, not to this log ***
(005341) [05:12:41] Starting waydroid session
(005341) [05:12:41] ERROR: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
(005341) [05:12:41] See also: <https://github.com/waydroid>
(005341) [05:12:41] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 64, in maybeLaunchLater
    tools.helpers.ipc.DBusSessionService()
  File "/usr/lib/waydroid/tools/helpers/ipc.py", line 44, in DBusSessionService
    return dbus.Interface(dbus.SessionBus().get_object("id.waydro.Session", object_path), intf)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 130, in main
    actions.app_manager.showFullUI(args)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 132, in showFullUI
    maybeLaunchLater(args, justShow)
  File "/usr/lib/waydroid/tools/actions/app_manager.py", line 72, in maybeLaunchLater
    tools.actions.session_manager.start(args, launchNow, background=False)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

(005346) [05:12:45] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(005346) [05:12:45] *** output passed to waydroid stdout, not to this log ***
(000846) [05:15:19] Hardware service is not even started
(000846) [05:15:19] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000846) [05:15:19] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(000846) [05:15:19] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(000943) [05:15:37] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000943) [05:15:37] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(000943) [05:15:37] % mkdir -p /dev/binderfs
(000943) [05:15:37] % mount -t binder binder /dev/binderfs
(000943) [05:15:37] % ln -s /dev/binderfs/features /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/binder-control /dev/
(000943) [05:15:37] % modprobe -q ashmem_linux
(000943) [05:15:37] % chmod 666 -R /dev/anbox-binder
(000943) [05:15:37] % chmod 666 -R /dev/anbox-vndbinder
(000943) [05:15:37] % chmod 666 -R /dev/anbox-hwbinder
(004882) [05:19:15] % tail -n 60 -F /var/lib/waydroid/waydroid.log

```

**Comment by peterxmon** [comment]
After setting `~/.bashrc` 
`export WAYLAND_DISPLAY=wayland-0`  

I got a new error 
```
$ waydroid first-launch
[06:02:51] Starting waydroid session
[06:02:51] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?

```

**Comment by Quackdoc** [comment]
the latest issue in this implies you aren't running wayland, wayland is necessary for waydroid.
