### ISSUE TITLE
[BUG]Waydroid always needs to start dnsmasq in order to launch itself. However, I am using another DNS server on port 53 of my local machine, which prevents dnsmasq from starting and consequently causes Waydroid to exit directly.

### ISSUE THREAD

**Issue by NONAME-2121237** [waydroid/waydroid#1197]
### Describe the bug

Waydroid always needs to start dnsmasq in order to launch itself. However, I am using another DNS server on port 53 of my local machine, which prevents dnsmasq from starting and consequently causes Waydroid to exit directly.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Ubuntu 22.04.3 LTS amd64

### Kernel version

6.2.0-39-generic

### Desktop Environment

GNOME 42.9

### GPU

Mesa Intel® UHD Graphics (JSL)

### Logs

(000581) [22:32:22] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(000581) [22:32:22] % mkdir -p /dev/binderfs
(000581) [22:32:22] % mount -t binder binder /dev/binderfs
(000581) [22:32:22] % ln -s /dev/binderfs/features /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/binder-control /dev/
(000581) [22:32:22] % modprobe -q ashmem_linux
(000581) [22:32:22] % chmod 666 -R /dev/anbox-binder
(000581) [22:32:22] % chmod 666 -R /dev/anbox-vndbinder
(000581) [22:32:22] % chmod 666 -R /dev/anbox-hwbinder
(002371) [22:34:56] Starting waydroid session
(000581) [22:34:56] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 200: dnsmasq: not found
Failed to setup waydroid-net.
Failed to setup waydroid-net.
(000581) [22:34:56] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000581) [22:34:56] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(002371) [22:34:56] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

(002371) [22:34:56] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(002457) [22:35:05] Starting waydroid session
(000581) [22:35:05] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 200: dnsmasq: not found
Failed to setup waydroid-net.
Failed to setup waydroid-net.
(000581) [22:35:06] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000581) [22:35:06] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(002457) [22:35:06] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

(002457) [22:35:06] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(002574) [22:36:27] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(002574) [22:36:27] *** output passed to waydroid stdout, not to this log ***
(003194) [22:48:05] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(003194) [22:48:05] *** output passed to waydroid stdout, not to this log ***

**Comment by lightkey-store** [comment]
@NONAME-2121237,  did you figure out it some how?

**Comment by NONAME-2121237** [comment]
I have no idea about this but [https://github.com/waydroid/waydroid/issues/537#issue-1391036647](url) here is a new way to solve that.

**Comment by NONAME-2121237** [comment]
> @NONAME-2121237, did you figure out it some how?

I have no idea about this but [https://github.com/waydroid/waydroid/issues/537#issue-1391036647](url) here is a new way to solve that.

**Comment by NONAME-2121237** [comment]
> @NONAME-2121237, did you figure out it some how?

I have no idea about this but [https://github.com/waydroid/waydroid/issues/537#issue-1391036647](url) here is a new way to solve that.
