### ISSUE TITLE
Waydroid does not start on WSLg

### ISSUE THREAD

**Issue by stelios333** [waydroid/waydroid#1217]
### Describe the bug

Whenever I run `waydroid session start` I get an OSError: container failed to start on WSLg

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Debian 13 (trixie) on Windows 11

### Kernel version

5.10.43.3-senjo-cont (The one from Telegram)

### Desktop Environment

None, wslg with weston

### GPU

Intel Iris Xe

### Logs

(000030) [11:10:03] New background process: pid=359, output=background
(000030) [11:10:03] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-start: waydroid: ../src/lxc/utils.c: lxc_mkdir_p: 236 Read-only file system - Failed to create directory "/usr/lib/x86_64-linux-gnu/lxc/rootfs/mnt/wslg/"
lxc-start: waydroid: ../src/lxc/conf.c: mount_entry_create_dir_file: 2623 Read-only file system - Failed to create directory "/usr/lib/x86_64-linux-gnu/lxc/rootfs/mnt/wslg/runtime-dir/wayland-0"
lxc-start: waydroid: ../src/lxc/conf.c: lxc_setup: 4415 Failed to setup mount entries
lxc-start: waydroid: ../src/lxc/start.c: do_start: 1272 Failed to setup container "waydroid"
lxc-start: waydroid: ../src/lxc/sync.c: sync_wait: 34 An error occurred in another process (expected sequence number 3)
lxc-start: waydroid: ../src/lxc/start.c: __lxc_start: 2107 Failed to spawn container "waydroid"
STOPPED
(000030) [11:10:03] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: main: 306 The container failed to start
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options
STOPPED
(000030) [11:10:03] waiting 10 seconds for container to start...
(000030) [11:10:04] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000030) [11:10:04] waiting 9 seconds for container to start...
(000030) [11:10:05] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000030) [11:10:05] waiting 8 seconds for container to start...
(000030) [11:10:06] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000030) [11:10:06] waiting 7 seconds for container to start...
(000030) [11:10:07] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000030) [11:10:07] waiting 6 seconds for container to start...
(000030) [11:10:08] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000030) [11:10:08] waiting 5 seconds for container to start...
(000030) [11:10:09] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000030) [11:10:09] waiting 4 seconds for container to start...
(000030) [11:10:10] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000030) [11:10:10] waiting 3 seconds for container to start...
(000030) [11:10:11] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000030) [11:10:11] waiting 2 seconds for container to start...
(000030) [11:10:12] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000030) [11:10:12] waiting 1 seconds for container to start...
(000320) [11:10:13] org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 189, in do_start
    helpers.lxc.start(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 397, in start
    wait_for_running(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 391, in wait_for_running
    raise OSError("container failed to start")
OSError: container failed to start

(000320) [11:10:13] OSError: container failed to start
(000373) [11:10:46] % tail -n 60 -F /var/lib/waydroid/waydroid.log

**Comment by Timbo303** [comment]
I have the same exact issue with this kernel.

**Comment by rama982** [comment]
same exact issue

**Comment by oemaix** [comment]
exactly the same issue.

**Comment by Adhjie** [comment]
The wsl kernel from telegram is outdated, there's a convo of me and others there. and someone said the kernel for it must be built from source with the android option selected on driver tab/selection page in
```
https://github.com/microsoft/WSL2-Linux-Kernel
Modify WSL2 kernel configs (optional):
$ make menuconfig KCONFIG_CONFIG=Microsoft/config-wsl
```
I think this would solved the problem here by using the latest kernel, and also will solve binder module problem from this PopOS issue:
https://github.com/waydroid/waydroid/issues/590#issuecomment-2621050637
> After asking in telegram, since anbox binder modules failed on my wsl ubuntu; the solution is to make a custom build kernel for wsl2 and picking android option on the driver selection of makeconfig menu. I can't do it now, since I'm busy. I'll do it later. the wsl kernel in telegram is outdated for current wsl2 version.

**Comment by facepunch01** [comment]
## waydroid log
```
(000464) [15:37:29] waiting 9 seconds for container to start...
(000623) [15:37:30] Skipping clipboard manager service because of missing pyclip package
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
(000623) [15:42:13] Clipboard service is not even started
(000464) [15:42:13] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
```
## Dmesg
```
[  228.518248] init: InitFatalReboot: signal 6
[  228.523747] init: #00 pc 00000000000aee54  /system/bin/init (android::init::InitFatalReboot(int)+208)
[  228.524548] init: #01 pc 00000000000af234  /system/bin/init (android::init::InstallRebootSignalHandlers()::$_22::__invoke(int)+32)
[  228.524958] init: #02 pc 000000000000078c  [vdso:0000007f89f91000]
[  228.525261] init: #03 pc 0000000000089ac4  /system/lib64/bootstrap/libc.so (abort+160)
[  228.526039] init: #04 pc 000000000004b10c  /system/lib64/libc++.so (abort_message+248)
[  228.526902] init: #05 pc 000000000004b224  /system/lib64/libc++.so (demangling_terminate_handler()+40)
[  228.528005] init: #06 pc 000000000004bdc4  /system/lib64/libc++.so (std::__terminate(void (*)())+12)
[  228.528301] init: #07 pc 000000000004bd6c  /system/lib64/libc++.so (std::terminate()+52)
[  228.529255] init: #08 pc 00000000000a18f0  /system/lib64/libc++.so (std::__1::thread::~thread()+24)
[  228.530235] init: #09 pc 00000000000efb2c  /system/lib64/bootstrap/libc.so (__cxa_finalize+148)
[  228.531055] init: #10 pc 00000000000eac30  /system/lib64/bootstrap/libc.so (exit+24)
[  228.531346] init: #11 pc 00000000000aec1c  /system/bin/init (android::init::RebootSystem(unsigned int, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)+188)
[  228.532934] init: #12 pc 00000000000ac84c  /system/bin/init (std::__1::__function::__func<android::init::HandlePowerctlMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_32, std::__1::allocator<android::init::HandlePowerctlMessage(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_32>, android::base::expected<void, android::base::ResultError> (android::init::BuiltinArguments const&)>::operator()(android::init::BuiltinArguments const&)+4648)
[  228.536894] init: #13 pc 0000000000040740  /system/bin/init (android::init::RunBuiltinFunction(std::__1::function<android::base::expected<void, android::base::ResultError> (android::init::BuiltinArguments const&)> const&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)+480)
[  228.539508] init: #14 pc 0000000000040860  /system/bin/init (android::init::Command::InvokeFunc(android::init::Subcontext*) const+140)
[  228.539837] init: #15 pc 000000000004133c  /system/bin/init (android::init::Action::ExecuteCommand(android::init::Command const&) const+76)
[  228.540154] init: #16 pc 0000000000041238  /system/bin/init (android::init::Action::ExecuteOneCommand(unsigned long) const+332)
[  228.540443] init: #17 pc 000000000006e994  /system/bin/init (android::init::ActionManager::ExecuteOneCommand()+184)
[  228.540715] init: #18 pc 0000000000083dbc  /system/bin/init (android::init::SecondStageMain(int, char**)+5584)
[  228.541038] init: #19 pc 000000000002f184  /system/bin/init (main+304)
[  228.541594] init: #20 pc 000000000008506c  /system/lib64/bootstrap/libc.so (__libc_init+108)
[  228.541838] init: Reboot ending, jumping to kernel
[  228.543581] waydroid0: port 1(vetheqWy4L) entered disabled state
[  228.544005] device vetheqWy4L left promiscuous mode
[  228.544011] waydroid0: port 1(vetheqWy4L) entered disabled state
[  228.597479] binder: 955 RLIMIT_NICE not set
[  228.597539] binder: 955 RLIMIT_NICE not set
[  228.597570] binder: 692:692 BC_DEAD_BINDER_DONE 0000000000000000 not found
[  228.597670] binder: 852:852 BC_DEAD_BINDER_DONE 0000000000000000 not found
[  228.707120] binder: 692:692 transaction failed 29189/-22, size 0-0 line 2917
```
dmesg then gets spammed with the last line
## zgrep -i -e android -e memfd -e ashmem /proc/config.gz
```
# Android
CONFIG_ASHMEM=y
# end of Android
# Android
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES=""
CONFIG_ANDROID_BINDER_IPC_SELFTEST=y
# end of Android
CONFIG_MEMFD_CREATE=y
```
## uname -a
```
Linux DESKTOP-QCC15PV 5.15.167.4-microsoft-standard-WSL2+ #1 SMP Wed Feb 12 09:29:38 CST 2025 aarch64 aarch64 aarch64 GNU/Linux
```

At least on arm64 even with a updated kernel it is still not functioning. However it could be related to #1387
