### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by seach-io** [waydroid/waydroid#1222]
### Describe the bug

When ran: sudo waydroid init
output:
"[17:33:50] Failed to load binder driver
[17:33:50] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.1.60-08594-g03a802b9a072
[17:33:50] ERROR: Binder node "binder" for waydroid not found
[17:33:50] See also: <https://github.com/waydroid>
Run 'waydroid log' for details."

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Debian 12.4 (Chrome OS flex [Linux Development Environment])

### Kernel version

6.1.60-08594-g03a802b9a072

### Desktop Environment

none

### GPU

Intel integrated (i5 6th gen)

### Logs

When ran "waydroid log"
output:
"(003698) [16:41:43] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 97, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(006076) [17:09:29] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.1.60-08594-g03a802b9a072
(006076) [17:09:29] Failed to load binder driver
(006076) [17:09:29] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.1.60-08594-g03a802b9a072
(006076) [17:09:29] ERROR: Binder node "binder" for waydroid not found
(006076) [17:09:29] See also: <https://github.com/waydroid>
(006076) [17:09:29] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 97, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(006117) [17:19:24] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.1.60-08594-g03a802b9a072
(006117) [17:19:24] Failed to load binder driver
(006117) [17:19:24] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.1.60-08594-g03a802b9a072
(006244) [17:33:40] ERROR: Action "init" needs root access
(006244) [17:33:40] See also: <https://github.com/waydroid>
(006244) [17:33:40] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 63, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "init" needs root access

(006247) [17:33:50] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.1.60-08594-g03a802b9a072
(006247) [17:33:50] Failed to load binder driver
(006247) [17:33:50] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.1.60-08594-g03a802b9a072
(006247) [17:33:50] ERROR: Binder node "binder" for waydroid not found
(006247) [17:33:50] See also: <https://github.com/waydroid>
(006247) [17:33:50] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 97, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(006250) [17:35:27] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(006250) [17:35:27] *** output passed to waydroid stdout, not to this log ***
"

**Comment by User8395** [comment]
1. Who in their right mind would choose to use ChromeOS?
2. If you're going to use ChromeOS, use the Brunch Framework which has native support for Android apps.

**Comment by Quackdoc** [comment]
You need to be running on a kernel with binder support.

**Comment by Interested-Deving-1896** [comment]
Couldn't, in theory, WayDroid be deployed through Brunch's Brioche . . . Since it also uses LXC?

https://github.com/sebanc/brioche

Brioche is also included in the Brunch Toolchain . . . Found here.

https://github.com/sebanc/brunch-toolchain
