### ISSUE TITLE
[BUG] ERROR: org.freedesktop.DBus.Error.NotSupported

### ISSUE THREAD

**Issue by ignxcy** [waydroid/waydroid#1232]
### Describe the bug

Everytime I'm trying to start a waydroid session, I'm getting this error:
[21:50:25] ERROR: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
[21:50:25] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Arch BTW x86_64

### Kernel version

6.6.10-zen1-1-zen

### Desktop Environment

Hyprland

### GPU

Intel UHD Graphics 620

### Logs

/var/lib/waydroid/waydroid.cfg:
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1704518256
vendor_datetime = 1704540089
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = anbox-binder
vndbinder = anbox-vndbinder
hwbinder = anbox-hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3

[properties]
/var/lib/waydroid/waydroid.prop:
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
waydroid.host.user=ignacy
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/ignacy/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-1
waydroid.background_start=false
waydroid.stub_sensors_hal=1
/var/lib/waydroid/waydroid_base.prop:
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
/var/lib/waydroid/waydroid.log:
(018805) [21:50:25] ERROR: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
(018805) [21:50:25] See also: <https://github.com/waydroid>
(018805) [21:50:25] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
                                                     ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/_dbus.py", line 209, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/_dbus.py", line 99, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dbus/bus.py", line 120, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

`sudo waydroid shell -- logcat -d | tee logcat.txt`
[21:53:01] WayDroid container is STOPPED

**Comment by zhuohoudeputao** [comment]
Meet this bug, too, on Arch 6.6.10-arch1-1

**Comment by George-Seven** [comment]
export $(dbus-launch)

**Comment by ignxcy** [comment]
It's in conflict with dbus :/

**Comment by TeamBattino** [comment]
I'm encountering the same issue, on Arch linux with kde 6..

**Comment by shahrooz1397** [comment]
i have the same problem 
Linux Arch-PC 6.9.6-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Fri, 21 Jun 2024 19:48:59 +0000 x86_64 GNU/Linux

[~]$ sudo waydroid session start                     
[10:59:02] ERROR: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
[10:59:02] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.

[~]$ waydroid session start          
[10:59:42] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
[~]$

**Comment by TacoDogg** [comment]
This still happens with kernel 6.10.2-arch1-1 and Waydroid 1.4.2.

**Comment by rhythmcache** [comment]
Same problem..
These commands fixed it

export WAYLAND_DISPLAY=wayland-0
sudo waydroid show-full-ui
sudo waydroid session start

**Comment by 4rtemis-4rrow** [comment]
same issue here

**Comment by SlapJackNpNp** [comment]
Hey, i'm using CachyOS Linux 
Kernel-Version: 6.16.5-2-cachyos (64-bit)
Grafik-Plattform: Wayland

i also get this error. Is there any way to fix this?

**Comment by clombt** [comment]
Also having the same issue:
Arch: amd64
Kernel: 7.0.11-arch1-1
Compositor: Hyprland
Waydroid version: 1.6.3
