### ISSUE TITLE
[BUG] OSError: container failed to start; "lxc-checkconfig" missing CONFIGs

### ISSUE THREAD

**Issue by Dyxen07** [waydroid/waydroid#1258]
### Describe the bug

I am a beginner when it comes to programming and a raspberry pi5 is very new for me.
So I run my Raspberry Pi5 8Gb through TigerVNC with wayland. I don't know how to fix the OSError: container failed to start in Waydroid with GAPPS. I have researched on the internet and Github but everything I have tryed to do it don't want to work even when I have formatted the SD-Card and flashed PiOS new. I have several times reinstall Waydroid and the problem don't go away. I have been trying it since a week and I never came to an Waydroid ui. After I checked the log it says something with "Failed to run lxc.".

So I know that 3 things in "Ceckpoint/Restore" are missing when I run lxc-checkconfig. But how can I fix that?

**OS:**
```
x@raspberrypi:~ $  cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**OSError:Container failed to start**
```
x@raspberrypi:~ $ waydroid --details-to-stdout show-full-ui
(009534) [15:43:53] Starting waydroid session
(009534) [15:44:03] org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 189, in do_start
    helpers.lxc.start(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 397, in start
    wait_for_running(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 391, in wait_for_running
    raise OSError("container failed to start")
OSError: container failed to start


(009534) [15:44:03] OSError: container failed to start
```

**Waydroid Log:**
```
x@raspberrypi:~ $ waydroid log
(002826) [17:38:37] Save config: /var/lib/waydroid/waydroid.cfg
(002826) [17:38:37] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(002826) [17:38:37] New background process: pid=18736, output=background
(002826) [17:38:37] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002826) [17:38:37] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
STOPPED
(002826) [17:38:37] waiting 10 seconds for container to start...
(002826) [17:38:38] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002826) [17:38:38] waiting 9 seconds for container to start...
(002826) [17:38:39] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002826) [17:38:39] waiting 8 seconds for container to start...
(002826) [17:38:40] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002826) [17:38:40] waiting 7 seconds for container to start...
(002826) [17:38:41] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002826) [17:38:41] waiting 6 seconds for container to start...
(002826) [17:38:42] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002826) [17:38:42] waiting 5 seconds for container to start...
(002826) [17:38:43] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002826) [17:38:43] waiting 4 seconds for container to start...
(002826) [17:38:44] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002826) [17:38:44] waiting 3 seconds for container to start...
(002826) [17:38:45] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002826) [17:38:45] waiting 2 seconds for container to start...
(002826) [17:38:46] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002826) [17:38:46] waiting 1 seconds for container to start...
(018684) [17:38:47] org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 189, in do_start
    helpers.lxc.start(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 397, in start
    wait_for_running(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 391, in wait_for_running
    raise OSError("container failed to start")
OSError: container failed to start


(018684) [17:38:47] OSError: container failed to start
(018999) [17:41:14] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(018999) [17:41:14] WayDroid container is STOPPED
```

**lxc-checkconfig:**
```
x@raspberrypi:~ $ "lxc-checkconfig"
LXC version 5.0.2
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-6.1.0-rpi7-rpi-2712


--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
Network namespace: enabled


--- Control groups ---
Cgroups: enabled
Cgroup namespace: enabled
Cgroup v1 mount points: 
Cgroup v2 mount points: 
 - /sys/fs/cgroup
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled


--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, not loaded
FUSE (for use with lxcfs): enabled, loaded


--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: missing
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: missing
CONFIG_NETLINK_DIAG: missing
File capabilities: enabled


Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Raspberry PiOS 64-Bit

### Kernel version

6.1.0-rpi7-rpi-2712

### Desktop Environment

Pixel (wayland)

### GPU

Broadcom VideoCore VII

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by firemeteorxx** [comment]
Your lxc-checkconfig result looks okay to me. But that may not be enough...

Are you on a custom built kernel or distro provided kernel? Waydroid is picky on kernel config. Distro kernels are usually fine. 

In my case my custom kernel passed lxc-checkconfig and could run Anbox just fine, but still failed on Waydroid. It took me quite some time to figure out that I missed the CONFIG_CGROUP_BPF in my kernel and was not able to get the Android container through the boot process. 

logcat log could be helpful if your container run for a short while but finally ends up with a STOPPED state. You could also manually execute the lxc command find from the log to get more verbose log info.

**Comment by Dyxen07** [comment]
@firemeteorxx thanks for your answer.

> logcat log could be helpful if your container run for a short while but finally ends up with a STOPPED state. You could also manually execute the lxc command find from the log to get more verbose log info.

I have tryed to do the logcat log, but everything I have been trying the logcat file was empty. 
I don't even get a window or a screen with waydroid. The only way I get output is via the Terminal, but all of the output is an error and the container/session is stopped.

> Are you on a custom built kernel or distro provided kernel? Waydroid is picky on kernel config. Distro kernels are usually fine.

I have nothing customize on the kernal. I just installed Raspberry PiOS 64-Bit and on the Pi5 Waydroid with the Ubuntu/Debian install instruction, because the PiOS is based on Debain. I have seen videos of a guy running Linux Container (LXC) on the Raspberry Pi with PiOS and when he checked lxc-checkconfig nothing in _--- Checkpoint/Restore ---_ was missing.

What comes in my mind right now is that maybe Waydroid can't run on Raspberry PiOS. Is that possible?
Shut I switch to Ubuntu?

I still don't know how to edit the lxc that the 3 files arent't missing anymore.
