### ISSUE TITLE
[BUG] Container can't start, errors

### ISSUE THREAD

**Issue by ruzko** [waydroid/waydroid#1281]
### Describe the bug

**Expected behaviour**
1. Install waydroid as defined in docs
2. Waydroid-container.service starts automatically
3. Waydroid works

**Actual behaviour**
1. Waydroid installed using `sudo waydroid init -v https://ota.waydro.id/vendor -c https://ota.waydro.id/system -r lineage`, because defining images via the gui [as requested in docs](https://docs.waydro.id/usage/install-on-desktops) doesn't work.
2. Waydroid service and session can't start

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Fedora Kinoite Atomic [f39/f40]

### Kernel version

6.7 and 6.8.0-0.rc4.20240212git716f4aaa7b48.35.fc40.x86_64

### Desktop Environment

KDE Plasma 5.27.10 and 6.0rc2

### GPU

Nvidia GTX1070 mobile

### Logs

Github doesn't support attaching `.log` files... so I've just pasted them here

/var/lib/waydroid/waydroid.cfg
```
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1707542245
vendor_datetime = 1707564121
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = binder
vndbinder = vndbinder
hwbinder = hwbinder

[properties]
```

/var/lib/waydroid/waydroid.prop
no file, since waydroid doesn't start

/var/lib/waydroid/waydroid_base.prop
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
```

/var/lib/waydroid/waydroid.log
```
(014097) [09:04:39] ERROR: Action "init" needs root access
(014097) [09:04:39] See also: <https://github.com/waydroid>
(014097) [09:04:39] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 63, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "init" needs root access

(014122) [09:04:48] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1
(014122) [09:04:48] See also: <https://github.com/waydroid>
(014122) [09:04:48] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 65, in setup_config
    raise ValueError(
ValueError: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1

(014249) [09:06:07] % mkdir -p /dev/binderfs
(014249) [09:06:07] % mount -t binder binder /dev/binderfs
(014249) [09:06:07] % ln -s /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/features /dev/binderfs/vndbinder /dev/binderfs/hwbinder /dev/binderfs/binder /dev/binderfs/binder-control /dev/
(014249) [09:06:07] Save config: /var/lib/waydroid/waydroid.cfg
(014249) [09:06:07] % mkdir -p /var/lib/waydroid/cache_http
(014249) [09:06:07] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20240210-VANILLA-waydroid_x86_64-system.zip/download
(014249) [09:07:13] Validating system image
(014249) [09:07:14] Extracting to /var/lib/waydroid/images
(014249) [09:07:23] Save config: /var/lib/waydroid/waydroid.cfg
(014249) [09:07:23] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-18.1-20240210-MAINLINE-waydroid_x86_64-vendor.zip/download
(014249) [09:07:41] Validating vendor image
(014249) [09:07:42] Extracting to /var/lib/waydroid/images
(014249) [09:07:44] Save config: /var/lib/waydroid/waydroid.cfg
(014249) [09:07:44] % modprobe -q ashmem_linux
(014249) [09:07:44] % lxc-info --version
4.0.12
(014249) [09:07:44] % mkdir -p /var/lib/waydroid/lxc/waydroid
(014249) [09:07:44] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(014249) [09:07:44] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(014249) [09:07:44] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(014249) [09:07:44] % systemctl is-active -q apparmor
(014249) [09:07:44] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(014472) [09:09:08] Starting waydroid session
(014472) [09:09:08] org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
(014472) [09:09:08] WayDroid container is not listening
(014863) [09:11:39] ERROR: org.freedesktop.DBus.Error.AccessDenied: Request to own name refused by policy
(014863) [09:11:39] See also: <https://github.com/waydroid>
(014863) [09:11:39] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 81, in main
    dbus_name_scope = dbus.service.BusName("id.waydro.Container", dbus.SystemBus(), do_not_queue=True)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/dbus/service.py", line 134, in __new__
    retval = bus.request_name(name, name_flags)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/dbus/bus.py", line 299, in request_name
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/site-packages/dbus/connection.py", line 634, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Request to own name refused by policy

(014887) [09:11:52] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(014887) [09:11:52] *** output passed to waydroid stdout, not to this log ***
(004623) [10:00:53] Starting waydroid session
(004623) [10:00:53] org.freedesktop.DBus.Error.ServiceUnknown: Could not activate remote peer: startup job failed.
(004623) [10:00:53] WayDroid container is not listening
(004651) [10:01:04] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(004651) [10:01:04] *** output passed to waydroid stdout, not to this log ***
````

`sudo waydroid shell -- logcat -d | tee logcat.txt`
no output since container service can't start

`sudo dmesg | tee dmesg.txt`

systemctl status waydroid-container.service
```
× waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled; preset: enabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: failed (Result: exit-code
[dmesg.txt](https://github.com/waydroid/waydroid/files/14277683/dmesg.txt)
) since Wed 2024-02-14 10:28:36 CET; 6s ago
    Process: 6987 ExecStartPre=/usr/bin/ln -sf /dev/binderfs/binder /dev/binderfs/vndbinder /dev/binderfs/hwbinder /dev/ (code=exited, status=0/SUCCESS)
    Process: 6989 ExecStart=/usr/bin/waydroid -w container start (code=exited, status=1/FAILURE)
   Main PID: 6989 (code=exited, status=1/FAILURE)
        CPU: 124ms

feb. 14 10:28:35 fedora systemd[1]: Starting waydroid-container.service - Waydroid Container...
feb. 14 10:28:36 fedora waydroid[6989]: Run 'waydroid log' for details. Alternatively you can use '--details-to-stdout' to get more output, e.g. 'waydroid --details-to-stdout init'.
feb. 14 10:28:36 fedora systemd[1]: waydroid-container.service: Main process exited, code=exited, status=1/FAILURE
feb. 14 10:28:36 fedora systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
feb. 14 10:28:36 fedora systemd[1]: Failed to start waydroid-container.service - Waydroid Container
```

journalctl -xeu waydroid-container.service
```
feb. 14 09:50:43 fedora systemd[1]: Starting waydroid-container.service - Waydroid Container...
░░ Subject: A start job for unit waydroid-container.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has begun execution.
░░ 
░░ The job identifier is 337.
feb. 14 09:50:44 fedora waydroid[1310]: Run 'waydroid log' for details. Alternatively you can use '--details-to-stdout' to get more output, e.g. 'waydroid --details-to-stdout init'.
feb. 14 09:50:44 fedora systemd[1]: waydroid-container.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit waydroid-container.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
feb. 14 09:50:44 fedora systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit waydroid-container.service has entered the 'failed' state with result 'exit-code'.
feb. 14 09:50:44 fedora systemd[1]: Failed to start waydroid-container.service - Waydroid Container.
░░ Subject: A start job for unit waydroid-container.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has finished with a failure.
░░ 
░░ The job identifier is 337 and the job result is failed.
feb. 14 10:00:53 fedora systemd[1]: Starting waydroid-container.service - Waydroid Container...
░░ Subject: A start job for unit waydroid-container.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has begun execution.
░░ 
░░ The job identifier is 4895.
feb. 14 10:00:53 fedora waydroid[4631]: Run 'waydroid log' for details. Alternatively you can use '--details-to-stdout' to get more output, e.g. 'waydroid --details-to-stdout init'.
feb. 14 10:00:53 fedora systemd[1]: waydroid-container.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit waydroid-container.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
feb. 14 10:00:53 fedora systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit waydroid-container.service has entered the 'failed' state with result 'exit-code'.
feb. 14 10:00:53 fedora systemd[1]: Failed to start waydroid-container.service - Waydroid Container.
░░ Subject: A start job for unit waydroid-container.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has finished with a failure.
░░ 
░░ The job identifier is 4895 and the job result is failed.
feb. 14 10:00:53 fedora systemd[1]: Starting waydroid-container.service - Waydroid Container...
░░ Subject: A start job for unit waydroid-container.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has begun execution.
░░ 
░░ The job identifier is 5040.
feb. 14 10:00:53 fedora waydroid[4637]: Run 'waydroid log' for details. Alternatively you can use '--details-to-stdout' to get more output, e.g. 'waydroid --details-to-stdout init'.
feb. 14 10:00:53 fedora systemd[1]: waydroid-container.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit waydroid-container.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
feb. 14 10:00:53 fedora systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit waydroid-container.service has entered the 'failed' state with result 'exit-code'.
feb. 14 10:00:53 fedora systemd[1]: Failed to start waydroid-container.service - Waydroid Container.
░░ Subject: A start job for unit waydroid-container.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has finished with a failure.
░░ 
░░ The job identifier is 5040 and the job result is failed.
feb. 14 10:28:35 fedora systemd[1]: Starting waydroid-container.service - Waydroid Container...
░░ Subject: A start job for unit waydroid-container.service has begun execution
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has begun execution.
░░ 
░░ The job identifier is 8792.
feb. 14 10:28:36 fedora waydroid[6989]: Run 'waydroid log' for details. Alternatively you can use '--details-to-stdout' to get more output, e.g. 'waydroid --details-to-stdout init'.
feb. 14 10:28:36 fedora systemd[1]: waydroid-container.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ An ExecStart= process belonging to unit waydroid-container.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
feb. 14 10:28:36 fedora systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ The unit waydroid-container.service has entered the 'failed' state with result 'exit-code'.
feb. 14 10:28:36 fedora systemd[1]: Failed to start waydroid-container.service - Waydroid Container.
░░ Subject: A start job for unit waydroid-container.service has failed
░░ Defined-By: systemd
░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
░░ 
░░ A start job for unit waydroid-container.service has finished with a failure.
░░ 
░░ The job identifier is 8792 and the job result is failed.

````

**Comment by kerneis-anssi** [comment]
Probably related: https://github.com/waydroid/waydroid/discussions/681

**Comment by kerneis-anssi** [comment]
@ruzko I face the same issue on Fedora Silverblue. I don't have a fix, but as a work-around, it works for me to start the daemon manually instead of via a systemd service: https://docs.waydro.id/usage/install-on-desktops#manually-starting-waydroid
