### ISSUE TITLE
Skipping clipboard manager service because of missing pyclip package

### ISSUE THREAD

**Issue by GuyGuyute** [waydroid/waydroid#1300]
I'm using Ubuntu 22.04.  On "waydroid session start" I receive the error:  "Skipping clipboard manager service because of missing pyclip package".  I've followed the directions to create a virtual environment for pyclip.  It appears to be installed correctly.  I can execute pyclip from the terminal.  The path to pyclip is exported in $HOME/.bashrc.

Any help or advice would be greatly appreciated.

Here's the detail of the pyclip install process I used:

```
cd ~

sudo apt install python3.10-venv
sudo apt install python3-pip
sudo apt install wl-clipboard

python3 -m venv ~/.venvs/pyclip
source ~/.venvs/pyclip/bin/activate
pip install pyclip
deactivate
mkdir "$HOME/bin"
cd "$HOME/bin"
ln -s ../.venvs/pyclip/bin/pyclip
echo 'export PATH="$HOME/bin:$PATH"' >> "$HOME/.bashrc"

shutdown -r now

```

![Screenshot from 2024-02-27 15-59-07_defaced](https://github.com/waydroid/waydroid/assets/161534073/33924e22-e12e-4106-88b8-a837542fc225)

**Comment by GuyGuyute** [comment]
Adding a symlink of the pyclip directory in the venv to /usr/lib/waydroid/ removed the error, but, copy-paste still does not work both from waydroid to the host and from the host to the guest.

```
cd /usr/lib/waydroid
sudo ln -s $HOME/.venvs/pyclip
```

![Screenshot from 2024-02-28 12-01-23_defaced](https://github.com/waydroid/waydroid/assets/161534073/d87e4e50-b3f8-473c-9036-f9a8ed9568c6)

**Comment by GuyGuyute** [comment]
Found it!  I needed python3.11.

```
sudo apt install python3.11
sudo apt install python3.11-venv
```

Now the shared clipboard is working.

**Comment by Hash6232** [comment]
I tried following your instructions but although I managed to make the warning in the terminal disappear symlinking the pyclicp venv directory, I still have no shared clipboard available both toward and from waydroid.


```bash
[11:58:06] Starting waydroid session
[gbinder] Service manager /dev/anbox-binder has appeared
[11:58:16] Android with user 0 is ready
[11:58:16] Desktop file '/home/user/.local/share/applications//Waydroid.desktop' is not writeable, not updating it
```
```
python3.12-venv/noble-updates,noble-security,now 3.12.3-1ubuntu0.1 amd64 [installed]
python3.12/noble-updates,noble-security,now 3.12.3-1ubuntu0.1 amd64 [installed]
python3/noble,now 3.12.3-0ubuntu1 amd64 [installed]
```
```bash
$ uname -vsr
Linux 6.8.0-40-generic #40-Ubuntu SMP PREEMPT_DYNAMIC Fri Jul  5 10:34:03 UTC 2024

$ ls /usr/lib/waydroid/ -l
total 16
drwxr-xr-x 4 root root 4096 Aug 19 22:12 data
drwxr-xr-x 2 root root 4096 Aug 19 22:12 __pycache__
lrwxrwxrwx 1 root root   35 Aug 21 11:40 pyclip -> /home/user/.local/share/venv/pyclip
drwxr-xr-x 8 root root 4096 Aug 19 22:12 tools
-rwxr-xr-x 1 root root  228 Aug  7 22:58 waydroid.py

$ ls ~/.local/share/venv/pyclip/ -l
total 16
drwxrwxr-x 2 user user 4096 Aug 20 16:59 bin
drwxrwxr-x 3 user user 4096 Aug 20 16:58 include
drwxrwxr-x 3 user user 4096 Aug 20 16:58 lib
lrwxrwxrwx 1 user user    3 Aug 20 16:58 lib64 -> lib
-rw-rw-r-- 1 user user  174 Aug 20 16:58 pyvenv.cfg
```

**Comment by DeutscheGabanna** [comment]
I cannot get the common clipboard working.

```
> pacman -Qs pyclip  
local/python-pyclip 0.7.0-5 Cross-platform clipboard utilities supporting both binary and text data
```

```
> waydroid show-full-ui
[23:24:13] Starting waydroid session
[23:24:13] Skipping clipboard manager service because of missing pyclip package
```

This might be useful to know - when I try to run waydroid with my main conda profile activated, it fails:

```
> waydroid show-full-ui
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus' 
```

But when I deactivate conda, wayland runs properly (although still without discovering pyclip):

```
> conda deactivate               
> waydroid show-full-ui          
[23:55:03] Starting waydroid session
[23:55:03] Skipping clipboard manager service because of missing pyclip package
[gbinder] Service manager /dev/anbox-binder has appeared
```

It seems like pyclip installed itself in conda for 3.10 - do I need the pyclip for 3.11? Maybe that's why it isn't working?

```
> pacman -Ql python-pyclip           
...
python-pyclip /home/deutschegabanna/miniconda3/lib/python3.10/site-packages/pyclip/
python-pyclip /home/deutschegabanna/miniconda3/bin/pyclip
...
```

Pyclip "on its own" in the terminal seems to work correctly when I test it like this:
```

> python -m pyclip paste
[outputs what i had in clipboard no problem]
```

Here's my $PATH:

```
> echo $PATH               
/home/deutschegabanna/miniconda3/bin:
/home/deutschegabanna/miniconda3/condabin:
/home/deutschegabanna/.local/share/zinit/polaris/bin:
/usr/local/sbin:/usr/local/bin:
/usr/bin:
/usr/lib/jvm/default/bin:
/usr/bin/site_perl:
/usr/bin/vendor_perl:
/usr/bin/core_perl:
/home/deutschegabanna/script
```
