### ISSUE TITLE
[BUG] Initialize Waydroid - Download stuck with message "Waiting for waydroid container service..." but service is currently runnign 

### ISSUE THREAD

**Issue by daivolt** [waydroid/waydroid#1305]
### Describe the bug

As per instructions followed in https://docs.waydro.id/usage/install-on-desktops#ubuntu-debian-and-derivatives
1. sudo apt install curl ca-certificates -y
2. curl https://repo.waydro.id | sudo bash
3. sudo apt install waydroid -y
4. Started Waydroid from the applications menu.
5. Clicked on Download (https://ota.waydro.id/system https://ota.waydro.id/vendor)

"Waiting for waydroid container service..." is displayed and no download starts after.

Verified the service is active:
- sudo systemctl enable --now waydroid-container
- systemctl status waydroid-container.service returns:

```
waydroid-container.service - Waydroid Container
     Loaded: loaded (/lib/systemd/system/waydroid-container.service; enabled; >
     Active: active (running) since Sun 2024-03-03 03:56:18 -03; 30min ago
   Main PID: 28728 (waydroid)
      Tasks: 17 (limit: 18656)
     Memory: 35.2M
     CGroup: /system.slice/waydroid-container.service
             ├─28728 /usr/bin/python3 /usr/bin/waydroid -w container start
             ├─30942 /usr/bin/python3 /usr/bin/waydroid -w container start
             ├─31000 /usr/bin/python3 /usr/bin/waydroid -w container start
             ├─31086 /usr/bin/python3 /usr/bin/waydroid -w container start
             └─31101 /usr/bin/python3 /usr/bin/waydroid -w container start
```

I'm unable to proceed with the installation process. 

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Ubuntu 22.04 and Ubuntu 20.04

### Kernel version

5.15.0-94-generic

### Desktop Environment

Gnome 3.36.8

### GPU

Radeon RX 570 | AMD® Radeon(tm) vega 8 graphics

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

[dmesg.txt](https://github.com/waydroid/waydroid/files/14472138/dmesg.txt)
[waydroid.log](https://github.com/waydroid/waydroid/files/14472139/waydroid.log)

**Comment by githottub** [comment]
I was seeing same thing on Ubuntu 22.04 but if patient and wait 2-3 minutes it then fails due to:

Waiting for waydroid container service...
Failed to load binder driver
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.5.0-1015-azure
Binder node "binder" for waydroid not found

Waydroid was installed exactly per current Ubuntu installation instructions.

**Comment by YuxuanQin** [comment]
I have the same problem on Debian Bookworm, and I tried manually initialize it use command `waydroid init -f -i /etc/waydroid-extra/images`, but no good news. When I used `Ctrl c` to interrupt it, there was a Traceback:

```pyhton
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 9, in <module>
    sys.exit(tools.main())
             ^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 62, in setup_config
    system_request = helpers.http.retrieve(args.system_ota)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/http.py", line 143, in retrieve
    with urllib.request.urlopen(req) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.11/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.11/http/client.py", line 941, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
```

Does anyone know how to solve this problem?

**Comment by feer9** [comment]
I'm seeing the same output than @YuxuanQin, it's getting stuck at `sock.connect(sa)`.

**Comment by feer9** [comment]
> I'm seeing the same output than @YuxuanQin, it's getting stuck at `sock.connect(sa)`.

Ok I've just let it there for a few hours and it completed, the download is just extremely slow but it finally finishes

**Comment by ismaelsilvabetter** [comment]
Olha no meu caso m]deu certo qundao eu mudedi o DNS para o DNS publico do GOOGLE

**Comment by codecnotsupported** [comment]
Same issue.

**Comment by codecnotsupported** [comment]
Found a solution.
It's a permissions issue.
`/var/lib/waydroid` Required root permissions.
After the download seemed to be completed I closed the downloader and ran.
`sudo chown $USER:$USER /var/lib/waydroid -R`
