### ISSUE TITLE
[BUG] 'Binder node "vndbinder" for waydroid not found'

### ISSUE THREAD

**Issue by joshudson** [waydroid/waydroid#1321]
### Describe the bug

On trying to install to debian it installs a waydroid that doesn't work at all.

The original problem was it can't find its kernel modules. The solution was found in the other bug links to go install this anbox kernel module provider. Bug? Shouldn't these be declared dependencies? No matter; I suppose you could just list them in the installation instructions.

On clearing that (and rebooting) I get: Binder node "vndbinder" for waydroid not found

The error message is intractible and the installation instructions are useless. There's a reference to popos in the issue list; but those instructions don't make sense in context.

I think the reference to anbox modules install is simply wrong and needs fixing; the only other possibility I can think of is you have a number of nondeclared dependencies.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Debian bookworm x64

### Kernel version

6.1.0-17-amd64

### Desktop Environment

wayland terminal

### GPU

AMD integrated

### Logs

Log output:
```
(005080) [17:47:40] % modprobe binder_linux devices="anbox-vndbinder,anbox-hwbinder"
(005080) [17:47:40] ERROR: Binder node "vndbinder" for waydroid not found
(005080) [17:47:40] See also: <https://github.com/waydroid>
(005080) [17:47:40] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 97, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 141, in setupBinderNodes
    raise OSError('Binder node "vndbinder" for waydroid not found')
OSError: Binder node "vndbinder" for waydroid not found
```

dmesg:
```
[   15.747992] NET: Registered PF_BLUETOOTH protocol family
[   15.747993] Bluetooth: HCI device and connection manager initialized
[   15.747996] Bluetooth: HCI socket layer initialized
[   15.747998] Bluetooth: L2CAP socket layer initialized
[   15.748000] Bluetooth: SCO socket layer initialized
[   15.755295] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   15.755297] Bluetooth: BNEP filters: protocol multicast
[   15.755299] Bluetooth: BNEP socket layer initialized
[   15.760197] Generic FE-GE Realtek PHY rxxxxxxx: attached PHY driver (mii_bus:phy_addr=rxxxxxxxx, irq=MAC)
[   15.884734] rxxxxxxxx eth0: Link is Down
[   18.969090] rxxxxxxxx eth0: Link is Up - 1Gbps/Full - flow control rx/tx
[   18.969108] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   18.975728] 8021q: 802.1Q VLAN Support v1.8
```

The rest of the requested diagnostics don't exist

**Comment by black13ua** [comment]
the same problem ((

**Comment by zyxhere** [comment]
Duplicate of https://github.com/waydroid/waydroid/issues/801 ?

**Comment by joshudson** [comment]
@zyxhere : No. My install failed earlier in booting.

**Comment by zyxhere** [comment]
Whats the output of `grep -i -e android -e memfd -e ashmem "/boot/config-$(uname -r)"` ? https://docs.waydro.id/debugging/getting-essential-information
Your kernel doesn't seems to have `binder` don't know why since waydroid worked for me on debian 12 without any problems

**Comment by joshudson** [comment]
Answer:

```
CONFIG_X86_ANDROID_TABLETS=m
# Android
CONFIG_ANDROID_BINDER_IPC=m
# CONFIG_ANDROID_BINDERFS is not set
CONFIG_ANDROID_BINDER_DEVICES="binder"
# CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set
# end of Android
CONFIG_MEMFD_CREATE=y
```

I think the problem is you are missing package dependency declarations so things you think must exist don't.

**Comment by zyxhere** [comment]
Heres mine
```
CONFIG_MEMFD_CREATE=y
CONFIG_X86_ANDROID_TABLETS=m
# Android
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
# CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set
# end of Android
```
But I haven't ran waydroid on this kernel so not sure if it will work.
I'll try running waydroid later and see if it works with these configs

**Comment by zyxhere** [comment]
See: https://wiki.archlinux.org/title/Waydroid#Kernel_Modules
Duplicate of https://github.com/waydroid/waydroid/issues/801
