### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hhhhhge** [waydroid/waydroid#1329]
### Describe the bug

when i wanted to run it,it didnt work

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Ubuntu 22.04 arm64

### Kernel version

5.10.110-rockchip-rk3588

### Desktop Environment

GNOME 42.9

### GPU

mali

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by hhhhhge** [comment]
[logs.zip](https://github.com/waydroid/waydroid/files/14635975/logs.zip)

**Comment by lexiismadd** [comment]
same issue here

**Comment by effettot** [comment]
same issue on debian 12

**Comment by prljav** [comment]
same issue, debian 12

**Comment by starise-wg** [comment]
I have also encountered the same problem. Have you solved it? Thank you very much for sharing your experience

`(027488) [10:18:57] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(027488) [10:18:57] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(027488) [10:18:58] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(027488) [10:18:58] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(027488) [10:18:58] % umount /var/lib/waydroid/rootfs/vendor
(027488) [10:18:58] % umount /var/lib/waydroid/rootfs/vendor
(027488) [10:18:58] % umount /var/lib/waydroid/rootfs
(027488) [10:18:58] % umount /var/lib/waydroid/rootfs
(030065) [10:19:23] ERROR: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
(030065) [10:19:23] See also: <[https://github.com/waydroid>](https://github.com/waydroid%3E)
(030065) [10:19:23] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message`
