### ISSUE TITLE
[BUG] dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply

### ISSUE THREAD

**Issue by QuetzalcoutlDev** [waydroid/waydroid#1368]
### Describe the bug

I had uninstalled Waydroid so I could reinstall it, but when I wanted to start it again it only gave me dbus error messages

Does anyone know how to fix it?

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Devuan 5

### Kernel version

6.1.0-20-amd64

### Desktop Environment

Plasma 5.27.5

### GPU

Intel HD Graphics 4600

### Logs

[waydroid.log](https://github.com/waydroid/waydroid/files/15045993/waydroid.log)

**Comment by Quackdoc** [comment]
can you completely reinstall waydroid with the steps provided here? https://docs.waydro.id/usage/install-on-desktops#reinstalling-waydroid

**Comment by Vance-ng-vn** [comment]
run startx and it's fixed for me :))

**Comment by MindastDaMindTaker** [comment]
I've been having a similar issue recently. I am having the same issues on multiple machines. 

My desktop is running Bazzite Gnome Nvidia Distro. AMD Ryzen 7 3800X with a Geforce RTX 2070 Super

My Laptop is running Bazzite-Deck:Stable using KDE. AMD Ryzen 9 6900HS with Radeon RX 6700S and Intergrated Graphics.

I have tried everything under the sun, but since the recent update I either get a black screen that stays up when Waydroid tries to run, or I get Waydroid to open up and immediately close after. 

I have followed the instructions on the guide, I have reset waydroid, rebooted my PC, deleted all remnants of waydroid I could from both machines, but I was only able to get it to run once on each machine using waydroid show-full-ui

Now they are not working on either machine.

On my Laptop, I am getting the following message: 

```
bazzite@bazzite:~$ waydroid show-full-ui
[16:03:37] Starting waydroid session
[16:03:38] Introspect error on :1.479:/ContainerManager: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Remote peer disconnected
[16:03:38] WayDroid container is not listening
```

On my desktop i am currently getting just a full black screen, but looking through the logs this is what is showing up:

```
(115581) [16:05:48] Starting waydroid session
(086069) [16:05:48] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
Warning: ZONE_ALREADY_SET: 'waydroid0' already bound to 'trusted'
success
(086069) [16:05:48] % chmod 777 -R /dev/dri
(086069) [16:05:48] % chmod 777 -R /dev/video2
(086069) [16:05:48] % chmod 777 -R /dev/video1
(086069) [16:05:48] % chmod 777 -R /dev/video0
(086069) [16:05:48] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(086069) [16:05:48] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(086069) [16:05:48] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(086069) [16:05:48] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(086069) [16:05:48] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(086069) [16:05:48] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(086069) [16:05:48] Save config: /var/lib/waydroid/waydroid.cfg
(086069) [16:05:48] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(086069) [16:05:48] New background process: pid=115646, output=background
(086069) [16:05:48] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(086069) [16:05:48] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(086069) [16:05:48] waiting 10 seconds for container to start...
(115581) [16:05:57] waydroidusermonitor: Received transaction: 1
(115581) [16:05:57] Android with user 0 is ready
(086069) [16:06:29] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(086069) [16:06:29] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: ../src/lxc/utils.c: run_buffer: 571 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 986 Failed to run lxc.hook.post-stop for container "waydroid"
(086069) [16:06:29] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(086069) [16:06:29] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(086069) [16:06:30] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(086069) [16:06:30] % umount /var/lib/waydroid/rootfs/vendor
(086069) [16:06:30] % umount /var/lib/waydroid/rootfs/vendor
(086069) [16:06:30] % umount /var/lib/waydroid/rootfs
(086069) [16:06:30] % umount /var/lib/waydroid/rootfs
(124072) [16:06:32] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(124072) [16:06:32] *** output passed to waydroid stdout, not to this log ***
```
I've spent multiple hours on this yesterday and today and I'm just going to call it quits unless I get some new insight on the matter. I'm hoping someone can shine some light on this.

P.S. - I've also tried a sudo startx command on both PCs and I am getting error messages on both as well. Don't know if its the intended behavior or not but Getting Failed to create screen resources on both machines

**Comment by alvv-z** [comment]
@MindastDaMindTaker I am having the same error now, even though it used to work. I changed my graphics driver and kernel since it last worked properly, so that might be part of the issue. Even a clean reinstallation doesn't fix it for me. Sometimes, it just starts the first time after a reinstallation and then hangs when stopping. I managed to boilerplate-fix it by killing the `lxc-start` process. After that, I can start another session and UI. When stopping it, I still have to kill the `lxc-start` process again, however. I found the following in my `waydroid.log`, but I'm not sure whether it comes from me killing a process or if it is the underlying issue:
```py
(7191) [Sat, 14 Feb 2026 16:26:04] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
(7191) [Sat, 14 Feb 2026 16:31:54] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(7191) [Sat, 14 Feb 2026 16:31:54] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(7191) [Sat, 14 Feb 2026 16:31:54] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
(7191) [Sat, 14 Feb 2026 16:31:54] RUNNING
(7191) [Sat, 14 Feb 2026 16:31:54] 
Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/helpers/logging.py", line 96, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 27, in Start
    uid = dbus_info.GetConnectionUnixUser(sender)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
                                          self._object_path,
                                          ^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
                                          args,
                                          ^^^^^
                                          **keywords)
                                          ^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 696, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
        message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NameHasNoOwner: Could not get UID of name ':1.632': no such name
```

**Comment by alvv-z** [comment]
After a recent update of Ubuntu, it seems to work again. Not sure what fixed it.
