### ISSUE TITLE
Fedora logs out when I Alt + F4 the Waydroid session

### ISSUE THREAD

**Issue by saadfrhan** [waydroid/waydroid#1390]
### Describe the bug

When I Alt + F4 the Waydroid session, my Fedora logs out and doesn't start again until I restart the session.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Fedora 40 amd64

### Kernel version

6.8.8-300.fc40.x86_64

### Desktop Environment

GNOME 46

### GPU

Intel i7-4600U (4) @ 3.300GHz

### Logs

/var/lib/waydroid/waydroid.cfg
```
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1714195056
vendor_datetime = 1714216970
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = binder
vndbinder = vndbinder
hwbinder = hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3

[properties]
```
/var/lib/waydroid/waydroid.prop
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
waydroid.host.user=saadfarhan
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/saadfarhan/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-0
waydroid.background_start=true
waydroid.stub_sensors_hal=1
```
/var/lib/waydroid/waydroid_base.prop
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
```
/var/lib/waydroid/waydroid.log
```
(042894) [20:34:32] Save config: /var/lib/waydroid/waydroid.cfg
(042894) [20:34:32] % mkdir -p /var/lib/waydroid/cache_http
(042894) [20:34:32] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20240427-GAPPS-waydroid_x86_64-system.zip/download
(044178) [20:48:33] Save config: /var/lib/waydroid/waydroid.cfg
(044178) [20:48:33] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20240427-VANILLA-waydroid_x86_64-system.zip/download
(044178) [21:49:14] Validating system image
(044178) [21:49:16] Extracting to /var/lib/waydroid/images
(044178) [21:49:24] Save config: /var/lib/waydroid/waydroid.cfg
(044178) [21:49:27] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-18.1-20240427-MAINLINE-waydroid_x86_64-vendor.zip/download
(044178) [22:06:37] Validating vendor image
(044178) [22:06:37] Extracting to /var/lib/waydroid/images
(044178) [22:06:39] Save config: /var/lib/waydroid/waydroid.cfg
(044178) [22:06:39] % modprobe -q ashmem_linux
(044178) [22:06:39] % lxc-info --version
5.0.3
(044178) [22:06:39] % mkdir -p /var/lib/waydroid/lxc/waydroid
(044178) [22:06:39] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(044178) [22:06:39] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(044178) [22:06:39] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(044178) [22:06:39] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(000943) [23:55:48] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000943) [23:55:48] % modprobe -q ashmem_linux
(000943) [23:55:48] % chmod 666 -R /dev/binder
(000943) [23:55:48] % chmod 666 -R /dev/vndbinder
(000943) [23:55:48] % chmod 666 -R /dev/hwbinder
(003620) [23:56:56] Starting waydroid session
(000943) [23:56:56] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
success
(000943) [23:56:56] % chmod 777 -R /dev/dri
(000943) [23:56:56] % chmod 777 -R /dev/video0
(000943) [23:56:56] % chmod 777 -R /dev/video1
(000943) [23:56:56] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(000943) [23:56:56] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(000943) [23:56:56] % mkdir -p /var/lib/waydroid/overlay_work/system
(000943) [23:56:56] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(000943) [23:56:57] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(000943) [23:56:57] % mkdir -p /var/lib/waydroid/overlay_work/vendor
(000943) [23:56:57] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(000943) [23:56:57] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(000943) [23:56:57] Save config: /var/lib/waydroid/waydroid.cfg
(000943) [23:56:57] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(000943) [23:56:57] New background process: pid=3731, output=background
(000943) [23:56:57] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000943) [23:56:57] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(000943) [23:56:57] waiting 10 seconds for container to start...
(003620) [23:57:15] waydroidusermonitor: Received transaction: 1
(003620) [23:57:15] Android with user 0 is ready
(000943) [23:59:09] waydroidhardware: Received transaction: 3
(000943) [23:59:09] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(000943) [23:59:09] % lxc-freeze -P /var/lib/waydroid/lxc -n waydroid
(000943) [23:59:09] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
FROZEN
(008424) [23:59:10] WayDroid session is stopped
(009615) [00:03:36] Starting waydroid session
(009615) [00:03:36] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 133, in do_start
    raise RuntimeError("Already tracking a session")
RuntimeError: Already tracking a session

(009615) [00:03:36] RuntimeError: Already tracking a session
(009776) [00:04:27] Starting waydroid session
(009776) [00:04:27] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 133, in do_start
    raise RuntimeError("Already tracking a session")
RuntimeError: Already tracking a session

(009776) [00:04:27] RuntimeError: Already tracking a session
(010651) [00:05:47] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 133, in do_start
    raise RuntimeError("Already tracking a session")
RuntimeError: Already tracking a session

(010651) [00:05:47] RuntimeError: Already tracking a session
(010762) [00:05:52] Starting waydroid session
(010762) [00:05:52] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 133, in do_start
    raise RuntimeError("Already tracking a session")
RuntimeError: Already tracking a session

(010762) [00:05:52] RuntimeError: Already tracking a session
(000943) [00:06:04] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
FROZEN
(000943) [00:06:04] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
(000943) [00:06:04] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000943) [00:06:04] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
(000943) [00:06:04] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(000943) [00:06:04] % umount /var/lib/waydroid/rootfs/vendor
(000943) [00:06:04] % umount /var/lib/waydroid/rootfs/vendor
(000943) [00:06:04] % umount /var/lib/waydroid/rootfs
(000943) [00:06:04] % umount /var/lib/waydroid/rootfs
(000943) [00:06:06] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
Warning: ZONE_ALREADY_SET: 'waydroid0' already bound to 'trusted'
success
(000943) [00:06:06] % chmod 777 -R /dev/dri
(000943) [00:06:06] % chmod 777 -R /dev/video0
(000943) [00:06:06] % chmod 777 -R /dev/video1
(000943) [00:06:06] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(000943) [00:06:06] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(000943) [00:06:06] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(000943) [00:06:06] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(000943) [00:06:06] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(000943) [00:06:06] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(000943) [00:06:06] Save config: /var/lib/waydroid/waydroid.cfg
(000943) [00:06:06] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(000943) [00:06:06] New background process: pid=11020, output=background
(000943) [00:06:06] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(010969) [00:06:20] waydroidusermonitor: Received transaction: 1
(010969) [00:06:20] Android with user 0 is ready
(000943) [00:06:25] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
```
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`
I don't know how to select all the logs from the terminal.

**Comment by saadfrhan** [comment]
I manually stop the session using `waydroid session stop` command and it worked file.

**Comment by saadfrhan** [comment]
I manually stop the session using `waydroid session stop` command and it worked fine.
