### ISSUE TITLE
ERROR: container failed to start

### ISSUE THREAD

**Issue by jakbin** [waydroid/waydroid#148]
Here is the log :- 

```
(000972) [09:57:49] See also: <https://github.com/waydroid>
(000972) [09:57:49] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 130, in start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"])
  File "/usr/lib/waydroid/tools/helpers/images.py", line 92, in mount_rootfs
    helpers.mount.mount(args, images_dir + "/vendor.img",
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 131, in mount
    tools.helpers.run.user(args, ["mount", source, destination])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor

(003828) [09:57:49] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(003828) [09:57:49] % mount -o bind /home/dj/.local/share/waydroid/data /var/lib/waydroid/data
(003828) [09:57:49] % chmod 777 -R /dev/ashmem
(003828) [09:57:49] % chmod 777 -R /dev/dri
(003828) [09:57:49] % chmod 777 -R /dev/fb0
(003828) [09:57:49] % chmod 777 -R /dev/video1
(003828) [09:57:49] % chmod 777 -R /dev/video0
(003828) [09:57:49] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(003828) [09:57:50] New background process: pid=4084, output=background
(004078) [09:57:50] UserMonitor service is not even started
(004078) [09:57:50] Clipboard service is not even started
lxc-start: waydroid: network.c: instantiate_veth: 323 No such file or directory - Failed to attach "vethzBzvyx" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: network.c: lxc_create_network_priv: 3068 No such file or directory - Failed to create network device
lxc-start: waydroid: start.c: lxc_spawn: 1786 Failed to create the network
lxc-start: waydroid: start.c: __lxc_start: 1999 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 314 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 958 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
(003828) [09:57:50] waiting 10 seconds for container to start...
(004007) [09:57:50] UserMonitor service is not even started
(004007) [09:57:50] Clipboard service is not even started
(003828) [09:57:51] waiting 9 seconds for container to start...
(003828) [09:57:52] waiting 8 seconds for container to start...
(003828) [09:57:53] waiting 7 seconds for container to start...
(003828) [09:57:54] waiting 6 seconds for container to start...
(003828) [09:57:55] waiting 5 seconds for container to start...
(003828) [09:57:56] waiting 4 seconds for container to start...
(003828) [09:57:57] waiting 3 seconds for container to start...
(003828) [09:57:58] waiting 2 seconds for container to start...
(003828) [09:57:59] waiting 1 seconds for container to start...
(003828) [09:58:00] ERROR: container failed to start
(003828) [09:58:00] See also: <https://github.com/waydroid>
(003828) [09:58:00] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 160, in start
    raise OSError("container failed to start")
OSError: container failed to start

(004289) [09:59:39] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(004289) [09:59:39] *** output passed to waydroid stdout, not to this log ***
```

**Comment by jakbin** [comment]
I am using parrot os

**Comment by aleasto** [comment]
What is parrot os...
It's missing networking tools
