### ISSUE TITLE
[BUG] Waydroid failed to start session

### ISSUE THREAD

**Issue by Sota4Ever** [waydroid/waydroid#1493]
### Describe the bug

It's the problem about cgroup but I don't know how to do it:
```
papeto@power-bob:~$ mount | grep cgroup
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,seclabel,size=4096k,nr_inodes=1024,mode=755)
cgroup2 on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,noatime)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,noatime,name=systemd)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,noatime,cpuset,noprefix,release_agent=/sbin/cpuset_release_agent)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,noatime,freezer)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,noatime,pids)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,noatime,devices)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,noatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,noatime,memory)
cpu on /sys/fs/cgroup/cpu type cgroup (rw,nosuid,nodev,noexec,cpu)
cpuacct on /sys/fs/cgroup/cpuacct type cgroup (rw,nosuid,nodev,noexec,cpuacct)
```

### Waydroid version

1.4.2

### Device

Linux Smartphone

### Operating System

Ubuntu 23.10 aarch64

### Kernel version

4.19.87-ExtremeKernel-v4.6

### Desktop Environment

MATE 1.26.2

### GPU

virgl (ANGLE (ARM, Vulkan 1.1..213 (Mali-G77 ) )

### Logs

/var/lib/waydroid/waydroid.cfg
```
[waydroid]
arch = arm64
vendor_type = MAINLINE
system_datetime = 1721411983
vendor_datetime = 1722034351
suspend_action = freeze
mount_overlays = True
auto_adb = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_arm64/VANILLA.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_arm64/MAINLINE.json
binder = binder
vndbinder = vndbinder
hwbinder = hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3

[properties]
ro.hardware.gralloc = default
ro.hardware.egl = swiftshader
```
/var/lib/waydroid/waydroid.prop
```
debug.stagefright.ccodec=0
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_arm64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_arm64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
ro.product.waydroid.model=Samsung R8S EUR OPEN 02 based on EXYNOS990
ro.hardware.gralloc=default
ro.hardware.egl=swiftshader
waydroid.host.user=papeto
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/papeto/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-1
waydroid.background_start=false
waydroid.stub_sensors_hal=1
```
/var/lib/waydroid/waydroid_base.prop
```
debug.stagefright.ccodec=0
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_arm64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_arm64/MAINLINE.json
waydroid.tools_version=1.4.2
ro.vndk.lite=true
ro.product.waydroid.model=Samsung R8S EUR OPEN 02 based on EXYNOS990
ro.hardware.gralloc=default
ro.hardware.egl=swiftshader
```
/var/lib/waydroid/waydroid.log
```
xc-start: waydroid: ../src/lxc/cgroups/cgfsng.c: cpuset1_initialize: 666 No such file or directory - Failed to initialize cpuset.cpus
lxc-start: waydroid: ../src/lxc/cgroups/cgfsng.c: __cgroup_tree_create: 731 Invalid argument - Failed to initialize cpuset controller in the legacy hierarchy
lxc-start: waydroid: ../src/lxc/cgroups/cgfsng.c: cpuset1_cpus_initialize: 592 No such file or directory - Failed to read file 13/cpuset.cpus
lxc-start: waydroid: ../src/lxc/cgroups/cgfsng.c: cpuset1_initialize: 666 No such file or directory - Failed to initialize cpuset.cpus
lxc-start: waydroid: ../src/lxc/cgroups/cgfsng.c: __cgroup_tree_create: 731 Invalid argument - Failed to initialize cpuset controller in the legacy hierarchy
lxc-start: waydroid: ../src/lxc/cgroups/cgfsng.c: cpuset1_cpus_initialize: 592 No such file or directory - Failed to read file 13/cpuset.cpus
lxc-start: waydroid: ../src/lxc/cgroups/cgfsng.c: cpuset1_initialize: 666 No such file or directory - Failed to initialize cpuset.cpus
lxc-start: waydroid: ../src/lxc/cgroups/cgfsng.c: __cgroup_tree_create: 731 Invalid argument - Failed to initialize cpuset controller in the legacy hierarchy
lxc-start: waydroid: ../src/lxc/cgroups/cgfsng.c: cgfsng_monitor_create: 1381 Numerical result out of range - Failed to create monitor cgroup
lxc-start: waydroid: ../src/lxc/start.c: __lxc_start: 2042 Failed to create monitor cgroup
STOPPED
(000278) [00:38:47] waiting 10 seconds for container to start...
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: lxc_start_main: 307 The container failed to start
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: lxc_start_main: 312 Additional information can be obtained by setting the --logfile and --logpriority options
(000278) [00:38:48] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000278) [00:38:48] waiting 9 seconds for container to start...
(000278) [00:38:49] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000278) [00:38:49] waiting 8 seconds for container to start...
(000278) [00:38:50] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000278) [00:38:50] waiting 7 seconds for container to start...
(000278) [00:38:51] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000278) [00:38:51] waiting 6 seconds for container to start...
(000278) [00:38:52] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000278) [00:38:52] waiting 5 seconds for container to start...
(000278) [00:38:53] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000278) [00:38:53] waiting 4 seconds for container to start...
(000278) [00:38:54] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000278) [00:38:54] waiting 3 seconds for container to start...
(000278) [00:38:55] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000278) [00:38:55] waiting 2 seconds for container to start...
(000278) [00:38:56] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000278) [00:38:56] waiting 1 seconds for container to start...
(002388) [00:38:57] org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 189, in do_start
    helpers.lxc.start(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 397, in start
    wait_for_running(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 391, in wait_for_running
    raise OSError("container failed to start")
OSError: container failed to start

(002388) [00:38:57] OSError: container failed to start
(002505) [00:40:56] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(002505) [00:40:56] *** output passed to waydroid stdout, not to this log ***
```
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by zyxhere** [comment]
Maybe try the normal Ubuntu kernel? Whatever kernel you're using has some missing/messed up configs
