### ISSUE TITLE
[BUG] Failed to start session with latest Fedora updates

### ISSUE THREAD

**Issue by Swiftloke** [waydroid/waydroid#1497]
### Describe the bug

Looks like something about my Fedora update last night broke Waydroid. It's an SELinux thing, it seems; setting SELinux to "permissive" status lets it boot again.

Waydroid log:
```
(001264) [17:31:28] waiting 6 seconds for container to start...
(001264) [17:31:29] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-info: waydroid: ../src/lxc/utils.c: lxc_mkdir_p: 240 Permission denied - Failed to create directory "/run/lxc/lock//"
Failed to create lock for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
(001264) [17:31:29] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(001264) [17:31:29] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(001264) [17:31:29] Couldn't get LXC status. Assuming STOPPED.
(001264) [17:31:29] waiting 5 seconds for container to start...
(001264) [17:31:30] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-info: waydroid: ../src/lxc/utils.c: lxc_mkdir_p: 240 Permission denied - Failed to create directory "/run/lxc/lock//"
Failed to create lock for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
(001264) [17:31:30] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(001264) [17:31:30] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(001264) [17:31:30] Couldn't get LXC status. Assuming STOPPED.
(001264) [17:31:30] waiting 4 seconds for container to start...
(001264) [17:31:31] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-info: waydroid: ../src/lxc/utils.c: lxc_mkdir_p: 240 Permission denied - Failed to create directory "/run/lxc/lock//"
Failed to create lock for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
(001264) [17:31:31] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(001264) [17:31:31] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(001264) [17:31:31] Couldn't get LXC status. Assuming STOPPED.
(001264) [17:31:31] waiting 3 seconds for container to start...
(001264) [17:31:32] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-info: waydroid: ../src/lxc/utils.c: lxc_mkdir_p: 240 Permission denied - Failed to create directory "/run/lxc/lock//"
Failed to create lock for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
(001264) [17:31:32] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(001264) [17:31:32] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(001264) [17:31:32] Couldn't get LXC status. Assuming STOPPED.
(001264) [17:31:32] waiting 2 seconds for container to start...
(001264) [17:31:33] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-info: waydroid: ../src/lxc/utils.c: lxc_mkdir_p: 240 Permission denied - Failed to create directory "/run/lxc/lock//"
Failed to create lock for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
(001264) [17:31:33] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(001264) [17:31:33] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(001264) [17:31:33] Couldn't get LXC status. Assuming STOPPED.
(001264) [17:31:33] waiting 1 seconds for container to start...
(008978) [17:31:34] org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 189, in do_start
    helpers.lxc.start(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 394, in start
    wait_for_running(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 388, in wait_for_running
    raise OSError("container failed to start")
OSError: container failed to start

(008978) [17:31:34] OSError: container failed to start
(010045) [17:41:35] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(010045) [17:41:35] *** output passed to waydroid stdout, not to this log ***
(010052) [17:41:41] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(010052) [17:41:41] *** output passed to waydroid stdout, not to this log ***
```

Relevant journalctl lines:
```
Aug 03 17:09:11 fedora audit[2755]: AVC avc:  denied  { create } for  pid=2755 comm="lxc-start" name="lxc" scontext=system_u:system_r:waydroid_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=dir permissive=0
Aug 03 17:09:11 fedora audit[2756]: AVC avc:  denied  { create } for  pid=2756 comm="lxc-info" name="lxc" scontext=system_u:system_r:waydroid_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=dir permissive=0 
Aug 03 17:09:11 fedora waydroid[1264]: [17:09:11] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
Aug 03 17:09:11 fedora waydroid[1264]: [17:09:11] Couldn't get LXC status. Assuming STOPPED.
Aug 03 17:09:11 fedora audit[2757]: AVC avc:  denied  { create } for  pid=2757 comm="lxc-info" name="lxc" scontext=system_u:system_r:waydroid_t:s0 tcontext=system_u:object_r:var_run_t:s0 tclass=dir permissive=0
```
[waydroid.zip](https://github.com/user-attachments/files/16482970/waydroid.zip)

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Fedora 40

### Kernel version

6.9.12-200.fc40.x86_64

### Desktop Environment

KDE Plasma 6

### GPU

Intel UHD Graphics 630

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by Swiftloke** [comment]
I saw that bug report, but strangely enough that line isn't present for me to comment out. I only see the ``lxc.seccomp.profile`` setting, not the ``lxc.apparmor.profile`` setting.

**Comment by Quackdoc** [comment]
> I saw that bug report, but strangely enough that line isn't present for me to comment out. I only see the `lxc.seccomp.profile` setting, not the `lxc.apparmor.profile` setting.

try creating the line and see if it works

**Comment by zyxhere** [comment]
Isn't this is upstream fedora bug?

**Comment by Airtuboat72588** [comment]
I'm having the exact same problem.
