### ISSUE TITLE
[BUG]Can Waydroid run without a graphical interface

### ISSUE THREAD

**Issue by yll-waydroid** [waydroid/waydroid#1515]
### Describe the bug

HI
Can the aarch64 device run Waydroid normally without a graphics card or interface?

The steps are as follows
/*Wayland environment variables set*/
#export XDG_SESSION_TYPE=wayland
#systemctl start waydroid-container

(101271) [03:04:33] ERROR: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead
(101271) [03:04:33] See also: <https://github.com/waydroid>
(101271) [03:04:33] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3.10/site-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3.10/site-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3.10/site-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION_BUS_ADDRESS instead

export XDG_SESSION_TYPE=wayland

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

yocto

### Kernel version

Linux kalama 5.15.104-qki-consolidate-android13-8-00013-g11678728f1d8-dirty #1 SMP PREEMPT Fri May 10 01:57:36 UTC 2024 aarch64 GNU/Linux

### Desktop Environment

null

### GPU

null

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by yll-waydroid** [comment]
Qualcomm's 8550 chip, Yocto system, without graphics card and graphical interface, can WayDroid run normally if it compiles itself？
thanks
