### ISSUE TITLE
[BUG]  Fails to Verify System Image during Init

### ISSUE THREAD

**Issue by jayyh01** [waydroid/waydroid#1529]
### Describe the bug

Every time I try to follow the steps on the Bazzite docs, i get this far. I've restarted my deck multiple times and tried Ethernet to no avail. This is a fresh install of Bazzite on Steam deck

deck@bazzite:~$ ujust setup-waydroid
Waydroid Setup
Please read the Waydroid setup documentation before continuing
[sudo] password for deck: 
[00:53:04] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20240817-VANILLA-waydroid_x86_64-system.zip/download
[Downloading] 769.79 MB/774.51 MB    2292.01 kbps(approx.)[01:05:20] Validating system image
[01:05:21] ERROR: Downloaded system image hash doesn't match, expected: 8154ec63378ea2dc0e5e7dceb7b1ea59c3af9aa45760e51e989dd5ee11126e80
[01:05:21] See also: <https://github.com/waydroid>
 Run 'waydroid log' for details.
Waydroid has been initialized, please run waydroid once before you Configure Waydroid
deck@bazzite:~$ waydroid log
(030714) [15:33:30] Save config: /var/lib/waydroid/waydroid.cfg
(030714) [15:33:30] % mkdir -p /var/lib/waydroid/cache_http
(030714) [15:33:30] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20240817-VANILLA-waydroid_x86_64-system.zip/download
(030714) [15:53:44] Validating system image
(030714) [15:53:45] ERROR: Downloaded system image hash doesn't match, expected: 8154ec63378ea2dc0e5e7dceb7b1ea59c3af9aa45760e51e989dd5ee11126e80
(030714) [15:53:45] See also: <https://github.com/waydroid>
(030714) [15:53:45] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 124, in init
    helpers.images.get(args)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 44, in get
    raise ValueError("Downloaded system image hash doesn't match, expected: {}".format(
ValueError: Downloaded system image hash doesn't match, expected: 8154ec63378ea2dc0e5e7dceb7b1ea59c3af9aa45760e51e989dd5ee11126e80

(031907) [15:54:00] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(031907) [15:54:00] *** output passed to waydroid stdout, not to this log ***
(032392) [15:55:57] Run waydroid -h for usage information.
(032863) [15:57:44] Save config: /var/lib/waydroid/waydroid.cfg
(032863) [15:57:44] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20240817-VANILLA-waydroid_x86_64-system.zip/download
(032863) [16:15:13] Validating system image
(032863) [16:15:14] ERROR: Downloaded system image hash doesn't match, expected: 8154ec63378ea2dc0e5e7dceb7b1ea59c3af9aa45760e51e989dd5ee11126e80
(032863) [16:15:14] See also: <https://github.com/waydroid>
(032863) [16:15:14] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 124, in init
    helpers.images.get(args)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 44, in get
    raise ValueError("Downloaded system image hash doesn't match, expected: {}".format(
ValueError: Downloaded system image hash doesn't match, expected: 8154ec63378ea2dc0e5e7dceb7b1ea59c3af9aa45760e51e989dd5ee11126e80

(053988) [00:53:04] Save config: /var/lib/waydroid/waydroid.cfg
(053988) [00:53:04] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20240817-VANILLA-waydroid_x86_64-system.zip/download
(053988) [01:05:20] Validating system image
(053988) [01:05:21] ERROR: Downloaded system image hash doesn't match, expected: 8154ec63378ea2dc0e5e7dceb7b1ea59c3af9aa45760e51e989dd5ee11126e80
(053988) [01:05:21] See also: <https://github.com/waydroid>
(053988) [01:05:21] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 124, in init
    helpers.images.get(args)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 44, in get
    raise ValueError("Downloaded system image hash doesn't match, expected: {}".format(
ValueError: Downloaded system image hash doesn't match, expected: 8154ec63378ea2dc0e5e7dceb7b1ea59c3af9aa45760e51e989dd5ee11126e80

(055402) [01:18:49] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(055402) [01:18:49] *** output passed to waydroid stdout, not to this log ***

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Bazzite Latest

### Kernel version

6.10.4-201.fsync.fc40.x86_64

### Desktop Environment

KDE 6.1.4

### GPU

AMD Custom GPU 0405

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by jayyh01** [comment]
am now getting the same issue wh3n installing on fedora, nobara 40. happens around the same point, on image
