### ISSUE TITLE
mount: /var/lib/waydroid/rootfs: mount failed: Operation not permitted.

### ISSUE THREAD

**Issue by satyrnsstuff** [waydroid/waydroid#153]
running Artix.

log:
```
(027925) [07:40:23] % mkdir -p /var/lib/waydroid/lxc/waydroid
(027925) [07:40:23] % cp -fpr /usr/lib/waydroid/data/configs/config_2 /var/lib/waydroid/lxc/waydroid/config
(027925) [07:40:23] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(027925) [07:40:23] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(030952) [07:40:35] % chmod 666 -R /dev/binder
(030952) [07:40:35] % chmod 666 -R /dev/vndbinder
(030952) [07:40:35] % chmod 666 -R /dev/hwbinder
(030952) [07:40:35] Container manager is waiting for session to load
(030952) [07:40:35] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
Error: Unknown device type.
Failed to setup waydroid-net.
(030952) [07:40:35] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
mount: /var/lib/waydroid/rootfs: mount failed: Operation not permitted.
(030952) [07:40:35] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(030952) [07:40:35] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(030952) [07:40:35] ERROR: Command failed: % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(030952) [07:40:35] See also: <https://github.com/waydroid>
(030952) [07:40:35] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 130, in start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"])
  File "/usr/lib/waydroid/tools/helpers/images.py", line 90, in mount_rootfs
    helpers.mount.mount(args, images_dir + "/system.img",
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 131, in mount
    tools.helpers.run.user(args, ["mount", source, destination])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs

(031091) [07:41:29] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(031091) [07:41:29] *** output passed to waydroid stdout, not to this log ***
```

**Comment by satyrnsstuff** [comment]
I forgot to add `fuse` to my modprobed-db config. After recompiling my kernel with `fuse` enabled, the problem is now fixed.

**Comment by caidi1224** [comment]
> Never mind, it appeared to be working for a while, but no longer is. Same error.

try config your kernel config, enable    Device Drivers-------Block devices-------Loopback device support    and reinstall kernel again.

**Comment by satyrnsstuff** [comment]
> > Never mind, it appeared to be working for a while, but no longer is. Same error.
> 
> try config your kernel config, enable Device Drivers-------Block devices-------Loopback device support and reinstall kernel again.

That worked, thanks! Having a new issue now however. I'll look into it a bit more and if i cant find anything ill make another issue.

**Comment by caidi1224** [comment]
> > > Never mind, it appeared to be working for a while, but no longer is. Same error.
> > 
> > 
> > try config your kernel config, enable Device Drivers-------Block devices-------Loopback device support and reinstall kernel again.
> 
> That worked, thanks! Having a new issue now however. I'll look into it a bit more and if i cant find anything ill make another issue.

okay.
