### ISSUE TITLE
[BUG] Failing to install on OpenSUSE Tumbleweed

### ISSUE THREAD

**Issue by ObwarzanekKrakowski** [waydroid/waydroid#1533]
### Describe the bug

After installing WayDroid following these directions https://github.com/waydroid/waydroid/discussions/1463

 `sudo waydroid init` returns

`[21:39:35] Failed to load binder driver
[21:39:35] modprobe: ERROR: could not insert 'binder_linux': Key was rejected by service
[21:39:35] ERROR: Binder node "binder" for waydroid not found
[21:39:35] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.`

And when launching WayDroid through the App launcher, after clicking the "Download" button, the log window shows
`Waiting for waydroid container service...
Failed to load binder driver
modprobe: ERROR: could not insert 'binder_linux': Key was rejected by service
Binder node "binder" for waydroid not found`

And nothing else happens.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

OpenSUSE Tumblweed 20240822

### Kernel version

6.10.5-1-default

### Desktop Environment

KDE Plasma 6.1.4 / KDE Frameworks 6.5.0

### GPU

Mesa Intel® HD Graphics 620

### Logs

/var/lib/waydroid/waydroid.cfg does not exist
/var/lib/waydroid/waydroid.prop does not exist
/var/lib/waydroid/waydroid_base.prop does not exist
/var/lib/waydroid/waydroid.log 
[waydroid.log](https://github.com/user-attachments/files/16732746/waydroid.log)

`sudo waydroid shell -- logcat -d | tee logcat.txt`
`ERROR: WayDroid is not initialized, run "waydroid init"`

`sudo dmesg | tee dmesg.txt` 
[dmesg.txt](https://github.com/user-attachments/files/16732755/dmesg.txt)

**Comment by Dannyzen** [comment]
I'm also impacted by this issue. 
Upstream tutorial followed at: https://github.com/waydroid/waydroid/discussions/1463 for context

**Comment by zyxhere** [comment]
Whats the output of `zgrep -i -e android -e memfd -e ashmem /proc/config.gz` ?
Also see https://docs.waydro.id/debugging/getting-essential-information

**Comment by ObwarzanekKrakowski** [comment]
Hello

Thank you for your follow-up. Here are the `outputs` of the **command lines** you provided and those from the docs.

**zgrep -i -e android -e memfd -e ashmem /proc/config.gz**
`/proc/config.gz:CONFIG_MEMFD_CREATE=y
/proc/config.gz:CONFIG_X86_ANDROID_TABLETS=m
/proc/config.gz:# Android
/proc/config.gz:# CONFIG_ANDROID_BINDER_IPC is not set
/proc/config.gz:# end of Android
gzip: ?.gz: No such file or directory`

**sudo systemctl status waydroid-container.service**
` waydroid-container.service - Waydroid Container
Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled; preset: disabled)
Active: active (running) since Sat 2024-10-05 07:14:43 CEST; 15min ago
Invocation: df9cdab0ef2e4efbb586ecc021120a76
Main PID: 1539 (waydroid)
Tasks: 1 (limit: 19002)
CPU: 279ms
CGroup: /system.slice/waydroid-container.service
             └─1539 /usr/bin/python3 /usr/bin/waydroid -w container start
oct. 05 07:14:42 amour systemd[1]: Starting Waydroid Container...
oct. 05 07:14:43 amour systemd[1]: Started Waydroid Container.`

**waydroid log**
`(003909) [21:03:49] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: ERROR: could not insert 'binder_linux': Key was rejected by service
(003909) [21:03:49] Failed to load binder driver
(003909) [21:03:49] modprobe: ERROR: could not insert 'binder_linux': Key was rejected by service
(003909) [21:03:49] ERROR: Binder node "binder" for waydroid not found
(003909) [21:03:49] See also: <https://github.com/waydroid>
(003909) [21:03:49] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 97, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(004818) [21:07:56] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: ERROR: could not insert 'binder_linux': Key was rejected by service
(004818) [21:07:56] Failed to load binder driver
(004818) [21:07:56] modprobe: ERROR: could not insert 'binder_linux': Key was rejected by service
(005548) [07:31:18] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(005548) [07:31:18] *** output passed to waydroid stdout, not to this log ***
`

**sudo waydroid logcat > ~/waydroid-logcat.txt**
[waydroid-logcat.txt](https://github.com/user-attachments/files/17265254/waydroid-logcat.txt)

**lsb_release -a**
`LSB Version:    n/a
Distributor ID: openSUSE
Description:    openSUSE Tumbleweed
Release:        20240822
Codename:       n/a
`

**uname -a**
`Linux NAME_OF_COMPUTER 6.10.5-1-default #1 SMP PREEMPT_DYNAMIC Fri Aug 16 11:15:41 UTC 2024 (30fd964) x86_64 x86_64 x86_64 GNU/Linux
`

**Comment by ObwarzanekKrakowski** [comment]
Hello

Yes I have secure-boot enabled. Just tried to disable it and it does not work although the error message in the log window is now different
`Waiting for waydroid container service...
Failed to load binder driver
modprobe: FATAL: Module binder_linux not found in directory /usr/lib/modules/6.11.0-1-default
Binder node "binder" for waydroid not found`

**Comment by zyxhere** [comment]
See https://github.com/waydroid/waydroid/issues/801#issuecomment-2570011249
