### ISSUE TITLE
[BUG] Init fails on openSUSE

### ISSUE THREAD

**Issue by BalazsManus** [waydroid/waydroid#1539]
### Describe the bug

I installed everything.
`ls /dev/binderfs` returns nothing
modprobing binder-linux doesn nothing

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

openSUSE Tumbleweed-Slowroll x86_64

### Kernel version

6.10.5-1-default

### Desktop Environment

Plasma 6.1.4

### GPU

NVIDIA Geforce RTX 3050

### Logs

(003038) [11:32:36] % mkdir -p /dev/binderfs
(003038) [11:32:36] % mount -t binder binder /dev/binderfs
(003104) [11:32:46] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(003104) [11:32:46] *** output passed to waydroid stdout, not to this log ***
(003121) [11:32:54] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(003121) [11:32:54] *** output passed to waydroid stdout, not to this log ***
(003186) [11:33:06] % mkdir -p /dev/binderfs
(003186) [11:33:06] % mount -t binder binder /dev/binderfs
(003186) [11:33:06] ERROR: [Errno 2] No such file or directory: '/dev/binderfs/binder-control'
(003186) [11:33:06] See also: <https://github.com/waydroid>
(003186) [11:33:06] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 97, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 128, in setupBinderNodes
    probeBinderDriver(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 105, in probeBinderDriver
    allocBinderNodes(args, binder_dev_nodes)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 59, in allocBinderNodes
    binderctrlfd = open('/dev/binderfs/binder-control','rb')
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/dev/binderfs/binder-control'

**Comment by zyxhere** [comment]
OpenSUSE default kernels don't have `binder` so waydroid will not work
Duplicate of https://github.com/waydroid/waydroid/issues/801

Can try this guid for openSUSE https://github.com/waydroid/waydroid/discussions/1463
