### ISSUE TITLE
Pinephone - ERROR: container failed to start

### ISSUE THREAD

**Issue by thesheepcat** [waydroid/waydroid#154]
Hardware: 
- PINEPHONE – Beta Edition With Convergence Package Linux SmartPhone
- OS: Manjaro with Plasma Mobile OS build (updated with pacman -Syu on October 14th 2021)
- Chipset: Allwinner A64
- CPU: 64-bit Quad-core 1.2 GHz ARM Cortex A-53
- GPU: MALI-400MP2
- Internal Flash Memory: 32GB eMMCSystem 
- Memory: 3GB LPDDR3 SDRAM

I installed waydroid with:
- sudo pacman -S waydroid-image
- sudo waydroid init -f
- sudo systemctl enable waydroid-container --now

After installation, i tried to activate it by clicking Waydroid icon on Pinephone App launcher but nothing happens (the splash screen stays open for few seconds and nothing elase happens).

When i checked the status of waydroid-container service (systemctl status waydroid-container), it says the service failed and it's not active.

Then, i tried activate the container with "sudo waydroid container start".
After that, i tried to activate the session with "sudo waydroid session start": the session started the container activation but it failed; this is the waydroid log that i find:

sudo waydroid log
(005046) [20:15:53] XDG Session is not "wayland"   
(005046) [20:15:53] Save session config: /var/lib/waydroid/session.cfg                                
(005046) [20:15:53] UserMonitor service is not even started                                           
(005046) [20:15:53] Clipboard service is not even started                                             
(004909) [20:15:54] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start                            
which: no nft in (/usr/local/sbin:/usr/local/bin:/usr/bin)                                            
/usr/lib/waydroid/data/scripts/waydroid-net.sh: line 185: dnsmasq: command not found
Failed to setup waydroid-net.
Failed to setup waydroid-net.
(004909) [20:15:55] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(004909) [20:15:55] % umount /var/lib/waydroid/rootfs/vendor
(004909) [20:15:55] % umount /var/lib/waydroid/rootfs
(004909) [20:15:55] % mount /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(004909) [20:15:55] % mount -o remount,ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(004909) [20:15:55] % mount /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(004909) [20:15:55] % mount -o remount,ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(004909) [20:15:55] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(004909) [20:15:55] % chmod 777 -R /dev/ashmem
(004909) [20:15:55] % chmod 777 -R /dev/dri
(004909) [20:15:55] % chmod 777 -R /dev/fb0
(004909) [20:15:55] % chmod 777 -R /dev/video3
(004909) [20:15:55] % chmod 777 -R /dev/video2
(004909) [20:15:55] % chmod 777 -R /dev/video1
(004909) [20:15:55] % chmod 777 -R /dev/video0
(004909) [20:15:55] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(004909) [20:15:55] New background process: pid=5133, output=background
lxc-start: waydroid: cgroups/cgroup2_devices.c: bpf_program_load_kernel: 334 Function not implemented - Failed to load bpf program: (null)
lxc-start: waydroid: network.c: netdev_configure_server_veth: 708 No such file or directory - Failed to attach "veth3RA6UM" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: network.c: lxc_create_network_priv: 3419 No such file or directory - Failed to create network device
lxc-start: waydroid: start.c: lxc_spawn: 1826 Failed to create the network
lxc-start: waydroid: start.c: __lxc_start: 2053 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 996 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
(004909) [20:15:56] waiting 10 seconds for container to start...
(004909) [20:15:57] waiting 9 seconds for container to start...
(004909) [20:15:58] waiting 8 seconds for container to start...
(004909) [20:15:59] waiting 7 seconds for container to start...
(004909) [20:16:00] waiting 6 seconds for container to start...
(004909) [20:16:01] waiting 5 seconds for container to start...
(004909) [20:16:02] waiting 4 seconds for container to start...
(004909) [20:16:03] waiting 3 seconds for container to start...
(004909) [20:16:04] waiting 2 seconds for container to start...
(004909) [20:16:05] waiting 1 seconds for container to start...
(004909) [20:16:06] ERROR: container failed to start
(004909) [20:16:06] See also: <https://github.com/waydroid>
(004909) [20:16:06] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 160, in start
    raise OSError("container failed to start")
OSError: container failed to start

(005170) [20:16:07] UserMonitor service is not even started
(005170) [20:16:07] Clipboard service is not even started
(005046) [20:16:07] UserMonitor service is not eve2n started
(005046) [20:16:07] Clipboard service is not even started
(005436) [20:18:32] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(005436) [20:18:32] *** output passed to waydroid stdout, not to this log ***

I tried to remove the complete waydroid-image with "sudo pacman -Rns waydroid-image" and, then, i re-installed it.

Nothing has changed: every time i try to activate waydroid, the same situation as above is constantly happening.

**Comment by thesheepcat** [comment]
Yes, i solved the issue yesterday evening: i installed dnsmasq.

Anyway, with the current waydroid-image on pacman, i need to workaroud the issue about "log permissions" identified in this issue here: https://github.com/waydroid/waydroid/issues/103

By running `waydroid --details-to-stdout session start` i'm able to correctly start waydroid from terminal
