### ISSUE TITLE
[BUG] OSError: container failed to start

### ISSUE THREAD

**Issue by ccaneke** [waydroid/waydroid#1543]
### Describe the bug

* Started WayDroid for first time and downloaded GAPPS version.
* Launching Waydroid from desktop menu failed to start Waydroid
* Launching Waydroid from commandline also failed:
 ```
 $ sudo waydroid container start
 ERROR: WayDroid container service is already running
 $ waydroid session start
 $ OSError: container failed to start
```

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Fedora Linux 39 (Workstation Edition)

### Kernel version

6.8.9-200.fc39.x86_64

### Desktop Environment

GNOME Shell 45.6

### GPU

Intel Quadro P500

### Logs

```
$ waydroid log 
Failed to load config for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
(3147994) [00:07:48] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(3147994) [00:07:48] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(3147994) [00:07:48] Couldn't get LXC status. Assuming STOPPED.
(3147994) [00:07:48] waiting 6 seconds for container to start...
(3147994) [00:07:49] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
Failed to load config for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
(3147994) [00:07:49] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(3147994) [00:07:49] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(3147994) [00:07:49] Couldn't get LXC status. Assuming STOPPED.
(3147994) [00:07:49] waiting 5 seconds for container to start...
(3147994) [00:07:50] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
Failed to load config for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
(3147994) [00:07:50] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(3147994) [00:07:50] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(3147994) [00:07:50] Couldn't get LXC status. Assuming STOPPED.
(3147994) [00:07:50] waiting 4 seconds for container to start...
(3147994) [00:07:51] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
Failed to load config for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
(3147994) [00:07:51] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(3147994) [00:07:51] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(3147994) [00:07:51] Couldn't get LXC status. Assuming STOPPED.
(3147994) [00:07:51] waiting 3 seconds for container to start...
(3147994) [00:07:52] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
Failed to load config for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
(3147994) [00:07:52] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(3147994) [00:07:52] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(3147994) [00:07:52] Couldn't get LXC status. Assuming STOPPED.
(3147994) [00:07:52] waiting 2 seconds for container to start...
(3147994) [00:07:53] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
Failed to load config for waydroid
Failure to retrieve information on /var/lib/waydroid/lxc:waydroid
(3147994) [00:07:53] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(3147994) [00:07:53] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(3147994) [00:07:53] Couldn't get LXC status. Assuming STOPPED.
(3147994) [00:07:53] waiting 1 seconds for container to start...
(3169439) [00:07:54] org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 189, in do_start
    helpers.lxc.start(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 397, in start
    wait_for_running(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 391, in wait_for_running
    raise OSError("container failed to start")
OSError: container failed to start

(3169439) [00:07:54] OSError: container failed to start
(3169669) [00:08:09] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(3169669) [00:08:09] *** output passed to waydroid stdout, not to this log ***
(3170079) [00:09:02] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(3170079) [00:09:02] *** output passed to waydroid stdout, not to this log ***
```

**Comment by ccaneke** [comment]
#493 [comment](https://github.com/waydroid/waydroid/issues/493#issuecomment-1220516970) fixed this issue. Why is that line in the config file uncommented if it breaks waydroid?

**Comment by Dlopx** [comment]
> [#493](https://github.com/waydroid/waydroid/issues/493) [comment](https://github.com/waydroid/waydroid/issues/493#issuecomment-1220516970) fixed this issue. Why is that line in the config file uncommented if it breaks waydroid?

tried and didn't work, also tried reinstalling and changing images
`david@david-VJF155F11UAR:~$ waydroid first-launch

(waydroid:17801): dbind-WARNING **: 20:11:01.588: Couldn't connect to accessibility bus: Failed to connect to socket /root/.cache/at-spi/bus_0: Permiso denegado
[20:11:01] Starting waydroid session
[20:11:01] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
[20:11:12] OSError: container failed to start
`

**Comment by TheXnlyGhxst** [comment]
Getting the same error, tried commenting out the lxc.apparmor thing, same error.
