### ISSUE TITLE
[BUG] WSL binder node "binder" not found

### ISSUE THREAD

**Issue by EvanLei1** [waydroid/waydroid#1561]
### Describe the bug

I was using a Windows 11 WSL2 terminal running Ubuntu (22.04) when I encountered an error initializing Waydroid. I tried to download VANILLA, but the code showed:
`[20:02:59] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.153.1-microsoft-standard-WSL2
[20:02:59] ERROR: Binder node "binder" for waydroid not found
[20:02:59] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.`
and the download was not completed.

### Waydroid version

1.4.3

### Device

Linux Desktop

### Operating System

Windows 11 23H2

### Kernel version

5.15.153.1-microsoft-standard-WSL2

### Desktop Environment

N/A

### GPU

Nvidia GeForce RTX 3050 6 GB mobile

### Logs

(003567) [20:02:59] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.153.1-microsoft-standard-WSL2
(003567) [20:02:59] Failed to load binder driver
(003567) [20:02:59] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.153.1-microsoft-standard-WSL2
(003567) [20:02:59] ERROR: Binder node "binder" for waydroid not found
(003567) [20:02:59] See also: <https://github.com/waydroid>
(003567) [20:02:59] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 117, in init
    if not setup_config(args):
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 103, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

**Comment by moonsur** [comment]
I am facing the same issue. how to we solve it?

**Comment by zyxhere** [comment]
Whats the output of `zgrep -i -e android -e memfd -e ashmem /proc/config.gz`
If the above command doesn't work try `grep -i -e android -e memfd -e ashmem "/boot/config-$(uname -r)"`
See: https://docs.waydro.id/debugging/getting-essential-information

**Comment by zyxhere** [comment]
Duplicate of https://github.com/waydroid/waydroid/issues/1544

**Comment by zyxhere** [comment]
Duplicate of https://github.com/waydroid/waydroid/issues/801

**Comment by nos1609** [comment]
Simply rebuild WSL kernel with binder modules included.

https://learn.microsoft.com/en-us/community/content/wsl-user-msft-kernel-v6

```
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
CONFIG_ANDROID_BINDER_IPC=y
```
