### ISSUE TITLE
RuntimeError: Command failed: % mount -o ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor 

### ISSUE THREAD

**Issue by Anglos333** [waydroid/waydroid#1567]
The first time I installed Waydroid on Arch was fine, but when I tried to start Waydroid again after the computer restarted, I found that it was unresponsive, so I tried to reinstall it, and then I encountered the following problem, the full log is as follows:

[Angelos@angelos local]$ waydroid log 
(001775) [18:38:51] % chmod 777 -R /dev/video9 
(001775) [18:38:51] % chmod 777 -R /dev/video10 
(001775) [18:38:51] % chmod 777 -R /dev/video11 
(001775) [18:38:51] % chmod 777 -R /dev/video12 
(001775) [18:38:51] % chmod 777 -R /dev/video13 
(001775) [18:38:51] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid 
(001775) [18:38:51] % umount /var/lib/waydroid/rootfs 
(001775) [18:38:51] % umount /var/lib/waydroid/rootfs 
(001775) [18:38:51] % mount -o ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs 
(001775) [18:38:51] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdi
r=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs 
(001775) [18:38:51] % mount -o ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor 
mount: /var/lib/waydroid/rootfs/vendor: wrong fs type, bad option, bad superblock on /dev/loop1, missing codepage or helper program, or other error. 
      dmesg(1) may have more information after failed mount system call. 
(001775) [18:38:51] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
(001775) [18:38:51] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log 
(003131) [18:38:51] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last): 
 File "/usr/lib/python3.12/site-packages/dbus/service.py", line 712, in _message_cb 
   retval = candidate_method(self, *args, **keywords) 
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
 File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start 
   do_start(self.args, session) 
 File "/usr/lib/waydroid/tools/actions/container_manager.py", line 185, in do_start 
   helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"], session) 
 File "/usr/lib/waydroid/tools/helpers/images.py", line 171, in mount_rootfs 
   helpers.mount.mount(args, images_dir + "/vendor.img", 
 File "/usr/lib/waydroid/tools/helpers/mount.py", line 148, in mount 
   tools.helpers.run.user(args, ["mount", *extra_args, source, destination]) 
 File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user 
   return tools.helpers.run_core.core(args, msg, cmd, working_dir, output, 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
 File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core 
   check_return_code(args, code, log_message) 
 File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code 
   raise RuntimeError("Command failed: " + log_message) 
RuntimeError: Command failed: % mount -o ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor 

(003131) [18:38:51] RuntimeError: Command failed: % mount -o ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor 
(003216) [18:43:32] % tail -n 60 -F /var/lib/waydroid/waydroid.log 
(003216) [18:43:32] *** output passed to waydroid stdout, not to this log *** 
(003311) [18:52:15] ERROR: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SESSION
_BUS_ADDRESS instead 
(003311) [18:52:15] See also: <https://github.com/waydroid> 
(003311) [18:52:15] Traceback (most recent call last): 
 File "/usr/lib/waydroid/tools/__init__.py", line 70, in main 
   actions.session_manager.start(args) 
 File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start 
   name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True) 
                                                    ^^^^^^^^^^^^^^^^^ 
 File "/usr/lib/python3.12/site-packages/dbus/_dbus.py", line 209, in __new__ 
   return Bus.__new__(cls, Bus.TYPE_SESSION, private=private, 
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
 File "/usr/lib/python3.12/site-packages/dbus/_dbus.py", line 99, in __new__ 
   bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop) 
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
 File "/usr/lib/python3.12/site-packages/dbus/bus.py", line 120, in __new__ 
   bus = cls._new_for_bus(address_or_type, mainloop=mainloop) 
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NotSupported: Using X11 for dbus-daemon autolaunch was disabled at compile time, set your DBUS_SES
SION_BUS_ADDRESS instead 

(003326) [18:55:25] % tail -n 60 -F /var/lib/waydroid/waydroid.log 
(003326) [18:55:25] *** output passed to waydroid stdout, not to this log *** 
^C

**Comment by Anglos333** [comment]
[Angelos@angelos local]$ sudo systemctl status waydroid-container.service
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled; preset: disabled)
     Active: active (running) since Fri 2024-09-20 18:07:34 UTC; 47min ago
 Invocation: 045030a1d88444f4aa80f9586af5353b
   Main PID: 1775 (python3)
      Tasks: 3 (limit: 9339)
     Memory: 20.5M (peak: 25M)
        CPU: 707ms
     CGroup: /system.slice/waydroid-container.service
             ├─1775 python3 /usr/bin/waydroid -w container start
             └─1891 dnsmasq --conf-file=/dev/null -u dnsmasq --strict-order --bind-interfaces --pid-file=/run/waydroid-lxc/dnsmasq.pid --listen-address 192.168.240.1 --dhcp-range 192.168.240.2,192.168.240.254 --dhcp-lease-max=253 --dhcp-no-override --except-interface=lo --interface=waydroid0 --dhcp-leasefile=/var/lib/misc/dnsmasq.waydroid0.leases --dhcp-authoritative

9月 20 18:07:34 angelos systemd[1]: Started Waydroid Container.
9月 20 18:13:00 angelos dnsmasq[1891]: started, version 2.90 cachesize 150
9月 20 18:13:00 angelos dnsmasq[1891]: compile time options: IPv6 GNU-getopt DBus no-UBus i18n IDN2 DHCP DHCPv6 no-Lua TFTP conntrack ipset nftset auth cryptohash DNSSEC loop-detect inotify dumpfile
9月 20 18:13:00 angelos dnsmasq-dhcp[1891]: DHCP, IP range 192.168.240.2 -- 192.168.240.254, lease time 1h
9月 20 18:13:00 angelos dnsmasq-dhcp[1891]: DHCP, sockets bound exclusively to interface waydroid0
9月 20 18:13:00 angelos dnsmasq[1891]: reading /etc/resolv.conf
9月 20 18:13:00 angelos dnsmasq[1891]: using nameserver 127.0.0.53#53
9月 20 18:13:00 angelos dnsmasq[1891]: read /etc/hosts - 4 names
9月 20 18:13:00 angelos waydroid[1775]: [18:13:00] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
9月 20 18:38:51 angelos waydroid[1775]: [18:38:51] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log

**Comment by WlloX** [comment]
same issue here! 

here are my logs

  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 185, in do_start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"], session)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 157, in mount_rootfs
    helpers.mount.mount(args, images_dir + "/system.img",
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 148, in mount
    tools.helpers.run.user(args, ["mount", *extra_args, source, destination])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs

(009015) [18:54:06] RuntimeError: Command failed: % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(009104) [18:54:41] Starting waydroid session
(000922) [18:54:41] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
waydroid-net is already running
(000922) [18:54:41] % systemctl is-active -q nfcd
(000922) [18:54:41] % chmod 777 -R /dev/dri
(000922) [18:54:41] % chmod 777 -R /dev/video0
(000922) [18:54:41] % chmod 777 -R /dev/video1
(000922) [18:54:41] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(000922) [18:54:41] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
mount: /var/lib/waydroid/rootfs: wrong fs type, bad option, bad superblock on /dev/loop12, missing codepage or helper program, or other error.
       dmesg(1) may have more information after failed mount system call.
(000922) [18:54:41] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000922) [18:54:41] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(009104) [18:54:41] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib64/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 185, in do_start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"], session)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 157, in mount_rootfs
    helpers.mount.mount(args, images_dir + "/system.img",
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 148, in mount
    tools.helpers.run.user(args, ["mount", *extra_args, source, destination])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs

**Comment by brandon-hawbaker** [comment]
I'm also experiencing the same issue as well.  Any luck trying to resolve this issue?

(000769) [15:27:35] % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
mount: /var/lib/waydroid/rootfs/vendor: wrong fs type, bad option, bad superblock on /dev/loop10, missing codepage or helper program, or other error.
(000769) [15:27:35] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000769) [15:27:35] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(000769) [15:27:35] ERROR: Command failed: % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(000769) [15:27:35] See also: <https://github.com/waydroid>
(000769) [15:27:35] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 68, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 97, in start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"])
  File "/usr/lib/waydroid/tools/helpers/images.py", line 146, in mount_rootfs
    helpers.mount.mount(args, images_dir + "/vendor.img",
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 147, in mount
    tools.helpers.run.user(args, ["mount", *extra_args, source, destination])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor

(000980) [15:27:36] UserMonitor service is not even started
(000980) [15:27:36] Clipboard service is not even started
(039465) [20:27:52] Starting waydroid session
(039465) [20:27:52] Save session config: /var/lib/waydroid/session.cfg
(039465) [20:27:52] UserMonitor service is not even started
(039465) [20:27:52] Clipboard service is not even started
(041669) [09:45:03] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(041669) [09:45:03] *** output passed to waydroid stdout, not to this log ***

I also tried to run the following command to see if the source image contained multiple partitions, but I don't even see one partition?  Could it be possible that the waydroid image for performing the update is a bad image?  If so, couldn't we potentially fix this by downloading a new image to be used instead?

fdisk -l /var/lib/waydroid/images/vendor.img
Disk /var/lib/waydroid/images/vendor.img: 192.63 MiB, 201981952 bytes, 394496 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

**Comment by brandon-hawbaker** [comment]
I have some potentially good news that may help some of you experiencing this issue.  In my particular case, I was able to fix mine by opening up a shell and running the command:

sudo waydroid upgrade

In my case, it downloaded fresh system and vendor img files.  I tested it by running:

waydroid container start

Once I saw that it was working fine, I restarted my device and I could once again launch waydroid like I have always done.  Hopefully that helps!

**Comment by Brahvim** [comment]
Yeee-ep, @brandon-hawbaker's solution worked fine for me! _Didn't even need to reboot!_  
(I'm on Debian 13 with KDE Plasma.)
