### ISSUE TITLE
[BUG]  No such file or directory: 'modprobe'

### ISSUE THREAD

**Issue by stonemic2293** [waydroid/waydroid#1575]
### Describe the bug

waydroid wont init 
error:  No such file or directory: 'modprobe'

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

Vanilla OS 2.0

### Kernel version

6.10.9-amd64

### Desktop Environment

GNOME 46

### GPU

Intel® Graphics (RPL-P)

### Logs

logs not found(001594) [20:08:15] Run waydroid -h for usage information.
(001598) [20:09:04] ERROR: Action "init" needs root access
(001598) [20:09:04] See also: <https://github.com/waydroid>
(001598) [20:09:04] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 63, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "init" needs root access

(001601) [20:09:14] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(001601) [20:09:14] ERROR: [Errno 2] No such file or directory: 'modprobe'
(001601) [20:09:14] See also: <https://github.com/waydroid>
(001601) [20:09:14] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 97, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 128, in setupBinderNodes
    probeBinderDriver(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 95, in probeBinderDriver
    output = tools.helpers.run.user(args, command, check=False, output_return=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 335, in core
    (code, output_after_run) = foreground_pipe(args, cmd, working_dir,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 147, in foreground_pipe
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'modprobe'

(001637) [20:19:01] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(001637) [20:19:01] *** output passed to waydroid stdout, not to this log ***

![Screenshot from 2024-09-26 13-13-23](https://github.com/user-attachments/assets/d89ca321-ae20-48cf-aff9-88dc0e1421b9)
![Screenshot from 2024-09-26 13-16-22](https://github.com/user-attachments/assets/d905c032-fc41-4e3b-b503-f7268916ca50)

**Comment by zyxhere** [comment]
How did you install it?
Looks to me its a VanillaOS packaging bug

**Comment by zyxhere** [comment]
Related https://github.com/waydroid/waydroid/issues/1132#issuecomment-1765082946 ?

**Comment by Geo-programme001** [comment]
same damn thing

**Comment by jardon** [comment]
Waydroid operations are supposed to be performed through `vso` on VanillaOS.  There is a special image that is downloaded and configured for waydroid using `vso`.  If you installed it into the pico container, that is going to be a bad time.

Try doing it that way, and if you have issues, submit a bug for VanillaOS first!
