### ISSUE TITLE
[BUG] lxc pulse audio fails to mount, on a VM with pulse audio not installed (dont care about waydroid audio)

### ISSUE THREAD

**Issue by Retera** [waydroid/waydroid#1576]
### Describe the bug

I set up Waydroid for myself running inside of a rented VPS, which was running:
- debian bookworm, installed by VPS provider
- sway window manager, with xwayland disabled
- wayvnc for remote access to sway
- Waydroid suggestions for running in VM from here: https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm

I do not need audio, and there is no graphics card for this VM. My objective i to click "Yes" repeatedly every day on an obfuscated Android app that has no purpose other than to connect to a server which provides it an address to another server in an obfuscated way, to then connect to that other server, to then present the user with a "Yes" button [my description is an oversimplification]. The app is sufficiently obfuscated to the point that the only way to run it is to run the APK and not recreate what that is or how it works, even though its only purpose is to click on "Yes." So I want to be able to run this Waydroid technology stack to click on "Yes" and this has been working for almost a year to use it for clicking "Yes" repeatedly.

However, last night I did `sudo apt update && sudo apt full-upgrade` and it told me that the only software that would upgrade would be `waydroid`, and I allowed it to upgrade. Then I did a `sudo reboot`.

It's been a year since I set this thing up -- I was quite in the habit of clicking my magical "Yes" button and depending on that -- but it seems that Waydroid regressed to where it no longer works in my configuration. If I'm understanding the log, the problem is that Waydroid might be assuming the existence of a native pulse audio device, even though it's a VPS and there isn't one. Unfortunately I no longer have access to the "previous good" configuration to check what the older version of waydroid's log looked like, but here's what I get when following the advice from here: https://docs.waydro.id/debugging/getting-essential-information

```
$ sudo systemctl status waydroid-container.service
? waydroid-container.service - Waydroid Container
     Loaded: loaded (/lib/systemd/system/waydroid-container.service; enabled; preset: enabled)
     Active: active (running) since Fri 2024-09-27 13:59:23 UTC; 25min ago
   Main PID: 2272 (waydroid)
      Tasks: 3 (limit: 4651)
     Memory: 17.2M
        CPU: 448ms
     CGroup: /system.slice/waydroid-container.service
             +-2272 /usr/bin/python3 /usr/bin/waydroid -w container start
             +-2403 dnsmasq --conf-file=/dev/null -u dnsmasq --strict-order --bind-interfaces --pid-file=/run/waydroid-lxc/dnsmasq.pid --listen-address 192.168.240.1 --dhcp-range 192.168.24>

Sep 27 13:59:57 cthulhu-auth-003 waydroid[2272]: [13:59:57] waiting 10 seconds for container to start...
Sep 27 13:59:58 cthulhu-auth-003 waydroid[2272]: [13:59:58] waiting 9 seconds for container to start...
Sep 27 13:59:59 cthulhu-auth-003 waydroid[2272]: [13:59:59] waiting 8 seconds for container to start...
Sep 27 14:00:00 cthulhu-auth-003 waydroid[2272]: [14:00:00] waiting 7 seconds for container to start...
Sep 27 14:00:01 cthulhu-auth-003 waydroid[2272]: [14:00:01] waiting 6 seconds for container to start...
Sep 27 14:00:02 cthulhu-auth-003 waydroid[2272]: [14:00:02] waiting 5 seconds for container to start...
Sep 27 14:00:03 cthulhu-auth-003 waydroid[2272]: [14:00:03] waiting 4 seconds for container to start...
Sep 27 14:00:04 cthulhu-auth-003 waydroid[2272]: [14:00:04] waiting 3 seconds for container to start...
Sep 27 14:00:05 cthulhu-auth-003 waydroid[2272]: [14:00:05] waiting 2 seconds for container to start...
Sep 27 14:00:06 cthulhu-auth-003 waydroid[2272]: [14:00:06] waiting 1 seconds for container to start...
```

```
$ waydroid log
(002272) [13:59:56] New background process: pid=2416, output=background
(002272) [13:59:56] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-start: waydroid: ../src/lxc/utils.c: safe_mount: 1220 No such file or directory - Failed to mount "/tmp/sway/pulse/native" onto "/usr/lib/x86_64-linux-gnu/lxc/rootfs/run/xdg/pulse/native"
lxc-start: waydroid: ../src/lxc/conf.c: mount_entry: 2442 No such file or directory - Failed to mount "/tmp/sway/pulse/native" on "/usr/lib/x86_64-linux-gnu/lxc/rootfs/run/xdg/pulse/native"
lxc-start: waydroid: ../src/lxc/conf.c: lxc_setup: 4415 Failed to setup mount entries
lxc-start: waydroid: ../src/lxc/start.c: do_start: 1272 Failed to setup container "waydroid"
lxc-start: waydroid: ../src/lxc/sync.c: sync_wait: 34 An error occurred in another process (expected sequence number 3)
lxc-start: waydroid: ../src/lxc/start.c: __lxc_start: 2107 Failed to spawn container "waydroid"
STOPPED
lxc-start: waydroid: ../src/lxc/conf.c: run_buffer: 322 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 985 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: main: 306 The container failed to start
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options
(002272) [13:59:57] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002272) [13:59:57] waiting 10 seconds for container to start...
(002272) [13:59:58] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002272) [13:59:58] waiting 9 seconds for container to start...
(002272) [13:59:59] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002272) [13:59:59] waiting 8 seconds for container to start...
(002272) [14:00:00] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002272) [14:00:00] waiting 7 seconds for container to start...
(002272) [14:00:01] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002272) [14:00:01] waiting 6 seconds for container to start...
(002272) [14:00:02] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002272) [14:00:02] waiting 5 seconds for container to start...
(002272) [14:00:03] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002272) [14:00:03] waiting 4 seconds for container to start...
(002272) [14:00:04] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002272) [14:00:04] waiting 3 seconds for container to start...
(002272) [14:00:05] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002272) [14:00:05] waiting 2 seconds for container to start...
(002272) [14:00:06] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(002272) [14:00:06] waiting 1 seconds for container to start...
(002373) [14:00:07] org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 189, in do_start
    helpers.lxc.start(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 400, in start
    wait_for_running(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 394, in wait_for_running
    raise OSError("container failed to start")
OSError: container failed to start

(002373) [14:00:07] OSError: container failed to start
(005614) [14:25:16] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(005614) [14:25:16] *** output passed to waydroid stdout, not to this log ***
```

```
$ sudo waydroid logcat
[14:25:53] WayDroid container is STOPPED
```

```
$ cat /var/lib/waydroid/waydroid.cfg
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1726882253
vendor_datetime = 1726917703
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = anbox-binder
vndbinder = anbox-vndbinder
hwbinder = anbox-hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3
auto_adb = True

[properties]
ro.hardware.gralloc = default
ro.hardware.egl = swiftshader
```

### Waydroid version

1.4.3

### Device

Linux Desktop

### Operating System

Debian GNU/Linux 12 (bookworm)

### Kernel version

6.1.0-25-amd64

### Desktop Environment

sway/stable,now 1.7-6 amd64

### GPU

N/A

### Logs

/var/lib/waydroid/waydroid.cfg
```
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1726882253
vendor_datetime = 1726917703
suspend_action = freeze
mount_overlays = True
images_path = /var/lib/waydroid/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = anbox-binder
vndbinder = anbox-vndbinder
hwbinder = anbox-hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3
auto_adb = True

[properties]
ro.hardware.gralloc = default
ro.hardware.egl = swiftshader
```
/var/lib/waydroid/waydroid.prop
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.3
ro.vndk.lite=true
ro.hardware.gralloc=default
ro.hardware.egl=swiftshader
waydroid.host.user=etheller
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/etheller/.local/share/waydroid/data
waydroid.background_start=false
waydroid.xdg_runtime_dir=/run/xdg
waydroid.pulse_runtime_path=/run/xdg/pulse
waydroid.wayland_display=wayland-0
waydroid.stub_sensors_hal=1
```
/var/lib/waydroid/waydroid_base.prop
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.3
ro.vndk.lite=true
ro.hardware.gralloc=default
ro.hardware.egl=swiftshader
```
/var/lib/waydroid/waydroid.log
[waydroid.log](https://github.com/user-attachments/files/17165644/waydroid.log)
`sudo waydroid shell -- logcat -d | tee logcat.txt`
```
[14:31:26] WayDroid container is STOPPED
```
`sudo dmesg | tee dmesg.txt`

[dmesg.txt](https://github.com/user-attachments/files/17165673/dmesg.txt)

**Comment by Retera** [comment]
I still don't fully understand why this is necessary but it seems that as a temporary workaround, I can use:

```
sudo apt install pulseaudio
# then did a reboot between the above command and the below
cd /tmp/sway
ln -sf /run/user/1000/pulse/ .
```

Note that I am using `XDG_RUNTIME_DIR=/tmp/sway` when I launch the sway window manager, and that is from a custom script so it's possible that another user running their own sway window manager from their own directory of choice might not have `/tmp/sway` as the exact path.

**Comment by TimoPtr** [comment]
I had the same issue. While I was trying to find the root cause of the issue I found out that pulseaudio was not started so the `native` socket was not created, which led to the same issue as you. On my side a simple `pulseaudio --start` before `waydroid session start` fixed the issue.

**Comment by adrian-moisa** [comment]
Had the same issue, Thanks to @TimoPtr managed to fix it with:
```
sudo apt update
sudo apt install pulseaudio
pulseaudio --start
# and then started waydroid as usual
```

**Comment by AlexeiScherbakov** [comment]
In debian 13 with gnome
```
sudo apt install pulseaudio
```
will lead to removing UI :-), so it is not a solution.
```
Installing:                     
  pulseaudio

Installing dependencies:
  libasound2-plugins  libpulsedsp  pulseaudio-utils

Suggested packages:
  pavumeter  pavucontrol  paprefs

REMOVING:
  gnome  gnome-core  pipewire-alsa  pipewire-audio  task-gnome-desktop
```

On debian 13 with KDE this command can be executed, but it works with pipewire/pipewire-pulse.

You shouldn't add direct dependency to pulseaudio on debian because modern debian has pipewire installed as default with Gnome
