### ISSUE TITLE
[BUG] OSError: container failed to start

### ISSUE THREAD

**Issue by themg95** [waydroid/waydroid#1580]
### Describe the bug

The container fails to start for what seems like no reason at all.

### Waydroid version

1.4.2

### Device

Linux Desktop

### Operating System

NixOS

### Kernel version

6.10.6-asahi

### Desktop Environment

Hyprland

### GPU

Apple M2

### Logs

```
/nix/store/acp9lvz5qx2wqpa71r07jmd22afrfgh1-waydroid-1.4.2/lib/waydroid/tools/helpers/net.py:34: SyntaxWarning: invalid escape sequence '\d'
  return re.search("(\d{1,3}\.){3}\d{1,3}\s", f.read()).group().strip()
(009151) [10:12:48] % mount -o ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(009151) [10:12:48] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(009151) [10:12:48] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(009151) [10:12:48] Save config: /var/lib/waydroid/waydroid.cfg
(009151) [10:12:48] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(009151) [10:12:48] New background process: pid=9221, output=background
(009151) [10:12:48] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-start: waydroid: ../src/lxc/conf.c: turn_into_dependent_mounts: 3451 No such file or directory - Failed to recursively turn old root mount tree into dependent mount. Continuing...
lxc-info: waydroid: ../src/lxc/af_unix.c: lxc_abstract_unix_recv_fds_iov: 218 Connection reset by peer - Failed to receive response
lxc-info: waydroid: ../src/lxc/commands.c: lxc_cmd_rsp_recv_fds: 128 Failed to receive file descriptors for command "get_init_pid"
STOPPED
(009151) [10:12:48] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(009151) [10:12:48] waiting 10 seconds for container to start...
lxc-start: waydroid: ../src/lxc/utils.c: run_buffer: 571 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 986 Failed to run lxc.hook.post-stop for container "waydroid"
(009151) [10:12:49] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(009151) [10:12:49] waiting 9 seconds for container to start...
(009151) [10:12:50] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(009151) [10:12:50] waiting 8 seconds for container to start...
(009151) [10:12:51] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(009151) [10:12:51] waiting 7 seconds for container to start...
(009151) [10:12:52] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(009151) [10:12:52] waiting 6 seconds for container to start...
(009151) [10:12:53] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(009151) [10:12:53] waiting 5 seconds for container to start...
(009151) [10:12:54] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(009151) [10:12:54] waiting 4 seconds for container to start...
(009151) [10:12:55] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(009151) [10:12:55] waiting 3 seconds for container to start...
(009151) [10:12:56] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(009151) [10:12:56] waiting 2 seconds for container to start...
(009151) [10:12:57] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(009151) [10:12:57] waiting 1 seconds for container to start...
(009149) [10:12:58] org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):
  File "/nix/store/2bqgcmdzwm1jf0341mjbf3ih8qkhc99m-python3.12-dbus-python-1.3.2/lib/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/acp9lvz5qx2wqpa71r07jmd22afrfgh1-waydroid-1.4.2/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/nix/store/acp9lvz5qx2wqpa71r07jmd22afrfgh1-waydroid-1.4.2/lib/waydroid/tools/actions/container_manager.py", line 189, in do_start
    helpers.lxc.start(args)
  File "/nix/store/acp9lvz5qx2wqpa71r07jmd22afrfgh1-waydroid-1.4.2/lib/waydroid/tools/helpers/lxc.py", line 397, in start
    wait_for_running(args)
  File "/nix/store/acp9lvz5qx2wqpa71r07jmd22afrfgh1-waydroid-1.4.2/lib/waydroid/tools/helpers/lxc.py", line 391, in wait_for_running
    raise OSError("container failed to start")
OSError: container failed to start

(009149) [10:12:58] OSError: container failed to start
```

**Comment by misterspleepy** [comment]
I meet this problem too, is there anyone who can solve it

**Comment by argonaut0** [comment]
repro as well. seems like an issue specific to asahi nixos.

**Comment by Vikthor** [comment]
No, it's not. I have the same problem - Gentoo, Waydroid 1.4.3-r1.

**Comment by sirkorgo** [comment]
@argonaut0 i can confirm that this occurs on asahi fedora (i get the same error)

**Comment by suoko** [comment]
Somebody suggested special arm builds but I still have error 
https://drive.usercontent.google.com/download?id=1Ikk7BnwAGFT28LHMMTVQjbGdPBQz6nne&export=download&authuser=0&confirm=t&uuid=1e5baaad-8c32-4e3a-8e10-a206e7ad5996&at=APcmpowAoVf_9xYNHYaZGEZPoA1n%3A1744645061822

**Comment by Kyuugeki** [comment]
Having the same error on the Raspberry Pi 5 (Raspberry Pi OS)
Anyone solved this?

**Comment by themg95** [comment]
are there any updates on this?

**Comment by lks9** [comment]
Duplicate to #1158.
