### ISSUE TITLE
[BUG] [Errno 2] No such file or directory: 'modprobe'

### ISSUE THREAD

**Issue by Danielperfull-00** [waydroid/waydroid#1584]
### Describe the bug

daniel@penguin:~$ waydroid log
(014080) [07:16:48] ERROR: Action "init" needs root access
(014080) [07:16:48] See also: <https://github.com/waydroid>
(014080) [07:16:48] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 63, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "init" needs root access

(014105) [07:19:53] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(014105) [07:19:53] ERROR: [Errno 2] No such file or directory: 'modprobe'
(014105) [07:19:53] See also: <https://github.com/waydroid>
(014105) [07:19:53] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 117, in init
    if not setup_config(args):
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 103, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 128, in setupBinderNodes
    probeBinderDriver(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 95, in probeBinderDriver
    output = tools.helpers.run.user(args, command, check=False, output_return=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 335, in core
    (code, output_after_run) = foreground_pipe(args, cmd, working_dir,
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 147, in foreground_pipe
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'modprobe'

(014108) [07:21:41] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(014108) [07:21:41] *** output passed to waydroid stdout, not to this log ***

### Waydroid version

1.4.3

### Device

Linux Desktop

### Operating System

Debian GNU/Linux 12 (bookworm) on Chrome OS x86_64 

### Kernel version

6.1.60-08594-g03a802b9a072 

### Desktop Environment

Chromebook

### GPU

Intel Celeron N4000 (2) @ 1.094GHz 

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log
`sudo waydroid shell -- logcat -d | tee logcat.txt`
`sudo dmesg | tee dmesg.txt`

**Comment by abtye** [comment]
Have you installed `kmod`?

**Comment by Danielperfull-00** [comment]
Yes sudo apt-get install kmod

**Comment by Danielperfull-00** [comment]
Yes 

> ¿Lo has instalado `kmod`?

**Comment by abtye** [comment]
Oh, I didn't examine the log carefully. You need to execute this command with root privileges. Try to run `sudo waydroid init`. On Debian, `modprobe` is located in `/sbin`, which is not included in the PATH for regular users.

**Comment by abtye** [comment]
Did you solve the problem?

**Comment by gariac** [comment]
Log into root using su -

The minus sign after su is the trick. I did the init using debian 13

There is an explanation here:
https://www.baeldung.com/linux/su-command-options
