### ISSUE TITLE
[BUG] OSError: container failed to start, in ARCH LINUX LTS KERNEL

### ISSUE THREAD

**Issue by Tenuka22** [waydroid/waydroid#1595]
### Describe the bug

I've installed the Modules required to the LTS KERNEL and default Image works with this but My custom Image dosent work [arm64](https://drive.google.com/file/d/1Ikk7BnwAGFT28LHMMTVQjbGdPBQz6nne/view?pli=1) I neeed this one becuase I want to install mlbb in this one. I need help to continue, I copied the images to the folder `/etc/waydroid-extra/images/`
![image](https://github.com/user-attachments/assets/c9e46145-19a0-490c-8cb1-54df564b83db)
 and I ran the `sudo waydroid init -f` and once I run this the following errors pops.

```
sudo waydroid log
(000636) [19:55:50] New background process: pid=75013, output=background
(000636) [19:55:50] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-start: waydroid: ../src/lxc/conf.c: turn_into_dependent_mounts: 3451 No such file or directory - Failed to recursively turn old root mount tree into dependent mount. Continuing...
lxc-start: waydroid: ../src/lxc/start.c: start: 2204 Exec format error - Failed to exec "/init"
lxc-start: waydroid: ../src/lxc/sync.c: sync_wait: 34 An error occurred in another process (expected sequence number 7)
lxc-start: waydroid: ../src/lxc/start.c: __lxc_start: 2114 Failed to spawn container "waydroid"
lxc-info: waydroid: ../src/lxc/af_unix.c: lxc_abstract_unix_recv_fds_iov: 218 Connection reset by peer - Failed to receive response
lxc-info: waydroid: ../src/lxc/commands.c: lxc_cmd_rsp_recv_fds: 128 Failed to receive file descriptors for command "get_init_pid"
STOPPED
(000636) [19:55:51] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-start: waydroid: ../src/lxc/utils.c: run_buffer: 571 Script exited with status 126
lxc-start: waydroid: ../src/lxc/start.c: lxc_end: 986 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: lxc_start_main: 307 The container failed to start
lxc-start: waydroid: ../src/lxc/tools/lxc_start.c: lxc_start_main: 312 Additional information can be obtained by setting the --logfile and --logpriority options
STOPPED
(000636) [19:55:51] waiting 10 seconds for container to start...
(000636) [19:55:52] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000636) [19:55:52] waiting 9 seconds for container to start...
(000636) [19:55:53] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000636) [19:55:53] waiting 8 seconds for container to start...
(000636) [19:55:54] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000636) [19:55:54] waiting 7 seconds for container to start...
(000636) [19:55:55] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000636) [19:55:55] waiting 6 seconds for container to start...
(000636) [19:55:56] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000636) [19:55:56] waiting 5 seconds for container to start...
(000636) [19:55:57] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000636) [19:55:57] waiting 4 seconds for container to start...
(000636) [19:55:58] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000636) [19:55:58] waiting 3 seconds for container to start...
(000636) [19:55:59] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000636) [19:55:59] waiting 2 seconds for container to start...
(000636) [19:56:00] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(000636) [19:56:00] waiting 1 seconds for container to start...
(074983) [19:56:01] org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):
File "/usr/lib/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
retval = candidate_method(self, *args, **keywords)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
do_start(self.args, session)
File "/usr/lib/waydroid/tools/actions/container_manager.py", line 189, in do_start
helpers.lxc.start(args)
File "/usr/lib/waydroid/tools/helpers/lxc.py", line 400, in start
wait_for_running(args)
File "/usr/lib/waydroid/tools/helpers/lxc.py", line 394, in wait_for_running
raise OSError("container failed to start")
OSError: container failed to start

(074983) [19:56:01] OSError: container failed to start
(075145) [19:56:21] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(075145) [19:56:21] *** output passed to waydroid stdout, not to this log ***
```

### Waydroid version

1.4.3

### Device

Linux Desktop

### Operating System

GARUDA LINUX ( KDE ARCH )

### Kernel version

6.6.56-1-lts

### Desktop Environment

KDE 6 

### GPU

INTEL UHD GRAPHICs

### Logs

/var/lib/waydroid/waydroid.cfg
/var/lib/waydroid/waydroid.prop
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log

[waydroid.zip](https://github.com/user-attachments/files/17397457/waydroid.zip)
This is the configs

`sudo waydroid shell -- logcat -d | tee logcat.txt
[sudo] password for tenuka:
[20:03:37] WayDroid container is STOPPED
`
[dmesg.txt](https://github.com/user-attachments/files/17397470/dmesg.txt)
[logcat.txt](https://github.com/user-attachments/files/17397473/logcat.txt)

**Comment by Artem3213212** [comment]
The same problem. If you see to https://github.com/waydroid/waydroid/blob/5000c9703de873e4f477ebcdd3556ad163252115/tools/helpers/lxc.py#L397
You will see command that not work. Full version in console: `lxc-start -P lxc -F /var/lib/waydroid/lxc -n waydroid -- /init`
When i tryed to execute it i had problem:

**Comment by starise-wg** [comment]
May I ask if this issue has been resolved? I have also encountered the same problem

**Comment by Tenuka22** [comment]
> May I ask if this issue has been resolved? I have also encountered the same problem

This is the problem I thnk this is because my pc only supports 86x64 If I had a amd cpu then I can have amd os running
