### ISSUE TITLE
[BUG] Waydroid won't run if system doesn't use WAYLAND.

### ISSUE THREAD

**Issue by EvilSupahFly** [waydroid/waydroid#1641]
### Describe the bug

When attempting to run Waydroid for the first time, I get this error:
```
⎧evilsupahfly on Black-Beast - Wed 11 Dec 2024 12:17:13 EST
⎩[~] waydroid -v --details-to-stdout first-launch
(2039353) [12:18:01] Starting waydroid session
(2039353) [12:18:01] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(2039353) [12:18:01] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?
```
X11 still accounts for over two thirds of use cases. Wayland might have some major improvements, but it's still (essentially) a beta release in terms of bug squashing and mainstream adoption.

Because Wayland isn't the defacto default universal compositor, failing on launch just because Wayland isn't running rather than looking for a fallback hurts Waydroid in the long term.

### Waydroid version

1.4.3

### Device

Linux Desktop

### Operating System

Linux Mint 22 (based on Ubuntu 24.04)

### Kernel version

6.8.0-49-lowlatency

### Desktop Environment

Cinnamon (X11)

### GPU

Primary GPU: NVIDIA Corporation TU116 [GeForce GTX 1660], Secondary GPU: NVIDIA Corporation GP106 [GeForce GTX 1060 6GB]

### Logs

/var/lib/waydroid/waydroid.cfg:
```
⎧evilsupahfly on Black-Beast - Wed 11 Dec 2024 12:40:05 EST
⎩[~] cat /var/lib/waydroid/waydroid.cfg
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 1733548611
vendor_datetime = 1733570504
suspend_action = freeze
mount_overlays = True
auto_adb = True
images_path = /var/lib/waydroid/images
binder = anbox-binder
vndbinder = anbox-vndbinder
hwbinder = anbox-hwbinder
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json

[properties]

```
/var/lib/waydroid/waydroid.prop:
```
⎧evilsupahfly on Black-Beast - Wed 11 Dec 2024 12:40:16 EST
⎩[~] cat /var/lib/waydroid/waydroid.prop
cat: /var/lib/waydroid/waydroid.prop: No such file or directory
```
/var/lib/waydroid/waydroid_base.prop:
```
⎧evilsupahfly on Black-Beast - Wed 11 Dec 2024 12:41:00 EST
⎩[~] cat /var/lib/waydroid/waydroid_base.prop
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=default
ro.hardware.egl=swiftshader
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.4.3
ro.vndk.lite=true
```
/var/lib/waydroid/waydroid.log
```
⎧evilsupahfly on Black-Beast - Wed 11 Dec 2024 12:41:41 EST
⎩[~] cat /var/lib/waydroid/waydroid.log
(2012498) [12:11:36] ERROR: Action "init" needs root access
(2012498) [12:11:36] See also: <https://github.com/waydroid>
(2012498) [12:11:36] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 63, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 21, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "init" needs root access

(2012502) [12:11:43] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(2012502) [12:11:43] % mkdir -p /dev/binderfs
(2012502) [12:11:43] % mount -t binder binder /dev/binderfs
(2012502) [12:11:43] % ln -s /dev/binderfs/features /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/binder-control /dev/
(2012502) [12:11:43] Save config: /var/lib/waydroid/waydroid.cfg
(2012502) [12:11:43] % mkdir -p /var/lib/waydroid/cache_http
(2012502) [12:11:43] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20241207-VANILLA-waydroid_x86_64-system.zip/download
(2012502) [12:12:42] Validating system image
(2012502) [12:12:44] Extracting to /var/lib/waydroid/images
(2012502) [12:12:52] Save config: /var/lib/waydroid/waydroid.cfg
(2012502) [12:12:53] Downloading https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-18.1-20241207-MAINLINE-waydroid_x86_64-vendor.zip/download
(2012502) [12:13:12] Validating vendor image
(2012502) [12:13:12] Extracting to /var/lib/waydroid/images
(2012502) [12:13:15] Save config: /var/lib/waydroid/waydroid.cfg
(2012502) [12:13:15] % modprobe -q ashmem_linux
(2012502) [12:13:15] % lxc-info --version
5.0.3
(2012502) [12:13:15] % mkdir -p /var/lib/waydroid/lxc/waydroid
(2012502) [12:13:15] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(2012502) [12:13:15] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(2012502) [12:13:15] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(2012502) [12:13:15] % aa-enabled --quiet
(2012502) [12:13:15] % sed -i -E /lxc.aa_profile|lxc.apparmor.profile/ s/unconfined/lxc-waydroid/g /var/lib/waydroid/lxc/waydroid/config
(2012502) [12:13:15] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(2012404) [12:13:15] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(2012404) [12:13:15] % modprobe -q ashmem_linux
(2012404) [12:13:15] % chmod 666 -R /dev/anbox-binder
(2012404) [12:13:15] % chmod 666 -R /dev/anbox-vndbinder
(2012404) [12:13:15] % chmod 666 -R /dev/anbox-hwbinder
(2012699) [12:13:34] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(2012699) [12:13:34] % modprobe -q ashmem_linux
(2012699) [12:13:34] % lxc-info --version
5.0.3
(2012699) [12:13:34] % mkdir -p /var/lib/waydroid/lxc/waydroid
(2012699) [12:13:34] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(2012699) [12:13:34] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(2012699) [12:13:34] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(2012699) [12:13:34] % aa-enabled --quiet
(2012699) [12:13:34] % sed -i -E /lxc.aa_profile|lxc.apparmor.profile/ s/unconfined/lxc-waydroid/g /var/lib/waydroid/lxc/waydroid/config
(2012699) [12:13:34] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(2012404) [12:13:35] Hardware service is not even started
(2012404) [12:13:35] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(2012404) [12:13:35] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(2012404) [12:13:35] % systemctl is-enabled -q nfcd
(2012883) [12:13:35] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(2012883) [12:13:35] % modprobe -q ashmem_linux
(2012883) [12:13:35] % chmod 666 -R /dev/anbox-binder
(2012883) [12:13:35] % chmod 666 -R /dev/anbox-vndbinder
(2012883) [12:13:35] % chmod 666 -R /dev/anbox-hwbinder
(2018945) [12:15:41] Starting waydroid session
(2018945) [12:15:41] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(2018945) [12:15:41] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?
(2027699) [12:16:48] Run waydroid -h for usage information.
(2029659) [12:17:13] Starting waydroid session
(2029659) [12:17:13] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
(2029659) [12:17:13] Wayland socket '/run/user/1000/wayland-0' doesn't exist; are you running a Wayland compositor?
(2072366) [12:38:03] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(2072366) [12:38:03] WayDroid container is STOPPED
(2072421) [12:39:47] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(2072421) [12:39:47] WayDroid container is STOPPED
(2072432) [12:40:04] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(2072432) [12:40:04] WayDroid container is STOPPED
```
`sudo waydroid shell -- logcat -d | tee logcat.txt`:
```
⎧evilsupahfly on Black-Beast - Wed 11 Dec 2024 12:42:22 EST
⎩[~] sudo waydroid shell -- logcat -d | tee logcat.txt
[12:43:11] WayDroid container is STOPPED
```
`sudo dmesg | tee dmesg.txt`:

See https://pastebin.com/KyKEQK0Z for dmesg output.

**Comment by yxles-dev** [comment]
Waydroid is developed specifically to use Wayland an X11 support is likely not to happen. You could either use a nested compositor like Weston or setup a QEMU with hardware acceleration (guide can be seen here: https://docs.waydro.id/faq/get-waydroid-to-work-through-a-vm)

**Comment by EvilSupahFly** [comment]
Ah. Perhaps an addendum to the README is in order then?

**Comment by Quackdoc** [comment]
Waydroid supports nested wayland compositors, on x11 you can use cage weston etc.
