### ISSUE TITLE
ModuleNotFoundError: No module named 'gbinder'

### ISSUE THREAD

**Issue by zxcv05** [waydroid/waydroid#1658]
I'm running Arch Linux, I have installed installed `waydroid=1.4.3-1`, `python-gbinder=1.1.2-2`, and `libgbinder=1.1.40-2`

When running `waydroid`:
```
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 7, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 12, in <module>
    from . import actions
  File "/usr/lib/waydroid/tools/actions/__init__.py", line 3, in <module>
    from tools.actions.initializer import init, wait_for_init, remote_init_client
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 5, in <module>
    from tools import helpers
  File "/usr/lib/waydroid/tools/helpers/__init__.py", line 5, in <module>
    import tools.helpers.props
  File "/usr/lib/waydroid/tools/helpers/props.py", line 8, in <module>
    from tools.interfaces import IPlatform
  File "/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 1, in <module>
    import gbinder
ModuleNotFoundError: No module named 'gbinder'
```

In a venv with `include-system-site-packages = true` in `pyvenv.cfg`, doing `import gbinder` results in `ModuleNotFoundError` aswell

**Comment by nneewwoo** [comment]
Maybe your system's python version has updated.
Try `yay -S python-gbinder --rebuild`

**Comment by dchmelik** [comment]
I have same problem on Slackware-current (up-to-date 64-bit n86).
