### ISSUE TITLE
Clipboard fails to load anything and leads to crashing of the apps

### ISSUE THREAD

**Issue by rinigus** [waydroid/waydroid#167]
On Sailfish, when installing pyclip and latest gbinder-python (https://github.com/waydroid/gbinder-python/tree/cd7620aa0d2e8875785708ad4263808636f3dce5) and Waydroid (https://github.com/waydroid/waydroid/tree/9a87b10bbfd9cc04c8259207233fadad9acbf5d3), I am getting following stdout from `waydroid session start` when typing:

```
Traceback (most recent call last):
  File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
  File "/opt/waydroid/tools/interfaces/IClipboard.py", line 29, in response_handler
    local_response.append_string16(ret)
  File "gbinder.pyx", line 350, in gbinder.LocalReply.append_string16
  File "gbinder.pyx", line 9, in gbinder.ensure_binary
TypeError: not expecting type '<class 'NoneType'>'
Exception ignored in: 'gbinder.local_transact_callback'
Traceback (most recent call last):
  File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
  File "/opt/waydroid/tools/interfaces/IClipboard.py", line 29, in response_handler
    local_response.append_string16(ret)
  File "gbinder.pyx", line 350, in gbinder.LocalReply.append_string16
  File "gbinder.pyx", line 9, in gbinder.ensure_binary
TypeError: not expecting type '<class 'NoneType'>'

```

Occasionally that can lead to Firefox crashes in Android. Pasting is not possible from Android to Sailfish nor in the opposite direction. Old Wayland composer?

**Comment by aleasto** [comment]
Closing this because it's very old. Probably fixed by now
