### ISSUE TITLE
Possible to have access to camera?

### ISSUE THREAD

**Issue by ghost** [waydroid/waydroid#170]
Hi,

I wanted to ask if it is possible to access the camera inside the Waydroid-Container.
Or is this technically impossible to implement?

**Comment by julianfairfax** [comment]
@MartijnBraam since you're the developer of Megapixels, which is the only app on my PinePhone that seems to actually work with the camera, would you have any input on how camera access could be achieved in Waydroid? Thanks for your help and thanks for all your development!

**Comment by rizzini** [comment]
+1 vote for this. Anbox doesn't have camera support either, but, as you can see [here](https://github.com/anbox/anbox/issues/727#issuecomment-882068226), a user managed to develop a way us to use vídeo device on it and it works, poorly, but works enough to make WhatsApp Web feasible. You can use virtual video devices and USB real ones. It's the only thing that holds me with Anbox, which [doesn't run on my super old NVIDIA card using its proprietary drivers](https://github.com/anbox/anbox/issues/1776).

**Comment by rizzini** [comment]
> OBS virtual camera also doesnt work with v4l2loopback-dkms

Either my super generic webcam and my v4l2loopback-dkms as well.

**Comment by superjerry-zhu** [comment]
I have a uvc camera, but l can not use it in the waydroid container, the camera app can not find the device.
Does any one know how to make it works? any guide or steps, many thanks.
lsusb -t
/:  Bus 08.Port 1: Dev 1, Class=root_hub, Driver=ohci-platform/1p, 12M
/:  Bus 07.Port 1: Dev 1, Class=root_hub, Driver=ehci-platform/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/7p, 480M
        |__ Port 1: Dev 3, If 1, Class=Human Interface Device, Driver=usbhid, 1.5M
        |__ Port 1: Dev 3, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
        |__ Port 2: Dev 4, If 0, Class=Diagnostic, Driver=, 480M
        |__ Port 3: Dev 5, If 0, Class=Human Interface Device, Driver=usbhid, 1.5M
        |__ Port 4: Dev 7, If 0, Class=Video, Driver=uvcvideo, 480M
        |__ Port 4: Dev 7, If 1, Class=Video, Driver=uvcvideo, 480M
/:  Bus 06.Port 1: Dev 1, Class=root_hub, Driver=xhci-hcd/1p, 5000M
/:  Bus 05.Port 1: Dev 1, Class=root_hub, Driver=xhci-hcd/1p, 480M
/:  Bus 04.Port 1: Dev 1, Class=root_hub, Driver=ohci-platform/1p, 12M
/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=ehci-platform/1p, 480M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci-hcd/1p, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci-hcd/1p, 480M

**Comment by nmschulte** [comment]
I as well am having trouble with Waydroid not using the `/dev/video*` devices that are being exposed to it, of my UVC web camera.

Please assist me in diagnosing this issue.

```
12-03 15:59:04.140   450   672 I chatty  : uid=1000(system) Binder:450_5 identical 79 lines
12-03 15:59:04.156   450   672 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.017   450   554 W AS.AudioService: onLoadSoundEffects(), Error -1 while loading samples
12-03 15:59:05.017   450  2091 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.android.camera2/com.android.camera.CameraLauncher bnds=[795,434][1125,593]} from uid 10095
12-03 15:59:05.019   450   672 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.020  3864  3864 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@cfbf1fa
12-03 15:59:05.022  3864  3864 V CAM_QuickActivity: START onCreate: Activity = com.android.camera.CameraActivity@c5c63ab
12-03 15:59:05.022  3864  3864 V CAM_Profiler: [  0.000ms][ui] GUARD: CameraActivity.onCreateTasks - START
12-03 15:59:05.022  3864  3864 D CAM_LocationManager: Using LegacyLocationProvider
12-03 15:59:05.023  3864  3864 I CAM_OneCamFtrCnfgCrtr: CaptureModule? true
12-03 15:59:05.023  3864  3864 V CAM_Profiler: [  0.812ms][ui] GUARD: CameraActivity.onCreateTasks - [ 0.002ms] Glide.setup
12-03 15:59:05.023  3864  3864 D CAM_Camera2OneCamMgr: Getting First BACK Camera
12-03 15:59:05.023  3864  3864 W CAM_Camera2OneCamMgr: No back-facing camera found.
12-03 15:59:05.023  3864  3864 D CAM_Camera2OneCamMgr: Getting First FRONT Camera
12-03 15:59:05.024  3864  3864 W CAM_Camera2OneCamMgr: No front-facing camera found.
12-03 15:59:05.024  3864  3864 V CAM_Profiler: [  1.506ms][ui] GUARD: CameraActivity.onCreateTasks - [ 0.694ms] OneCameraManager.get
12-03 15:59:05.024  3864  3864 V CAM_SettingsManager: listeners: [com.android.camera.CameraActivity@c5c63ab]
12-03 15:59:05.025  3864  3864 V CAM_Profiler: [  2.557ms][ui] GUARD: CameraActivity.onCreateTasks - [ 0.336ms] computePictureSizes
12-03 15:59:05.034  3864  3864 V CAM_Profiler: [ 11.601ms][ui] GUARD: CameraActivity.onCreateTasks - [ 8.950ms] setContentView()
12-03 15:59:05.035  3864  3864 V CAM_Profiler: [ 12.802ms][ui] GUARD: CameraActivity.onCreateTasks - [ 1.201ms] Configure Camera UI
12-03 15:59:05.035  3864  3864 V CAM_CameraController: Closing camera
12-03 15:59:05.035  3864  4652 W CAM2PORT_AndCamAgntImp: Releasing camera without any camera opened.
12-03 15:59:05.035  3864  3864 V CAM_ModulesInfo: EnableCaptureModule = true
12-03 15:59:05.035  3864  3864 V CAM_Profiler: [  0.000ms][ui] GUARD: new CaptureModule - START
12-03 15:59:05.036  3864  3864 V CAM_Profiler: [  0.363ms][ui] GUARD: new CaptureModule - STOP
12-03 15:59:05.036  3864  3864 V CAM_SettingsManager: listeners: [com.android.camera.CameraActivity@c5c63ab, com.android.camera.app.CameraAppUI@88b8cf]
12-03 15:59:05.036   450  2091 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.036  3864  3864 V CAM_SettingsManager: listeners: [com.android.camera.CameraActivity@c5c63ab, com.android.camera.app.CameraAppUI@88b8cf, com.android.camera.ButtonManager@167d848]
12-03 15:59:05.036  3864  3864 V CAM_SettingsManager: listeners: [com.android.camera.CameraActivity@c5c63ab, com.android.camera.app.CameraAppUI@88b8cf, com.android.camera.ButtonManager@167d848, com.android.camera.widget.IndicatorIconController@d1f1c06]
12-03 15:59:05.036  3864  3864 V CAM_Profiler: [ 14.376ms][ui] GUARD: CameraActivity.onCreateTasks - [ 0.586ms] Init Current Module UI
12-03 15:59:05.036  3864  3864 V CAM_Profiler: [  0.000ms][ui] GUARD: CaptureModule.init - START
12-03 15:59:05.036  3864  3864 D CAM_CaptureModule: init UseAutotransformUiLayout = false
12-03 15:59:05.037  3864  3864 D CAM_Camera2OneCamMgr: Getting First BACK Camera
12-03 15:59:05.037  3864  3864 W CAM_Camera2OneCamMgr: No back-facing camera found.
12-03 15:59:05.037  3864  3864 D CAM_Camera2OneCamMgr: Getting First FRONT Camera
12-03 15:59:05.037  3864  3864 W CAM_Camera2OneCamMgr: No front-facing camera found.
12-03 15:59:05.037  3864  3864 D CAM_Camera2OneCamMgr: Getting First FRONT Camera
12-03 15:59:05.037  3864  3864 W CAM_Camera2OneCamMgr: No front-facing camera found.
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler: Handling Camera Access Failure:
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler: java.lang.Exception
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at com.android.camera.FatalErrorHandlerImpl.onGenericCameraAccessFailure(FatalErrorHandlerImpl.java:84)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at com.android.camera.CaptureModule.updateCameraCharacteristics(CaptureModule.java:396)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at com.android.camera.CaptureModule.init(CaptureModule.java:417)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at com.android.camera.CameraActivity.onCreateTasks(CameraActivity.java:1651)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at com.android.camera.util.QuickActivity.onCreate(QuickActivity.java:114)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at android.app.Activity.performCreate(Activity.java:7834)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at android.app.Activity.performCreate(Activity.java:7823)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1306)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at android.os.Handler.dispatchMessage(Handler.java:107)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at android.os.Looper.loop(Looper.java:214)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at android.app.ActivityThread.main(ActivityThread.java:7356)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at java.lang.reflect.Method.invoke(Native Method)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
12-03 15:59:05.037  3864  3864 E CAM_FatalErrorHandler:         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
12-03 15:59:05.037  3864  3864 E CAM_CameraUtil: Show fatal error dialog
12-03 15:59:05.039   450  2091 E WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
12-03 15:59:05.039  3864  3864 V CAM_Profiler: [ 17.117ms][ui] GUARD: CameraActivity.onCreateTasks - [ 2.741ms] Init CurrentModule
12-03 15:59:05.040  3864  3864 I CAM_Profiler: [ 17.662ms][ui] GUARD: CameraActivity.onCreateTasks - STOP
12-03 15:59:05.040  3864  3864 V CAM_QuickActivity: END onCreate: Activity = com.android.camera.CameraActivity@c5c63ab
12-03 15:59:05.040  3864  3864 V CAM_QuickActivity: START onStart: Activity = com.android.camera.CameraActivity@c5c63ab
12-03 15:59:05.040  3864  4661 D CAM_MemoryQuery: timestamp=3671923, availMem=22858, totalMem=32117, totalPSS=50, lastTrimLevel=0, largeMemoryClass=512, nativePSS=0, dalvikPSS=0, otherPSS=50,threshold=216, lowMemory=false
12-03 15:59:05.040  3864  3864 V CAM_QuickActivity: END onStart: Activity = com.android.camera.CameraActivity@c5c63ab
12-03 15:59:05.040  3864  3864 V CAM_QuickActivity: START onResume: Activity = com.android.camera.CameraActivity@c5c63ab
12-03 15:59:05.040  3864  3864 V CAM_QuickActivity: onResume(): isKeyguardLocked() = false
12-03 15:59:05.040  3864  3864 V CAM_QuickActivity: onResume --> onResumeTasks()
12-03 15:59:05.040  3864  3864 V CAM_Profiler: [  0.000ms][ui] GUARD: CameraActivity.resume - START
12-03 15:59:05.040  3864  3864 V CAM_CameraActivity: Build info: lineage_waydroid_x86_64-userdebug 10 QQ3A.200805.001 20 test-keys
12-03 15:59:05.041  3864  3864 W OrientationEventListener: Cannot detect sensors. Not enabled
12-03 15:59:05.041  3864  3864 V CAM_Profiler: [  0.348ms][ui] GUARD: CameraActivity.resume - [ 0.007ms] mCurrentModule.resume
12-03 15:59:05.041  3864  3864 V CAM_Profiler: [  0.404ms][ui] GUARD: CameraActivity.resume - [ 0.001ms] mPanoramaViewHelper.onResume()
12-03 15:59:05.041  3864  3864 V CAM_Profiler: [  0.432ms][ui] GUARD: CameraActivity.resume - STOP
12-03 15:59:05.041  3864  3864 V CAM_QuickActivity: END onResume: Activity = com.android.camera.CameraActivity@c5c63ab
12-03 15:59:05.041  3864  4661 D CAM_Storage: External storage state=mounted
12-03 15:59:05.041  3864  3864 E MediaActionSound: OnLoadCompleteListener() error: -1 loading sound: 0
12-03 15:59:05.043  3864  4537 V CAM_CameraDataAdapter: retrieved photo metadata, number of items: 0
12-03 15:59:05.043  3864  4537 V CAM_CameraDataAdapter: retrieved video metadata, number of items: 0
12-03 15:59:05.043  3864  4537 V CAM_CameraDataAdapter: sorting video/photo metadata
12-03 15:59:05.043  3864  4537 V CAM_CameraDataAdapter: sorted video/photo metadata
12-03 15:59:05.053   450   672 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.041   450  2091 E WindowManager: App trying to use insecure INPUT_FEATURE_NO_INPUT_CHANNEL flag. Ignoring
12-03 15:59:05.053   786   786 W ViewRootImpl[LineageLauncher]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_ALT_LEFT, scanCode=56, metaState=META_ALT_ON|META_ALT_LEFT_ON, flags=0x28, repeatCount=0, eventTime=3671935, downTime=2035513, deviceId=1, source=0x101, displayId=0 }
12-03 15:59:05.054  3864  3864 V CAM_TexViewHelper: onLayoutChange
12-03 15:59:05.054  3864  3864 V CAM_TexViewHelper: updateTransform
12-03 15:59:05.055  3864  3864 V CAM_TexViewHelper: updateTransform
12-03 15:59:05.055  3864  3864 V CAM_CameraAppUI: SurfaceTexture is available
12-03 15:59:05.055  3864  3864 I CAM_FocusRingView: Computing center via view bounds.
12-03 15:59:05.055  3864  3864 V CAM_CameraActivity: ignoring storage callback after activity pause
12-03 15:59:05.053   786   786 I chatty  : uid=10095(com.android.launcher3) identical 7 lines
12-03 15:59:05.053   786   786 W ViewRootImpl[LineageLauncher]: Cancelling event due to no window focus: KeyEvent { action=ACTION_UP, keyCode=KEYCODE_ALT_LEFT, scanCode=56, metaState=META_ALT_ON|META_ALT_LEFT_ON, flags=0x28, repeatCount=0, eventTime=3671935, downTime=2035513, deviceId=1, source=0x101, displayId=0 }
12-03 15:59:05.063   450   531 W WindowManager: Failed looking up window callers=com.android.server.wm.InputManagerCallback.interceptKeyBeforeDispatching:182 com.android.server.input.InputManagerService.interceptKeyBeforeDispatching:1933 <bottom of call stack> 
12-03 15:59:05.067   450   477 I ActivityTaskManager: Displayed com.android.camera2/com.android.camera.CameraLauncher: +49ms
12-03 15:59:05.068  3864  3864 V CAM_CameraDataAdapter: new photos query return num items: 0
12-03 15:59:05.070   450  2160 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.103   450  2160 I chatty  : uid=1000(system) Binder:450_F identical 2 lines
12-03 15:59:05.120   450  2160 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.120   108   108 E RenderEngine: GL error 0x0501
12-03 15:59:05.137   450   672 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.406   450   672 I chatty  : uid=1000(system) Binder:450_5 identical 16 lines
12-03 15:59:05.423   450   672 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.435  3864  3864 V CAM_TexViewHelper: onLayoutChange
12-03 15:59:05.439   450   672 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.472   450   672 I chatty  : uid=1000(system) Binder:450_5 identical 2 lines
12-03 15:59:05.489   450   672 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.503   579   579 D ImageWallpaper: wallpaper visibility changes to: false
12-03 15:59:05.506   108   108 E Layer   : [AppWindowToken{59c7c00 token=Token{5089283 ActivityRecord{202b532 u0 com.android.camera2/com.android.camera.CameraLauncher t38}}} - animation-leash#0] No local sync point found
12-03 15:59:05.506   108   108 E Layer   : [AppWindowToken{126da25 token=Token{5c8ae1c ActivityRecord{4737aee u0 com.android.launcher3/.lineage.LineageLauncher t23}}} - animation-leash#0] No local sync point found
12-03 15:59:05.506   450  2091 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.523   450  2091 I chatty  : uid=1000(system) Binder:450_B identical 1 line
12-03 15:59:05.539   450  2091 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.556   450   672 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.707   450   672 I chatty  : uid=1000(system) Binder:450_5 identical 9 lines
12-03 15:59:05.723   450   672 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.740   450  2160 E InputDispatcher: Window handle WindowManager has no registered input channel
12-03 15:59:05.752  3864  3864 D ViewRootImpl[CameraLauncher]: updatePointerIcon called with position out of bounds
```

**Comment by cristiioan** [comment]
Any update on this? My personal solution for now is to copy waydroid files to pc and back for using the camera. I will activate everything I need camera for in one run.

**Comment by L0v3P01s0n** [comment]
> 

Maybe I can offer myself so you can work with my PP, it's the convergence one. My internal emmc storage as well as a 32gb sd card I have lying around are all yours if you need to. I don't have the knowledge to have any idea of what do to myself but I hope I can contribute by using my unit as a testing device.

**Comment by plata** [comment]
Issue should be merged with #284 and #186.

**Comment by klem-everywhere** [comment]
Shouldn't libcamera be the way to go here?

**Comment by sidevesh** [comment]
Open Camera surprisingly works but I couldn't get any other app to see the camera.

**Comment by psqli** [comment]
> Shouldn't libcamera be the way to go here?

Probably yes. libcamera has an **Android Camera HAL (Hardware Abstraction Layer)** [under development](https://git.libcamera.org/libcamera/libcamera.git/tree/src/android).

Something I'm wondering is whether the current infrastructure would allow a PipeWire video stream to be forward as a camera device on Android. As I've [checked out](https://gitlab.freedesktop.org/pipewire/pipewire/-/tree/master/spa/plugins/libcamera) there is only a source stream for libcamera on PipeWire (ping @wtay).

**Comment by pizdjuk** [comment]
> Open Camera surprisingly works but I couldn't get any other app to see the camera.

Same here. 6 month and I still could not set the camera work. It would be sufficient to get to pass some image into the "cam"

**Comment by MayeulC** [comment]
@psqli I looked into something similar some time ago (not too deeply though).

I think allowing PipeWire streams as input would require a few modifications to the Android Camera HAL, that currently only supports v4l2 devices (IIRC). The HAL mandates that the device supports a few specific image formats, so some conversion or deeper work needs to happen on one side or another of the PipeWire stream (maybe related to the libcamera HAL support work? Interesting, thanks for pointing this out).

Moreover, shared memory needs to be supported by the Android guest, I am not how this is handled.

**Comment by PhilDevProg** [comment]
@erfanoabdi 
> camera on halium devices with treble and on mainline devices v4l2 generic camera is supported

I have a normal USB Webcam. Can you tell me, how to setup v4l2 for it so that Waydroid works with it?

**Comment by gotgot1995** [comment]
Hi, I'm also very interested in passing through my camera to the Waydroid container.

**Comment by baptx** [comment]
Now that there has been an announcement that Anbox is officially deprecated, it would be time to bring camera support to Waydroid.

**Comment by baptx** [comment]
There is ongoing work on a fork to get camera support:
https://github.com/waydroid/waydroid/issues/519#issuecomment-1693988404

**Comment by djibrilchanfi966-bit** [comment]
I managed to get it working on Ubuntu 22.04 by modifying the AOSP source code i give the method for 100$ hahahahaha
