### ISSUE TITLE
Waydroid container failed to start

### ISSUE THREAD

**Issue by Catchal** [waydroid/waydroid#189]
(031069) [16:17:57] % umount /var/lib/waydroid/rootfs/vendor
(031069) [16:17:57] % umount /var/lib/waydroid/rootfs
(031069) [16:17:58] % lxc-info --version
4.0.6
(031069) [16:17:58] % mkdir -p /var/lib/waydroid/lxc/waydroid
(031069) [16:17:58] % cp -fpr /usr/lib/waydroid/data/configs/config_2 /var/lib/waydroid/lxc/waydroid/config
(031069) [16:17:58] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(031069) [16:17:58] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(031300) [16:18:06] Run waydroid app -h for usage information.
(031746) [16:18:29] % chmod 666 -R /dev/anbox-binder
(031746) [16:18:29] % chmod 666 -R /dev/anbox-vndbinder
(031746) [16:18:29] % chmod 666 -R /dev/anbox-hwbinder
(031746) [16:18:29] Container manager is waiting for session to load
(031746) [16:18:29] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

dnsmasq: unknown interface waydroid0
Failed to setup waydroid-net.
Failed to setup waydroid-net.
(031746) [16:18:30] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(031746) [16:18:30] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(031746) [16:18:30] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(031746) [16:18:30] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(031746) [16:18:30] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(031746) [16:18:30] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(031746) [16:18:30] % chmod 777 -R /dev/ashmem
(031746) [16:18:30] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
(031746) [16:18:30] % chmod 777 -R /dev/dri
(031746) [16:18:30] % chmod 777 -R /dev/fb0
(031746) [16:18:30] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(031746) [16:18:30] New background process: pid=31821, output=background
lxc-start: waydroid: network.c: instantiate_veth: 323 No such file or directory - Failed to attach "vethPpuDv6" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: network.c: lxc_create_network_priv: 3068 No such file or directory - Failed to create network device
lxc-start: waydroid: start.c: lxc_spawn: 1786 Failed to create the network
lxc-start: waydroid: start.c: __lxc_start: 1999 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 314 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 958 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
(031746) [16:18:30] waiting 10 seconds for container to start...
(031746) [16:18:31] waiting 9 seconds for container to start...
(031746) [16:18:32] waiting 8 seconds for container to start...
(031746) [16:18:33] waiting 7 seconds for container to start...
(031746) [16:18:34] waiting 6 seconds for container to start...
(031746) [16:18:35] waiting 5 seconds for container to start...
(031746) [16:18:36] waiting 4 seconds for container to start...
(031746) [16:18:37] waiting 3 seconds for container to start...
(031746) [16:18:38] waiting 2 seconds for container to start...
(031746) [16:18:39] waiting 1 seconds for container to start...
(031746) [16:18:40] ERROR: container failed to start
(031746) [16:18:40] See also: <https://github.com/waydroid>
(031746) [16:18:40] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 163, in start
    raise OSError("container failed to start")
OSError: container failed to start

(032124) [16:18:44] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(032124) [16:18:44] *** output passed to waydroid stdout, not to this log ***

heres my logs

**Comment by teppyboy** [comment]
Execute `ip addr` see if there's anything assigned to 192.168.250.1, if yes then remove it (typically Anbox)
And next time please wrap log into a code block
```
like this
```

**Comment by caidi1224** [comment]
try run xxx/waydroid-net.sh and report log.   maybe you need config your kernel config , check some iptables,nat,filter options.............or just run "lxc-checkconfig" on your terminal.   check lxc support status, fix some "miss"

**Comment by scottzhang** [comment]
I can go further but still can't start

lxc-start waydroid 20211112152131.326 DEBUG    cgfsng - cgroups/cgfsng.c:__cgroupfs_mount:1582 - Mounted cgroup filesystem cgroup2 onto 18((null))
lxc-start waydroid 20211112152131.326 INFO     conf - conf.c:lxc_transient_proc:3580 - Caller's PID is 1; /proc/self points to 1
lxc-start waydroid 20211112152131.327 DEBUG    conf - conf.c:lxc_setup_devpts_child:1669 - No new devpts instance will be mounted since no pts devices are requested
lxc-start waydroid 20211112152131.327 INFO     conf - conf.c:lxc_setup_ttys:1048 - Finished setting up 0 /dev/tty<N> device(s)
lxc-start waydroid 20211112152131.327 INFO     conf - conf.c:setup_personality:1783 - Set personality to "0lx0"
lxc-start waydroid 20211112152131.327 DEBUG    conf - conf.c:setup_caps:3008 - Capabilities have been setup
lxc-start waydroid 20211112152131.327 NOTICE   conf - conf.c:lxc_setup:4199 - The container "waydroid" is set up
lxc-start waydroid 20211112152131.327 INFO     apparmor - lsm/apparmor.c:apparmor_process_label_set_at:1186 - Set AppArmor label to "unconfined"
lxc-start waydroid 20211112152131.327 INFO     apparmor - lsm/apparmor.c:apparmor_process_label_set:1231 - Changed AppArmor profile to unconfined
lxc-start waydroid 20211112152131.327 DEBUG    conf - conf.c:lxc_send_devpts_to_parent:1759 - No devpts file descriptor will be sent since no pts devices are requested
lxc-start waydroid 20211112152131.327 NOTICE   utils - utils.c:lxc_drop_groups:1345 - Dropped supplimentary groups
lxc-start waydroid 20211112152131.327 NOTICE   start - start.c:start:2139 - Exec'ing "/init"
lxc-start waydroid 20211112152131.327 NOTICE   start - start.c:post_start:2150 - Started "/init" with pid "9006"
lxc-start waydroid 20211112152151.858 DEBUG    start - start.c:signal_handler:466 - Container init process 9006 exited
lxc-start waydroid 20211112152151.858 DEBUG    start - start.c:__lxc_start:2085 - Container "waydroid" is rebooting
lxc-start waydroid 20211112152151.858 INFO     error - error.c:lxc_error_set_and_log:33 - Child <9006> ended on signal (1)
lxc-start waydroid 20211112152151.973 INFO     network - network.c:lxc_delete_network_priv:3671 - Removed interface "vethP9V9ql" from "waydroid0"
lxc-start waydroid 20211112152151.973 DEBUG    network - network.c:lxc_delete_network:4185 - Deleted network devices
lxc-start waydroid 20211112152152.709 INFO     conf - conf.c:run_script_argv:339 - Executing script "/dev/null" for container "waydroid", config section "lxc"
lxc-start waydroid 20211112152152.740 DEBUG    conf - conf.c:run_buffer:312 - Script exec /dev/null waydroid lxc post-stop produced output: sh: line 1: /dev/null: Permission denied
sh: line 1: exec: /dev/null: cannot execute: Permission denied

lxc-start waydroid 20211112152152.743 ERROR    conf - conf.c:run_buffer:323 - Script exited with status 126
lxc-start waydroid 20211112152152.743 ERROR    start - start.c:lxc_end:996 - Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start waydroid 20211112152152.744 WARN     start - start.c:lxc_end:998 - Container will be stopped instead of rebooted
"/tmp/waydroid.log" 238L, 35316B

**Comment by KaratekHD** [comment]
I have a similar Error on openSUSE Tumbleweed.
Running `waydroid-net start` results in this:
```
# /usr/lib/waydroid/data/scripts/waydroid-net.sh start

dnsmasq: failed to open pidfile /run/waydroid-lxc/dnsmasq.pid: Permission denied
Failed to setup waydroid-net.
Failed to setup waydroid-net.
```

**Comment by Quackdoc** [comment]
@scottzhang if you haven't yet, you need to add an apparmor rule edit `/etc/apparmor.d/usr.sbin.dnsmasq` and add 

```
@{run}/waydroid-lxc/ r, 
@{run}/waydroid-lxc/* rw,
```

**Comment by Philainel** [comment]
@KaratekHD did you solve the problem?

**Comment by infinito84** [comment]
> @scottzhang if you haven't yet, you need to add an apparmor rule edit `/etc/apparmor.d/usr.sbin.dnsmasq` and add
> 
> ```
> @{run}/waydroid-lxc/ r, 
> @{run}/waydroid-lxc/* rw,
> ```

this works for me (in manjaro) after I restarted apparmor with:
```
sudo systemctl restart apparmor
```

**Comment by billbeans** [comment]
When I use the solutions given by @Quackdoc and @infinito84 , Apparmor fails to start. I believe it has something to do with this, but I don't know what it means:

`AppArmor parser error for /etc/apparmor.d in profile /etc/apparmor.d/usr.sbin.dnsmasq at line 1: syntax error, unexpected TOK_MODE, expecting TOK_OPEN`
