### ISSUE TITLE
Waydroid doesn't initialize on Qubes debian 11 VM

### ISSUE THREAD

**Issue by Sforg26** [waydroid/waydroid#254]
Hello! Thanks for the work on this software, I think it could be a good tool. I installed a fresh copy of Waydroid on Debian 11 but when I try to initialize the software it give me the following error:

```
user@debian-11:~$ sudo waydroid init
[21:30:39] ERROR: <urlopen error [Errno -2] Name or service not known>
[21:30:39] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```

the log give me the following informations:

```
user@debian-11:~$ waydroid log
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

(024423) [21:30:39] ERROR: <urlopen error [Errno -2] Name or service not known>
(024423) [21:30:39] See also: <https://github.com/waydroid>
(024423) [21:30:39] Traceback (most recent call last):
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 47, in setup_config
    system_request = helpers.http.retrieve(args.system_ota)
  File "/usr/lib/waydroid/tools/helpers/http.py", line 85, in retrieve
    with urllib.request.urlopen(req) as response:
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1375, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

(024425) [21:30:52] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(024425) [21:30:52] *** output passed to waydroid stdout, not to this log ***

```
Does anyone have any suggestion?

Thanks in Advance

**Comment by gregg00** [comment]
hi, 
make sure you're using wayland, not x11.  you can check with echo $XDG_SESSION_TYPE
that was giving me problems

**Comment by BenMueller** [comment]
I had the same issue on Mobian, but by doing an apt upgrade it fixed itself. Have you upgraded all your packages to the latest versions?

**Comment by Sforg26** [comment]
> hi, make sure you're using wayland, not x11. you can check with echo $XDG_SESSION_TYPE that was giving me problems

Hi, I had replied by email but it doesn't seem to have worked.
Anyway, thanks for your reply! I actually checked and effectively I'm using x11. I installed weston to be able to use a wayland environment, but in it it's also x11 and waydroid don't work. I don't know what commands to use to change it or if there are other ways to solve the problem.
thanks in advance

**Comment by Sforg26** [comment]
> I had the same issue on Mobian, but by doing an apt upgrade it fixed itself. Have you upgraded all your packages to the latest versions?

Hello, thanks for your reply. Yes, I have. I'm on debian 11 with all packages upgraded. I'm stuck with that issue and don't know how to solve it...

**Comment by nobodysu** [comment]
It looks like a network problem, do you have connectivity and DNS resolution on the host? Could you download the image [manually](https://github.com/waydroid/waydroid/issues/215) from sourceforge?
Does `sudo waydroid init -f` change anything?

**Comment by Sforg26** [comment]
> It looks like a network problem, do you have connectivity and DNS resolution on the host? Could you download the image [manually](https://github.com/waydroid/waydroid/issues/215) from sourceforge? Does `sudo waydroid init -f` change anything?

Hello, thanks for the help and sorry if I answer just now. With the update, running the command (equal `waydroid init` or `waydroid init f`) give me this:
```
user@work:~$ sudo waydroid init -f
[14:02:42] Failed to load binder driver
[14:02:42] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.109-1.fc32.qubes.x86_64
[14:02:42] ERROR: Binder node "binder" for waydroid not found
[14:02:42] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```

While this is the log:
```
user@work:~$ waydroid log
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.9/urllib/request.py", line 1349, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

(003695) [14:00:56] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.109-1.fc32.qubes.x86_64
(003695) [14:00:56] Failed to load binder driver
(003695) [14:00:56] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.109-1.fc32.qubes.x86_64
(003695) [14:00:56] ERROR: Binder node "binder" for waydroid not found
(003695) [14:00:56] See also: <https://github.com/waydroid>
(003695) [14:00:56] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 77, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 137, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(003699) [14:01:06] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.109-1.fc32.qubes.x86_64
(003699) [14:01:06] Failed to load binder driver
(003699) [14:01:06] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.109-1.fc32.qubes.x86_64
(003699) [14:01:06] ERROR: Binder node "binder" for waydroid not found
(003699) [14:01:06] See also: <https://github.com/waydroid>
(003699) [14:01:06] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 77, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 137, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(003705) [14:01:15] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(003705) [14:01:15] *** output passed to waydroid stdout, not to this log ***
(003797) [14:02:41] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.109-1.fc32.qubes.x86_64
(003797) [14:02:42] Failed to load binder driver
(003797) [14:02:42] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.10.109-1.fc32.qubes.x86_64
(003797) [14:02:42] ERROR: Binder node "binder" for waydroid not found
(003797) [14:02:42] See also: <https://github.com/waydroid>
(003797) [14:02:42] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 77, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 137, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(003841) [14:05:45] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(003841) [14:05:45] *** output passed to waydroid stdout, not to this log ***
```
Maybe it's a Qube related issue? Any help would be appreciated, thanks in advance!

**Comment by nobodysu** [comment]
So it's not a stock Debian but rather Qubes template? I think they could exclude binder modules in order to harden the kernel.
`# find /lib/modules -name *binder*`
If it's empty - maybe you could still load the modules with DKMS? I can't tell for sure. It will be the issue for Qubes then.

**Comment by Sforg26** [comment]
Yes, it is. My fault, I should I should have written this right away but I thought it was a debian problem. Looking at this new error, however, I realized that I had not made it explicit.
I will try run it with DKMS as you suggested and I'll tell you what happen
Thanks for your patience

**Comment by Sforg26** [comment]
I have not been able to solve the problem so far. Nevertheless, I was able to successfully install the latest debian-based version of Waydroid-Linux as a Standalone VM.
I haven't fully tested it yet, but it seems to be working fine for now.

**Comment by aleasto** [comment]
> urlopen error [Errno -2] Name or service not known

Networking issue on your Qubes, not on our side
