### ISSUE TITLE
[Xperia X] Unable to init Waydroid

### ISSUE THREAD

**Issue by 24mu13** [waydroid/waydroid#269]
I tried to install Waydroid on my Xperia X (Sailfish OS 4.3.0.12), getting the following error:

```
[defaultuser@XperiaXDualSIM ~]$ devel-su waydroid init
Password: 
[08:40:13] Failed to load binder driver
[08:40:13] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/3.10.84
[08:40:13] ERROR: Binder node "vndbinder" for waydroid not found
[08:40:13] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```
Any clue?

The log itself does not add more..
```
(016721) [08:40:13] % modprobe binder_linux devices="anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/3.10.84
(016721) [08:40:13] Failed to load binder driver
(016721) [08:40:13] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/3.10.84
(016721) [08:40:13] ERROR: Binder node "vndbinder" for waydroid not found
(016721) [08:40:13] See also: <https://github.com/waydroid>
(016721) [08:40:13] Traceback (most recent call last):
  File "/opt/waydroid/tools/__init__.py", line 54, in main
    actions.init(args)
  File "/opt/waydroid/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/opt/waydroid/tools/actions/initializer.py", line 77, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/opt/waydroid/tools/helpers/drivers.py", line 144, in setupBinderNodes
    raise OSError('Binder node "vndbinder" for waydroid not found')
OSError: Binder node "vndbinder" for waydroid not found
```

**Comment by ErgFox3DS** [comment]
me too
[19:48:41] Failed to load binder driver
[19:48:41] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.5-76051505-generic
[19:48:41] ERROR: Binder node "binder" for waydroid not found
[19:48:41] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.

**Comment by Quackdoc** [comment]
have you verified that kernel modules ashmem and binder are present? 

you can verify by either of these commands 
`zgrep -i -e android -e ashmem /proc/config.gz`

`zcat /proc/config.gz | grep -i android && zcat /proc/config.gz | grep -i ashmem `

**Comment by ErgFox3DS** [comment]
gzip: /proc/config.gz: No such file or directory
gzip: /proc/config.gz: No such file or directory

**Comment by Quackdoc** [comment]
I think sailfish-OS has their own waydroid packaging @24mu13 you should check their first. so @ErgFox3DS POP OS 5.15 does not seem to have the necessary kernel modules built in, you will need updated anbox-modules-dkms, or a custom kernel. I believe xanmod has compiled kernels that work with POPOS, or if not, I believe this is the updated dkms modules https://github.com/choff/anbox-modules

**Comment by Fuseteam** [comment]
you guys might be interested in https://github.com/pop-os/linux/issues/39

**Comment by aleasto** [comment]
Added PopOS install instructions: https://docs.waydro.id/usage/install-on-desktops#popos
