### ISSUE TITLE
Error messages at launch

### ISSUE THREAD

**Issue by stemy2** [waydroid/waydroid#312]
**Describe the bug**
I can't start wayland. I only have error messages.

**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version 1.2.0
 - Waydroid Images Version 20211021

**Desktop (please complete the following information):**
 - OS:  Ubuntu Impish
 - GPU: Nvidia GTX 1050
 - Kernel version: 5.13.0-28-generic
 - Host mesa version: don't know
 - Desktop: KDE 5.x

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
```
 debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.camera=v4l2
ro.opengles.version=196608
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.2.0
ro.vndk.lite=true
```

- Output of `waydroid log`
```
(049139) [13:40:53] % chmod 666 -R /dev/anbox-binder
(049139) [13:40:53] % chmod 666 -R /dev/anbox-vndbinder
(049139) [13:40:53] % chmod 666 -R /dev/anbox-hwbinder
(049139) [13:40:53] Container manager is waiting for session to load
(049249) [13:41:26] XDG Session is not "wayland"
(049249) [13:41:26] Save session config: /var/lib/waydroid/session.cfg
(049249) [13:41:26] UserMonitor service is not even started
(049249) [13:41:26] Clipboard service is not even started
(049059) [13:41:26] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(049059) [13:41:26] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(049059) [13:41:26] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(049059) [13:41:26] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(049059) [13:41:27] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(049059) [13:41:27] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(049059) [13:41:27] % mkdir -p /var/lib/waydroid/data
(049059) [13:41:27] % mount -o bind /home/stem/.local/share/waydroid/data /var/lib/waydroid/data
(049059) [13:41:27] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: Aucun point de montage indiqué.
(049059) [13:41:27] % chmod 777 -R /dev/ashmem
(049059) [13:41:27] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
(049059) [13:41:27] % chmod 777 -R /dev/dri
(049059) [13:41:27] % chmod 777 -R /dev/fb0
(049059) [13:41:27] % chmod 777 -R /dev/video1
(049059) [13:41:27] % chmod 777 -R /dev/video0
(049059) [13:41:27] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(049059) [13:41:27] New background process: pid=49351, output=background
(049139) [13:41:27] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
waydroid-net is already running
(049139) [13:41:27] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(049139) [13:41:27] % umount /var/lib/waydroid/rootfs/vendor
(049139) [13:41:27] % umount /var/lib/waydroid/rootfs
(049139) [13:41:27] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
mount: /var/lib/waydroid/rootfs: /dev/loop22 déjà monté ou point de montage actif.
(049139) [13:41:27] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(049139) [13:41:27] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(049139) [13:41:27] ERROR: Command failed: % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(049139) [13:41:27] See also: <https://github.com/waydroid>
(049139) [13:41:27] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 132, in start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"])
  File "/usr/lib/waydroid/tools/helpers/images.py", line 98, in mount_rootfs
    helpers.mount.mount(args, images_dir + "/system.img",
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 131, in mount
    tools.helpers.run.user(args, ["mount", source, destination])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs

(049059) [13:41:27] Save session config: /var/lib/waydroid/session.cfg
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 991 Failed to run lxc.hook.post-stop for container "waydroid"
(049249) [13:41:27] Failed to start Clipboard manager service, check logs
(050244) [13:46:09] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(050244) [13:46:09] *** output passed to waydroid stdout, not to this log ***
```

 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services
`[13:51:38] WayDroid container is STOPPED`

**Comment by D3faIt** [comment]
Try changing `ro.hardware.gralloc=gbm` to `ro.hardware.gralloc=default` and `ro.hardware.egl=mesa` to `ro.hardware.egl=swiftshader`

**Comment by aleasto** [comment]
Stale. Very likely works now
