### ISSUE TITLE
Lag in Cursor while moving inside window

### ISSUE THREAD

**Issue by afzl-wtu** [waydroid/waydroid#314]
**Describe the bug**

When sliding finger on touchpad or moving a mouse the pointer arrow show a clear lag nearly 100ms. This is really very bad thing for gaming and performance perspective.

**General information :**

 - Waydroid tools Version 1.2.0
 - Waydroid Images Version VANILLA LineageOS latest

**Desktop :**

 - OS: Manjaro latest
 - GPU: Intel HD 4600
 - Core i5 4200M 3.0 GHz Processor, SSD, RAM: 16GB 1600MHz
 - Kernel version: 5.15.21
 - Host mesa version: 21.3.5
 - Desktop: KDE Plasma 5.23.5

**Additional context**
Months ago When I used Virtual box on windows 10, I felt the same lag in PhoenixOS VM but **not** for Linux VM or Windows 7 or XP VMs. But If I dual boot Windows 10 with PhoenixOS there is no lag.. So Whenever Android is in VM it show cursor lag. Same happens with waydroid. 

**Logs (please upload as file)**

 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`

 ```
 debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.camera=v4l2
ro.opengles.version=196608
waydroid.system_ota=http://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=http://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.2.0
ro.vndk.lite=true
```

 - Output of `waydroid log`

```
    ~  waydroid log                                                                         ✔  1m 33s  
(001321) [22:51:22] % chmod 777 -R /dev/fb0
(001321) [22:51:22] % chmod 777 -R /dev/video1
(001321) [22:51:22] % chmod 777 -R /dev/video0
(001321) [22:51:22] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(001321) [22:51:22] New background process: pid=1400, output=background
(001321) [22:51:22] Save session config: /var/lib/waydroid/session.cfg
(003047) [22:52:27] Save session config: /var/lib/waydroid/session.cfg
(003047) [22:52:27] Failed to start Clipboard manager service, check logs
(003047) [22:56:01] Clipboard service is not even started
(001321) [22:56:01] session manager stopped, stopping container and waiting...
(001321) [22:56:01] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(001321) [22:56:01] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
(001321) [22:56:02] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(001321) [22:56:02] % umount /var/lib/waydroid/rootfs/vendor
(001321) [22:56:02] % umount /var/lib/waydroid/rootfs
(001321) [22:56:02] % umount /var/lib/waydroid/data
(001321) [22:56:02] % chmod 666 -R /dev/binder
(001321) [22:56:02] % chmod 666 -R /dev/vndbinder
(001321) [22:56:02] % chmod 666 -R /dev/hwbinder
(001321) [22:56:02] Container manager is waiting for session to load
(006347) [22:58:17] Save session config: /var/lib/waydroid/session.cfg
(006347) [22:58:17] UserMonitor service is not even started
(006347) [22:58:17] Clipboard service is not even started
(001321) [22:58:17] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(001321) [22:58:17] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(001321) [22:58:17] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(001321) [22:58:17] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(001321) [22:58:17] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(001321) [22:58:17] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(001321) [22:58:17] % mount -o bind /home/afzl/.local/share/waydroid/data /var/lib/waydroid/data
(001321) [22:58:17] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(001321) [22:58:17] % chmod 777 -R /dev/ashmem
(001321) [22:58:17] % chmod 777 -R /dev/dri
(001321) [22:58:17] % chmod 777 -R /dev/fb0
(001321) [22:58:17] % chmod 777 -R /dev/video1
(001321) [22:58:17] % chmod 777 -R /dev/video0
(001321) [22:58:17] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(001321) [22:58:17] New background process: pid=6399, output=background
(001321) [22:58:17] Save session config: /var/lib/waydroid/session.cfg
(006347) [22:58:27] waydroidusermonitor: Received transaction: 1
(006347) [22:58:27] Android with user 0 is ready
(007882) [23:00:15] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(007882) [23:00:15] *** output passed to waydroid stdout, not to this log ***
(010447) [23:48:50] ERROR: Action "logcat" needs root access
(010447) [23:48:50] See also: <https://github.com/waydroid>
(010447) [23:48:50] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 107, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 18, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "logcat" needs root access

lxc-start: waydroid: confile.c: get_config_unsupported_key: 159 Invalid argument - Unsupported config key "lxc.seccomp"
(010581) [23:53:19] Save session config: /var/lib/waydroid/session.cfg
(012457) [00:49:53] Save session config: /var/lib/waydroid/session.cfg
(013532) [01:16:49] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(013532) [01:16:49] *** output passed to waydroid stdout, not to this log ***
```

 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services:

[wdlogcat.txt](https://github.com/waydroid/waydroid/files/8135534/wdlogcat.txt)

**Comment by arch-btw** [comment]
If you're using virtualbox, try changing the pointing device to PS/2 in the virtualbox settings.

This resolved it for me.
