### ISSUE TITLE
Unable to Finish Starting a Waydroid Session

### ISSUE THREAD

**Issue by FedX-sudo** [waydroid/waydroid#318]
**Describe the bug**
I am unable to get WayDroid to function as it hangs whenever I try `waydroid session start` it hangs and never starts. 

**Screenshots**
waydroid log:
```
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(013567) [13:01:18] % chmod 777 -R /dev/ashmem
(013567) [13:01:18] % chmod 777 -R /dev/dri
(013567) [13:01:18] % chmod 777 -R /dev/fb0
(013567) [13:01:18] % chmod 777 -R /dev/video1
(013567) [13:01:18] % chmod 777 -R /dev/video0
(013567) [13:01:18] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(013567) [13:01:18] New background process: pid=13678, output=background
(013567) [13:01:18] waiting 10 seconds for container to start...
(013567) [13:01:19] Save session config: /var/lib/waydroid/session.cfg
(019049) [13:08:01] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(019049) [13:08:01] *** output passed to waydroid stdout, not to this log ***
(020579) [13:10:14] ERROR: Action "container" needs root access
(020579) [13:10:14] See also: <https://github.com/waydroid>
(020579) [13:10:14] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 67, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 18, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "container" needs root access

(020926) [13:10:28] WayDroid container is RUNNING
(013567) [13:10:34] session manager stopped, stopping container and waiting...
(013567) [13:10:34] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(013567) [13:10:35] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
(013567) [13:10:36] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(013567) [13:10:36] % umount /var/lib/waydroid/rootfs/vendor
(013567) [13:10:36] % umount /var/lib/waydroid/rootfs
(013567) [13:10:36] % umount /var/lib/waydroid/data
(013567) [13:10:36] % chmod 666 -R /dev/binder
(013567) [13:10:36] % chmod 666 -R /dev/vndbinder
(013567) [13:10:36] % chmod 666 -R /dev/hwbinder
(013567) [13:10:36] Container manager is waiting for session to load
(021117) [13:10:40] Save session config: /var/lib/waydroid/session.cfg
(021117) [13:10:40] UserMonitor service is not even started
(021117) [13:10:40] Clipboard service is not even started
(013567) [13:10:41] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(013567) [13:10:42] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(013567) [13:10:42] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(013567) [13:10:42] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(013567) [13:10:42] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(013567) [13:10:42] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(013567) [13:10:42] % mount -o bind /home/alarm/.local/share/waydroid/data /var/lib/waydroid/data
(013567) [13:10:42] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(013567) [13:10:42] % chmod 777 -R /dev/ashmem
(013567) [13:10:42] % chmod 777 -R /dev/dri
(013567) [13:10:42] % chmod 777 -R /dev/fb0
(013567) [13:10:42] % chmod 777 -R /dev/video1
(013567) [13:10:42] % chmod 777 -R /dev/video0
(013567) [13:10:42] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(013567) [13:10:42] New background process: pid=21169, output=background
(013567) [13:10:42] waiting 10 seconds for container to start...
(013567) [13:10:43] Save session config: /var/lib/waydroid/session.cfg
(021517) [13:10:55] Failed to get service waydroidplatform, trying again...
(021517) [13:10:56] Failed to get service waydroidplatform, trying again...
(021996) [13:11:38] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(021996) [13:11:38] *** output passed to waydroid stdout, not to this log ***
(013567) [13:13:21] session manager stopped, stopping container and waiting...
(013567) [13:13:21] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(013567) [13:13:21] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
(013567) [13:13:22] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(013567) [13:13:22] % umount /var/lib/waydroid/rootfs/vendor
(013567) [13:13:22] % umount /var/lib/waydroid/rootfs
(013567) [13:13:22] % umount /var/lib/waydroid/data
(013567) [13:13:22] % chmod 666 -R /dev/binder
(013567) [13:13:22] % chmod 666 -R /dev/vndbinder
(013567) [13:13:22] % chmod 666 -R /dev/hwbinder
(013567) [13:13:22] Container manager is waiting for session to load
(023485) [13:14:12] Save session config: /var/lib/waydroid/session.cfg
(023485) [13:14:12] UserMonitor service is not even started
(023485) [13:14:12] Clipboard service is not even started
(013567) [13:14:12] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(013567) [13:14:13] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(013567) [13:14:13] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(013567) [13:14:13] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(013567) [13:14:13] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(013567) [13:14:13] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(013567) [13:14:13] % mount -o bind /home/alarm/.local/share/waydroid/data /var/lib/waydroid/data
(013567) [13:14:13] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(013567) [13:14:14] % chmod 777 -R /dev/ashmem
(013567) [13:14:14] % chmod 777 -R /dev/dri
(013567) [13:14:14] % chmod 777 -R /dev/fb0
(013567) [13:14:14] % chmod 777 -R /dev/video1
(013567) [13:14:14] % chmod 777 -R /dev/video0
(013567) [13:14:14] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(013567) [13:14:14] New background process: pid=23542, output=background
tail: cannot watch '/var/lib/waydroid/waydroid.log': Permission denied
tail: cannot watch '/var/lib/waydroid/waydroid.log': Permission denied
tail: cannot watch '/var/lib/waydroid/waydroid.log': Permission denied
(013567) [13:14:14] waiting 10 seconds for container to start...
(013567) [13:14:15] Save session config: /var/lib/waydroid/session.cfg
lxc-start: waydroid: confile.c: get_config_unsupported_key: 159 Invalid argument - Unsupported config key "lxc.seccomp"
```
**General information (please complete the following information):**
 - Waydroid tools Version: 1.2.0
 - Waydroid Images Version: VANILLA Latest

**Smartphone (please complete the following information):**
 - Device: PinePhone
 - OS: Arch
 - Mainline
 - Kernel version:  5.16.10-1-danctnix

**Comment by doctorcolossus** [comment]
This seems to be a duplicate of [issue 282](https://github.com/waydroid/waydroid/issues/282). I'm getting this too.

**Comment by FedX-sudo** [comment]
Thanks! I fixed it by moving to Manjaro from Arch, so not sure what the issue was... Good luck!
