### ISSUE TITLE
ERROR: LXC not installed

### ISSUE THREAD

**Issue by raffaem** [waydroid/waydroid#34]
```
$ sudo python3 waydroid.py init
[sudo] password for raffaele: 
[08:43:28] Download https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-17.1-20210908-VANILLA-waydroid_x86_64-system.zip/download
[08:48:58] Validating system image
[08:49:01] Extracting to /var/lib/waydroid/images
[08:49:15] Download https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-17.1-20210908-MAINLINE-waydroid_x86_64-vendor.zip/download
[08:50:07] Validating vendor image
[08:50:07] Extracting to /var/lib/waydroid/images
[08:50:09] ERROR: LXC is not installed
[08:50:09] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```

```
(076965) [08:43:27] Starting new HTTPS connection (1): raw.githubusercontent.com:443
(076965) [08:43:27] https://raw.githubusercontent.com:443 "GET /waydroid/OTA/master/system/lineage/waydroid_x86_64/VANILLA.json HTTP/1.1" 200 560
(076965) [08:43:27] Starting new HTTPS connection (1): raw.githubusercontent.com:443
(076965) [08:43:28] https://raw.githubusercontent.com:443 "GET /waydroid/OTA/master/vendor/waydroid_x86_64/.json HTTP/1.1" 404 14
(076965) [08:43:28] Starting new HTTPS connection (1): raw.githubusercontent.com:443
(076965) [08:43:28] https://raw.githubusercontent.com:443 "GET /waydroid/OTA/master/vendor/waydroid_x86_64/MAINLINE.json HTTP/1.1" 200 618
(076965) [08:43:28] % sudo mkdir -p /dev/binderfs
(076965) [08:43:28] % sudo mount -t binder binder /dev/binderfs
(076965) [08:43:28] % sudo ln -s /dev/binderfs/vndbinder /dev/binderfs/hwbinder /dev/binderfs/binder /dev/binderfs/binder-control /dev/
(076965) [08:43:28] Save config: /var/lib/waydroid/waydroid.cfg
(076965) [08:43:28] Starting new HTTPS connection (1): raw.githubusercontent.com:443
(076965) [08:43:28] https://raw.githubusercontent.com:443 "GET /waydroid/OTA/master/system/lineage/waydroid_x86_64/VANILLA.json HTTP/1.1" 200 560
(076965) [08:43:28] % mkdir -p /var/lib/waydroid/cache_http
(076965) [08:43:28] Download https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-17.1-20210908-VANILLA-waydroid_x86_64-system.zip/download
(076965) [08:48:58] Validating system image
(076965) [08:49:01] Extracting to /var/lib/waydroid/images
(076965) [08:49:15] Save config: /var/lib/waydroid/waydroid.cfg
(076965) [08:49:15] Starting new HTTPS connection (1): raw.githubusercontent.com:443
(076965) [08:49:15] https://raw.githubusercontent.com:443 "GET /waydroid/OTA/master/vendor/waydroid_x86_64/MAINLINE.json HTTP/1.1" 200 618
(076965) [08:49:15] Download https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-17.1-20210908-MAINLINE-waydroid_x86_64-vendor.zip/download
(076965) [08:50:07] Validating vendor image
(076965) [08:50:07] Extracting to /var/lib/waydroid/images
(076965) [08:50:09] Save config: /var/lib/waydroid/waydroid.cfg
(076965) [08:50:09] ERROR: LXC is not installed
(076965) [08:50:09] See also: <https://github.com/waydroid>
(076965) [08:50:09] Traceback (most recent call last):
  File "/run/media/raffaele/55ab61c4-83cf-4d9f-a5cd-7fcfdc14b4fb/data/progetti_altrui/waydroid/tools/__init__.py", line 49, in main
    actions.init(args)
  File "/run/media/raffaele/55ab61c4-83cf-4d9f-a5cd-7fcfdc14b4fb/data/progetti_altrui/waydroid/tools/actions/initializer.py", line 99, in init
    helpers.lxc.set_lxc_config(args)
  File "/run/media/raffaele/55ab61c4-83cf-4d9f-a5cd-7fcfdc14b4fb/data/progetti_altrui/waydroid/tools/helpers/lxc.py", line 110, in set_lxc_config
    raise OSError("LXC is not installed")
OSError: LXC is not installed

(077193) [08:55:21] % tail -n 60 -F /var/lib/waydroid/tools.log
(077193) [08:55:21] *** output passed to waydroid stdout, not to this log ***
```

**Comment by erfanoabdi** [comment]
so install lxc

**Comment by raffaem** [comment]
Yes `sudo dnf install lxc` moved the initialization forward on Fedora 34
