### ISSUE TITLE
Fedora on PinePhone: lxc-start: waydroid: cgroups/cgfsng.c: __cgfsng_delegate_controllers: 2945 Invalid argument - Could not enable "+cpuset +cpu +io +memory +pids" controllers in the unified cgroup 

### ISSUE THREAD

**Issue by skeydan** [waydroid/waydroid#346]
**Describe the bug**

I can successfully start the container, but once I run `waydroid show-full-ui` it dies. In waydroid log (see below), the relevant lines may be:

```
lxc-start: waydroid: cgroups/cgfsng.c: __cgfsng_delegate_controllers: 2945 Invalid argument - Could not enable "+cpuset +cpu +io +memory +pids" controllers in the unified cgroup 7
lxc-start: waydroid: cgroups/cgfsng.c: __cgfsng_delegate_controllers: 2945 Invalid argument - Could not enable "+cpuset +cpu +io +memory +pids" controllers in the unified cgroup 7
lxc-start: waydroid: network.c: netdev_configure_server_veth: 708 No such file or directory - Failed to attach "vethwh3cPT" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: network.c: lxc_create_network_priv: 3419 No such file or directory - Failed to create network device

```
Thank you very much for looking into this, and please let me know if I can provide further information!

**General information (please complete the following information):**

- Installed from: https://copr.fedorainfracloud.org/coprs/aleasto/waydroid/
 - Waydroid tools Version: 1.2.0
 - Waydroid Images Version: https://sourceforge.net/projects/aleasto-lineageos/files/LineageOS%2017.1/waydroid/lineage-17.1-20220226-VANILLA-waydroid_arm64-system

**Smartphone (please complete the following information):**
 - Device: PinePhone
 - OS: Fedora release 37 (Rawhide)
 - Kernel version: 5.17.0-rc2-00640-ge81be0978d7e

**waydroid log**

```
(004037) [17:31:33] Clipboard service is not even started
(003744) [17:31:33] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
which: no iptables-legacy in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
which: no ip6tables-legacy in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
Warning: ZONE_ALREADY_SET: 'waydroid0' already bound to 'trusted'
success
Warning: Extension udp revision 0 not supported, missing kernel module?
iptables v1.8.7 (nf_tables):  RULE_INSERT failed (No such file or directory): rule in chain INPUT
Failed to setup waydroid-net.
Warning: Extension udp revision 0 not supported, missing kernel module?
iptables: Bad rule (does a matching rule exist in that chain?).
Warning: Extension tcp revision 0 not supported, missing kernel module?
iptables: Bad rule (does a matching rule exist in that chain?).
Warning: Extension udp revision 0 not supported, missing kernel module?
iptables: Bad rule (does a matching rule exist in that chain?).
Warning: Extension tcp revision 0 not supported, missing kernel module?
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?
iptables: Bad rule (does a matching rule exist in that chain?).
Warning: Extension udp revision 0 not supported, missing kernel module?
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: Bad rule (does a matching rule exist in that chain?).
(003744) [17:31:36] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(003744) [17:31:36] % umount /var/lib/waydroid/rootfs/vendor
(003744) [17:31:36] % umount /var/lib/waydroid/rootfs
(003744) [17:31:36] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(003744) [17:31:36] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(003744) [17:31:36] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(003744) [17:31:36] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(003744) [17:31:36] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(003744) [17:31:36] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(003744) [17:31:36] % chmod 777 -R /dev/ashmem
(003744) [17:31:36] % chmod 777 -R /dev/dri
(003744) [17:31:36] % chmod 777 -R /dev/fb0
(003744) [17:31:36] % chmod 777 -R /dev/video2
(003744) [17:31:36] % chmod 777 -R /dev/video1
(003744) [17:31:36] % chmod 777 -R /dev/video0
(003744) [17:31:36] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(003744) [17:31:36] New background process: pid=4125, output=background
lxc-start: waydroid: cgroups/cgfsng.c: __cgfsng_delegate_controllers: 2945 Invalid argument - Could not enable "+cpuset +cpu +io +memory +pids" controllers in the unified cgroup 7
lxc-start: waydroid: cgroups/cgfsng.c: __cgfsng_delegate_controllers: 2945 Invalid argument - Could not enable "+cpuset +cpu +io +memory +pids" controllers in the unified cgroup 7
lxc-start: waydroid: network.c: netdev_configure_server_veth: 708 No such file or directory - Failed to attach "vethwh3cPT" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: network.c: lxc_create_network_priv: 3419 No such file or directory - Failed to create network device
lxc-start: waydroid: start.c: lxc_spawn: 1826 Failed to create the network
lxc-start: waydroid: start.c: __lxc_start: 2053 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 996 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
(003744) [17:31:36] waiting 10 seconds for container to start...
(003744) [17:31:37] waiting 9 seconds for container to start...
(003744) [17:31:38] waiting 8 seconds for container to start...
(003744) [17:31:39] waiting 7 seconds for container to start...
(003744) [17:31:40] waiting 6 seconds for container to start...
(003744) [17:31:41] waiting 5 seconds for container to start...
(004147) [17:31:41] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(004147) [17:31:41] *** output passed to waydroid stdout, not to this log ***
(003744) [17:31:42] waiting 4 seconds for container to start...
(003744) [17:31:43] waiting 3 seconds for container to start...
(003744) [17:31:44] waiting 2 seconds for container to start...
(003744) [17:31:45] waiting 1 seconds for container to start...
(003744) [17:31:46] ERROR: container failed to start
(003744) [17:31:46] See also: <https://github.com/waydroid>
(003744) [17:31:46] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 163, in start
    raise OSError("container failed to start")
OSError: container failed to start

```

**Comment by skeydan** [comment]
#345 seems to be the same

**Comment by skeydan** [comment]
I tried if updating to the newest Lineage OS image helped (the one in https://copr.fedorainfracloud.org/coprs/aleasto/waydroid/ is from February)

`sudo waydroid init -f -c https://ota.waydro.id/system -v https://ota.waydro.id/vendor`

but I get the same error.

**Comment by skeydan** [comment]
In this issue

https://github.com/lxc/lxc/issues/4038

it is recommended to upgrade `lxc` to 4.0.11. 

In fact, I really am on 4.0.10 (Fedora 37/Rawhide).
 Maybe I have a chance once Rawhide packages a newer version.

**Comment by aleasto** [comment]
Cannot reproduce on Fedora 35 aarch64 via QEMU.
Are you using an unofficial kernel?

**Comment by skeydan** [comment]
Thanks @aleasto!

I have this:

```
[key@champfer ~]$ uname -a
Linux champfer 5.17.0-00479-g1cad4dcac30c #22 SMP Sun Mar 20 22:05:12 CET 2022 aarch64 aarch64 aarch64 GNU/Linux
[key@champfer ~]$ cat /etc/redhat-release 
Fedora release 37 (Rawhide)
```

(all from https://github.com/nikhiljha/pp-fedora-sdsetup - continuously updated)

Now (for a different reason) anyway I'll install this kernel : `5.17-2.fc35` from https://copr.fedorainfracloud.org/coprs/njha/mobile/package/megi-kernel/  - will report back if that works!

**Comment by skeydan** [comment]
On a kernel with `iptables` enabled and `config_cgroups` set, I still get the same error.

Current waydroid log:

```
[pine@pinephone ~]$ waydroid log
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?
iptables: Bad rule (does a matching rule exist in that chain?).
Warning: Extension udp revision 0 not supported, missing kernel module?
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: Bad rule (does a matching rule exist in that chain?).
(011630) [15:38:00] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(011630) [15:38:00] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(011630) [15:38:00] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(011630) [15:38:00] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(011630) [15:38:00] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(011630) [15:38:00] % mkdir -p /var/lib/waydroid/data
(011630) [15:38:00] % mount -o bind /home/pine/.local/share/waydroid/data /var/lib/waydroid/data
(011630) [15:38:00] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(011630) [15:38:00] % chmod 777 -R /dev/ashmem
(011630) [15:38:00] % chmod 777 -R /dev/dri
(011630) [15:38:00] % chmod 777 -R /dev/fb0
(011630) [15:38:00] % chmod 777 -R /dev/video2
(011630) [15:38:00] % chmod 777 -R /dev/video1
(011630) [15:38:00] % chmod 777 -R /dev/video0
(011630) [15:38:00] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(011630) [15:38:00] New background process: pid=12518, output=background
lxc-start: waydroid: cgroups/cgfsng.c: __cgfsng_delegate_controllers: 2945 Invalid argument - Could not enable "+cpuset +cpu +io +memory +pids" controllers in the unified cgroup 7
lxc-start: waydroid: cgroups/cgfsng.c: __cgfsng_delegate_controllers: 2945 Invalid argument - Could not enable "+cpuset +cpu +io +memory +pids" controllers in the unified cgroup 7
lxc-start: waydroid: network.c: netdev_configure_server_veth: 708 No such file or directory - Failed to attach "vethhy8hzD" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: network.c: lxc_create_network_priv: 3419 No such file or directory - Failed to create network device
lxc-start: waydroid: start.c: lxc_spawn: 1826 Failed to create the network
lxc-start: waydroid: start.c: __lxc_start: 2053 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 996 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 (011630) [15:38:01] waiting 10 seconds for container to start...
Additional information can be obtained by setting the --logfile and --logpriority options
(011630) [15:38:02] waiting 9 seconds for container to start...
(011630) [15:38:03] waiting 8 seconds for container to start...
(011630) [15:38:04] waiting 7 seconds for container to start...
(011630) [15:38:05] waiting 6 seconds for container to start...
(011630) [15:38:06] waiting 5 seconds for container to start...
(011630) [15:38:07] waiting 4 seconds for container to start...
(011630) [15:38:08] waiting 3 seconds for container to start...
(011630) [15:38:09] waiting 2 seconds for container to start...
(011630) [15:38:10] waiting 1 seconds for container to start...
(011630) [15:38:11] ERROR: container failed to start
(011630) [15:38:11] See also: <https://github.com/waydroid>
(011630) [15:38:11] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 163, in start
    raise OSError("container failed to start")
OSError: container failed to start
```

**Comment by skeydan** [comment]
@aleasto tried if installing `dnsmasq` would help (because of partly-similar https://github.com/waydroid/waydroid/issues/154#issuecomment-944933638), but no...

Also, `CONFIG_RT_GROUP_SCHED=y` was present in the kernel already ...

On the upside, I now have the config for the megi kernel! I'll upload both configs - that and mobian's - in an instant.

**Comment by aleasto** [comment]
I know it is, that's why you should try to unset it

**Comment by skeydan** [comment]
[megi.txt](https://github.com/waydroid/waydroid/files/8682261/megi.txt)
[mobian.txt](https://github.com/waydroid/waydroid/files/8682262/mobian.txt)

**Comment by skeydan** [comment]
oops, then i misunderstood :-(
will bother someone again ... thanks!

**Comment by skeydan** [comment]
@aleasto with that setting removed, i get (from `waydroid log`):

```
(002128) [15:52:58] New background process: pid=2241, output=background
lxc-start: waydroid: network.c: netdev_configure_server_veth: 708 No such file or directory - Failed to attach "vethljjnKu" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: network.c: lxc_create_network_priv: 3419 No such file or directory - Failed to create network device
lxc-start: waydroid: start.c: lxc_spawn: 1826 Failed to create the network
lxc-start: waydroid: start.c: __lxc_start: 2053 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 996 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
```

I can't run `waydroid logcat`, it immediately says "waydroid is stopped" - probably fails too fast?

**Comment by aleasto** [comment]
That's not the whole log

**Comment by skeydan** [comment]
sorry, right

here it is (after updating to current lineage image and service restart):

```
(002285) [16:01:41] % sed -i s/LXCARCH/aarch64/ /var/lib/waydroid/lxc/waydroid/config
(002285) [16:01:41] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(002331) [16:02:06] % chmod 666 -R /dev/binder
(002331) [16:02:06] % chmod 666 -R /dev/vndbinder
(002331) [16:02:06] % chmod 666 -R /dev/hwbinder
(002331) [16:02:06] Container manager is waiting for session to load
(002338) [16:02:52] Save session config: /var/lib/waydroid/session.cfg
(002338) [16:02:52] UserMonitor service is not even started
(002338) [16:02:52] Clipboard service is not even started
(002331) [16:02:52] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
which: no iptables-legacy in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
which: no ip6tables-legacy in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
Warning: ZONE_ALREADY_SET: 'waydroid0' already bound to 'trusted'
success
Warning: Extension udp revision 0 not supported, missing kernel module?
Warning: Extension tcp revision 0 not supported, missing kernel module?
Warning: Extension udp revision 0 not supported, missing kernel module?
Warning: Extension tcp revision 0 not supported, missing kernel module?
Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?
iptables v1.8.8 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain POSTROUTING
Failed to setup waydroid-net.
Warning: Extension udp revision 0 not supported, missing kernel module?
Warning: Extension tcp revision 0 not supported, missing kernel module?
Warning: Extension tcp revision 0 not supported, missing kernel module?
Warning: Extension udp revision 0 not supported, missing kernel module?
Warning: Extension udp revision 0 not supported, missing kernel module?
Warning: Extension tcp revision 0 not supported, missing kernel module?
Warning: Extension tcp revision 0 not supported, missing kernel module?
Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?
iptables: Bad rule (does a matching rule exist in that chain?).
Warning: Extension udp revision 0 not supported, missing kernel module?
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables: Bad rule (does a matching rule exist in that chain?).
(002331) [16:02:55] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(002331) [16:02:55] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(002331) [16:02:55] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(002331) [16:02:55] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(002331) [16:02:55] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(002331) [16:02:55] % umount -l /sys/fs/cgroup/schedtune
umount: /sys/fs/cgroup/schedtune: no mount point specified.
(002331) [16:02:55] % chmod 777 -R /dev/ashmem
(002331) [16:02:55] % chmod 777 -R /dev/dri
(002331) [16:02:55] % chmod 777 -R /dev/fb0
(002331) [16:02:55] % chmod 777 -R /dev/video2
(002331) [16:02:55] % chmod 777 -R /dev/video1
(002331) [16:02:55] % chmod 777 -R /dev/video0
(002331) [16:02:55] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(002331) [16:02:56] New background process: pid=2438, output=background
lxc-start: waydroid: network.c: netdev_configure_server_veth: 708 No such file or directory - Failed to attach "vethghf7hY" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: network.c: lxc_create_network_priv: 3419 No such file or directory - Failed to create network device
lxc-start: waydroid: start.c: lxc_spawn: 1826 Failed to create the network
lxc-start: waydroid: start.c: __lxc_start: 2053 Failed to spawn container "waydroid"
(002331) [16:02:56] waiting 10 seconds for container to start...
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 996 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
(002331) [16:02:57] waiting 9 seconds for container to start...
(002459) [16:02:57] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(002459) [16:02:57] *** output passed to waydroid stdout, not to this log ***
(002331) [16:02:58] waiting 8 seconds for container to start...
(002331) [16:02:59] waiting 7 seconds for container to start...
(002331) [16:03:00] waiting 6 seconds for container to start...
(002331) [16:03:01] waiting 5 seconds for container to start...
(002331) [16:03:02] waiting 4 seconds for container to start...
(002331) [16:03:03] waiting 3 seconds for container to start...
(002331) [16:03:04] waiting 2 seconds for container to start...
(002331) [16:03:05] waiting 1 seconds for container to start...
(002331) [16:03:06] ERROR: container failed to start
(002331) [16:03:06] See also: <https://github.com/waydroid>
(002331) [16:03:06] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 163, in start
    raise OSError("container failed to start")
OSError: container failed to start

(002470) [16:03:07] UserMonitor service is not even started
(002470) [16:03:07] Clipboard service is not even started
(002338) [16:03:08] UserMonitor service is not even started
(002338) [16:03:08] Clipboard service is not even started

```

**Comment by aleasto** [comment]
I've updated the waydroid package. Try `dnf update --refresh`

**Comment by skeydan** [comment]
Congratulations- that worked!! Thanks!

I'd be curious - could you link the commit that did this?

And summing up the rest, kernel-wise, what we need is

- `iptables` set
- `config_cgroups` set
- `CONFIG_RT_GROUP_SCHED` unset

That should do it, right?

Thanks!

**Comment by aleasto** [comment]
Just need CONFIG_RT_GROUP_SCHED unset.

https://pagure.io/waydroid/waydroid/c/691c86ed2c380ca2ae76d63dd88a6258715831e3?branch=main that removes the dependency on iptables which is deprecated

**Comment by skeydan** [comment]
thanks! Got it!

**Comment by Fornball** [comment]
Im still having this issue on Ubuntu 22.04. Fresh install of system and waydroid. 
Kernel: ```cros_secure console=tty1 root=/dev/sda2 i915.modeset=1 rootwait rw fbcon=logo-pos:center,logo-count:1 loglevel=0 splash``` (dont mind the other options, its because im using the chromeos kernel, see [breath](https://github.com/cb-linux/breath) for more details)
