### ISSUE TITLE
Nothing happens when launching the UI

### ISSUE THREAD

**Issue by matteodev8** [waydroid/waydroid#357]
**Describe the bug**
After I insalled Waydroid on Arch Linux, set everything up and tried to run `waydroid show-full-ui`, it just hangs on Starting waydroid session and doesn't do anything afterwards

**Screenshots**

![image](https://user-images.githubusercontent.com/59450459/162713195-4e5745d5-cb9a-4a1f-8dbe-adf8ff5f8544.png)

**General information (please complete the following information):**
 - Waydroid tools Version 1.2.0-2
 - Waydroid Images Version VANILLA 17.1_20220316-1

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - GPU: AMD Radeon RX 580
 - Kernel version: Arch Linux 5.17.2-zen1-1-zen
 - Host mesa version: Mesa 22.0.1-3
 - Desktop: KDE Plasma 5.24.4

**Additional context**

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`:
```
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.camera=v4l2
ro.opengles.version=196608
waydroid.system_ota=http://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=http://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.2.0
ro.vndk.lite=true
```

 - Output of `waydroid log`:
 ```
 (048523) [11:41:21] Clipboard service is not even started
(048539) [11:41:24] ERROR: Action "shell" needs root access
(048539) [11:41:24] See also: <https://github.com/waydroid>
(048539) [11:41:24] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 104, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 18, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "shell" needs root access

(048541) [11:41:27] WayDroid container is STOPPED
(048545) [11:41:34] Save session config: /var/lib/waydroid/session.cfg
(048545) [11:41:34] UserMonitor service is not even started
(048545) [11:41:34] Clipboard service is not even started
(048545) [11:41:40] UserMonitor service is not even started
(048545) [11:41:40] Clipboard service is not even started
(048571) [11:42:07] % chmod 666 -R /dev/anbox-binder
(048571) [11:42:07] % chmod 666 -R /dev/anbox-vndbinder
(048571) [11:42:07] % chmod 666 -R /dev/anbox-hwbinder
(048571) [11:42:07] Container manager is waiting for session to load
(048582) [11:42:33] Already initialized
(048586) [11:42:41] Save session config: /var/lib/waydroid/session.cfg
(048586) [11:42:41] UserMonitor service is not even started
(048586) [11:42:41] Clipboard service is not even started
(048571) [11:42:42] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
Error: Unknown device type.
Failed to setup waydroid-net.
(048571) [11:42:42] % mount /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
mount: /var/lib/waydroid/rootfs: das Einhängen ist fehlgeschlagen: Die Operation ist nicht erlaubt.
(048571) [11:42:42] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(048571) [11:42:42] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(048571) [11:42:42] ERROR: Command failed: % mount /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(048571) [11:42:42] See also: <https://github.com/waydroid>
(048571) [11:42:42] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 132, in start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"])
  File "/usr/lib/waydroid/tools/helpers/images.py", line 90, in mount_rootfs
    helpers.mount.mount(args, images_dir + "/system.img",
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 131, in mount
    tools.helpers.run.user(args, ["mount", source, destination])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mount /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs

(048601) [11:42:42] UserMonitor service is not even started
(048601) [11:42:42] Clipboard service is not even started
(048586) [11:42:42] UserMonitor service is not even started
(048586) [11:42:42] Clipboard service is not even started
(048604) [11:42:51] Starting waydroid session
(048604) [11:42:51] Save session config: /var/lib/waydroid/session.cfg
(048604) [11:42:51] UserMonitor service is not even started
(048604) [11:42:51] Clipboard service is not even started
(049393) [11:48:10] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(049393) [11:48:10] *** output passed to waydroid stdout, not to this log ***
```
 
 
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services:
 ```
 [11:49:21] WayDroid container is STOPPED
 ```

**Comment by Quackdoc** [comment]
have you enabled and started the systemd service for waydroid-container?

**Comment by matteodev8** [comment]
I did like 5 times

**Comment by Quackdoc** [comment]
seems like you have a perms issue, how did you install and how did you start waydroid?

**Comment by xiguayuyichao** [comment]
I have the same problem as you. I can run the waydroid shell, but no interface pops up

**Comment by Quackdoc** [comment]
@xiguayuyichao how did you install waydroid? and how are you launching it?

**Comment by aleasto** [comment]
```
(048571) [11:42:42] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
Error: Unknown device type.
Failed to setup waydroid-net.
(048571) [11:42:42] % mount /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
mount: /var/lib/waydroid/rootfs: das Einhängen ist fehlgeschlagen: Die Operation ist nicht erlaubt.
```

Report the issue downstream, or try to understand what network component is missing and why the mount fails. If still relevant today...

**Comment by lm2lm2** [comment]
RuntimeError: Command failed: % mount -o ro /var/lib/waydroid/images/
system.img /var/lib/waydroid/rootfs

honestly, on my side i went up to solve this error by :
removing any .img file (vendor, system) related to waydroid
reinstalling waydroid
then -f -s GAPPS /path/to/waydroidimages
then show-full-ui

**Comment by ligix** [comment]
for anyone randomly stumbling upon this issue, the command that fails is `ip`:
```
+ set -e
+ '[' '!' -d /sys/class/net/waydroid0 ']'
+ ip link add dev waydroid0 type bridge
Error: Unknown device type.
```
Either you are running an unbelievably cursed system or you just did not reboot after a kernel upgrade.
