### ISSUE TITLE
Cannot init without sudo

### ISSUE THREAD

**Issue by SameExpert** [waydroid/waydroid#48]
~~~
(125846) [07:31:22] ERROR: [Errno 2] No such file or directory: 'sudo'
(125846) [07:31:22] See also: <https://github.com/waydroid>
(125846) [07:31:22] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 49, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 85, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 77, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 98, in setupBinderNodes
    probeBinderDriver(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 68, in probeBinderDriver
    tools.helpers.run.root(args, command, check=False)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 77, in root
    return user(args, cmd, working_dir, output, output_return, check, env,
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 308, in core
    sudo_timer_start(args)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 244, in sudo_timer_start
    sudo_timer_iterate()
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 227, in sudo_timer_iterate
    subprocess.Popen(["sudo", "-v"]).wait()
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sudo'
~~~

I'd prefer using `doas` due to its simplicity and lightweightness. Maybe better using `su` instead of `sudo`? If not, adding `doas` support?

**Comment by allaeddineomc** [comment]
Try pkexec command it might get the job done without installing  sudo

**Comment by Luciogi** [comment]
-I did tried `opendoas-sudo` (from Arch User Repository), this package creates a symlink for using Doas as a drop-in replacement to sudo.
same problem here.

**Comment by erfanoabdi** [comment]
sudo requirements is dropped: https://github.com/waydroid/waydroid/commit/37d108429469d1f2784ccb3756390243823a4454

**Comment by marktnz1** [comment]
Still requires sudo

$ waydroid init
[18:04:32] ERROR: Action "init" needs root access
[18:04:32] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
