### ISSUE TITLE
ERROR: Can't open /dev/anbox-binder: Permission denied

### ISSUE THREAD

**Issue by ngxson** [waydroid/waydroid#480]
**Describe the bug**
I have no idea what to do
https://copr.fedorainfracloud.org/coprs/aleasto/waydroid/

```
waydroid show-full-ui
[gbinder] ERROR: Can't open /dev/anbox-binder: Permission denied
[17:51:14] Failed to add presence handler: None
[gbinder] ERROR: Can't open /dev/anbox-binder: Permission denied
[17:51:14] Failed to add presence handler: None
[gbinder] ERROR: Can't open /dev/anbox-binder: Permission denied
[17:51:14] Failed to add presence handler: None
[gbinder] ERROR: Can't open /dev/anbox-binder: Permission denied
[17:51:14] Failed to add presence handler: None
[gbinder] ERROR: Can't open /dev/anbox-binder: Permission denied
[17:51:14] Failed to add presence handler: None
[gbinder] ERROR: Can't open /dev/anbox-binder: Permission denied
[17:51:14] Failed to add presence handler: None
[gbinder] ERROR: Can't open /dev/anbox-binder: Permission denied
[17:51:14] Failed to add presence handler: None
[gbinder] ERROR: Can't open /dev/anbox-binder: Permission denied
[17:51:14] Failed to add presence handler: None
[gbinder] ERROR: Can't open /dev/anbox-binder: Permission denied
[17:51:14] Failed to add presence handler: None
[gbinder] ERROR: Can't open /dev/anbox-binder: Permission denied
[17:51:14] Failed to add presence handler: None
```

**Desktop (please complete the following information):**
 - Fedora 36 with Xanmod kernel 5.19

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.camera=v4l2
ro.opengles.version=196608
waydroid.system_ota=https://waydroid.bardia.tech/OTA/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://waydroid.bardia.tech/OTA/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.3.0
ro.vndk.lite=true
```

 - Output of `waydroid log`
```
➜  binderfs waydroid log
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] % umount /var/lib/waydroid/data
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] Failed to add presence handler: None
(018609) [17:51:16] % mkdir -p /dev/binderfs
(018609) [17:51:16] % mount -t binder binder /dev/binderfs
(018609) [17:51:16] % ln -s /dev/
ln: failed to create symbolic link './dev': File exists
(018609) [17:51:16] Container manager is waiting for session to load
(020547) [17:53:04] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(020547) [17:53:04] *** output passed to waydroid stdout, not to this log ***
```

 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services
```
sudo waydroid logcat
[17:53:31] WayDroid container is STOPPED
```

**Comment by aleasto** [comment]
Don't use xanmod kernel 👍

**Comment by ngxson** [comment]
Then I imagine that I must build the kernel myself, right?  
However, `fedpkg clone -a kernel` always gives me error:

```
➜  work fedpkg clone -a kernel
Traceback (most recent call last):
  File "/usr/bin/fedpkg", line 33, in <module>
    sys.exit(load_entry_point('fedpkg==1.42', 'console_scripts', 'fedpkg')())
  File "/usr/bin/fedpkg", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib64/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib64/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/fedpkg/__init__.py", line 36, in <module>
    from .bodhi_6 import BodhiClient, UPDATE_TYPES, REQUEST_TYPES, SUGGEST_TYPES
  File "/usr/lib/python3.10/site-packages/fedpkg/bodhi_6.py", line 12, in <module>
    from bodhi.client.bindings import BodhiClient as BodhiClient_
  File "/usr/lib/python3.10/site-packages/bodhi/client/bindings.py", line 171, in <module>
    class BodhiClient:
  File "/usr/lib/python3.10/site-packages/bodhi/client/bindings.py", line 972, in BodhiClient
    def get_koji_session(self) -> koji.ClientSession:
AttributeError: module 'koji' has no attribute 'ClientSession'
```

It would be nice if there's some sorts of pre-built kernel that I can just `dnf install`. Do you have any idea for that?
Thanks.

**Comment by ngxson** [comment]
It would be nice if there's some sorts of pre-built kernel that I can just dnf install. Do you have any idea for that?
Thanks.

**Comment by aleasto** [comment]
> It would be nice if there's some sorts of pre-built kernel that I can just `dnf install`. Do you have any idea for that?
> Thanks.

Yes. The default fedora kernel.

**Comment by ngxson** [comment]
> Yes. The default fedora kernel.
> 
> I suggest removing `/var/lib/waydroid` after switching kernel.

Oh thanks! It's now working.

I didn't know that `binder` driver was included in the fedora kernel itself. I followed this guide but it seems to be outdated: https://yanqiyu.info/2021/10/25/waydroid-fedora/

It should be removed from the docs then: https://docs.waydro.id/usage/install-on-desktops
