### ISSUE TITLE
Remove mention of FOSS system type or provide images

### ISSUE THREAD

**Issue by JamiKettunen** [waydroid/waydroid#495]
Currently `waydroid init -s FOSS` simply produces the following error:
```
[16:09:12] ERROR: No images found on system channel
[16:09:12] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```
And in `waydroid log`:
```
(010192) [16:09:12] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 53, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 107, in init
    helpers.images.get(args)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 31, in get
    raise ValueError("No images found on system channel")
ValueError: No images found on system channel
```
The `FOSS` channel is currently mentioned in `waydroid init -h`:
```
usage: waydroid init [-h] [-i IMAGES_PATH] [-f] [-c SYSTEM_CHANNEL] [-v VENDOR_CHANNEL] [-r ROM_TYPE] [-s SYSTEM_TYPE]

options:
...
  -s SYSTEM_TYPE, --system_type SYSTEM_TYPE
                        system type (options: VANILLA, FOSS or GAPPS; default is VANILLA)
```
Which is defined in [tools/helpers/arguments.py](https://github.com/waydroid/waydroid/blob/1.3.0/tools/helpers/arguments.py#L34-L35).

Should this mention be removed altogether since there's no images (it's nonfunctional)? Apparently @electrikjesus should know about these images.

**Comment by electrikjesus** [comment]
For FOSS apps on the vanilla release of Waydroid, we actually put together this project that acts like apt for Waydroid. https://github.com/waydroid/waydroid-package-manager

**Comment by JamiKettunen** [comment]
Right, but do `FOSS` variant images exist for any ROM images at all? I think the redundant mention of it should be removed if not.

**Comment by ACR-Jeff** [comment]
Maybe this will help. Images built with foss 
[https://sourceforge.net/projects/blissos-dev/files/waydroid/lineage/lineage-18.1/](url)

**Comment by JamiKettunen** [comment]
@ACR-Jeff but can that be installed using `waydroid init -s FOSS` somehow (how)? If not then that's irrelevant to this issue which is about mentioning `--system_type FOSS` in the output of `waydroid init -h`.

**Comment by electrikjesus** [comment]
We built the functionality for ROMs to use it, it is just gone unused so far due to lack of demand for foss images. I don't think we need to remove it from the instructions, maybe we comment that it has gone unused so far

**Comment by dos1** [comment]
Are there instructions somewhere on how to build the FOSS variant?

**Comment by ACR-Jeff** [comment]
> Right, but do `FOSS` variant images exist for any ROM at all? I think the redundant mention of it should be removed if not.



> @ACR-Jeff but can that be installed using `waydroid init -s FOSS` somehow (how)? If not then that's irrelevant to this issue which is about mentioning `--system_type FOSS` in the output of `waydroid init -h`.

You asked if any FOSS variant ROM's exist, I provided a source. Maybe that information will help someone else.

**Comment by hamishmb** [comment]
If the feature currently doesn't work as there are no images, maybe it can be removed and then re-added when there are images?

**Comment by Fuseteam** [comment]
Guys i think we're missing the point:

`waydroid -h` says `waydroid init -s FOSS` will initialize waydroid with a FOSS image, but it is not a valid option
`waydroid init -s FOSS` errors out instead, this misleading at best and misinfornation at worst

**Comment by hamishmb** [comment]
Yep, same in the official docs, it threw me cos then I'm wondering what Vanilla is, whether that has Foss in.

What about people who don't even know what "FOSS" means? It would probably just put them off because it's jargoney for the average non-super-techie person.

**Comment by hamishmb** [comment]
Bump, can we have a resolution of some kind?
