### ISSUE TITLE
Waydroid Emulated Filesystem is Incompatible with Play Store

### ISSUE THREAD

**Issue by rothn** [waydroid/waydroid#530]
**Describe the bug**
Something about the emulated filesystem Waydroid creates is incompatible with the Play Store, requiring occasional manual intervention via the shell to create directories when first installing an app and for some updates.

Key Logcat Subset (full logcat attached).
```
09-18 16:13:35.661  1385  1385 I Finsky  : [2] qpk.p(79): IT: Required downloads: [com.google.android.trichromelibrary]
09-18 16:13:35.668  4054  4054 W .android.chrom: JIT profile information will not be recorded: profile file does not exist.
09-18 16:13:35.673  1385  1857 I Finsky  : [80] xyz.run(38): Session for com.google.android.trichromelibrary already exists, skipping creation
09-18 16:13:35.690  4054  4054 I LoadedApk: No resource references to update in package com.google.android.trichromelibrary
09-18 16:13:35.690  4054  4054 D NetworkSecurityConfig: Using Network Security Config from resource 0_resource_name_obfuscated debugBuild: false
09-18 16:13:35.692  4054  4054 D NetworkSecurityConfig: Using Network Security Config from resource 0_resource_name_obfuscated debugBuild: false
09-18 16:13:35.721  1385  1621 I Finsky  : [49] qog.accept(22): IT: starting next download: package=com.google.android.trichromelibrary
09-18 16:13:35.738  1385  1624 I Finsky  : [50] qgr.a(155): Downloading compressed for com.google.android.trichromelibrary (adid: com.google.android.trichromelibrary , isid: EyVrIHB-RUKy-H5QDFG5lA)
09-18 16:13:35.766   226  3692 I ActivityManager: Killing 2879:org.calyxos.backup.contacts/u0a159 (adj 985): empty #17
09-18 16:13:35.767   226   254 W libprocessgroup: Failed to open process cgroup uid 10159 pid 2879: Permission denied
09-18 16:13:35.768   226   254 E libprocessgroup: Error encountered killing process cgroup uid 10159 pid 2879: Permission denied
09-18 16:13:35.780  1385  1624 I Finsky  : [50] msb.b(1): enqueue()
09-18 16:13:35.816  1385  1624 I Finsky  : [50] qms.a(128): IT: Already sent resource request for com.google.android.trichromelibrary, adid: com.google.android.trichromelibrary, isid: EyVrIHB-RUKy-H5QDFG5lA
09-18 16:13:35.822    57    57 I Zygote  : Process 2879 exited due to signal 9 (Killed)
09-18 16:13:35.838  1965  1965 I Finsky:download_service: [2] sxn.onCreate(2): IPC-SERVER: Starting gRPC host service...
09-18 16:13:35.870  1965  4079 I Finsky:download_service: [45] mkj.a(12): enqueue(request_id=31, files_to_download=1, context[group_id=com.google.android.trichromelibrary], display_data[invisible=false, title=com.google.android.trichromelibrary], network_restrictions=4)
09-18 16:13:35.879  1965  4079 E Finsky:download_service: [45] mjm.a(73): Failed to create downloadStatus files.
09-18 16:13:35.879  1965  4079 E Finsky:download_service: java.io.IOException: Can't create  file:///storage/emulated/0/Android/data/com.android.vending/files/installer/-1291719555/1663535615753
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at mjm.a(PG:72)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at mkj.a(PG:19)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at swl.a(PG:6)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at bdsr.b(PG:2)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at bdoa.a(PG:5)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at bdoe.a(PG:3)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at bdgo.run(PG:2)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at bdny.run(PG:2)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at java.lang.Thread.run(Thread.java:923)
09-18 16:13:35.879  1965  4079 E Finsky:download_service: Caused by: java.io.IOException: No such file or directory
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at java.io.UnixFileSystem.createFileExclusively0(Native Method)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at java.io.File.createNewFile(File.java:1008)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       at mjm.a(PG:35)
09-18 16:13:35.879  1965  4079 E Finsky:download_service:       ... 10 more
09-18 16:13:35.925  1385  4045 I Finsky  : [162] qpt.<init>(13): Installer: Setting Parallelism[DEFAULT]
09-18 16:13:35.930  1385  1385 I Finsky  : [2] wdm.a(18): Showing notification: [ID=com.google.android.trichromelibrary, Tag=null, Title=Can't download com.google.android.trichromelibrary, Message=Try again, and if it still doesn't work, <a href="https://support.google.com/googleplay/?p=fix_download_install&hl=en&error=7&ctx=com.google.android.trichromelibrary&isid=EyVrIHB-RUKy-H5QDFG5lA">see common ways to fix the problem </a>, channelId=security-and-errors, targetType=1, returnCode=4, uiElementType=930]
09-18 16:13:35.932  1385  4045 W Finsky  : [162] qpk.m(1): IT: Cleanup running installation of com.android.chrome (null)
09-18 16:13:35.940  1385  4045 I Finsky  : [162] qmo.V(1): Installer: stopping tracking of task: com.android.chrome
09-18 16:13:35.944  1385  4045 I Finsky  : [162] qmo.L(12): Installer: Notifying status update. package=com.android.chrome, status=INSTALL_ERROR
09-18 16:13:35.945  1385  4045 W Finsky  : [162] qpk.m(1): IT: Cleanup running installation of com.google.android.trichromelibrary (com.google.android.trichromelibrary)
```

**Reproducing:**
1. Attempt to install a new app with the Play Store.
2. Observe that the app does not install.

**Workaround:**
1. Run `sudo waydroid logcat` on the phone.
3. Attempt to install or update the app again.
4. Look for an error like the one above.
5. Manually create the parent directory:
    1. Start a root shell with `sudo waydroid shell`.
    2. Create the parent directory with `mkdir -p /storage/emulated/0/Android/data/com.android.vending/files/installer/-1291719555`.
    Note: Use the path from the logcat error with `mkdir`. The path above corresponds to the logcat in this ticket.

**General information (please complete the following information):**
Everything is from the latest "main" and "lineage-18.1" branches
- Waydroid tools version (main branch from git) 68ed713ca10e9570ec0dbea72a3ba04a4ca54b4e
- Waydroid Images version
  - lineage_waydroid_arm64-userdebug
  - Full list of repo versions from Android image (including Waydroid): [repos.txt](https://github.com/waydroid/waydroid/files/9595301/repos.txt)

**Desktop (please complete the following information):**
 - OS: 5.19.8-1-MANJARO-ARM SMP PREEMPT (not versioned IIUC; rolling release)
 - GPU: Rockchip RK3399
 - Kernel version: 5.19.8-1
 - Host mesa version: 22.1.7
 - Desktop: Phosh with GNOME Shell 42.4

**Smartphone (please complete the following information):**
 - Device: PinePhone Pro
 - OS: Manjaro + Phosh
 - Mainline
 - Kernel version: 5.19.8-1

**Logs (please upload as file)**
 - Prop file: [waydroid_base.prop.txt](https://github.com/waydroid/waydroid/files/9595302/waydroid_base.prop.txt)
 - Output of `waydroid log`: [waydroid.log](https://github.com/waydroid/waydroid/files/9595305/waydroid.log)
 - Full waydroid logcat: [gapp_store_cant_create_file_logcat.log](https://github.com/waydroid/waydroid/files/9595307/gapp_store_cant_create_file_logcat.log)

**Additional context**
Built with GMS from https://github.com/Suicide-Squirrel/vendor_partner_gms

**Comment by aleasto** [comment]
The linked gapps are SDK29, have you tried SDK30 gapps?

**Comment by aleasto** [comment]
I cannot seem to reproduce with [MindTheGapps](https://gitlab.com/MindTheGapps/vendor_gapps/-/tree/rho) (arch x86)

**Comment by rothn** [comment]
I will try to reproduce with MindTheGapps. I was not able to find an SDK30 gapps over an hour of Google searching, so I'll make sure to add this one to my [guide doc](https://docs.google.com/document/d/1Sly_VH3w6wFIdE72WXijQegoHZh8IxEnJ9m0hH7GodU/edit).

**Comment by rothn** [comment]
Cannot reproduce with MindTheGapps.
