### ISSUE TITLE
Configure to work without listen port 53

### ISSUE THREAD

**Issue by itsnotsaved** [waydroid/waydroid#537]
**Describe the Problem**

I install waydroid on ubuntu machine using https://github.com/n1lby73/waydroid-installer and i saw it listen to port 53 with dnsmasq; how to disable that? I use a local DNS server (adguradhome; what is it? similar to pihole etc) on my laptop and it needs the port 53; also i don't like waydroid use its own way to resolve DNS (no such trouble with anbox as i remember)

I couldn't find any details on https://docs.waydro.id

**General information (please complete the following information):**
 - Waydroid tools Version - 1.3.2
 - Waydroid Images Version [above]

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.01 64 bit
 - GPU: Skylake GT2
 - Kernel version: 5.15.0-48-generic
 - Desktop: Gnome 42.4

**Smartphone (please complete the following information):**

I don't use

**Comment by Quackdoc** [comment]
by changing the waydroid NIC in waydroid's LXC config, you can create your own network interface and rules, it's not something I yet have documented.

**Comment by itsnotsaved** [comment]
@Quackdoc please add a guide for it

Important parts:
- Free the port 53
- Configure to resolve DNS through custom DNS (e.g. LAN DNS IP) or system DNS or external DNS

**Comment by acheong08** [comment]
Updates? I have something running on port 53 that is conflicting with dnsmasq

**Comment by Petemir** [comment]
Ok, got it working for my case. 

The `/usr/lib/waydroid/data/scripts/waydroid-net.sh` script starts `dnsmasq` on the host. `dnsmasq` provides both DNS (port 53) and DHCP (port 67) servers to the waydroid container; this will conflict with any local DNS/DHCP servers running in the host. As I am running `pihole` through Docker, my default docker-composer.yml file was also forwarding port 67, even though I didn't use it. So, my first step was totally dependent on me using `pihole`:

* Disable port 67 forwarding in my docker-compose.yml file and recreate the pihole container.

The following step is to a) tell `dnsmasq` to stop providing its DNS services and b) to push via DHCP the address of the DNS server that the container should use. As my DNS server is on the host (i.e., the pihole running in the docker container of my computer), I want the container's DNS to be set to the container's gateway IP (i.e., the host's IP in the subnet created by the LXC configuration).  These two steps can be achieved by modifying the [waydroid-net.sh script](https://raw.githubusercontent.com/waydroid/waydroid/main/data/scripts/waydroid-net.sh); in particular, adding two options to the `dnsmasq` command  on line 200:

```
dnsmasq **-p 0 --dhcp-option=6,$LXC_ADDR** $LXC_DHCP_CONFILE_ARG $LXC_DOMAIN_ARG $LXC_DHCP_PING_ARG -u ${DNSMASQ_USER} \
```

`-p 0` tells `dnsmasq` to disable the DNS function, and `--dhcp-option=6,$LXC_ADDR` specifies to the DHCP server the DNS address (in my case, my computer's IP; change it according to your use case) that should be pushed to the clients (i.e., `waydroid`).

Hope this helps.

**Comment by Sonico98** [comment]
To expand a bit on Petemir's answer, my computer's IP is 192.168.1.14, so aside from modifying line 200 on the `waydroid-net.sh` script, I had to:
- Change `LXC_ADDR` on line 20 to `192.168.1.14`
- Change `LXC_NETWORK` on line 22 to `192.168.1.14/24`
- Set the `LXC_DHCP_RANGE` on line 23 to go from `192.168.1.100` to `192.168.1.254`

**Comment by dwdbmeagle** [comment]
I have run into the same problem, on my htpc machine (running EndeavourOS), pihole and the firewall.
I have changed my waydroid-net.sh script as indicated but I waydroid net-setup still fails:
`USE_LXC_BRIDGE="true"
LXC_BRIDGE="${vnic}"
LXC_BRIDGE_MAC="00:16:3e:00:00:01"
LXC_ADDR="10.14.7.110"
LXC_NETMASK="255.255.255.0"
LXC_NETWORK="10.14.7.110/24"
LXC_DHCP_RANGE="10.14.7.200,10.14.7.254"
LXC_DHCP_MAX="253"
LXC_DHCP_CONFILE=""
LXC_DHCP_PING="true"
LXC_DOMAIN=""
LXC_USE_NFT="true"


 dnsmasq -p 0 --dhcp-option=6,$LXC_ADDR $LXC_DHCP_CONFILE_ARG $LXC_DOMAIN_ARG $LXC_DHCP_PING_ARG -u ${DNSMASQ_USER} \
            --strict-order --bind-interfaces --pid-file="${varrun}"/dnsmasq.pid \
            --listen-address ${LXC_ADDR} --dhcp-range ${LXC_DHCP_RANGE} \
            --dhcp-lease-max=${LXC_DHCP_MAX} --dhcp-no-override \
            --except-interface=lo --interface=${LXC_BRIDGE}  \
            --dhcp-leasefile="${varlib}"/misc/dnsmasq.${LXC_BRIDGE}.leases \
            --dhcp-authoritative $LXC_IPV6_ARG || cleanup

`
I have opened the corresponding ports.

My waydroid log error:
`check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

(020025) [21:26:26] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(020064) [21:26:32] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(020064) [21:26:32] *** output passed to waydroid stdout, not to this log ***
(000691) [21:29:41] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
Failed to setup waydroid-net.
Failed to setup waydroid-net.
(000691) [21:29:41] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000691) [21:29:41] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(020234) [21:29:41] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
`
Maybe I python version is to new?

**Comment by Petemir** [comment]
@dwdbmeagle please correct your formatting, otherwise it's difficult to know what's wrong with your script, e.g. there are some missing `$` (`$LXC_DHCP_PING_ARG`, `${DNSMASQ_USER}`) and `\`.

**Comment by dwdbmeagle** [comment]
> @dwdbmeagle please correct your formatting, otherwise it's difficult to know what's wrong with your script, e.g. there are some missing `$` (`$LXC_DHCP_PING_ARG`, `${DNSMASQ_USER}`) and `\`.

Done

**Comment by WarpspeedSCP** [comment]
What worked for me was to just set the port to a different one. I chose 90.

**Comment by ikcikoR** [comment]
> What worked for me was to just set the port to a different one. I chose 90.

Where did you change that? I got unbound running on 53 so that all my DNS queries from my system are encrypted through it over TLS and waydroid HATES it... I can only resolve using my host system's /etc/hosts hostnames, and ofc Android's private DNS feature only accepts hostnames and not IPs, meaning it has to first resolve the DNS server IP using default DNS, which never works...

**Comment by WarpspeedSCP** [comment]
> Where did you change that?

In the dnsmasq command. Instead of -p 0, use -p <your custom port>.

**Comment by ikcikoR** [comment]
> In the dnsmasq command. Instead of -p 0, use -p .

That breaks the script
```
[03:01:30] Starting waydroid session
[03:01:30] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
```

**Comment by ikcikoR** [comment]
Ok, I'm going insane:

1) I have unbound running on 0.0.0.0 and ::0 providing DNS for my computer (routing encrypted calls to one random DNS provider)
2) Using waydroid shell and nc command, I can verify waydroid can connect to the port 53 of 192.168.240.1 (my Linux PC's IP on watdroid0 interface)
3) getprop net.dns1 shows that address as the DNS server waydroid is using in waydroid shell
4) I tried setting custom DNS in Android settings menu to both Off and Automatic but it makes no difference
5) I can use ping command in waydroid shell to ping every device on my local network and online IP addresses like 1.1.1.1 or 7.7.7.7 and everything else

But DNS still isn't working and I have no idea why

Oh also apparently waydroid uses my actual PC's /etc/hosts for domain names. (at least the ping command in waydroid shell does)

At this point I'm confused as hell, clueless as to what to try next and I don't really know what I'm doing anymore.

Oh also, everything works perfectly if I change my PC's configuration to use normal unencrypted DNS instead of unbound, but I don't want to have to do that just to fix waydroid having a stroke when it comes to name resolution...

One more thing, I was running some software on my phone that you use a web browser to interact with, connecting to some port on localhost and so on. I can use IP+port in the android browser in waydroid and everything works fine. So yeah, everything works except waydroid refuses to use DNS provided on my PC.

**Comment by ikcikoR** [comment]
> My mistake, @ikcikoR, i meant to say, `-p 50`.

Do I leave `--dhcp-option=6,$LXC_ADDR`?

**Comment by inoribea** [comment]
> Ok, I'm going insane:
> 
>     1. I have unbound running on 0.0.0.0 and ::0 providing DNS for my computer (routing encrypted calls to one random DNS provider)
> 
>     2. Using waydroid shell and nc command, I can verify waydroid can connect to the port 53 of 192.168.240.1 (my Linux PC's IP on watdroid0 interface)
> 
>     3. getprop net.dns1 shows that address as the DNS server waydroid is using in waydroid shell
> 
>     4. I tried setting custom DNS in Android settings menu to both Off and Automatic but it makes no difference
> 
>     5. I can use ping command in waydroid shell to ping every device on my local network and online IP addresses like 1.1.1.1 or 7.7.7.7 and everything else
> 
> 
> But DNS still isn't working and I have no idea why
> 
> Oh also apparently waydroid uses my actual PC's /etc/hosts for domain names. (at least the ping command in waydroid shell does)
> 
> At this point I'm confused as hell, clueless as to what to try next and I don't really know what I'm doing anymore.
> 
> Oh also, everything works perfectly if I change my PC's configuration to use normal unencrypted DNS instead of unbound, but I don't want to have to do that just to fix waydroid having a stroke when it comes to name resolution...
> 
> One more thing, I was running some software on my phone that you use a web browser to interact with, connecting to some port on localhost and so on. I can use IP+port in the android browser in waydroid and everything works fine. So yeah, everything works except waydroid refuses to use DNS provided on my PC.

hello bro, i used unbound with dnscrypt-proxy.
my configure is unbound use 53 dnsc-p use port 5353
also i cant bind which port for waydroid
so i changed to another way
`dnsmasq -p 0 --dhcp-option=6,192.168.0.0/255 $LXC_DHCP_CONFILE_ARG $LXC_DOMAIN_ARG $LXC_DHCP_PING_ARG -u ${DNSMASQ_USER} \`
so my waydroid can use router's dns.

**Comment by ikcikoR** [comment]
> hello bro, i used unbound with dnscrypt-proxy. my configure is unbound use 53 dnsc-p use port 5353 also i cant bind which port for waydroid so i changed to another way `dnsmasq -p 0 --dhcp-option=6,192.168.0.0 $LXC_DHCP_CONFILE_ARG $LXC_DOMAIN_ARG $LXC_DHCP_PING_ARG -u ${DNSMASQ_USER} \` so my waydroid can use router's dns.

Hm, that's a decent idea since I can then set encrypted DNS in Android settings, tho it is also annoying because if my local network configuration ever changes, waydroid will lose internet access-

I guess I can live with it for the time being, but if anybody comes up with something more reliable, it would be much appreciated.

**Comment by inoribea** [comment]
> > hello bro, i used unbound with dnscrypt-proxy. my configure is unbound use 53 dnsc-p use port 5353 also i cant bind which port for waydroid so i changed to another way `dnsmasq -p 0 --dhcp-option=6,192.168.0.0 $LXC_DHCP_CONFILE_ARG $LXC_DOMAIN_ARG $LXC_DHCP_PING_ARG -u ${DNSMASQ_USER} \` so my waydroid can use router's dns.
> 
> Hm, that's a decent idea since I can then set encrypted DNS in Android settings, tho it is also annoying because if my local network configuration ever changes, waydroid will lose internet access-
> 
> I guess I can live with it for the time being, but if anybody comes up with something more reliable, it would be much appreciated.

That's why I set 192.168.0.0，But as you said, it's still barely usable。

**Comment by winteriscariot** [comment]
This is not an issue with Waydroid, it's an issue of host dns server configuration. The waydroid script already has the 'bind-interfaces' option by default, so _that_ instance of dnsmasq will only bind to 192.168.240.1. But if you're using a default configuration of dnsmasq on your host, it will automatically bind itself to all interfaces, including 192.168.240.1. that's where the port conflict comes from.

So with that said, if you're using dnsmasq on your host this issue can be easily resolved by simply setting the `bind-interfaces` option on your hosts's dnsmasq.conf and restart the dnsmasq service. For anything other than dnsmasq you'll have to check the docs but i'm pretty sure all dns servers have the option of being bound to a single address or interface.

**Comment by ikcikoR** [comment]
> This is not an issue with Waydroid, it's an issue of host dns server configuration. The waydroid script already has the 'bind-interfaces' option by default, so _that_ instance of dnsmasq will only bind to 192.168.240.1. But if you're using a default configuration of dnsmasq on your host, it will automatically bind itself to all interfaces, including 192.168.240.1. that's where the port conflict comes from.
> 
> So with that said, if you're using dnsmasq on your host this issue can be easily resolved by simply setting the `bind-interfaces` option, as well as either the `listen-address` or `interface` options to appropriate, on your hosts's dnsmasq.conf and restart the dnsmasq service. For anything other than dnsmasq you'll have to check the docs but i'm pretty sure all dns servers have the option of being bound to a single address or interface.
> 
> i've confirmed this on Arch Linux

I don't have dnsmasq on host and waydroid is the only piece of software on my PC which doesn't work with the DNS setup I have that is more than conventional so that's a waydroid problem and it shouldn't force you to do manual bandaid fixes on your host OS if possible.

**Comment by winteriscariot** [comment]
> > This is not an issue with Waydroid, it's an issue of host dns server configuration. The waydroid script already has the 'bind-interfaces' option by default, so _that_ instance of dnsmasq will only bind to 192.168.240.1. But if you're using a default configuration of dnsmasq on your host, it will automatically bind itself to all interfaces, including 192.168.240.1. that's where the port conflict comes from.
> > So with that said, if you're using dnsmasq on your host this issue can be easily resolved by simply setting the `bind-interfaces` option, as well as either the `listen-address` or `interface` options to appropriate, on your hosts's dnsmasq.conf and restart the dnsmasq service. For anything other than dnsmasq you'll have to check the docs but i'm pretty sure all dns servers have the option of being bound to a single address or interface.
> > i've confirmed this on Arch Linux
> 
> I don't have dnsmasq on host and waydroid is the only piece of software on my PC which doesn't work with the DNS setup I have that is more than conventional so that's a waydroid problem and it shouldn't force you to do manual bandaid fixes on your host OS if possible.

it's not about dnsmasq specifically, i'm saying you need to tell your dns server on your host to not bind to all addresses, or tell it to exclude 192.168.240.1. that's the simplest, easiest, and most permanent fix you could do for this issue. i guarantee you it will fix the issue this issue is about, without having to edit the waydroid start script.

**Comment by ikcikoR** [comment]
Guess I'll test it later

**Comment by Asirelith** [comment]
> Ok, got it working for my case.
> 
> The `/usr/lib/waydroid/data/scripts/waydroid-net.sh` script starts `dnsmasq` on the host. `dnsmasq` provides both DNS (port 53) and DHCP (port 67) servers to the waydroid container; this will conflict with any local DNS/DHCP servers running in the host. As I am running `pihole` through Docker, my default docker-composer.yml file was also forwarding port 67, even though I didn't use it. So, my first step was totally dependent on me using `pihole`:
> 
> * Disable port 67 forwarding in my docker-compose.yml file and recreate the pihole container.
> 
> The following step is to a) tell `dnsmasq` to stop providing its DNS services and b) to push via DHCP the address of the DNS server that the container should use. As my DNS server is on the host (i.e., the pihole running in the docker container of my computer), I want the container's DNS to be set to the container's gateway IP (i.e., the host's IP in the subnet created by the LXC configuration). These two steps can be achieved by modifying the [waydroid-net.sh script](https://raw.githubusercontent.com/waydroid/waydroid/main/data/scripts/waydroid-net.sh); in particular, adding two options to the `dnsmasq` command on line 200:
> 
> ```
> dnsmasq -p 0 --dhcp-option=6,$LXC_ADDR $LXC_DHCP_CONFILE_ARG $LXC_DOMAIN_ARG $LXC_DHCP_PING_ARG -u ${DNSMASQ_USER} \
> ```
> 
> My modifications are:
> 
> * `-p 0` tells `dnsmasq` to disable the DNS function
> * `--dhcp-option=6,$LXC_ADDR` specifies to the DHCP server the DNS address (in my case, my computer's IP; change it according to your use case) that should be pushed to the clients (i.e., `waydroid`).
> 
> Hope this helps.

Thank you so so much, I was running pi-hole and waydroid, and since the port 53 was used by pi-hole, I was blocked.
Now they both run alltogether.
