### ISSUE TITLE
"Encoder failed (err=-38)" when adb shell screenrecord

### ISSUE THREAD

**Issue by diyism** [waydroid/waydroid#553]
It seems there's a problem in the video encoder in waydroid lineageos:
```
#in armbian:
$ adb kill-server
$ nohup adb -a nodaemon server start >/dev/null 2>&1 &
$ adb connect 192.168.240.112
$ adb forward tcp:5556 tcp:5555

#in remote linux:
$ adb connect <armbian ip>:5556
$ adb -s <armbian ip>:5556 shell screenrecord --verbose /sdcard/1.mp4
Main display is 1920x1053 @60.00fps (orientation=0)
Configuring recorder for 1920x1052 video/avc at 20.00Mbps
Content area is 1918x1052 at offset x=1 y=0
Stopping encoder and muxer
Encoder failed (err=-38)
```

#And scrcpy shows simimar problems:
```
$ scrcpy -s <armbian ip>:5556 -Vdebug
scrcpy 1.24 <https://github.com/Genymobile/scrcpy>
DEBUG: ADB device found:
DEBUG:     --> (tcpip)  <armbian ip>:5556             device  Pine64_
DEBUG: Device serial: <armbian ip>:5556
DEBUG: Using server: /usr/local/share/scrcpy/scrcpy-server
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 1.5 MB/s (41159 bytes in 0.027s)
[server] INFO: Device: Waydroid Pine64+ (Android 10)
DEBUG: Server connected
DEBUG: Starting controller thread
DEBUG: Starting receiver thread
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 21.2.6
INFO: Trilinear filtering enabled
DEBUG: Using icon: /usr/local/share/icons/hicolor/256x256/apps/scrcpy.png
INFO: Initial texture: 1920x1048
DEBUG: Starting demuxer thread
[server] DEBUG: Using encoder: 'OMX.google.h264.encoder'
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1600...
[server] DEBUG: Using encoder: 'OMX.google.h264.encoder'
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1280...
[server] DEBUG: Using encoder: 'OMX.google.h264.encoder'
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1024...
[server] DEBUG: Using encoder: 'OMX.google.h264.encoder'
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m800...
[server] DEBUG: Using encoder: 'OMX.google.h264.encoder'
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
DEBUG: Receiver stopped
DEBUG: End of frames
[server] DEBUG: Device message sender stopped
[server] DEBUG: Controller stopped
WARN: Device disconnected
DEBUG: quit...
[server] ERROR: Exception on thread Thread[main,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:2792)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
	at com.genymobile.scrcpy.Server.main(Server.java:335)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:340)
DEBUG: Server disconnected
DEBUG: Server terminated
```

**Comment by aleasto** [comment]
Please try again after updating waydroid `sudo waydroid upgrade`

**Comment by diyism** [comment]
I've upgraded it(lineage-18.1-20221111-VANILLA-waydroid_arm64-system.zip), it seems the problem is still there:

```
$ adb shell getprop ro.build.fingerprint
waydroid/lineage_waydroid_arm64/waydroid_arm64:11/RQ3A.211001.001/7:userdebug/test-keys

$ adb shell screenrecord --verbose /sdcard/1.mp4
Display is 1920x1053 @60.00fps (orientation=ROTATION_0), layerStack=0
Configuring recorder for 1920x1052 video/avc at 20.00Mbps
Content area is 1918x1052 at offset x=1 y=0
Stopping encoder and muxer
Encoder failed (err=-38)
```

**Comment by Hairo** [comment]
I'm having the same issue, video playback also doesn't work in the stock browser, only get audio, using lineage-18.1-20230114-VANILLA-waydroid_x86_64-system.zip

OS: EndeavourOS x64
GPU: AMD Radeon RX 5500 XT
Kernel version: 6.1.5-zen2-1-zen
Host mesa version: 22.3.3
Desktop: KDE Plasma 5.26.5

**Comment by SwetyCore** [comment]
I'm having the same issue,too

**Comment by xfl12345** [comment]
I'm having the same issue, too. Using [lineage-18.1-20230128-GAPPS-waydroid_arm-system.zip](https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_arm/lineage-18.1-20230128-GAPPS-waydroid_arm-system.zip/download)

Board model: Radxa Rockpi 4B plus
CPU: Rockchip RK3399
GPU: Mali-T860
OS: Armbian (Official release, base on Ubuntu 22.10)
Kernel version: `uname -a` output: Linux radxa-rockpi-4b-plus 5.15.90-rockchip64 #trunk SMP PREEMPT Thu Jan 26 19:31:53 HKT 2023 aarch64 aarch64 aarch64 GNU/Linux
Host mesa version: 23.1.0

```Text
xfl@radxa-rockpi-4b-plus:~$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa (0xffffffff)
    Device: Mali-T860 (Panfrost) (0xffffffff)
    Version: 23.1.0
    Accelerated: yes
    Video memory: 3863MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.1
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Mesa
OpenGL renderer string: Mali-T860 (Panfrost)
OpenGL core profile version string: 3.1 Mesa 23.1.0-devel (git-b1a3378 2023-02-03 jammy-oibaf-ppa)
OpenGL core profile shading language version string: 1.40
OpenGL core profile context flags: (none)

OpenGL version string: 3.1 Mesa 23.1.0-devel (git-b1a3378 2023-02-03 jammy-oibaf-ppa)
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 23.1.0-devel (git-b1a3378 2023-02-03 jammy-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10xfl@radxa-rockpi-4b-plus:~$ glxinfo -B

name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Mesa (0xffffffff)
    Device: Mali-T860 (Panfrost) (0xffffffff)
    Version: 23.1.0
    Accelerated: yes
    Video memory: 3863MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 3.1
    Max compat profile version: 3.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Mesa
OpenGL renderer string: Mali-T860 (Panfrost)
OpenGL core profile version string: 3.1 Mesa 23.1.0-devel (git-b1a3378 2023-02-03 jammy-oibaf-ppa)
OpenGL core profile shading language version string: 1.40
OpenGL core profile context flags: (none)

OpenGL version string: 3.1 Mesa 23.1.0-devel (git-b1a3378 2023-02-03 jammy-oibaf-ppa)
OpenGL shading language version string: 1.40
OpenGL context flags: (none)

OpenGL ES profile version string: OpenGL ES 3.1 Mesa 23.1.0-devel (git-b1a3378 2023-02-03 jammy-oibaf-ppa)
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
xfl@radxa-rockpi-4b-plus:~$
```

**Comment by bournedrewd** [comment]
I'm also experiencing this issue while trying to get QtScrcpy to work. `adb shell screenrecord` likewise fails for me.

OS: Arch Linux
GPU: Radeon RX 570
Kernel: 6.2.1-zen1-1zen

<details>
<summary>adb shell screenrecord log</summary>

```
adb shell screenrecord --verbose /sdcard/file.mp4
Display is 1920x1080 @60.00fps (orientation=ROTATION_0), layerStack=0
Configuring recorder for 1920x1080 video/avc at 20.00Mbps
Content area is 1920x1080 at offset x=0 y=0
Stopping encoder and muxer
Encoder failed (err=-38)
Executing: /system/bin/am broadcast -a android.intent.action.MEDIA_SCANNER_SCAN_FILE -d file:///sdcard/file.mp4
Broadcasting: Intent { act=android.intent.action.MEDIA_SCANNER_SCAN_FILE dat=file:///sdcard/file.mp4 flg=0x400000 }
Broadcast completed: result=0
```

</details>

<details>
<summary>QtScrcpy Exception</summary>

```
AdbProcessImpl::error:java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:152)
	at com.genymobile.scrcpy.ScreenEncoder.internalStreamScreen(ScreenEncoder.java:102)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:74)
	at com.genymobile.scrcpy.Server.scrcpy(Server.java:101)
	at com.genymobile.scrcpy.Server.main(Server.java:335)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
```

</details>


<details>
<summary>glxinfo -B</summary>

```
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon RX 570 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.2.10-zen1-1-zen) (0x67df)
    Version: 23.0.2
    Accelerated: yes
    Video memory: 8192MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 7637 MB, largest block: 7637 MB
    VBO free aux. memory - total: 7846 MB, largest block: 7846 MB
    Texture free memory - total: 7637 MB, largest block: 7637 MB
    Texture free aux. memory - total: 7846 MB, largest block: 7846 MB
    Renderbuffer free memory - total: 7637 MB, largest block: 7637 MB
    Renderbuffer free aux. memory - total: 7846 MB, largest block: 7846 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 16144 MB
    Currently available dedicated video memory: 7637 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon RX 570 Series (polaris10, LLVM 15.0.7, DRM 3.49, 6.2.10-zen1-1-zen)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.0.2
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.0.2
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.0.2
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

</details>

**Comment by J4ckTh3R1pper** [comment]
I have encountered this issue as well, I am using the original command line scrcpy,  `adb shell screenrecord` returns `Encoder failed (err=-38)`
OS: Gentoo Linux
GPU: AMD Radeon RX 550
Kernel: 6.2.12-xanmod1, configured by myself

>scrcpy 2.0 <https://github.com/Genymobile/scrcpy>
/usr/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 137.8 MB/s (52867 bytes in 0.000s)
[server] INFO: Device: Waydroid WayDroid x86_64 Device (Android 11)
[server] ERROR: Exception on thread Thread[Thread-4,5,main]
java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe
	at android.media.MediaCodec.native_setup(Native Method)
	at android.media.MediaCodec.<init>(MediaCodec.java:1912)
	at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1875)
	at com.genymobile.scrcpy.AudioEncoder.createMediaCodec(AudioEncoder.java:278)
	at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:174)
	at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:120)
	at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:923)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.3.7
INFO: Trilinear filtering enabled
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Initial texture: 1920x1040
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: newMaxSize = 1600
[server] INFO: Retrying with -m1600...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null

**Comment by kde-yyds** [comment]
the same

**Comment by diyism** [comment]
Tested with the latest lineage(waydroid_arm64/lineage-18.1-20230729-VANILLA-waydroid_arm64-system.zip), it still failed:

```
$ scrcpy -s 192.168.15.169:5556 --list-encoders
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:         (tcpip)  127.0.0.1:5555                  device  redroid13_x86_64_only
INFO:     --> (tcpip)  192.168.15.169:5556             device  Pine64_
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 7.0 MB/s (56995 bytes in 0.008s)
[server] INFO: List of video encoders:
    --video-codec=h264 --video-encoder='OMX.google.h264.encoder'
[server] INFO: List of audio encoders:
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'

$ scrcpy -s 192.168.15.169:5556
scrcpy 2.1.1 <https://github.com/Genymobile/scrcpy>
INFO: ADB device found:
INFO:         (tcpip)  127.0.0.1:5555                  device  redroid13_x86_64_only
INFO:     --> (tcpip)  192.168.15.169:5556             device  Pine64_
/usr/local/share/scrcpy/scrcpy-server: 1 file pushed, 0 skipped. 10.4 MB/s (56995 bytes in 0.005s)
[server] INFO: Device: [Waydroid] waydroid Pine64+ (Android 11)
[server] ERROR: Could not create default audio encoder for opus
List of audio encoders:
    --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'
[server] ERROR: Exception on thread Thread[audio-encoder,5,main]
java.lang.IllegalArgumentException: Failed to initialize audio/opus, error 0xfffffffe
	at android.media.MediaCodec.native_setup(Native Method)
	at android.media.MediaCodec.<init>(MediaCodec.java:1912)
	at android.media.MediaCodec.createEncoderByType(MediaCodec.java:1875)
	at com.genymobile.scrcpy.AudioEncoder.createMediaCodec(AudioEncoder.java:292)
	at com.genymobile.scrcpy.AudioEncoder.encode(AudioEncoder.java:184)
	at com.genymobile.scrcpy.AudioEncoder.lambda$start$0$com-genymobile-scrcpy-AudioEncoder(AudioEncoder.java:124)
	at com.genymobile.scrcpy.AudioEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 22.3.3
INFO: Trilinear filtering enabled
WARN: Demuxer 'audio': stream explicitly disabled by the device
INFO: Texture: 1920x1048
[server] INFO: Retrying with -m1600...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1280...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m1024...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] INFO: Retrying with -m800...
[server] INFO: Retrying...
[server] ERROR: Encoding error: java.lang.IllegalStateException: null
[server] ERROR: Exception on thread Thread[video,5,main]
java.lang.IllegalStateException
	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3452)
	at com.genymobile.scrcpy.ScreenEncoder.encode(ScreenEncoder.java:184)
	at com.genymobile.scrcpy.ScreenEncoder.streamScreen(ScreenEncoder.java:105)
	at com.genymobile.scrcpy.ScreenEncoder.lambda$start$0$com-genymobile-scrcpy-ScreenEncoder(ScreenEncoder.java:294)
	at com.genymobile.scrcpy.ScreenEncoder$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by abuu-u** [comment]
> 

are you using libndk/libhoudini ?

**Comment by diyism** [comment]
> > 
> 
> are you using libndk/libhoudini ?

I think that afte I run "waydroid upgrade" the lineage image has been overwritten, the old libhoudini patch should have been removed, so I have a clean lineage-18.1-20230729-VANILLA-waydroid_arm64 in my pine64 board now.

**Comment by diyism** [comment]
It seems the same: https://github.com/Genymobile/scrcpy/issues/4299

**Comment by kinow** [comment]
Same error message for me (with the err=-38) for me, upgraded Waydroid and re-installed the waydroid_scripts including gapps, libndk, magisk, fdroidpriv, libhoudini, and widevine.

**Comment by diyism** [comment]
Waydroid is shabby, to use redroid + scrcpy: https://github.com/remote-android/redroid-doc/issues/407

**Comment by kinow** [comment]
> Waydroid is shabby, to use redroid + scrcpy: [remote-android/redroid-doc#407 (comment)](https://github.com/remote-android/redroid-doc/issues/407#issuecomment-2156168301)

Tested and at least for me I could screenrecord and also use my projector over wifi6, thanks @diyism !

**Comment by Chubukov-Aleksey** [comment]
I am not sure if commenters have the same problem that causes this issue, but at least I managed to solve my instance.

<details>
<summary>Host device specs:</summary>

```
Machine:
  Type: Laptop System: LENOVO product: 82SB v: IdeaPad Gaming 3 15ARH7
    serial: <superuser required>
  Mobo: LENOVO model: LNVNB161216 v: No DPK serial: <superuser required>
    UEFI: LENOVO v: JNCN46WW(V2.06) date: 07/12/2023
CPU:
  Info: 6-core model: AMD Ryzen 5 7535HS with Radeon Graphics bits: 64
    type: MT MCP cache: L2: 3 MiB
  Speed (MHz): avg: 3141 min/max: 400/4603 cores: 1: 2968 2: 2962 3: 2961
    4: 2959 5: 4441 6: 400 7: 3225 8: 2955 9: 4460 10: 4442 11: 2960 12: 2961
Graphics:
  Device-1: NVIDIA AD107M [GeForce RTX 4050 Max-Q / Mobile] driver: nvidia
    v: 555.58.02
  Device-2: AMD Rembrandt [Radeon 680M] driver: amdgpu v: kernel
  Device-3: IMC Networks Integrated Camera driver: uvcvideo type: USB
  Display: wayland server: X.org v: 1.20.14 with: Xwayland v: 24.1.1
    compositors: 1: kwin_wayland 2: SurfaceFlinger driver: X:
    loaded: amdgpu,nvidia unloaded: fbdev,modesetting,nouveau,vesa
    dri: radeonsi gpu: nvidia,amdgpu resolution: 1: 1920x1080 2: 1707x960
  API: EGL v: 1.5 drivers: kms_swrast,nvidia,radeonsi,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6.0 compat-v: 4.5 vendor: amd mesa v: 24.1.5 renderer: AMD
    Radeon 660M (radeonsi rembrandt LLVM 18.1.6 DRM 3.57
    6.9.12-200.fc40.x86_64)
  API: Vulkan v: 1.3.283 drivers: N/A surfaces: xcb,xlib,wayland

```
</details>

In logcat, when starting scrcpy, just before crash backtrace I have noted this line:
`08-28 00:35:06.351  3175  3181 E android.hardware.media.omx@1.0-service: libminijail[3175]: blocked syscall: sysinfo`
Searching led me to this issue: https://github.com/remote-android/redroid-doc/issues/62. This was about Intel GPU, but I decided to give it a shot.

Note: waydroid was previously patched via waydroid_scripts and that enabled overlay for system partition.

In root shell:
```
mkdir -p /var/lib/waydroid/overlay/system/etc/seccomp_policy/
sed -e '/^kcmp/ a sysinfo: 1' /var/lib/waydroid/rootfs/system/etc/seccomp_policy/mediacodec.policy > /var/lib/waydroid/overlay/system/etc/seccomp_policy/mediacodec.policy
```
So that allows `sysinfo` syscall for mediacodec.
Finally, update configs: `waydroid upgrade -o`

After that, scrcpy started working. 

---

This line suggests that there is a separate path for additional policies, but I noticed it after fixing my problem:
```
08-28 00:35:06.278  3175  3175 W android.hardware.media.omx@1.0-service: Could not read additional policy file '/vendor_extra/etc/seccomp_policy/mediacodec.policy'
```

**Comment by dongshimou** [comment]
adb shell screenrecord /sdcard/file.mp4
Encoder failed (err=-38)

pve 8.0
gpu AMD rx580
bliss use the virGL
