### ISSUE TITLE
Unable to start waydroid session on AWS ec2 g4ad.xlarge instance.

### ISSUE THREAD

**Issue by caiiiycuk** [waydroid/waydroid#592]
Hi.

I am trying to run waydroid on aws g4ad ec2 instance (AMD EPYC x86_64 + AMD Radeon Pro V520). I used Ubuntu 20.04 because AMD driver have problems with installing on 22.04. I checked that GPU works (tested on glxgears). My display is sway on wayland.

**General information (please complete the following information):**
 - Waydroid tools Version: **1.3.3**
 - Waydroid Images Version: **VANILLA 20221109**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 x64
 - GPU: AMD Radeon Pro V520
 - Kernel version: 5.15.0-1022-aws
 - Host mesa version:
```
OpenGL vendor string: AMD
OpenGL renderer string: AMD NAVI12 (LLVM 14.0.1, DRM 3.46, 5.15.0-1022-aws)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 22.1.0-devel
```
 - Desktop: sway 1.4

**Smartphone (please complete the following information):**
???

**Additional context**

I tried both software render and GPU render, results are same, even logcat looks same. All logs looks normal, but nothing happened, the device initialization is stuck at some moment.

```
ubuntu@ip-172-31-18-8:~$ waydroid session start
[20:10:12] Failed to start Clipboard manager service, check logs
[gbinder] Service manager /dev/binder has appeared
```

**Logs (please upload as file)**
[logs.zip](https://github.com/waydroid/waydroid/files/10006673/logs.zip)

**Comment by caiiiycuk** [comment]
After rebooting ubuntu I have following errors when I do `sudo waydroid container start`:
```
002602) [20:24:11] Container manager is waiting for session to load
(002602) [20:24:11] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
waydroid-net is already running
(002602) [20:24:11] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(002602) [20:24:11] % umount /var/lib/waydroid/rootfs/vendor
(002602) [20:24:11] % umount /var/lib/waydroid/rootfs
(002602) [20:24:11] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(002602) [20:24:11] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(002602) [20:24:11] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(002602) [20:24:11] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(002602) [20:24:11] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(002602) [20:24:11] Save config: /var/lib/waydroid/waydroid.cfg
(002602) [20:24:11] % chmod 777 -R /dev/ashmem
(002602) [20:24:11] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
(002602) [20:24:11] % chmod 777 -R /dev/dri
(002602) [20:24:11] % chmod 777 -R /dev/fb0
(002602) [20:24:11] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(002602) [20:24:11] New background process: pid=2653, output=background
lxc-start: waydroid: network.c: netdev_configure_server_veth: 710 No such file or directory - Failed to attach "vethHljRxV" to bridge "waydroid0", bridge interface doesn't exist
lxc-start: waydroid: network.c: lxc_create_network_priv: 3413 No such file or directory - Failed to create network device
lxc-start: waydroid: start.c: lxc_spawn: 1843 Failed to create the network
lxc-start: waydroid: start.c: __lxc_start: 2074 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 306 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options
(002602) [20:24:11] waiting 10 seconds for container to start...
(002602) [20:24:12] waiting 9 seconds for container to start...
(002602) [20:24:13] waiting 8 seconds for container to start...
(002602) [20:24:14] waiting 7 seconds for container to start...
(002602) [20:24:15] waiting 6 seconds for container to start...
(002688) [20:24:15] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(002688) [20:24:15] *** output passed to waydroid stdout, not to this log ***
(002602) [20:24:16] waiting 5 seconds for container to start...
(002602) [20:24:17] waiting 4 seconds for container to start...
(002602) [20:24:18] waiting 3 seconds for container to start...
(002602) [20:24:19] waiting 2 seconds for container to start...
(002602) [20:24:20] waiting 1 seconds for container to start...
(002602) [20:24:21] ERROR: container failed to start
(002602) [20:24:21] See also: <https://github.com/waydroid>
(002602) [20:24:21] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 68, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 131, in start
    raise OSError("container failed to start")
OSError: container failed to start



```

**Comment by caiiiycuk** [comment]
Maybe it somehow related, I also can't setup docker:
```
INFO[2022-11-14T20:34:13.739905853Z] stopping event stream following graceful shutdown  error="<nil>" module=libcontainerd namespace=moby
failed to start daemon: Error initializing network controller: Error creating default "bridge" network: Failed to program NAT chain: Failed to inject DOCKER in PREROUTING chain: iptables failed: iptables --wait -t nat -A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER: iptables v1.8.4 (legacy): Couldn't load match `addrtype':No such file or directory
```

**Comment by caiiiycuk** [comment]
Okay, I fixed docker, the problem was with missed modules needed for iptables. And waydroid now reports that it finished starting:
```
[21:11:42] Android with user 0 is ready
```

But when I try to run `waydroid show-full-ui` nothing appears (both in software/gpu render modes), however there are a lot of errors in logcat, please check.
[log_new.zip](https://github.com/waydroid/waydroid/files/10007160/log_new.zip)

**Comment by aleasto** [comment]
Your wayland compositor is crashing? `Error sending request: Broken pipe`
So the android compositor crashes when committing a wayland surface

**Comment by caiiiycuk** [comment]
Nope I use sway, and it works fine all time.

**Comment by brianclinkenbeard** [comment]
I get the same broken pipe error in Sway running Debian.

**Comment by OpenOS-Project-Creator-Founder** [comment]
https://github.com/sickcodes/dock-droid

https://github.com/sickcodes/droid-native

https://github.com/remote-android/redroid-doc

**Comment by OpenOS-Project-Creator-Founder** [comment]
https://anbox-cloud.io/
