### ISSUE TITLE
Reduce audio latency

### ISSUE THREAD

**Issue by T2hhbmEK** [waydroid/waydroid#613]
I'm experiencing somewhat at least 300ms audio lagging using WayDroid. It would be better if WayDroid improves it. 

There was a hack to Anbox to fix similar issue. 

https://github.com/anbox/anbox/pull/1034

It fixed the issue by synchronizing the Android audio thread with the client. It requires changing some APIs and a rebuilding of the Android image. It may cause audio to stop working if the client application is running.

There maybe some better implementations. That remains to be discussed.

**Comment by Quackdoc** [comment]
alright, so I measures a round trip latency of 480~ms using jackdelay loop, this is certainly something that can be improved on for sure

**Comment by cobalt2727** [comment]
I'm also experiencing this, initially I just figured it was my Bluetooth headphones acting up but I got the same latency issues with my onboard speakers.

**Comment by NoEnd-yt** [comment]
I'm also experiencing this. The lag is especially annoying since I'm playing GDPS Editor 2.2 (Geometry Dash), which requires audio to sync (almost) perfectly.

**Comment by JamiKettunen** [comment]
Waydroid connects to the host Pulseaudio socket, someone with knowledge may look into https://github.com/waydroid/android_hardware_waydroid/tree/lineage-18.1/audio to figure out what's causing all the delay, perhaps playing with some environment variables from host (or even `system.img/init.environ.rc`) side like `PULSE_LATENCY_MSEC=60` would help too?

Some further reading for someone interested: https://juho.tykkala.fi/Pulseaudio-and-latency

**Comment by Quackdoc** [comment]
> Waydroid connects to the host Pulseaudio socket, someone with knowledge may look into https://github.com/waydroid/android_hardware_waydroid/tree/lineage-18.1/audio to figure out what's causing all the delay, perhaps playing with some environment variables from host (or even `system.img/init.environ.rc`) side like `PULSE_LATENCY_MSEC=60` would help too?
> 
> Some further reading for someone interested: https://juho.tykkala.fi/Pulseaudio-and-latency

IIRC I did try this to no success, but as I have no facilities to make test builds atm, I haven't really looked into it

**Comment by Quackdoc** [comment]
Seems like there are more victims of this I've had multiple people report that the audio latency makes games like sonolus (works with libhoudini) very much unenjoyable

**Comment by Quackdoc** [comment]
@JamiKettunen do you have any other potential variables? I was able to get the latency down to 350ms using that specific one, which brings it down to usable range for a decent number of folk (probably)

**Comment by T2hhbmEK** [comment]
Have been using redroid and scrcpy for a while. scrcpy started to support audio forwarding recently. Not yet checked WayDroid recently. IMO Audio latency is much lower. I prefer full screen emulation and redroid seems superior for my use case.

**Comment by Thesola10** [comment]
Setting `PIPEWIRE_LATENCY` and `PULSE_LATENCY_MSEC` to low values on `waydroid-container` doesn't work, maybe because it's an ALSA plugin.

**Comment by Quackdoc** [comment]
you can use a "Microphone to speaker" device and pipewire + `jackdelay` to get a physical number to check.

**Comment by Thesola10** [comment]
from what I can tell there's a slight improvement, but it's still very much unplayable. Not sure if `libhoudini` is inducing latency as well.

**Comment by ilhan-athn7** [comment]
Scrcpy seems to be able to forward audio with a little lower latency, but it still not feels like real-time audio.
I use these command to get sound from scrcpy;
`scrcpy --no-video --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'`

Additionally `--audio-buffer=value` and `--audio-bit-rate=value` arguments are available.

**Comment by Quackdoc** [comment]
> Scrcpy seems to be able to forward audio with a little lower latency, but it still not feels like real-time audio. I use these command to get sound from scrcpy; `scrcpy --no-video --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'`
> 
> Additionally `--audio-buffer=value` and `--audio-bit-rate=value` arguments are available.

any chance you could check the delay? I use a microphone to speaker app and jack_delay to test typically, I don't have time atm

**Comment by ilhan-athn7** [comment]
> > Scrcpy seems to be able to forward audio with a little lower latency, but it still not feels like real-time audio. I use these command to get sound from scrcpy; `scrcpy --no-video --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'`
> > Additionally `--audio-buffer=value` and `--audio-bit-rate=value` arguments are available.
> 
> any chance you could check the delay? I use a microphone to speaker app and jack_delay to test typically, I don't have time atm

I could not figure out how to use jack_delay to measure audio latency of waydroid.

**Comment by SteelT1** [comment]
> Scrcpy seems to be able to forward audio with a little lower latency, but it still not feels like real-time audio. I use these command to get sound from scrcpy; `scrcpy --no-video --audio-codec=aac --audio-encoder='OMX.google.aac.encoder'`
> 
> Additionally `--audio-buffer=value` and `--audio-bit-rate=value` arguments are available.

This method doesn't seem to work anymore, as trying to run that command just fails with this.
```
[server] ERROR: Controller error
java.io.IOException: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at com.genymobile.scrcpy.control.UhidManager.open(UhidManager.java:69)
        at com.genymobile.scrcpy.control.Controller.handleEvent(Controller.java:213)
        at com.genymobile.scrcpy.control.Controller.control(Controller.java:102)
        at com.genymobile.scrcpy.control.Controller.lambda$start$0$com-genymobile-scrcpy-control-Controller(Controller.java:110)
        at com.genymobile.scrcpy.control.Controller$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
        at java.lang.Thread.run(Thread.java:923)
Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at android.system.Os.open(Os.java:412)
        at com.genymobile.scrcpy.control.UhidManager.open(UhidManager.java:52)
        ... 5 more
INFO: Renderer: opengl
INFO: OpenGL version: 4.6 (Compatibility Profile) Mesa 24.2.6-arch1.1
INFO: Trilinear filtering disabled
WARN: Device disconnected
ERROR: Demuxer 'audio': stream disabled due to connection error
```

**Comment by ilhan-athn7** [comment]
@SteelT1 did you try previous scrcpy version?

**Comment by SteelT1** [comment]
> @SteelT1 did you try previous scrcpy version?

It seems like scrcpy v2.4 is the last version that the method works on, at least for me.

**Comment by GerardoBaeza** [comment]
are there any updates on this? There's not much info out about this issue anywhere

**Comment by SteelT1** [comment]
> > @SteelT1 did you try previous scrcpy version?
> 
> It seems like scrcpy v2.4 is the last version that the method works on, at least for me.

Follow up to this: It also works with scrcpy v2.5 or later if `--no-control` is passed to the command line args in addition to `--no-video` (scrcpy v3.0 was released recently though, making that be the default behavior now if video playback is disabled)

**Comment by aleasto** [comment]
This was significantly improved in recent updates
