### ISSUE TITLE
waydroid doesn't exist

### ISSUE THREAD

**Issue by mizzunet** [waydroid/waydroid#62]
WayDroid does not start. Here are some relevent data,
`sudo waydroid init`
```
[11:52:15] Already initialized
```

`sudo systemctl status waydroid-container.service`
```
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/lib/systemd/system/waydroid-container.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2021-09-21 11:51:36 IST; 2min 13s ago
    Process: 4500 ExecStart=/usr/bin/waydroid container start (code=exited, status=0/SUCCESS)
    Process: 4503 ExecStop=/usr/bin/waydroid container stop (code=exited, status=1/FAILURE)
    Process: 4510 ExecStopPost=/usr/bin/waydroid session stop (code=exited, status=0/SUCCESS)
   Main PID: 4500 (code=exited, status=0/SUCCESS)
        CPU: 395ms

Sep 21 11:51:36 missu-aspiree5571 sudo[4508]:     root : PWD=/ ; USER=root ; COMMAND=/usr/bin/lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
Sep 21 11:51:36 missu-aspiree5571 sudo[4508]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Sep 21 11:51:36 missu-aspiree5571 sudo[4508]: pam_unix(sudo:session): session closed for user root
Sep 21 11:51:36 missu-aspiree5571 waydroid[4503]: [11:51:36] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
Sep 21 11:51:36 missu-aspiree5571 waydroid[4503]: [11:51:36] ERROR: Command failed: % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
Sep 21 11:51:36 missu-aspiree5571 waydroid[4503]: [11:51:36] See also: <https://github.com/waydroid>
Sep 21 11:51:36 missu-aspiree5571 waydroid[4503]: Run 'waydroid log' for details.
Sep 21 11:51:36 missu-aspiree5571 systemd[1]: waydroid-container.service: Control process exited, code=exited, status=1/FAILURE
Sep 21 11:51:36 missu-aspiree5571 waydroid[4510]: [11:51:36] WayDroid session is not started
Sep 21 11:51:36 missu-aspiree5571 systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
```
`waydroid session start`
```[11:55:29] XDG Session is not "wayland"```

In another shell,
`waydroid status`
```Session:        RUNNING
Container:      STOPPED
Vendor type:    MAINLINE
Session user:   missu(1000)
Wayland display:        None
```
` sudo waydroid container start`
```
waydroid doesn't exist
[11:56:00] WayDroid container is
```

Distro Debian 11
Kernel 5.14.6-xanmod1-cacule

Let me know if anything else required

**Comment by philmmanjaro** [comment]
Well, you need a **Wayland** session. Seems you're still running **X11** on your end.

**Comment by Id2ndR** [comment]
You may check:
  * the result of `env | grep XDG_SESSION` (should display **XDG_SESSION_TYPE=wayland**)
  * the journal of the container unit `journalctl -u waydroid-container`
  * the log files `/var/lib/waydroid/waydroid.log` and `/var/lib/waydroid/lxc/waydroid/waydroid.log`

**Comment by mizzunet** [comment]
@Id2ndR  
1. It is
```
-- Journal begins at Wed 2021-09-22 23:32:16 IST, ends at Wed 2021-09-22 23:37:25 IST. --
Sep 22 23:32:25 debian systemd[1]: Started Waydroid Container.
Sep 22 23:32:35 debian sudo[1339]:     root : PWD=/ ; USER=root ; COMMAND=/usr/bin/lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
Sep 22 23:32:35 debian sudo[1339]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Sep 22 23:32:35 debian waydroid[1341]: waydroid doesn't exist
Sep 22 23:32:35 debian sudo[1339]: pam_unix(sudo:session): session closed for user root
Sep 22 23:32:35 debian waydroid[1055]: [23:32:35] WayDroid container is
Sep 22 23:32:35 debian sudo[1343]:     root : PWD=/ ; USER=root ; COMMAND=/usr/bin/lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
Sep 22 23:32:35 debian sudo[1343]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Sep 22 23:32:35 debian waydroid[1344]: waydroid doesn't exist
Sep 22 23:32:35 debian sudo[1343]: pam_unix(sudo:session): session closed for user root
Sep 22 23:32:35 debian sudo[1347]:     root : PWD=/ ; USER=root ; COMMAND=/usr/bin/lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
Sep 22 23:32:35 debian sudo[1347]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Sep 22 23:32:35 debian sudo[1347]: pam_unix(sudo:session): session closed for user root
Sep 22 23:32:35 debian waydroid[1342]: [23:32:35] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
Sep 22 23:32:35 debian waydroid[1342]: [23:32:35] ERROR: Command failed: % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
Sep 22 23:32:35 debian waydroid[1342]: [23:32:35] See also: <https://github.com/waydroid>
Sep 22 23:32:35 debian waydroid[1342]: Run 'waydroid log' for details.
Sep 22 23:32:35 debian systemd[1]: waydroid-container.service: Control process exited, code=exited, status=1/FAILURE
Sep 22 23:32:36 debian waydroid[1353]: [23:32:36] WayDroid session is not started
Sep 22 23:32:36 debian systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
```
3.
```(001055) [23:32:35] WayDroid container is 
(001342) [23:32:35] % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-stop: waydroid: tools/lxc_stop.c: main: 170 waydroid is not running
(001342) [23:32:35] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(001342) [23:32:35] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(001342) [23:32:35] ERROR: Command failed: % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
(001342) [23:32:35] See also: <https://github.com/waydroid>
(001342) [23:32:35] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 66, in main
    actions.container_manager.stop(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 185, in stop
    helpers.lxc.stop(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 240, in stop
    tools.helpers.run.root(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 77, in root
    return user(args, cmd, working_dir, output, output_return, check, env,
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k

(001353) [23:32:36] WayDroid session is not started
(007221) [23:34:35] WayDroid container is 
```

**Comment by severin-lemaignan** [comment]
Same issue here

**Comment by Id2ndR** [comment]
As explained before, **Way**droid is an application that required **Wayland** to work (see [prerequites](https://docs.waydro.id/usage/install-on-desktops#prerequisites) on the documentation). This means that it does not work with **X11**, so this is the expected behavior.

**Comment by Id2ndR** [comment]
However the python code may be improved to handle case where the waydroid container failed to start or stop, for whatever reason; this would avoid the message *WayDroid container is* follow by nothing (blank).

**Comment by severin-lemaignan** [comment]
Just to clarify: I encounter the exact same issue, while *being on wayland*:
```
$ env | grep XDG_SESSION
XDG_SESSION_DESKTOP=gnome
XDG_SESSION_TYPE=wayland
XDG_SESSION_CLASS=user
```
```
$ sudo systemctl start waydroid-container
$ sudo waydroid container start
waydroid doesn't exist
[23:49:00] WayDroid container is 
[23:49:00] Run waydroid container -h for usage information.
$ journalctl -u waydroid-container
Sep 22 23:47:25 electre systemd[1]: Started Waydroid Container.
Sep 22 23:47:25 electre sudo[64174]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/lxc-info -P /var/lib/waydroid/lxc -n way>
Sep 22 23:47:25 electre sudo[64174]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 22 23:47:25 electre waydroid[64175]: waydroid doesn't exist
Sep 22 23:47:25 electre sudo[64174]: pam_unix(sudo:session): session closed for user root
Sep 22 23:47:25 electre waydroid[64159]: [23:47:25] WayDroid container is
Sep 22 23:47:25 electre waydroid[64159]: [23:47:25] Run waydroid container -h for usage information.
Sep 22 23:47:25 electre sudo[64177]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/lxc-info -P /var/lib/waydroid/lxc -n way>
Sep 22 23:47:25 electre sudo[64177]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 22 23:47:25 electre waydroid[64178]: waydroid doesn't exist
Sep 22 23:47:25 electre sudo[64177]: pam_unix(sudo:session): session closed for user root
Sep 22 23:47:25 electre sudo[64179]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=validate
Sep 22 23:47:25 electre sudo[64181]:     root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/bin/lxc-stop -P /var/lib/waydroid/lxc -n way>
Sep 22 23:47:25 electre sudo[64181]: pam_unix(sudo:session): session opened for user root by (uid=0)
Sep 22 23:47:25 electre sudo[64181]: pam_unix(sudo:session): session closed for user root
Sep 22 23:47:25 electre waydroid[64176]: [23:47:25] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydr>
Sep 22 23:47:25 electre waydroid[64176]: [23:47:25] ERROR: Command failed: % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
Sep 22 23:47:25 electre waydroid[64176]: [23:47:25] See also: <https://github.com/waydroid>
Sep 22 23:47:25 electre waydroid[64176]: Run 'waydroid log' for details.
Sep 22 23:47:25 electre systemd[1]: waydroid-container.service: Control process exited, code=exited, status=1/FAILURE
Sep 22 23:47:25 electre waydroid[64183]: [23:47:25] WayDroid session is not started
Sep 22 23:47:25 electre systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
```

and more interestingly:
```
$ waydroid log
(064159) [23:47:25] WayDroid container is 
(064159) [23:47:25] Run waydroid container -h for usage information.
(064176) [23:47:25] % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-stop: waydroid: tools/lxc_stop.c: main: 170 waydroid is not running
(064176) [23:47:25] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(064176) [23:47:25] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/tools.log
(064176) [23:47:25] ERROR: Command failed: % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
(064176) [23:47:25] See also: <https://github.com/waydroid>
(064176) [23:47:25] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 65, in main
    actions.container_manager.stop(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 185, in stop
    helpers.lxc.stop(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 240, in stop
    tools.helpers.run.root(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 77, in root
    return user(args, cmd, working_dir, output, output_return, check, env,
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k

(064183) [23:47:25] WayDroid session is not started
(064213) [23:48:17] % tail -n 60 -F /var/lib/waydroid/tools.log
(064213) [23:48:17] *** output passed to waydroid stdout, not to this log ***
```

**Comment by Id2ndR** [comment]
When working (for me using Manjaro), the command `sudo lxc-ls -P /var/lib/waydroid/lxc` returns *waydroid*.

If it's not, maybe you can:
1. try again with `sudo waydroid init -f`
2. or, clean up everything and reinstalling using [this procedure](https://docs.waydro.id/usage/install-on-desktops#reinstalling-waydroid).

**Comment by Joecowboy** [comment]
This is a work in progress.  Needs work for this issue,  right now  you have to press the icon twice to launch and it will reset the stop the waydroid container.  Change the extension from txt to py.  Modded files for waydroid to restart if exited on desktop, you will have to create a password.txt file in /home/.waydroid/password.txt :
/usr/lib/waydroid/tools/init.py
/usr/lib/waydroid/tools/actions/container_manager.py
/usr/lib/waydroid/tools/helpers/run.py
/usr/lib/waydroid/tools/helpers/run_core.py
[run_core.txt](https://github.com/waydroid/waydroid/files/7318293/run_core.txt)
[__init__.txt](https://github.com/waydroid/waydroid/files/7318294/__init__.txt)
[container_manager.txt](https://github.com/waydroid/waydroid/files/7318295/container_manager.txt)
[run.txt](https://github.com/waydroid/waydroid/files/7318296/run.txt)

**Comment by Grouvya** [comment]
sudo waydroid init -f
 Missing system or vendor on preinstalled images dir, fallback to default
[02:27:43] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1
[02:27:43] See also: <https://github.com/waydroid>
how to fix?

**Comment by baermathias** [comment]
> sudo waydroid init -f Missing system or vendor on preinstalled images dir, fallback to default [02:27:43] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1 [02:27:43] See also: https://github.com/waydroid how to fix?

Could you fix that? I have the same issue.

**Comment by tazihad** [comment]
> sudo waydroid init -f Missing system or vendor on preinstalled images dir, fallback to default [02:27:43] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1 [02:27:43] See also: https://github.com/waydroid how to fix?

For anyone getting failed to get system OTA. This happens after cleaning. You need to reinstall images.
launch using `waydroid first-launch`. Then put System OTA and Vendor OTA.

**Comment by jmevel** [comment]
> > sudo waydroid init -f Missing system or vendor on preinstalled images dir, fallback to default [02:27:43] ERROR: Failed to get system OTA channel: /lineage/waydroid_x86_64/VANILLA.json, error: -1 [02:27:43] See also: https://github.com/waydroid how to fix?
> 
> For anyone getting failed to get system OTA. This happens after cleaning. You need to reinstall images. launch using `waydroid first-launch`. Then put System OTA and Vendor OTA.

Thanks!!! This is the command I've been looking for for an hour!
