### ISSUE TITLE
Waydroid fails to start

### ISSUE THREAD

**Issue by sidevesh** [waydroid/waydroid#643]
Waydroid fails to start, here's the logs:
```
5.0.1
(3220640) [18:01:46] % mkdir -p /var/lib/waydroid/lxc/waydroid
(3220640) [18:01:46] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_2" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(3220640) [18:01:46] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(3220640) [18:01:46] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(3220640) [18:01:46] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(3220961) [18:01:54] % modprobe -q ashmem_linux
(3220961) [18:01:54] % chmod 666 -R /dev/anbox-binder
(3220961) [18:01:54] % chmod 666 -R /dev/anbox-vndbinder
(3220961) [18:01:54] % chmod 666 -R /dev/anbox-hwbinder
(3220961) [18:01:54] Container manager is waiting for session to load
(3221478) [18:02:05] Starting waydroid session
(3221478) [18:02:05] Save session config: /var/lib/waydroid/session.cfg
(3221478) [18:02:05] UserMonitor service is not even started
(3221478) [18:02:05] Clipboard service is not even started
(3220961) [18:02:05] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables v1.8.8 (legacy): can't initialize iptables table `mangle': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
Failed to setup waydroid-net.
Warning: Extension CHECKSUM revision 0 not supported, missing kernel module?
iptables v1.8.8 (legacy): can't initialize iptables table `mangle': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
(3220961) [18:02:05] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
mount: /var/lib/waydroid/rootfs: mount failed: Operation not permitted.
(3220961) [18:02:05] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(3220961) [18:02:05] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(3220961) [18:02:05] ERROR: Command failed: % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(3220961) [18:02:05] See also: <https://github.com/waydroid>
(3220961) [18:02:05] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 68, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 97, in start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"])
  File "/usr/lib/waydroid/tools/helpers/images.py", line 131, in mount_rootfs
    helpers.mount.mount(args, images_dir + "/system.img",
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 131, in mount
    tools.helpers.run.user(args, ["mount", source, destination])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs

(3221544) [18:02:05] UserMonitor service is not even started
(3221544) [18:02:05] Clipboard service is not even started
(3221478) [18:02:06] UserMonitor service is not even started
(3221478) [18:02:06] Clipboard service is not even started
(3221707) [18:02:10] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(3221707) [18:02:10] *** output passed to waydroid stdout, not to this log ***
(3224170) [18:03:32] Save session config: /var/lib/waydroid/session.cfg
(3224170) [18:03:32] UserMonitor service is not even started
(3224170) [18:03:32] Clipboard service is not even started
(3224170) [18:04:53] UserMonitor service is not even started
(3224170) [18:04:53] Clipboard service is not even started
(3230370) [18:06:53] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(3230370) [18:06:53] *** output passed to waydroid stdout, not to this log ***
```

I am running the latest available GAPPS image along with he latest waydroid package from arch on Linux 6.0.11-zen1-1-zen.

**Comment by sidevesh** [comment]
Based on a discussion on telegram group I did try setting LXC_USE_NFT= back to true, it was false in my case due to a conflict with docker,
still does not work.

**Comment by sidevesh** [comment]
Just realised that this started happening for me too on Linux 6.1.1, reverting back to older version fixed the issue.

**Comment by cniw** [comment]
Your logs clearly says, problem with `mount` command. I guess You've just did updated your system to new kernel but didn't restart your PC yet.

I tested and it's works fine with Arch Linux 6.1.1-zen1-1-zen, so please try it again.

**Comment by solitudealma** [comment]
> Your logs clearly says, problem with `mount` command. I guess You've just did updated your system to new kernel but didn't restart your PC yet.
> 
> I tested and it's works fine with Arch Linux 6.1.1-zen1-1-zen, so please try it again.

useful

**Comment by lm2lm2** [comment]
RuntimeError: Command failed: % mount -o ro /var/lib/waydroid/images/
system.img /var/lib/waydroid/rootfs

honestly, on my side i went up to solve this error by :
removing any .img file (vendor, system) related to waydroid
reinstalling waydroid
then -f -s GAPPS /path/to/waydroidimages
then show-full-ui
