### ISSUE TITLE
Waydroid UI is glitched

### ISSUE THREAD

**Issue by niksingh710** [waydroid/waydroid#669]
**Describe the bug**
`waydroid show-full-ui` is glitched 

**Screenshots**
![image](https://user-images.githubusercontent.com/60490474/210194405-fd9e798c-9891-4da8-9329-a8e82a99abb9.png)

**General information (please complete the following information):**
 - Waydroid tools Version 1.3.3 
 - Waydroid Images Version lineage-18.1-20221231-MAINLINE-waydroid_x86_64

**Desktop (please complete the following information):**
 - OS: Arch Linux x64
 - GPU: AMD ATI Radeon R7 M260/M265 / M340/M360 / M440/M445 / 530/535 / 620/625 Mobile
 - IGPU: Intel CometLake-U GT2 [UHD Graphics] 
 - Kernel version: 6.1.1-zen1-1-zen
 - Host mesa version: 22.3.1-2
 - Desktop: Hyprland 

**Additional context**

**Logs (please upload as file)**
 - Prop file, located on `/var/lib/waydroid/waydroid_base.prop`
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=radeon
ro.hardware.camera=v4l2
ro.opengles.version=196608
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/GAPPS.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.3.3
ro.vndk.lite=true
```

 - Output of `waydroid log`: 
 ```
(3856033) [09:29:20] % mkdir -p /var/lib/waydroid/data
(3856033) [09:29:20] % mount -o bind /home/niksingh710/.local/share/waydroid/data /var/lib/waydroid/data
(3856033) [09:29:20] % chmod 777 -R /dev/dri
(3856033) [09:29:20] % chmod 777 -R /dev/fb0
(3856033) [09:29:20] % chmod 777 -R /dev/video1
(3856033) [09:29:20] % chmod 777 -R /dev/video0
(3856033) [09:29:20] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(3856033) [09:29:20] New background process: pid=3857392, output=background
lxc-start: waydroid: ../src/lxc/utils.c: safe_mount: 1221 No such file or directory - Failed to mount "/dev/ashmem" onto "/usr/lib/lxc/rootfs/dev/ashmem"
(3856033) [09:29:21] Save session config: /var/lib/waydroid/session.cfg
(3857254) [09:29:31] waydroidusermonitor: Received transaction: 1
(3857254) [09:29:31] Android with user 0 is ready
(3870985) [09:30:48] ERROR: Action "shell" needs root access
(3870985) [09:30:48] See also: <https://github.com/waydroid>
(3870985) [09:30:48] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 105, in main
    actionNeedRoot(args.action)
  File "/usr/lib/waydroid/tools/__init__.py", line 18, in actionNeedRoot
    raise RuntimeError(
RuntimeError: Action "shell" needs root access

(3871439) [09:30:52] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(3871439) [09:30:52] *** output passed to waydroid stdout, not to this log ***
(3856033) [09:31:32] waydroidhardware: Received transaction: 3
(3856033) [09:31:32] % lxc-freeze -P /var/lib/waydroid/lxc -n waydroid
(3856033) [09:31:32] Save session config: /var/lib/waydroid/session.cfg
(3875141) [09:31:34] Save session config: /var/lib/waydroid/session.cfg
(3856033) [09:31:35] Save session config: /var/lib/waydroid/session.cfg
(3856033) [09:31:35] % lxc-unfreeze -P /var/lib/waydroid/lxc -n waydroid
(3856033) [09:31:35] Save session config: /var/lib/waydroid/session.cfg
(3856033) [09:33:18] waydroidhardware: Received transaction: 3
(3856033) [09:33:18] % lxc-freeze -P /var/lib/waydroid/lxc -n waydroid
(3856033) [09:33:18] Save session config: /var/lib/waydroid/session.cfg
(3895872) [09:34:43] Save session config: /var/lib/waydroid/session.cfg
(3856033) [09:34:43] Save session config: /var/lib/waydroid/session.cfg
(3856033) [09:34:43] % lxc-unfreeze -P /var/lib/waydroid/lxc -n waydroid
(3856033) [09:34:43] Save session config: /var/lib/waydroid/session.cfg
(3856033) [09:37:23] waydroidhardware: Received transaction: 3
(3856033) [09:37:23] % lxc-freeze -P /var/lib/waydroid/lxc -n waydroid
(3856033) [09:37:23] Save session config: /var/lib/waydroid/session.cfg
(3913847) [09:37:27] Save session config: /var/lib/waydroid/session.cfg
(3856033) [09:37:27] Save session config: /var/lib/waydroid/session.cfg
(3856033) [09:37:27] % lxc-unfreeze -P /var/lib/waydroid/lxc -n waydroid
(3856033) [09:37:27] Save session config: /var/lib/waydroid/session.cfg
(3856033) [09:38:31] waydroidhardware: Received transaction: 3
(3856033) [09:38:31] % lxc-freeze -P /var/lib/waydroid/lxc -n waydroid
(3856033) [09:38:31] Save session config: /var/lib/waydroid/session.cfg
(3920901) [09:38:37] Save session config: /var/lib/waydroid/session.cfg
(3856033) [09:38:38] Save session config: /var/lib/waydroid/session.cfg
(3856033) [09:38:38] % lxc-unfreeze -P /var/lib/waydroid/lxc -n waydroid
(3856033) [09:38:38] Save session config: /var/lib/waydroid/session.cfg
(3856033) [09:39:42] waydroidhardware: Received transaction: 3
(3856033) [09:39:42] % lxc-freeze -P /var/lib/waydroid/lxc -n waydroid
(3856033) [09:39:42] Save session config: /var/lib/waydroid/session.cfg
(3937434) [09:41:11] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(3937434) [09:41:11] *** output passed to waydroid stdout, not to this log ***
(3939690) [09:41:37] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(3939690) [09:41:37] *** output passed to waydroid stdout, not to this log ***
(3940738) [09:41:49] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(3940738) [09:41:49] *** output passed to waydroid stdout, not to this log ***
```
 - *Full* (not partially) Output of `waydroid logcat` from the beginning of starting waydroid services
 ```
[09:42:26] WayDroid container is FROZEN
```

**Comment by Hi-Angel** [comment]
Same here. In fact, it's not just `show-full-ui`, but anything. E.g. trying run a `waydroid app launch com.android.contacts` results in the same glitched interface. I also tried running the compositor with `LIBGL_ALWAYS_SOFTWARE=1` but that changed nothing.

**Comment by Hi-Angel** [comment]
I found a work around: if you edit `/var/lib/waydroid/waydroid_base.prop` to have these values *(instead of the default `gbm` and `mesa`)*:

```
ro.hardware.gralloc=default
ro.hardware.egl=swiftshader
```

then this starts working. Funnily enough, this makes use of software rendering, even though in the previous post sw rendering didn't work 🤷‍♂️

**Comment by niksingh710** [comment]
> I found a work around: if you edit `/var/lib/waydroid/waydroid_base.prop` to have these values _(instead of the default `gbm` and `mesa`)_:
> 
> ```
> ro.hardware.gralloc=default
> ro.hardware.egl=swiftshader
> ```
> 
> then this starts working. Funnily enough, this makes use of software rendering, even though in the previous post sw rendering didn't work man_shrugging

Did work mate Thanks.

**Comment by Quackdoc** [comment]
this is a known issue with multiple gpus, currently you can run [waydroid-choose-gpu.sh](https://raw.githubusercontent.com/Quackdoc/waydroid-scripts/main/waydroid-choose-gpu.sh) to select what gpu waydroid should use.

**Comment by amajust** [comment]
> I found a work around: if you edit `/var/lib/waydroid/waydroid_base.prop` to have these values _(instead of the default `gbm` and `mesa`)_:
> 
> ```
> ro.hardware.gralloc=default
> ro.hardware.egl=swiftshader
> ```
> 
> then this starts working. Funnily enough, this makes use of software rendering, even though in the previous post sw rendering didn't work man_shrugging

this happen to me also on arch linux using sway and dual GPU with AMD 6500XT
If everyone got this problem just follow this and after that restart your waydroid session. It will work again

**Comment by amajust** [comment]
> this is a known issue with multiple gpus, currently you can run [waydroid-choose-gpu.sh](https://raw.githubusercontent.com/Quackdoc/waydroid-scripts/main/waydroid-choose-gpu.sh) to select what gpu waydroid should use.

i try your script, but its still the same glitching, anyway thx for that script

**Comment by niksingh710** [comment]
btw anyone found a way to get it working with hardware rendering?

**Comment by CiscoDeTours** [comment]
This problem is present while using my dGPU (RX 6600M). https://github.com/waydroid/waydroid/issues/669#issuecomment-1372889917 was helpful enough to solve what the script unfortunately couldn't.

**Comment by 4180** [comment]
2 years now, has anyone found how to get it working with hardware rendering?

I recently upgraded with waydroid-updater on it and now i have this issue, it didn't do it before i upgraded... why?

**Comment by foinf** [comment]
> this is a known issue with multiple gpus, currently you can run [waydroid-choose-gpu.sh](https://raw.githubusercontent.com/Quackdoc/waydroid-scripts/main/waydroid-choose-gpu.sh) to select what gpu waydroid should use.

I would like to add that I had to modify this script to get waydroid to make it work on my hybrid (Radeon 5000 and Nvidia RTX 3060 laptop).

Either modify the script or directly edit `/var/lib/waydroid/lxc/waydroid/` file such that it changes 

`lxc.mount.entry = /dev/dri/$card dev/dri/card0 none bind,create=file,optional 0 0
lxc.mount.entry = /dev/dri/$rendernode dev/dri/renderD128 none bind,create=file,optional 0 0`

to 

`lxc.mount.entry = /dev/dri/$card dev/dri/$card none bind,create=file,optional 0 0
lxc.mount.entry = /dev/dri/$rendernode dev/dri/$rendernode none bind,create=file,optional 0 0`

And it started to work.

**Comment by alej0varas** [comment]
Maybe it's related to #2160 where the solution that worked for me is https://github.com/waydroid/waydroid/issues/2160#issuecomment-3767826178
