### ISSUE TITLE
NameError: name 're' is not defined

### ISSUE THREAD

**Issue by ardian923** [waydroid/waydroid#707]
When I type : waydroid show-full-ui
waydroid was not starting with the message : NameError: name 're' is not defined

This is the waydroid log 
======================
(000599) [05:43:43] % mount -o ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(008867) [05:43:43] org.freedesktop.DBus.Python.NameError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 27, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 140, in do_start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"], session)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 142, in mount_rootfs
    helpers.mount.mount_overlay(args, [tools.config.defaults["overlay"],
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 168, in mount_overlay
    if kernel_version() >= versiontuple("4.17"):
  File "/usr/lib/waydroid/tools/helpers/version.py", line 7, in kernel_version
    return tuple(map(int, re.match(r"(\d+)\.(\d+)", os.uname().release).groups()))
NameError: name 're' is not defined

(008867) [05:43:43] NameError: name 're' is not defined
===================================

**Comment by ardian923** [comment]
I opened version.py and add line : import re

still not working

**Comment by aleasto** [comment]
Force update waydroid by `apt remove` and installing again
