### ISSUE TITLE
SELinux blocks mkdir for user data

### ISSUE THREAD

**Issue by Doomsdayrs** [waydroid/waydroid#735]
**Describe the bug**
SELinux is blocking `mkdir` for user data. 
Because of this, there is no way to launch waydroid.

**General information (please complete the following information):**
 - Waydroid tools Version: 1.3.4
 - Waydroid Images Version: 2023-02-02

**Desktop (please complete the following information):**
 - OS: Fedora
 - GPU: AMD
 - Kernel version: 6.1.8-200.fc37.x86_64
 - Host mesa version: 22.3.4
 - Desktop: GNOME 43.2

**Logs (please upload as file)**
 ### Prop file
 ```
 cat /var/lib/waydroid/waydroid.prop 
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=radeon
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.system_ota=https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
waydroid.vendor_ota=https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
waydroid.tools_version=1.3.4
ro.vndk.lite=true
waydroid.host.user=doomsdayrs
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-0
waydroid.stub_sensors_hal=1
```
 - Output of `waydroid log`
 ```
 (037372) [18:03:56] % modprobe -q ashmem_linux
(037372) [18:03:56] % modprobe -q ashmem_linux
(037372) [18:03:56] % modprobe -q ashmem_linux
(037372) [18:03:56] % chmod 666 -R /dev/binder
(037372) [18:03:56] % chmod 666 -R /dev/binder
(037372) [18:03:56] % chmod 666 -R /dev/binder
(037372) [18:03:56] % chmod 666 -R /dev/vndbinder
(037372) [18:03:56] % chmod 666 -R /dev/vndbinder
(037372) [18:03:56] % chmod 666 -R /dev/vndbinder
(037372) [18:03:56] % chmod 666 -R /dev/hwbinder
(037372) [18:03:56] % chmod 666 -R /dev/hwbinder
(037372) [18:03:56] % chmod 666 -R /dev/hwbinder
(037372) [18:03:56] Container manager is waiting for session to load
(037372) [18:03:56] Container manager is waiting for session to load
(037372) [18:03:56] Container manager is waiting for session to load
(037716) [18:04:11] Starting waydroid session
(037716) [18:04:11] Starting waydroid session
(037716) [18:04:11] Starting waydroid session
(037716) [18:04:11] Save session config: /var/lib/waydroid/session.cfg
(037716) [18:04:11] Save session config: /var/lib/waydroid/session.cfg
(037716) [18:04:11] Save session config: /var/lib/waydroid/session.cfg
(037716) [18:04:11] UserMonitor service is not even started
(037716) [18:04:11] UserMonitor service is not even started
(037716) [18:04:11] UserMonitor service is not even started
(037716) [18:04:11] Clipboard service is not even started
(037716) [18:04:11] Clipboard service is not even started
(037716) [18:04:11] Clipboard service is not even started
(037372) [18:04:11] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(037372) [18:04:11] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
(037372) [18:04:11] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
vnic is waydroid0
vnic is waydroid0
which: no iptables-legacy in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
which: no iptables-legacy in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
which: no iptables-legacy in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
which: no ip6tables-legacy in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
which: no ip6tables-legacy in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
which: no ip6tables-legacy in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
waydroid-net is already running
waydroid-net is already running
waydroid-net is already running
(037372) [18:04:11] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(037372) [18:04:11] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(037372) [18:04:11] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(037372) [18:04:11] % umount /var/lib/waydroid/rootfs/vendor
(037372) [18:04:11] % umount /var/lib/waydroid/rootfs/vendor
(037372) [18:04:11] % umount /var/lib/waydroid/rootfs/vendor
(037372) [18:04:11] % umount /var/lib/waydroid/rootfs
(037372) [18:04:11] % umount /var/lib/waydroid/rootfs
(037372) [18:04:11] % umount /var/lib/waydroid/rootfs
(037372) [18:04:11] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0" /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(037372) [18:04:11] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0" /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(037372) [18:04:11] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0" /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(037372) [18:04:11] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(037372) [18:04:11] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(037372) [18:04:11] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(037372) [18:04:11] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0" /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(037372) [18:04:11] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0" /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(037372) [18:04:11] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0" /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(037372) [18:04:11] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(037372) [18:04:11] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(037372) [18:04:11] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(037372) [18:04:11] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(037372) [18:04:11] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(037372) [18:04:11] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(037372) [18:04:11] Save config: /var/lib/waydroid/waydroid.cfg
(037372) [18:04:11] Save config: /var/lib/waydroid/waydroid.cfg
(037372) [18:04:11] Save config: /var/lib/waydroid/waydroid.cfg
(037372) [18:04:11] % mkdir -p /home/doomsdayrs/.local/share/waydroid/data
(037372) [18:04:11] % mkdir -p /home/doomsdayrs/.local/share/waydroid/data
(037372) [18:04:11] % mkdir -p /home/doomsdayrs/.local/share/waydroid/data
mkdir: cannot create directory ‘/home/doomsdayrs’: Permission denied
mkdir: cannot create directory ‘/home/doomsdayrs’: Permission denied
mkdir: cannot create directory ‘/home/doomsdayrs’: Permission denied
(037372) [18:04:11] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(037372) [18:04:11] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(037372) [18:04:11] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(037372) [18:04:11] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(037372) [18:04:11] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(037372) [18:04:11] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(037372) [18:04:11] ERROR: Command failed: % mkdir -p /home/doomsdayrs/.local/share/waydroid/data
(037372) [18:04:11] ERROR: Command failed: % mkdir -p /home/doomsdayrs/.local/share/waydroid/data
(037372) [18:04:11] ERROR: Command failed: % mkdir -p /home/doomsdayrs/.local/share/waydroid/data
(037372) [18:04:11] See also: <https://github.com/waydroid>
(037372) [18:04:11] See also: <https://github.com/waydroid>
(037372) [18:04:11] See also: <https://github.com/waydroid>
(037372) [18:04:11] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 68, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 102, in start
    helpers.mount.bind(args, session_cfg["session"]["waydroid_data"],
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 40, in bind
    tools.helpers.run.user(args, ["mkdir", "-p", path])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mkdir -p /home/doomsdayrs/.local/share/waydroid/data

(037372) [18:04:11] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 68, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 102, in start
    helpers.mount.bind(args, session_cfg["session"]["waydroid_data"],
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 40, in bind
    tools.helpers.run.user(args, ["mkdir", "-p", path])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mkdir -p /home/doomsdayrs/.local/share/waydroid/data

(037372) [18:04:11] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 68, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 102, in start
    helpers.mount.bind(args, session_cfg["session"]["waydroid_data"],
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 40, in bind
    tools.helpers.run.user(args, ["mkdir", "-p", path])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mkdir -p /home/doomsdayrs/.local/share/waydroid/data

(037766) [18:04:11] UserMonitor service is not even started
(037766) [18:04:11] UserMonitor service is not even started
(037766) [18:04:11] UserMonitor service is not even started
(037766) [18:04:11] Clipboard service is not even started
(037766) [18:04:11] Clipboard service is not even started
(037766) [18:04:11] Clipboard service is not even started
(037716) [18:04:12] UserMonitor service is not even started
(037716) [18:04:12] UserMonitor service is not even started
(037716) [18:04:12] UserMonitor service is not even started
(037716) [18:04:12] Clipboard service is not even started
(037716) [18:04:12] Clipboard service is not even started
(037716) [18:04:12] Clipboard service is not even starte
```

**Comment by aleasto** [comment]
* We don't provide selinux rules upstream, fedora packages their own
* Your system has mislabeled home data; use restorecon
