### ISSUE TITLE
 waydroid-container.service: Failed with result 'exit-code'.

### ISSUE THREAD

**Issue by disdi** [waydroid/waydroid#79]
disdi@disdi-Precision-5540:~$ waydroid log
    return user(args, cmd, working_dir, output, output_return, check, env,
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % sudo mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs

(003541) [19:59:34] UserMonitor service is not even started
(003541) [19:59:34] Clipboard service is not even started
(011375) [20:19:06] % sudo chmod 666 -R /dev/anbox-binder
(011375) [20:19:06] % sudo chmod 666 -R /dev/anbox-vndbinder
(011375) [20:19:06] % sudo chmod 666 -R /dev/anbox-hwbinder
(011375) [20:19:06] Container manager is waiting for session to load
(012174) [20:19:46] Save session config: /var/lib/waydroid/session.cfg
(012174) [20:19:46] UserMonitor service is not even started
(012174) [20:19:46] Clipboard service is not even started
(011375) [20:19:47] % sudo /usr/lib/waydroid/data/scripts/waydroid-net.sh start
waydroid-net is already running
(011375) [20:19:47] % sudo waydroid-sensord /dev/anbox-hwbinder
(011375) [20:19:47] New background process: pid=12181, output=background
(011375) [20:19:47] % sudo mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
sudo: waydroid-sensord: command not found
mount: /var/lib/waydroid/rootfs: special device /var/lib/waydroid/images/system.img does not exist.
(011375) [20:19:47] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(011375) [20:19:47] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(011375) [20:19:47] ERROR: Command failed: % sudo mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(011375) [20:19:47] See also: <https://github.com/waydroid>
(011375) [20:19:47] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 128, in start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"])
  File "/usr/lib/waydroid/tools/helpers/images.py", line 90, in mount_rootfs
    helpers.mount.mount(args, images_dir + "/system.img",
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 131, in mount
    tools.helpers.run.root(args, ["mount", source, destination])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 77, in root
    return user(args, cmd, working_dir, output, output_return, check, env,
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % sudo mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs

(012184) [20:19:47] UserMonitor service is not even started
(012184) [20:19:47] Clipboard service is not even started
(012174) [20:19:47] UserMonitor service is not even started
(012174) [20:19:47] Clipboard service is not even started
(012437) [20:20:01] Starting waydroid session
(012437) [20:20:01] Save session config: /var/lib/waydroid/session.cfg
(012437) [20:20:01] UserMonitor service is not even started
(012437) [20:20:01] Clipboard service is not even started
(012437) [20:22:33] UserMonitor service is not even started
(012437) [20:22:33] Clipboard service is not even started
(014344) [20:23:08] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(014344) [20:23:08] *** output passed to waydroid stdout, not to this log ***

**Comment by Id2ndR** [comment]
*/var/lib/waydroid/images/system.img does not exist.* means that lineage OS image is not present on your system.
Did you run `sudo waydroid init`?

**Comment by gitati16** [comment]
try `sudo waydroid upgrade`

**Comment by disdi** [comment]
> _/var/lib/waydroid/images/system.img does not exist._ means that lineage OS image is not present on your system. Did you run `sudo waydroid init`?

yes. i did.

**Comment by disdi** [comment]
> sudo waydroid upgrade

disdi@disdi-Precision-5540:~$ sudo waydroid upgrade
[11:34:32] Download https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-17.1-20210928-VANILLA-waydroid_x86_64-system.zip/download
[11:35:03] Validating system image
[11:35:04] Extracting to /var/lib/waydroid/images
[11:35:12] Download https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-17.1-20210928-MAINLINE-waydroid_x86_64-vendor.zip/download
[11:35:19] Validating vendor image
[11:35:20] Extracting to /var/lib/waydroid/images

**Comment by disdi** [comment]
Still I face other issues:
Terminal 1-
disdi@disdi-Precision-5540:~$ sudo waydroid container start
[gbinder] Service manager /dev/anbox-binder has appeared

Terminal 2-
^Cdisdi@disdi-Precision-5540:~$ waydroid session start
[11:38:10] Failed to start Clipboard manager service, check logs
[gbinder] Service manager /dev/anbox-binder has appeared
[11:38:21] Android with user 0 is ready
[gbinder] WARNING: Transaction pipe polling error: Interrupted system call
Traceback (most recent call last):
  File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
  File "/usr/lib/waydroid/tools/interfaces/IUserMonitor.py", line 24, in response_handler
    userUnlocked(arg1)
  File "/usr/lib/waydroid/tools/services/user_manager.py", line 63, in userUnlocked
    os.mkdir(apps_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/.local/share/applications'
Exception ignored in: 'gbinder.local_transact_callback'
Traceback (most recent call last):
  File "gbinder.pyx", line 499, in gbinder.LocalObject.callback
  File "/usr/lib/waydroid/tools/interfaces/IUserMonitor.py", line 24, in response_handler
    userUnlocked(arg1)
  File "/usr/lib/waydroid/tools/services/user_manager.py", line 63, in userUnlocked
    os.mkdir(apps_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/.local/share/applications'

**Comment by erfanoabdi** [comment]
Should be fixed by now, reopen if you have same error on latest version
