### ISSUE TITLE
[ERROR] Waydroid Container service not starting

### ISSUE THREAD

**Issue by nesper8** [waydroid/waydroid#80]
OS: Arch Linux x86_64
Kernels tested: linux-zen, linux514-tkg-cfs
Issue: waydroid container doesnt start
SystemD Status:
```
× waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Fri 2021-09-24 00:02:44 IST; 23s ago
    Process: 1235 ExecStart=/usr/bin/waydroid container start (code=exited, status=0/SUCCESS)
    Process: 1242 ExecStop=/usr/bin/waydroid container stop (code=exited, status=1/FAILURE)
    Process: 1249 ExecStopPost=/usr/bin/waydroid session stop (code=exited, status=0/SUCCESS)
   Main PID: 1235 (code=exited, status=0/SUCCESS)
        CPU: 756ms

Sep 24 00:02:44 archlinux sudo[1243]: pam_unix(sudo:session): session closed for user root
Sep 24 00:02:44 archlinux sudo[1247]:     root : PWD=/ ; USER=root ; COMMAND=/usr/bin/lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
Sep 24 00:02:44 archlinux sudo[1247]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Sep 24 00:02:44 archlinux sudo[1247]: pam_unix(sudo:session): session closed for user root
Sep 24 00:02:44 archlinux waydroid[1242]: [00:02:44] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
Sep 24 00:02:44 archlinux waydroid[1242]: [00:02:44] ERROR: Command failed: % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
Sep 24 00:02:44 archlinux waydroid[1242]: [00:02:44] See also: <https://github.com/waydroid>
Sep 24 00:02:44 archlinux waydroid[1242]: Run 'waydroid log' for details.
Sep 24 00:02:44 archlinux systemd[1]: waydroid-container.service: Control process exited, code=exited, status=1/FAILURE
Sep 24 00:02:44 archlinux systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
```

Waydroid Log:
```
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k

(001249) [00:02:44] UserMonitor service is not even started
(001249) [00:02:44] Clipboard service is not even started
(002795) [00:13:16] Already initialized
(002806) [00:13:24] WayDroid container is 
(002813) [00:13:24] % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-stop: waydroid: tools/lxc_stop.c: main: 170 waydroid is not running
(002813) [00:13:24] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(002813) [00:13:24] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(002813) [00:13:24] ERROR: Command failed: % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
(002813) [00:13:24] See also: <https://github.com/waydroid>
(002813) [00:13:24] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 66, in main
    actions.container_manager.stop(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 185, in stop
    helpers.lxc.stop(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 240, in stop
    tools.helpers.run.root(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 77, in root
    return user(args, cmd, working_dir, output, output_return, check, env,
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k

(002821) [00:13:24] WayDroid session is not started
(002826) [00:13:41] WayDroid container is 
(002846) [00:14:08] % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-stop: waydroid: tools/lxc_stop.c: main: 170 waydroid is not running
(002846) [00:14:08] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(002846) [00:14:08] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(002846) [00:14:08] ERROR: Command failed: % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
(002846) [00:14:08] See also: <https://github.com/waydroid>
(002846) [00:14:08] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 66, in main
    actions.container_manager.stop(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 185, in stop
    helpers.lxc.stop(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 240, in stop
    tools.helpers.run.root(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 77, in root
    return user(args, cmd, working_dir, output, output_return, check, env,
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % sudo lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k

(002857) [00:14:17] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(002857) [00:14:17] *** output passed to waydroid stdout, not to this log ***
```

**Comment by AbhayF8** [comment]
+1 does anyone found any fix for this ?

**Comment by nesper8** [comment]
Looks like waydroid team just doesnt care

**Comment by electrikjesus** [comment]
It just states that waydroid is not running. Check the service. 
Also, another user thought this might be helpful https://wiki.archlinux.org/title/Waydroid#Commands_inside_Waydroid_shell_outputs_inaccessible_or_not_found

**Comment by Araly** [comment]
> It just states that waydroid is not running. Check the service, or force init. Also, another user thought this might be helpful https://wiki.archlinux.org/title/Waydroid#Commands_inside_Waydroid_shell_outputs_inaccessible_or_not_found

I'm also having this issue and I don't understand what the closing comment means. Is it normal for the service to fail ? It status that waydroid is not running, but isn't the purpose of the service to make waydroid run ?

following the arch wiki https://wiki.archlinux.org/title/Waydroid, I initialized waydroid, but from there I don't know where to go.

```
$ sudo waydroid init
[15:30:50] Already initialized

$ waydroid session start
(this just hangs, though it breaks when I restart waydroid-container.service)

$ waydroid show-full-ui
[15:31:02] WayDroid container is STOPPED
```

when I check the status of the service, I get the same kind of output as OP, but I'll post them anyways

```
$ sudo systemctl status waydroid-container.service
× waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Wed 2022-02-16 15:30:35 CET; 10s ago
    Process: 5697 ExecStart=/usr/bin/waydroid container start (code=exited, status=0/SUCCESS)
    Process: 5708 ExecStop=/usr/bin/waydroid container stop (code=exited, status=1/FAILURE)
    Process: 5711 ExecStopPost=/usr/bin/waydroid session stop (code=exited, status=0/SUCCESS)
   Main PID: 5697 (code=exited, status=0/SUCCESS)
        CPU: 161ms

feb 16 15:30:35 oak systemd[1]: Started Waydroid Container.
feb 16 15:30:35 oak waydroid[5707]: waydroid doesn't exist
feb 16 15:30:35 oak waydroid[5697]: [15:30:35] WayDroid container is
feb 16 15:30:35 oak waydroid[5709]: waydroid doesn't exist
feb 16 15:30:35 oak waydroid[5708]: [15:30:35] NOTE: The failed command's output is above the ^^^ line in the log fi>
feb 16 15:30:35 oak waydroid[5708]: [15:30:35] ERROR: Command failed: % lxc-stop -P /var/lib/waydroid/lxc -n waydroi>
feb 16 15:30:35 oak waydroid[5708]: [15:30:35] See also: <https://github.com/waydroid>
feb 16 15:30:35 oak waydroid[5708]: Run 'waydroid log' for details.
feb 16 15:30:35 oak systemd[1]: waydroid-container.service: Control process exited, code=exited, status=1/FAILURE
feb 16 15:30:35 oak systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
```

```
$ waydroid log
lxc-stop: waydroid: tools/lxc_stop.c: main: 168 waydroid is not running
(005382) [15:26:58] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(005382) [15:26:58] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(005382) [15:26:58] ERROR: Command failed: % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
(005382) [15:26:58] See also: <https://github.com/waydroid>
(005382) [15:26:58] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 71, in main
    actions.container_manager.stop(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 190, in stop
    helpers.lxc.stop(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 291, in stop
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k

(005385) [15:26:58] WayDroid session is not started
(005548) [15:29:42] Already initialized
(005608) [15:30:11] Save session config: /var/lib/waydroid/session.cfg
(005608) [15:30:11] UserMonitor service is not even started
(005608) [15:30:11] Clipboard service is not even started
(005697) [15:30:35] WayDroid container is
(005708) [15:30:35] % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
lxc-stop: waydroid: tools/lxc_stop.c: main: 168 waydroid is not running
(005708) [15:30:35] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(005708) [15:30:35] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(005708) [15:30:35] ERROR: Command failed: % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k
(005708) [15:30:35] See also: <https://github.com/waydroid>
(005708) [15:30:35] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 71, in main
    actions.container_manager.stop(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 190, in stop
    helpers.lxc.stop(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 291, in stop
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % lxc-stop -P /var/lib/waydroid/lxc -n waydroid -k

(005711) [15:30:35] UserMonitor service is not even started
(005711) [15:30:35] Clipboard service is not even started
(005608) [15:30:35] UserMonitor service is not even started
(005608) [15:30:35] Clipboard service is not even started
(005749) [15:30:50] Already initialized
(005762) [15:30:53] Save session config: /var/lib/waydroid/session.cfg
(005762) [15:30:53] UserMonitor service is not even started
(005762) [15:30:53] Clipboard service is not even started
(005780) [15:31:02] WayDroid container is STOPPED
(005762) [15:31:36] UserMonitor service is not even started
(005762) [15:31:36] Clipboard service is not even started
(005861) [15:33:50] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(005861) [15:33:50] *** output passed to waydroid stdout, not to this log ***
```

If I try to get in the shell, it doesn't work either, even when following the link you posted

```
$ sudo waydroid shell                                                                                           ↵ 2
waydroid doesn't exist
waydroid doesn't exist
[15:34:57] WayDroid container is 

$ sudo lxc-attach -P /var/lib/waydroid/lxc/ -n waydroid --clear-env
lxc-attach: waydroid: attach.c: get_attach_context: 405 Connection refused - Failed to get init pid
lxc-attach: waydroid: attach.c: lxc_attach: 1469 Connection refused - Failed to get attach context
```

The logs are weird, especially the "WayDroid container is" that seems to abruptly stop. 

Can we open this issue back ? The issue has not been resolved, and it really doesn't seem like this behavior is on purpose.
