### ISSUE TITLE
Unable to open waydroid session

### ISSUE THREAD

**Issue by hidiyou** [waydroid/waydroid#808]
**本issue使用机器翻译**
**This issue uses machine translation**
  
  
**Describe the bug**
无法打开waydroid  
Unable to open waydroid

**Screenshots**
![image](https://user-images.githubusercontent.com/98258846/226087707-e922351b-7dd9-4600-959d-d95fbb51f995.png)
![image](https://user-images.githubusercontent.com/98258846/226087724-b400c163-5469-44d7-9c0a-0aa843c96876.png)
(The meaning of 没有那个文件或目录 is There is no such file or directory)

**General information (please complete the following information):**
我不知道如何查看`Waydroid tools Version`
I don't know how to view `Waydroid tools Version`

以下为`/var/lib/waydroid/waydroid.cfg`
The following is `/var/lib/waydroid/waydroid.cfg`

```config
[waydroid]
arch = x86_64
vendor_type = MAINLINE
system_datetime = 0
vendor_datetime = 0
suspend_action = freeze
mount_overlays = True
images_path = /usr/share/waydroid-extra/images
system_ota = https://ota.waydro.id/system/lineage/waydroid_x86_64/VANILLA.json
vendor_ota = https://ota.waydro.id/vendor/waydroid_x86_64/MAINLINE.json
binder = anbox-binder
vndbinder = anbox-vndbinder
hwbinder = anbox-hwbinder
binder_protocol = aidl3
service_manager_protocol = aidl3

[properties]

```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS
 - GPU: HAINAN (, LLVM 15.0.6, DRM 2.50, 5.19.0-35-generic) / Mesa Intel® HD Graphics 620 (KBL GT2)
 - Kernel version: 5.19.0-35-generic
 - Host mesa version: No mesa (没有安装Mesa） `找不到命令 “glxinfo”，但可以通过以下软件包安装它：`
 - Desktop: Gnome 42.5

**Additional context**
我想使用它来运行安卓软件，我用apt安装了waydroid，然后自行下载了`https://udomain.dl.sourceforge.net/project/waydroid/images/vendor/waydroid_arm64/lineage-18.1-20230318-MAINLINE-waydroid_arm64-vendor.zip`和`https://udomain.dl.sourceforge.net/project/waydroid/images/system/lineage/waydroid_x86_64/lineage-18.1-20230318-GAPPS-waydroid_x86_64-system.zip`并把他们解压放进了`/usr/share/waydroid-extra/images`
"I want to use it to run Android software. I installed the waydroid using apt and downloaded it myself."` https://udomain.dl.sourceforge.net/project/waydroid/images/vendor/waydroid_arm64/lineage-18.1-20230318-MAINLINE-waydroid_arm64-vendor.zip `And` https://udomain.dl.sourceforge.net/project/waydroid/images/system/lineage/waydroid_x86_64/lineage-18.1-20230318-GAPPS-waydroid_x86_64-system.zip `And unzipped them into `/usr/share/waydroid-extra/images`
![image](https://user-images.githubusercontent.com/98258846/226088497-a10fd7aa-c600-4c2c-8508-afa45d86430f.png)

**Logs (please upload as file)**
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running
 - Output of `dmesg`

/var/lib/waydroid/waydroid.prop
```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.updater.disabled=true
waydroid.tools_version=1.4.0
ro.vndk.lite=true
waydroid.host.user=diyou
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/diyou/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-0
waydroid.background_start=false
waydroid.stub_sensors_hal=1
```

/var/lib/waydroid/waydroid_base.prop

```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=intel
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.updater.disabled=true
waydroid.tools_version=1.4.0
ro.vndk.lite=true
```
/var/lib/waydroid/waydroid.log
```
(016487) [12:02:00] % mkdir -p /dev/binderfs
(016487) [12:02:00] % mount -t binder binder /dev/binderfs
(016487) [12:02:00] % ln -s /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/features /dev/binderfs/binder-control /dev/
(016487) [12:02:00] Save config: /var/lib/waydroid/waydroid.cfg
(016487) [12:02:01] % mkdir -p /var/lib/waydroid/cache_http
(016487) [12:02:01] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20230311-VANILLA-waydroid_x86_64-system.zip/download
(007944) [12:16:34] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(007944) [12:16:34] % mkdir -p /dev/binderfs
(007944) [12:16:34] % mount -t binder binder /dev/binderfs
(007944) [12:16:34] % ln -s /dev/binderfs/features /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/binder-control /dev/
(007944) [12:16:34] Save config: /var/lib/waydroid/waydroid.cfg
(007944) [12:16:35] Downloading https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-18.1-20230318-GAPPS-waydroid_x86_64-system.zip/download
(007944) [12:18:03] Validating system image
(013782) [13:21:37] Save config: /var/lib/waydroid/waydroid.cfg
(013782) [13:21:37] % modprobe -q ashmem_linux
(013782) [13:21:37] % lxc-info --version
5.0.0~git2209-g5a7b9ce67
(013782) [13:21:37] % mkdir -p /var/lib/waydroid/lxc/waydroid
(013782) [13:21:37] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(013782) [13:21:37] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(013782) [13:21:37] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(013782) [13:21:37] % aa-enabled --quiet
(013782) [13:21:37] % sed -i -E /lxc.aa_profile|lxc.apparmor.profile/ s/unconfined/lxc-waydroid/g /var/lib/waydroid/lxc/waydroid/config
(013782) [13:21:37] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(013774) [13:21:37] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(013774) [13:21:37] % modprobe -q ashmem_linux
(013774) [13:21:37] % chmod 666 -R /dev/anbox-binder
(013774) [13:21:37] % chmod 666 -R /dev/anbox-vndbinder
(013774) [13:21:37] % chmod 666 -R /dev/anbox-hwbinder
(013774) [13:22:17] Hardware service is not even started
(013774) [13:22:17] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(013774) [13:22:17] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(013774) [13:22:17] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(013879) [13:22:17] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(013879) [13:22:17] % modprobe -q ashmem_linux
(013879) [13:22:17] % chmod 666 -R /dev/anbox-binder
(013879) [13:22:17] % chmod 666 -R /dev/anbox-vndbinder
(013879) [13:22:17] % chmod 666 -R /dev/anbox-hwbinder
(013888) [13:22:22] Starting waydroid session
(013879) [13:22:22] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(013879) [13:22:22] % systemctl is-active -q nfcd
(013879) [13:22:22] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
chmod: 更改 '/sys/kernel/debug/sync/sw_sync' 的权限: 不允许的操作
(013879) [13:22:22] % chmod 777 -R /dev/dri
(013879) [13:22:22] % chmod 777 -R /dev/fb0
(013879) [13:22:22] % chmod 777 -R /dev/video5
(013879) [13:22:22] % chmod 777 -R /dev/video4
(013879) [13:22:22] % chmod 777 -R /dev/video1
(013879) [13:22:22] % chmod 777 -R /dev/video0
(013879) [13:22:22] % chmod 777 -R /dev/video3
(013879) [13:22:22] % chmod 777 -R /dev/video2
(013879) [13:22:22] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(013879) [13:22:22] % mount -o ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(013879) [13:22:22] % mkdir -p /var/lib/waydroid/overlay_work/system
(013879) [13:22:22] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(013879) [13:22:22] % mount -o ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(013879) [13:22:22] % mkdir -p /var/lib/waydroid/overlay_work/vendor
(013879) [13:22:22] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(013879) [13:22:22] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(013879) [13:22:22] Save config: /var/lib/waydroid/waydroid.cfg
(013879) [13:22:22] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(013879) [13:22:22] New background process: pid=13976, output=background
(013879) [13:22:22] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(013888) [13:22:22] Failed to start Clipboard manager service, check logs
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(014077) [13:23:06] ERROR: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
(014077) [13:23:06] See also: <https://github.com/waydroid>
(014077) [13:23:06] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

(013879) [13:23:22] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(013879) [13:23:22] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 255: kill: No such process

(013879) [13:23:22] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(013879) [13:23:22] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(013879) [13:23:22] % umount /var/lib/waydroid/rootfs/vendor
(013879) [13:23:22] % umount /var/lib/waydroid/rootfs/vendor
(013879) [13:23:22] % umount /var/lib/waydroid/rootfs
(013879) [13:23:22] % umount /var/lib/waydroid/rootfs
(013888) [13:23:22] Clipboard service is not even started
(014166) [13:23:45] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(014166) [13:23:45] % modprobe -q ashmem_linux
(014166) [13:23:45] % chmod 666 -R /dev/anbox-binder
(014166) [13:23:45] % chmod 666 -R /dev/anbox-vndbinder
(014166) [13:23:45] % chmod 666 -R /dev/anbox-hwbinder
(014424) [13:28:14] ERROR: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
(014424) [13:28:14] See also: <https://github.com/waydroid>
(014424) [13:28:14] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

(014166) [13:29:30] Hardware service is not even started
(014166) [13:29:30] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(014166) [13:29:30] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(014166) [13:29:30] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(014577) [13:29:45] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(014577) [13:29:45] % modprobe -q ashmem_linux
(014577) [13:29:45] % chmod 666 -R /dev/anbox-binder
(014577) [13:29:45] % chmod 666 -R /dev/anbox-vndbinder
(014577) [13:29:45] % chmod 666 -R /dev/anbox-hwbinder
(014597) [13:29:54] Starting waydroid session
(014577) [13:29:54] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(014577) [13:29:54] % systemctl is-active -q nfcd
(014577) [13:29:54] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
chmod: 更改 '/sys/kernel/debug/sync/sw_sync' 的权限: 不允许的操作
(014577) [13:29:54] % chmod 777 -R /dev/dri
(014577) [13:29:54] % chmod 777 -R /dev/fb0
(014577) [13:29:54] % chmod 777 -R /dev/video5
(014577) [13:29:54] % chmod 777 -R /dev/video4
(014577) [13:29:54] % chmod 777 -R /dev/video1
(014577) [13:29:54] % chmod 777 -R /dev/video0
(014577) [13:29:54] % chmod 777 -R /dev/video3
(014577) [13:29:54] % chmod 777 -R /dev/video2
(014577) [13:29:54] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(014577) [13:29:54] % mount -o ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(014577) [13:29:54] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(014577) [13:29:54] % mount -o ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(014577) [13:29:54] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(014577) [13:29:54] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(014577) [13:29:54] Save config: /var/lib/waydroid/waydroid.cfg
(014577) [13:29:54] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(014577) [13:29:54] New background process: pid=14676, output=background
(014577) [13:29:54] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(014597) [13:29:54] Failed to start Clipboard manager service, check logs
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(014887) [13:31:49] ERROR: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
(014887) [13:31:49] See also: <https://github.com/waydroid>
(014887) [13:31:49] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

(015012) [13:32:00] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(015012) [13:32:00] *** output passed to waydroid stdout, not to this log ***
(014577) [13:32:59] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(015076) [13:32:59] Waiting for binder Service Manager...
(015093) [13:33:04] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(015093) [13:33:04] *** output passed to waydroid stdout, not to this log ***
(015098) [13:33:14] ERROR: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
(015098) [13:33:14] See also: <https://github.com/waydroid>
(015098) [13:33:14] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

(015076) [13:33:59] Service Manager never appeared
(015076) [13:33:59] Failed to access IPlatform service
(015277) [13:36:48] ERROR: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
(015277) [13:36:48] See also: <https://github.com/waydroid>
(015277) [13:36:48] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

(014577) [13:37:28] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(014577) [13:37:28] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 255: kill: No such process

(014577) [13:37:28] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(014577) [13:37:28] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(014577) [13:37:28] % umount /var/lib/waydroid/rootfs/vendor
(014577) [13:37:28] % umount /var/lib/waydroid/rootfs/vendor
(014577) [13:37:28] % umount /var/lib/waydroid/rootfs
(014577) [13:37:28] % umount /var/lib/waydroid/rootfs
(014597) [13:37:28] Clipboard service is not even started
(015779) [13:38:15] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(015779) [13:38:15] % modprobe -q ashmem_linux
(015779) [13:38:15] % lxc-info --version
5.0.0~git2209-g5a7b9ce67
(015779) [13:38:15] % mkdir -p /var/lib/waydroid/lxc/waydroid
(015779) [13:38:15] % sh -c cat "/usr/lib/waydroid/data/configs/config_base" "/usr/lib/waydroid/data/configs/config_3" "/usr/lib/waydroid/data/configs/config_4" > "/var/lib/waydroid/lxc/waydroid/config"
(015779) [13:38:15] % sed -i s/LXCARCH/x86_64/ /var/lib/waydroid/lxc/waydroid/config
(015779) [13:38:15] % cp -fpr /usr/lib/waydroid/data/configs/waydroid.seccomp /var/lib/waydroid/lxc/waydroid/waydroid.seccomp
(015779) [13:38:15] % aa-enabled --quiet
(015779) [13:38:15] % sed -i -E /lxc.aa_profile|lxc.apparmor.profile/ s/unconfined/lxc-waydroid/g /var/lib/waydroid/lxc/waydroid/config
(015779) [13:38:15] % mv /var/lib/waydroid/config_nodes /var/lib/waydroid/lxc/waydroid
(015869) [13:38:16] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(015869) [13:38:16] % modprobe -q ashmem_linux
(015869) [13:38:16] % chmod 666 -R /dev/anbox-binder
(015869) [13:38:16] % chmod 666 -R /dev/anbox-vndbinder
(015869) [13:38:16] % chmod 666 -R /dev/anbox-hwbinder
(016003) [13:38:59] Starting waydroid session
(015869) [13:38:59] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
(015869) [13:38:59] % systemctl is-active -q nfcd
(015869) [13:38:59] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
chmod: 更改 '/sys/kernel/debug/sync/sw_sync' 的权限: 不允许的操作
(015869) [13:38:59] % chmod 777 -R /dev/dri
(015869) [13:38:59] % chmod 777 -R /dev/fb0
(015869) [13:38:59] % chmod 777 -R /dev/video5
(015869) [13:38:59] % chmod 777 -R /dev/video4
(015869) [13:38:59] % chmod 777 -R /dev/video1
(015869) [13:38:59] % chmod 777 -R /dev/video0
(015869) [13:38:59] % chmod 777 -R /dev/video3
(015869) [13:38:59] % chmod 777 -R /dev/video2
(015869) [13:38:59] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(015869) [13:38:59] % mount -o ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(015869) [13:38:59] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(015869) [13:38:59] % mount -o ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(015869) [13:38:59] % mount -t overlay -o ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(015869) [13:38:59] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(015869) [13:38:59] Save config: /var/lib/waydroid/waydroid.cfg
(015869) [13:38:59] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(015869) [13:38:59] New background process: pid=16071, output=background
(015869) [13:38:59] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(015869) [13:38:59] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
RUNNING
(015869) [13:38:59] waiting 10 seconds for container to start...
(016003) [13:39:00] Failed to start Clipboard manager service, check logs
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
(016387) [13:40:06] Already initialized
(015869) [13:40:21] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(015869) [13:40:21] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
/usr/lib/waydroid/data/scripts/waydroid-net.sh: 255: kill: No such process

(015869) [13:40:21] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(015869) [13:40:21] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(015869) [13:40:21] % umount /var/lib/waydroid/rootfs/vendor
(015869) [13:40:21] % umount /var/lib/waydroid/rootfs/vendor
(015869) [13:40:21] % umount /var/lib/waydroid/rootfs
(015869) [13:40:21] % umount /var/lib/waydroid/rootfs
(016003) [13:40:21] Clipboard service is not even started
(016458) [13:40:21] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(016458) [13:40:21] % modprobe -q ashmem_linux
(016458) [13:40:21] % chmod 666 -R /dev/anbox-binder
(016458) [13:40:21] % chmod 666 -R /dev/anbox-vndbinder
(016458) [13:40:21] % chmod 666 -R /dev/anbox-hwbinder
(016458) [13:41:19] Hardware service is not even started
(016458) [13:41:19] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(016458) [13:41:19] % /usr/lib/waydroid/data/scripts/waydroid-net.sh stop
vnic is waydroid0
waydroid-net isn't running
(016458) [13:41:19] % systemctl is-enabled -q nfcd
Failed to get unit file state for nfcd.service: No such file or directory
(016578) [13:41:47] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(016578) [13:41:47] % modprobe -q ashmem_linux
(016578) [13:41:47] % chmod 666 -R /dev/anbox-binder
(016578) [13:41:47] % chmod 666 -R /dev/anbox-vndbinder
(016578) [13:41:47] % chmod 666 -R /dev/anbox-hwbinder
(016620) [13:42:25] ERROR: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
(016620) [13:42:25] See also: <https://github.com/waydroid>
(016620) [13:42:25] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

(016627) [13:42:50] ERROR: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
(016627) [13:42:50] See also: <https://github.com/waydroid>
(016627) [13:42:50] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message

(016916) [13:45:57] ERROR: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
(016916) [13:45:57] See also: <https://github.com/waydroid>
(016916) [13:45:57] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 70, in main
    actions.session_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/session_manager.py", line 35, in start
    name = dbus.service.BusName("id.waydro.Session", dbus.SessionBus(), do_not_queue=True)
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 212, in __new__
    return Bus.__new__(cls, Bus.TYPE_SESSION, private=private,
  File "/usr/lib/python3/dist-packages/dbus/_dbus.py", line 102, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 124, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.Spawn.ExecFailed: /usr/bin/dbus-launch terminated abnormally without any error message
```

**Comment by aleasto** [comment]
Don't use sudo

**Comment by MissLeely** [comment]
这个问题解决了吗？我重新安装一下就这样了啊啊啊啊
