### ISSUE TITLE
OSError: container failed to start

### ISSUE THREAD

**Issue by Jetrom17** [waydroid/waydroid#853]
- I installed Weston.

- I executed Weston.

- I ran the command: 
```bash
jetrom•~» waydroid show-full-ui [11:38:32]
[11:38:36] Starting waydroid session
[11:38:36] WAYLAND_DISPLAY is not set, defaulting to "wayland-0"
[11:38:47] OSError: container failed to start
```
Logs:

```bash
(008024) [11:33:35] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(008024) [11:33:35] Save config: /var/lib/waydroid/waydroid.cfg
(008024) [11:33:35] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(008024) [11:33:35] New background process: pid=8696, output=background
(008024) [11:33:35] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
lxc-start: waydroid: lsm/apparmor.c: apparmor_process_label_set_at: 1183 No such file or directory - Failed to write AppArmor profile "lxc-waydroid" to 53
lxc-start: waydroid: lsm/apparmor.c: apparmor_process_label_set: 1229 Invalid argument - Failed to change AppArmor profile to lxc-waydroid
lxc-start: waydroid: sync.c: sync_wait: 34 An error occurred in another process (expected sequence number 4)
lxc-start: waydroid: start.c: __lxc_start: 2074 Failed to spawn container "waydroid"
STOPPED
lxc-start: waydroid: conf.c: run_buffer: 321 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 988 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 306 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 311 Additional information can be obtained by setting the --logfile and --logpriority options
(008024) [11:33:35] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(008024) [11:33:35] waiting 10 seconds for container to start...
(008024) [11:33:36] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(008024) [11:33:36] waiting 9 seconds for container to start...
(008024) [11:33:37] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(008024) [11:33:37] waiting 8 seconds for container to start...
(008024) [11:33:38] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(008024) [11:33:38] waiting 7 seconds for container to start...
(008024) [11:33:39] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(008024) [11:33:39] waiting 6 seconds for container to start...
(008024) [11:33:40] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(008024) [11:33:40] waiting 5 seconds for container to start...
(008024) [11:33:41] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(008024) [11:33:41] waiting 4 seconds for container to start...
(008024) [11:33:42] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(008024) [11:33:42] waiting 3 seconds for container to start...
(008024) [11:33:43] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(008024) [11:33:43] waiting 2 seconds for container to start...
(008024) [11:33:44] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
STOPPED
(008024) [11:33:44] waiting 1 seconds for container to start...
(008658) [11:33:45] org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/dbus/service.py", line 711, in _message_cb
     retval = candidate_method(self, *args, **keywords)
   File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
     do_start(self.args, session)
   File "/usr/lib/waydroid/tools/actions/container_manager.py", line 178, in do_start
     helpers.lxc.start(args)
   File "/usr/lib/waydroid/tools/helpers/lxc.py", line 397, in start
     wait_for_running(args)
   File "/usr/lib/waydroid/tools/helpers/lxc.py", line 391, in wait_for_running
     raise OSError("container failed to start")
OSError: container failed to start

(008658) [11:33:45] OSError: container failed to start
(008841) [11:35:38] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(008841) [11:35:38] *** output passed to waydroid stdout, not to this log ***
```

[Abou log: System stopped responding]

OS: Zorion (Lite)
CPU: 2.
RAM: 4 GB.

File: [waydroid.log](https://github.com/waydroid/waydroid/files/11251490/waydroid.log)

**Comment by eusoubrasileiro** [comment]
same issue here but for Ubuntu 20.04 gnome

**Comment by Jetrom17** [comment]
> same issue here but for Ubuntu 20.04 gnome 

Thanks. I already solved my problem. Although it has been more than 5 months. I will close this issue. Thank you for being manifest and reminding me.

**Comment by eusoubrasileiro** [comment]
Well the problem is still @Jetrom17 persists for me. I just gave up totally of waydroid. I am using qemu with Android x86. Regards.

**Comment by justpeanuts** [comment]
> > same issue here but for Ubuntu 20.04 gnome
> 
> Thanks. I already solved my problem. Although it has been more than 5 months. I will close this issue. Thank you for being manifest and reminding me.

how did you solve the problem? @Jetrom17

**Comment by Jetrom17** [comment]
> > > same issue here but for Ubuntu 20.04 gnome
> > 
> > Thanks. I already solved my problem. Although it has been more than 5 months. I will close this issue. Thank you for being manifest and reminding me.
> 
> how did you solve the problem? @Jetrom17 

I don't remember. I must have installed it on another operating system.
