### ISSUE TITLE
DBusException: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.77" is not allowed to own the service "id.waydro.Container" due to security policies in the configuration file

### ISSUE THREAD

**Issue by suntong** [waydroid/waydroid#854]
**Describe the bug**

`DBusException: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.77" is not allowed to own the service "id.waydro.Container" due to security policies in the configuration file`

**General information (please complete the following information):**
 - Waydroid tools Version 1.4.0
 - Waydroid Images Version [e.g. VANILLA 20211021], or `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`

VANILLA latest:

```
system_datetime = 1681535843
vendor_datetime = 1681558011
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.1 x64
 - GPU: not sure
 - Kernel version: generic_5.15.0.60.58
 - Host mesa version: amd64_22.2.5-0ubuntu0.1~22.04.1
 - Desktop: kde plasma-desktop_4:5.24.7-0ubuntu0.1
plasma-workspace-wayland_4:5.24.7-0ubuntu0.1

**Additional context**

The error is caused by  
`sudo systemctl enable --now waydroid-container`

Interestingly, the command `sudo systemctl enable --now waydroid-container` runs fine under X11, but not wayland.

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead
 - Log file, located at `/var/lib/waydroid/waydroid.log`
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running
 - Output of `dmesg`

```
$ sudo systemctl status waydroid-container
x waydroid-container.service - Waydroid Container
     Loaded: loaded (/lib/systemd/system/waydroid-container.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2023-04-17 22:56:43 EDT; 20min ago
    Process: 1912 ExecStart=/usr/bin/waydroid -w container start (code=exited, status=1/FAILURE)
   Main PID: 1912 (code=exited, status=1/FAILURE)
        CPU: 147ms

Apr 17 22:56:42 wahoo systemd[1]: Starting Waydroid Container...
Apr 17 22:56:43 wahoo waydroid[1912]: [22:56:43] ERROR: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.79" is not allowed to own the service "id.waydro.Container" due to security policies in the configuration file
Apr 17 22:56:43 wahoo waydroid[1912]: [22:56:43] See also: <https://github.com/waydroid>
Apr 17 22:56:43 wahoo waydroid[1912]: Run 'waydroid log' for details.
Apr 17 22:56:43 wahoo systemd[1]: waydroid-container.service: Main process exited, code=exited, status=1/FAILURE
Apr 17 22:56:43 wahoo systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
Apr 17 22:56:43 wahoo systemd[1]: Failed to start Waydroid Container.


$ waydroid log
(001878) [22:56:42] Starting waydroid session
(001912) [22:56:43] ERROR: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.79" is not allowed to own the service "id.waydro.Container" due to security policies in the configuration file
(001912) [22:56:43] See also: <https://github.com/waydroid>
(001912) [22:56:43] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 81, in main
    dbus_name_scope = dbus.service.BusName("id.waydro.Container", dbus.SystemBus(), do_not_queue=True)
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 137, in __new__
    retval = bus.request_name(name, name_flags)
  File "/usr/lib/python3/dist-packages/dbus/bus.py", line 303, in request_name
    return self.call_blocking(BUS_DAEMON_NAME, BUS_DAEMON_PATH,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.AccessDenied: Connection ":1.79" is not allowed to own the service "id.waydro.Container" due to security policies in the configuration file

(001878) [22:57:07] org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'id.waydro.Container': timed out (service_start_timeout=25000ms)
(001878) [22:57:07] WayDroid container is not listening
```

**Comment by IlgazC** [comment]
Using https://build.opensuse.org/package/show/home%3AonlyJak0b%3AStable%3Awaydroid/waydroid under openSUSE Tumbleweed, I get the same messages with the same symptoms.

**Comment by etam** [comment]
In case of openSUSE package this is the fix (run as root):
```
ln -s /usr/lib/waydroid/dbus/id.waydro.Container.conf /usr/share/dbus-1/system.d/
ln -s /usr/lib/waydroid/dbus/id.waydro.Container.policy /usr/share/polkit-1/actions/
ln -s /usr/lib/waydroid/dbus/id.waydro.Container.service /usr/share/dbus-1/services/
dbus-send --print-reply --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
```

**Comment by poltpolt** [comment]
> In case of openSUSE package this is the fix (run as root):
> 
> ```
> ln -s /usr/lib/waydroid/dbus/id.waydro.Container.conf /usr/share/dbus-1/system.d/
> ln -s /usr/lib/waydroid/dbus/id.waydro.Container.policy /usr/share/polkit-1/actions/
> ln -s /usr/lib/waydroid/dbus/id.waydro.Container.service /usr/share/dbus-1/services/
> dbus-send --print-reply --system --type=method_call --dest=org.freedesktop.DBus / org.freedesktop.DBus.ReloadConfig
> ```
the fix worked on my Opensuse Tubleweed too. Thanks a  lot.
Do you know any way to install binder module in opensuse by chance?

**Comment by etam** [comment]
> Do you know any way to install binder module in opensuse by chance?

Unfortunately no. There's this project https://build.opensuse.org/project/show/home:tiwai:kernel:android which is supposed to build kernel with additional kernel modules, but it's not working as it should.

**Comment by M-Stenzel** [comment]
On opensuse Leap 15.6 that 

https://github.com/waydroid/waydroid/issues/854#issuecomment-1568921312

helped me, too
