### ISSUE TITLE
No module named gbinder | Arch

### ISSUE THREAD

**Issue by HxxThSwggr** [waydroid/waydroid#884]
**Describe the bug**
Can't run any `waydroid` command

**Screenshots**
![image](https://user-images.githubusercontent.com/67126208/236212751-4f1ad231-1efb-45e2-b268-cde1dc00d3ad.png)

**General information (please complete the following information):**
 - Waydroid tools Version: **1.4.1.r0.g7ce2e28-1**
 - Waydroid Images Version:
   - system_datetime = **1682140641**
   - vendor_datetime = **1682162466**

**Desktop (please complete the following information):**
 - OS: **Arch**
 - GPU: Integrated on **Ryzen 5 5600G**
 - Kernel version: **6.3.1-zen1-1-zen**
 - Host mesa version: **mesa 23.0.3-1**
 - Desktop: **KDE Plasma (Wayland)**

**Additional context**
I suspect it broke after updating python to 3.11
I have gbinder installed (from AUR)
Also tried installing with pip but it said:
```
ERROR: Could not find a version that satisfies the requirement gbinder (from versions: none)
ERROR: No matching distribution found for gbinder
```

**Logs (please upload as file)**
 - Prop file:
[waydroid.prop.txt](https://github.com/waydroid/waydroid/files/11397689/waydroid.prop.txt)

 - Log file:
[waydroid.log.txt](https://github.com/waydroid/waydroid/files/11397701/waydroid.log.txt)

 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running:
```
[HexxTheSwagger@OPC-Arch ~]$ waydroid logcat
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 12, in <module>
    from . import actions
  File "/usr/lib/waydroid/tools/actions/__init__.py", line 3, in <module>
    from tools.actions.initializer import init, wait_for_init, remote_init_client
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 5, in <module>
    from tools import helpers
  File "/usr/lib/waydroid/tools/helpers/__init__.py", line 5, in <module>
    import tools.helpers.props
  File "/usr/lib/waydroid/tools/helpers/props.py", line 8, in <module>
    from tools.interfaces import IPlatform
  File "/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 1, in <module>
    import gbinder
ModuleNotFoundError: No module named 'gbinder'
[HexxTheSwagger@OPC-Arch ~]$ 
```
 - Output of `dmesg`
[dmesg.txt](https://github.com/waydroid/waydroid/files/11397726/dmesg.txt)

**Comment by aleasto** [comment]
Report downstream

**Comment by cniw** [comment]
> I suspect it broke after updating python to 3.11
> I have gbinder installed (from AUR)
> ModuleNotFoundError: No module named 'gbinder'

it's can't find the module in python 3.11 site-packages directory because it's have been build for python 3.10 before,
you just need do rebuild and reinstall `python-gbinder` against 3.11 to make ir works again on your current update system, eg. you use `yay` as your aur helper program,
run `yay -S python-gbinder`

package files list before rebuild and reinstall
```bash
❯ pacman -Ql python-gbinder
python-gbinder /usr/
python-gbinder /usr/lib/
python-gbinder /usr/lib/python3.10/
python-gbinder /usr/lib/python3.10/site-packages/
python-gbinder /usr/lib/python3.10/site-packages/gbinder.cpython-310-x86_64-linux-gnu.so
python-gbinder /usr/lib/python3.10/site-packages/gbinder_python-1.1.1-py3.10.egg-info/
python-gbinder /usr/lib/python3.10/site-packages/gbinder_python-1.1.1-py3.10.egg-info/PKG-INFO
python-gbinder /usr/lib/python3.10/site-packages/gbinder_python-1.1.1-py3.10.egg-info/SOURCES.txt
python-gbinder /usr/lib/python3.10/site-packages/gbinder_python-1.1.1-py3.10.egg-info/dependency_links.txt
python-gbinder /usr/lib/python3.10/site-packages/gbinder_python-1.1.1-py3.10.egg-info/top_level.txt
```
after
```bash
❯ pacman -Ql python-gbinder
python-gbinder /usr/
python-gbinder /usr/lib/
python-gbinder /usr/lib/python3.11/
python-gbinder /usr/lib/python3.11/site-packages/
python-gbinder /usr/lib/python3.11/site-packages/gbinder.cpython-311-x86_64-linux-gnu.so
python-gbinder /usr/lib/python3.11/site-packages/gbinder_python-1.1.1-py3.11.egg-info/
python-gbinder /usr/lib/python3.11/site-packages/gbinder_python-1.1.1-py3.11.egg-info/PKG-INFO
python-gbinder /usr/lib/python3.11/site-packages/gbinder_python-1.1.1-py3.11.egg-info/SOURCES.txt
python-gbinder /usr/lib/python3.11/site-packages/gbinder_python-1.1.1-py3.11.egg-info/dependency_links.txt
python-gbinder /usr/lib/python3.11/site-packages/gbinder_python-1.1.1-py3.11.egg-info/top_level.txt
```

fyi, packages that you've installed from aur would not automatally updated when you do update using `sudo pacman -Syu` you need use aur helper `yay -Syu`
also you can check the others aur packages that need to be updated too related to python version update `pacman -Qqo /usr/lib/python3.10/` or you can pass the to `yay` to install it simultaneously `yay -S $(pacman -Qqo /usr/lib/python3.10/)
`

**Comment by HxxThSwggr** [comment]
Oh ic.
Sorry that it wasn't a waydroid problem.
It works now, thanks!

**Comment by tianyi725** [comment]
> 

> [HexxTheSwagger@OPC-Arch ~]$ waydroid logcat
> Traceback (most recent call last):
>   File "/usr/bin/waydroid", line 6, in <module>
>     import tools
>   File "/usr/lib/waydroid/tools/__init__.py", line 12, in <module>
>     from . import actions
>   File "/usr/lib/waydroid/tools/actions/__init__.py", line 3, in <module>
>     from tools.actions.initializer import init, wait_for_init, remote_init_client
>   File "/usr/lib/waydroid/tools/actions/initializer.py", line 5, in <module>
>     from tools import helpers
>   File "/usr/lib/waydroid/tools/helpers/__init__.py", line 5, in <module>
>     import tools.helpers.props
>   File "/usr/lib/waydroid/tools/helpers/props.py", line 8, in <module>
>     from tools.interfaces import IPlatform
>   File "/usr/lib/waydroid/tools/interfaces/IPlatform.py", line 1, in <module>
>     import gbinder
> ModuleNotFoundError: No module named 'gbinder'
> [HexxTheSwagger@OPC-Arch ~]$ 
> ```


Hello, I have the same error

How did you solve it in the end?
thanks

**Comment by HxxThSwggr** [comment]
I don't remember exactly.

First I think i tried to mess with my python packages. Tried manually removing old versions of python from `/lib` and reinstalling. **But that is most likely not the right way to do this.** A lot of programs depend on python so if you break it you break many more.

Then I found [a way how to check for and repair broken packages](https://unix.stackexchange.com/a/659777) in pacman (I assume you are also on Arch).

Then I believe I rebuilt `python-gbinder`.

Other than that, I'm afraid I can't help.
