### ISSUE TITLE
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

### ISSUE THREAD

**Issue by ROCKET1-1** [waydroid/waydroid#900]
Hello, how to solve this problem, I will be very grateful for the answer.
user: waydroid session start
[18:00:07] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

#log waydroid-container 
waydroid-container.service - Waydroid Container
     Loaded: loaded (/lib/systemd/system/waydroid-container.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2023-05-11 17:56:11 MSK; 4min 56s ago
   Main PID: 892 (waydroid)
      Tasks: 2 (limit: 4563)
     Memory: 18.1M
        CPU: 624ms
     CGroup: /system.slice/waydroid-container.service
             └─892 /usr/bin/python3 /usr/bin/waydroid -w container start

17:56:09 user systemd[1]: Starting Waydroid Container...
17:56:11 user systemd[1]: Started Waydroid Container.
18:00:07 user dnsmasq[6869]: failed to create listening socket for 192.168.240.1: Unable to assign requested address
18:00:07 user dnsmasq[6869]: FAILED to start up
18:00:07 user waydroid[892]: [18:00:07] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log

#journalctl log 
user: gnome-shell[3012]: Removing a network device that was not added

#waydroid log 
(000892) [18:00:06] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0

dnsmasq: failed to create listening socket for 192.168.240.1: Unable to assign requested address
Failed to setup waydroid-net.
Failed to setup waydroid-net.
(000892) [18:00:07] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(000892) [18:00:07] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(006819) [18:00:07] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/service.py", line 715, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 138, in do_start
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

(006819) [18:00:07] RuntimeError: Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

**Comment by kurtnettle** [comment]
I am also having the almost similar DBus.Python error only difference is I am getting.
```
Error: Unknown device type.
Failed to setup waydroid-net.
```

Does it have something to do with python 11?

**Comment by Kspiropali** [comment]
Hey there, @ROCKET1-1 , I also had the same problem. I tried to debug the /usr/lib/waydroid/data/scripts/waydroid-net.sh.
In my case, the problem was in:

```
1 start_nftables() {
102     start_ipv6
103     NFT_RULESET=""
104     if [ -n "$LXC_IPV6_ARG" ] && [ "$LXC_IPV6_NAT" = "true" ]; then
105         NFT_RULESET="${NFT_RULESET}
106 add table ip6 lxc;
107 flush table ip6 lxc;
108 add chain ip6 lxc postrouting { type nat hook postrouting priority 100; };
109 add rule ip6 lxc postrouting ip saddr ${LXC_IPV6_NETWORK} ip daddr != ${LXC_IPV6_NETWORK} counter masquerade;
110 "
111     fi
112     NFT_RULESET="${NFT_RULESET};
113 add table inet lxc;
114 flush table inet lxc;
115 add chain inet lxc input { type filter hook input priority 0; };
116 add rule inet lxc input iifname ${LXC_BRIDGE} udp dport { 53, 67 } accept;
117 add rule inet lxc input iifname ${LXC_BRIDGE} tcp dport { 53, 67 } accept;
118 add chain inet lxc forward { type filter hook forward priority 0; };
119 add rule inet lxc forward iifname ${LXC_BRIDGE} accept;
120 add rule inet lxc forward oifname ${LXC_BRIDGE} accept;
121 add table ip lxc;
122 flush table ip lxc;
123 add chain ip lxc postrouting { type nat hook postrouting priority 100; };
124 add rule ip lxc postrouting ip saddr ${LXC_NETWORK} ip daddr != ${LXC_NETWORK} counter masquerade"
125     nft "${NFT_RULESET}"
126 }
```

Where at line 124 remove the masquerade. It might have something to do with a dnsmasq syntax update but since I am no expert I am not sure. After that just normally do:
`waydroid session start`

**Comment by ROCKET1-1** [comment]
> Hey there, @ROCKET1-1 , I also had the same problem. I tried to debug the /usr/lib/waydroid/data/scripts/waydroid-net.sh. In my case, the problem was in:
> 
> ```
> 101 start_nftables() {
> 102     start_ipv6
> 103     NFT_RULESET=""
> 104     if [ -n "$LXC_IPV6_ARG" ] && [ "$LXC_IPV6_NAT" = "true" ]; then
> 105         NFT_RULESET="${NFT_RULESET}
> 106 add table ip6 lxc;
> 107 flush table ip6 lxc;
> 108 add chain ip6 lxc postrouting { type nat hook postrouting priority 100; };
> 109 add rule ip6 lxc postrouting ip saddr ${LXC_IPV6_NETWORK} ip daddr != ${LXC_IPV6_NETWORK} counter masquerade;
> 110 "
> 111     fi
> 112     NFT_RULESET="${NFT_RULESET};
> 113 add table inet lxc;
> 114 flush table inet lxc;
> 115 add chain inet lxc input { type filter hook input priority 0; };
> 116 add rule inet lxc input iifname ${LXC_BRIDGE} udp dport { 53, 67 } accept;
> 117 add rule inet lxc input iifname ${LXC_BRIDGE} tcp dport { 53, 67 } accept;
> 118 add chain inet lxc forward { type filter hook forward priority 0; };
> 119 add rule inet lxc forward iifname ${LXC_BRIDGE} accept;
> 120 add rule inet lxc forward oifname ${LXC_BRIDGE} accept;
> 121 add table ip lxc;
> 122 flush table ip lxc;
> 123 add chain ip lxc postrouting { type nat hook postrouting priority 100; };
> 124 add rule ip lxc postrouting ip saddr ${LXC_NETWORK} ip daddr != ${LXC_NETWORK} counter masquerade"
> 125     nft "${NFT_RULESET}"
> 126 }
> ```
> 
> Where at line 124 remove the masquerade. It might have something to do with a dnsmasq syntax update but since I am no expert I am not sure. After that just normally do: `waydroid session start`
> 
> and it should work as normal

 Hey, did as you wrote, but the error is still the same. 
If I'm not mistaken it should look like this?

start_nftables() {
    start_ipv6
    NFT_RULESET=""
    if [ -n "$LXC_IPV6_ARG" ] && [ "$LXC_IPV6_NAT" = "true" ]; then
        NFT_RULESET="${NFT_RULESET}
add table ip6 lxc;
flush table ip6 lxc;
add chain ip6 lxc postrouting { type nat hook postrouting priority 100; };
add rule ip6 lxc postrouting ip saddr ${LXC_IPV6_NETWORK} ip daddr != ${LXC_IPV6_NETWORK} counter masquerade;
"
    fi
    NFT_RULESET="${NFT_RULESET};
add table inet lxc;
flush table inet lxc;
add chain inet lxc input { type filter hook input priority 0; };
add rule inet lxc input iifname ${LXC_BRIDGE} udp dport { 53, 67 } accept;
add rule inet lxc input iifname ${LXC_BRIDGE} tcp dport { 53, 67 } accept;
add chain inet lxc forward { type filter hook forward priority 0; };
add rule inet lxc forward iifname ${LXC_BRIDGE} accept;
add rule inet lxc forward oifname ${LXC_BRIDGE} accept;
add table ip lxc;
flush table ip lxc;
add chain ip lxc postrouting { type nat hook postrouting priority 100; };
add rule ip lxc postrouting ip saddr ${LXC_NETWORK} ip daddr != ${LXC_NETWORK} counter" ##masquerade
    nft "${NFT_RULESET}"
}

After changing the container restarted

**Comment by ROCKET1-1** [comment]
vnic is waydroid0
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.


> Хм странно. Может быть, вы могли бы попробовать отладить его. Что я сделал, так это распечатал NFT_RULESET до того, как он будет применен с помощью команды nft. Итак, перед nft "${NFT_RULESET}" добавьте: `echo $NFT_RULESET` и для того, чтобы его вывод отображался, вам нужно будет запустить сценарий waydroid сам по себе, вместо использования запуска сеанса waydroid, например: Вы `sudo /usr/lib/waydroid/data/scripts/waydroid-net.sh start` можете получить вывод похож на мой: `; add table inet lxc; flush table inet lxc; add chain inet lxc input { type filter hook input priority 0; }; add rule inet lxc input iifname waydroid0 udp dport { 53, 67 } accept; add rule inet lxc input iifname waydroid0 tcp dport { 53, 67 } accept; add chain inet lxc forward { type filter hook forward priority 0; }; add rule inet lxc forward iifname waydroid0 accept; add rule inet lxc forward oifname waydroid0 accept; add table ip lxc; flush table ip lxc; add chain ip lxc postrouting { type nat hook postrouting priority 100; }; add rule ip lxc postrouting ip saddr 192.168.240.0/24 ip daddr != 192.168.240.0/24 counter`
> 
> и в своем терминале вы можете либо скопировать и вставить все это, либо запустить: `sudo nft "<PASTE NFT HERE>"` или, поскольку команда огромна, и вы можете не понять, где именно ошибка, запускайте команды nft одну за другой, с полустолбцом в качестве разделителя. (данный пример, замените своим собственным выводом $ NFT_RULESET) `sudo nft "add table inet lxc;"` `sudo nft " flush table inet lxc;"`
> 
> и так далее, пока не найдете виновника. Это также может быть другая часть сценария, но если вы действительно получаете: `Error: Could not process rule: No such file or directory ; ^^^^^^^^^^ Failed to setup waydroid-net.` Тогда это решение может решить проблему или, по крайней мере, указать вам направление.
> 
> Чтобы сбросить наборы правил nft, вы можете просто использовать: `waydroid session stop`

vnic is waydroid0
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: Bad rule (does a matching rule exist in that chain?).
iptables: No chain/target/match by that name.
iptables: No chain/target/match by that name.

**Comment by WORMSTweaker** [comment]
As of August 2023, this issue is still not resolved, what would be the solution? What changed in nftables for the `masquerade` keyword to break?

**Comment by HEIlZMaker** [comment]
I am also getting this issue. bookworm 12 
I run the command "waydroid app launch"
Command failed: % /usr/lib/waydroid/data/scripts/waydroid-net.sh start

**Comment by Everspace** [comment]
I am running into what seems to be this problem as well now (October 2025)

- Arch Linux 6.12.51-1-lts
- Plasma 6.4.5

waydroid log produces just the following:
```
(258135) [13:15:14] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
Error: Unknown device type.
Failed to setup waydroid-net.
```

This was after running the workaround mentioned from https://github.com/waydroid/waydroid/issues/2023

I do have containerd/docker existant as well.

**Comment by park72936** [comment]
я слаб пока;)
