### ISSUE TITLE
Unspecified DBus requirement?

### ISSUE THREAD

**Issue by andraxin** [waydroid/waydroid#915]
**Describe the bug**

Waydroid doesn't appear to function without a `dbus` Python module.
```console
$ waydroid --help
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus'
```

I _could_ probably just `pip install dbus`, but my system does *not* have
DBus _at all_; so, chances are doing so wouldn't help, anyway.

**Screenshots**
Not applicable.  The thing cannot even print its help message without DBus, it seems.

**General information (please complete the following information):**
 - Waydroid tools Version `1.4.0` (that's based on the Gentoo ebuild, the command fails with `--version` the same way)
 - Waydroid Images Version `None` (AFAIK)

**Desktop (please complete the following information):**
 - OS: Gentoo
 - GPU: `NVIDIA Corporation GA104M [GeForce RTX 3080 Mobile / Max-Q 8GB/16GB]`
 - Kernel version: `6.3.3-gentoo`
 - Host mesa version: `23.1.0`
 - Desktop: Sway 1.7

**Smartphone (please complete the following information):**
There's no smartphone involved here.

**Additional context**
Not aware of any additional context that may be relevant,
other that not all systems have DBus (for good reason);
so, relying on DBus sounds like a bad idea in general;
and totally weird on Wayland, which has its own IPC...

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`. In case that doesn't exist, use `/var/lib/waydroid/waydroid_base.prop` instead
 - Log file, located at `/var/lib/waydroid/waydroid.log`
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running
 - Output of `dmesg`

**None of those files listed above exist, nor is there any mention of Waydroid in `dmesg` output...**

**Comment by andraxin** [comment]
Having installed `dbus-python`, I can get the help message, but the situation is worse then I had thought.
```console
$ waydroid init
[01:51:18] ERROR: Action "init" needs root access
[01:51:18] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.
```

I guess, I'll just have to run this thing in Docker or a VM.
We'll see just how badly that affects performance
with nested containerizaiton/virtualization layers,
if it even works at all...

**Comment by HanoJing** [comment]
> Having installed `dbus-python`, I can get the help message, but the situation is worse then I had thought.
> 
> ```
> $ waydroid init
> [01:51:18] ERROR: Action "init" needs root access
> [01:51:18] See also: <https://github.com/waydroid>
> Run 'waydroid log' for details.
> ```
> 
> I guess, I'll just have to run this thing in Docker or a VM. We'll see just how badly that affects performance with nested containerizaiton/virtualization layers, if it even works at all...

I had the very same issue in #780. I can completely understand if you don't want to use dbus. Does your system support dbus though?

**Comment by 20121988** [comment]
C:\home\linux> waydroid          
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib
ModuleNotFoundError: No module named 'dbus.mainloop'

**Comment by coolst3r** [comment]
Traceback (most recent call last):
  File "/usr/bin/waydroid", line 6, in <module>
    import tools
  File "/usr/lib/waydroid/tools/__init__.py", line 8, in <module>
    import dbus.mainloop.glib

**Comment by coolst3r** [comment]
fixed it for me by deactivating my conda

**Comment by andraxin** [comment]
> > Having installed `dbus-python`, I can get the help message, but the situation is worse then I had thought.
> > ```
> > $ waydroid init
> > [01:51:18] ERROR: Action "init" needs root access
> > [01:51:18] See also: <https://github.com/waydroid>
> > Run 'waydroid log' for details.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I guess, I'll just have to run this thing in Docker or a VM. We'll see just how badly that affects performance with nested containerizaiton/virtualization layers, if it even works at all...
> 
> I had the very same issue in #780. I can completely understand if you don't want to use dbus. Does your system support dbus though?

I apologize for not having responded, but the answer is right there in the original issue:
> I could probably just pip install dbus-python, but my system does not have DBus
> at all; so, chances are doing so wouldn't help, anyway.

Of course, the nuance of "have" vs "support" might need consideration.
Yes, I _could_ install DBus, but I've been trying to keep my system junk-free,
and waydroid just isn't important enough to change that.

**Comment by RealYukiSan** [comment]
in my case, this error resolved by deactivate current virtual environment on [waydroid script](https://github.com/casualsnek/waydroid_script)

**Comment by agilgur5** [comment]
> * OS: Gentoo

Not sure about Gentoo, but [the Arch package](https://aur.archlinux.org/packages/waydroid) does specify `python-dbus` as a dependency. The [Debian package does too](https://github.com/waydroid/waydroid/blob/023c4e31e06e2a31110a346516a841e68063d473/debian/control#L21) afaict

**Comment by epicmet** [comment]
I had the same issue and it was because of a mismatch installation in python version

```sh
$ head -n 1 `which waydroid`
#!/usr/bin/env python3

$ python3 --version
Python 3.13.11

$ pacman -Ql python-dbus | grep site-packages | head -n 1
python-dbus /usr/lib/python3.14/site-packages/
```

Updating my packages using `pacman -Syyu` (i.e. installing python v3.14.x) fixed the issue for me.
