### ISSUE TITLE
`waydroid init` wrongly says LXC is not installed (debian bookworm/sid)

### ISSUE THREAD

**Issue by m-ar-c** [waydroid/waydroid#92]
Hello,

I know the documentation says only bullseye is supported but I tried to install it on sid anyway. This error looks like an easy resolvable one so I thought I should report it. Fell free to close if you want.

So, I followed the [documentation](https://docs.waydro.id/usage/install-on-desktops), and at the `waydroid init` step it gives the error `ERROR: LXC is not installed`. I can do `systemctl start waydroid-container`, it exits with no errors, but then when I launch `waydroid show-full-ui` it shows `[12:10:23] Starting waydroid session` but nothing happens then (no waydroid ui, no cpu usage detected from a waydroid related, etc...)

```
# whereis lxc
lxc: /snap/bin/lxc
```

```
# lxc --version
4.18
```

```
# cat /etc/debian_version 
bookworm/sid
```
```
# waydroid log
(282653) [12:03:01] Save config: /var/lib/waydroid/waydroid.cfg
(282653) [12:03:01] Download https://sourceforge.net/projects/waydroid/files/images/system/lineage/waydroid_x86_64/lineage-17.1-20210925-VANILLA-waydroid_x86_64-system.zip/download
(282653) [12:06:15] Validating system image
(282653) [12:06:18] Extracting to /var/lib/waydroid/images
(282653) [12:06:36] Save config: /var/lib/waydroid/waydroid.cfg
(282653) [12:06:37] Download https://sourceforge.net/projects/waydroid/files/images/vendor/waydroid_x86_64/lineage-17.1-20210925-MAINLINE-waydroid_x86_64-vendor.zip/download
(282653) [12:07:10] Validating vendor image
(282653) [12:07:10] Extracting to /var/lib/waydroid/images
(282653) [12:07:14] Save config: /var/lib/waydroid/waydroid.cfg
(282653) [12:07:14] ERROR: LXC is not installed
(282653) [12:07:14] See also: <https://github.com/waydroid>
(282653) [12:07:14] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 49, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 98, in init
    helpers.lxc.set_lxc_config(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 118, in set_lxc_config
    raise OSError("LXC is not installed")
OSError: LXC is not installed

(283329) [12:07:35] Already initialized
(283501) [12:08:53] ERROR: [Errno 2] No such file or directory: 'lxc-info'
(283501) [12:08:53] See also: <https://github.com/waydroid>
(283501) [12:08:53] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 87, in start
    status = helpers.lxc.status(args)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 247, in status
    return subprocess.run(command, stdout=subprocess.PIPE).stdout.decode('utf-8').strip()
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'lxc-info'
```

**Comment by Sunderland93** [comment]
Does it works with LXC from Debian packages?

**Comment by m-ar-c** [comment]
Yes, it did work after `apt install lxc`.
