### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted: '/var/lib/waydroid/waydroid.prop' on startup

### ISSUE THREAD

**Issue by Takashiidobe** [waydroid/waydroid#924]
**Describe the bug**
When I run `waydroid show-full-ui`, I get this error: `PermissionError: [Errno 1] Operation not permitted: '/var/lib/waydroid/waydroid.prop'. 

For context, when I first setup waydroid, I got this error, then I fiddled with the config to allow for ARM64 emulation (I'm on an x86_64 desktop), and I think I reinstalled waydroid (`sudo dnf remove waydroid && sudo dnf install waydroid`), and fiddled with configuration and it started working. After that, I restarted my computer, and waydroid stopped working.

**Screenshots**

**General information (please complete the following information):**
 - Waydroid tools Version: 1.4.1
 - Waydroid Images Version, or `system_datetime`/`vendor_datetime`: system_datetime=0, vendor_datetime=0, I'm using the most recent android 11 lineageos 18 images, since I installed a few days ago.

**Desktop (please complete the following information):**
 - OS: Fedora 38, x86_64
 - GPU: Intel Iris Xe
 - Kernel version: `$ uname -a
Linux fedora 6.2.14-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Mon May  1 00:55:28 UTC 2023 x86_64 GNU/Linux`
 - Host mesa version: `OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.0.3`
 - Desktop: Gnome 44.0

**Additional context**
Since `waydroid` used to work before I restarted, I assume there's nothing wrong with the setup, images, etc, but that I fiddled with configuration and didn't persist it to allow it to survive a restart. I tried reinstalling waydroid, but I still get the same issue.
When I run `waydroid show-full-ui` (or session start, etc) to start a shell, in `waydroid log`, this shows up:

```
(014895) [10:00:51] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
vnic is waydroid0
waydroid-net is already running
(014895) [10:00:51] % chmod 777 -R /dev/dri
(014895) [10:00:51] % chmod 777 -R /dev/fb0
(014895) [10:00:51] % chmod 777 -R /dev/video1
(014895) [10:00:51] % chmod 777 -R /dev/video0
(014895) [10:00:51] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(014895) [10:00:51] % umount /var/lib/waydroid/rootfs/vendor
(014895) [10:00:51] % umount /var/lib/waydroid/rootfs/vendor
(014895) [10:00:51] % umount /var/lib/waydroid/rootfs
(014895) [10:00:51] % umount /var/lib/waydroid/rootfs
(014895) [10:00:51] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /usr/share/waydroid-extra/images/system.img /var/lib/waydroid/rootfs
(014895) [10:00:51] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay:/var/lib/waydroid/rootfs,upperdir=/var/lib/waydroid/overlay_rw/system,workdir=/var/lib/waydroid/overlay_work/system,xino=off overlay /var/lib/waydroid/rootfs
(014895) [10:00:51] % mount -o context="system_u:object_r:waydroid_rootfs_t:s0",ro /usr/share/waydroid-extra/images/vendor.img /var/lib/waydroid/rootfs/vendor
(014895) [10:00:51] % mount -t overlay -o context="system_u:object_r:waydroid_rootfs_t:s0",ro,lowerdir=/var/lib/waydroid/overlay/vendor:/var/lib/waydroid/rootfs/vendor,upperdir=/var/lib/waydroid/overlay_rw/vendor,workdir=/var/lib/waydroid/overlay_work/vendor,xino=off overlay /var/lib/waydroid/rootfs/vendor
(015240) [10:00:51] org.freedesktop.DBus.Python.PermissionError: Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 174, in do_start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"], session)
  File "/usr/lib/waydroid/tools/helpers/images.py", line 178, in mount_rootfs
    make_prop(args, session, args.work + "/waydroid.prop")
  File "/usr/lib/waydroid/tools/helpers/images.py", line 139, in make_prop
    os.chmod(full_props_path, 0o644)
PermissionError: [Errno 1] Operation not permitted: '/var/lib/waydroid/waydroid.prop'

(015240) [10:00:51] PermissionError: [Errno 1] Operation not permitted: '/var/lib/waydroid/waydroid.prop'
```

So it seems like I can't alter `/var/lib/waydroid/waydroid.prop` to `0o644`. Here's the output of `ls -l` for `/var/lib/waydroid`:
(The .txt files are for uploading to this issue)

```
ls -l
total 1180
drwxr-xr-x. 1 takashi takashi    342 May 24 10:04 .
drwxr-xr-x. 1 root    root      1048 May 21 20:09 ..
drwxr-xr-x. 1 takashi takashi    242 May 20 20:51 cache_http
-rw-r--r--. 1 takashi takashi 101558 May 24 10:04 dmesg.log.txt
drwxr-xr-x. 1 takashi takashi      0 May 20 20:51 host-permissions
drwxr-xr-x. 1 takashi takashi     40 May 21 16:58 images
drwxr-xr-x. 1 takashi takashi     16 May 20 20:51 lxc
drwxr-xr-x. 1 takashi takashi     24 May 21 18:26 overlay
drwxr-xr-x. 1 root    root        24 May 24 08:30 overlay_rw
drwxr-xr-x. 1 root    root        24 May 24 08:31 overlay_work
drwxr-xr-x. 1 root    root         0 May 20 20:51 rootfs
-rw-r--r--. 1 takashi takashi    527 May 24 09:59 waydroid_base.prop
-rw-r--r--. 1 takashi takashi    643 May 24 08:30 waydroid.cfg
-rw-rw-rw-. 1 takashi takashi 541619 May 24 10:05 waydroid.log
-rw-r--r--. 1 takashi takashi 540926 May 24 10:02 waydroid.log.txt
-rw-r--r--. 1 takashi takashi    849 May 24 10:00 waydroid.prop
-rw-r--r--. 1 takashi takashi    849 May 24 10:03 waydroid.prop.txt
```

**Logs (please upload as file)**
 - Prop file: [waydroid.prop.txt](https://github.com/waydroid/waydroid/files/11555437/waydroid.prop.txt)
 - Log File: [waydroid.log.txt](https://github.com/waydroid/waydroid/files/11555428/waydroid.log.txt)
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running: Waydroid doesn't start, so I don't get any logs.
 ```sh
$ sudo waydroid logcat
[10:04:05] WayDroid container is STOPPED
```
 - Output of `dmesg`:  [dmesg.log.txt](https://github.com/waydroid/waydroid/files/11555449/dmesg.log.txt)

Thanks in advance :bow:

**Comment by Takashiidobe** [comment]
I chown -R'd the /var/lib/waydroid dir, so root must not have the correct permissions. Re initing waydroid with `waydroid init` fixes the issue after `rm -rf`ing `/var/lib/waydroid`. 

lesson learned: chown is hard to undo
