### ISSUE TITLE
I can't configure a screen lock

### ISSUE THREAD

**Issue by giraudan** [waydroid/waydroid#956]
**Describe the bug**
I can't configure a screen lock. Only `None` and `Swipe` seem to work. `Pattern`, `PIN` and `Password` allow me to configure them but then, it just reverts back to either `None` or `Swipe`.

**Screenshots**
[Video recording of the issue](https://github.com/waydroid/waydroid/assets/45098592/1b7ef220-06fc-42c1-9cf4-573ca1884e17).

**General information (please complete the following information):**
 - Waydroid tools Version: 1.4.1
 - Waydroid Images Version: waydroid-image-gapps 18.1_20230422-1
 - `system_datetime`/`vendor_datetime` from `/var/lib/waydroid/waydroid.cfg`: 0 and 0

**Desktop (please complete the following information):**
 - OS: Archlinux
 - GPU: AMD Ryzen 9 5900HS with Radeon Graphics + NVIDIA GeForce RTX 3050 Ti Laptop GPU
 - Kernel version: 6.3.7-zen
 - Host mesa version: 23.1.2
 - Desktop: sway

**Smartphone (please complete the following information):** none

**Additional context**
I need it because a feature of an application I use requires that I configure the device lock.

**Logs (please upload as file)**
 - Prop file, located at `/var/lib/waydroid/waydroid.prop`.
 ```
sys.use_memfd=true
debug.stagefright.ccodec=0
ro.hardware.gralloc=gbm
ro.hardware.egl=mesa
ro.hardware.vulkan=radeon
ro.hardware.camera=v4l2
ro.opengles.version=196609
waydroid.updater.disabled=true
waydroid.tools_version=1.3.4
ro.vndk.lite=true
waydroid.host.user=giraudan
waydroid.host.uid=1000
waydroid.host.gid=1000
waydroid.host_data_path=/home/giraudan/.local/share/waydroid/data
waydroid.xdg_runtime_dir=/run/user/1000
waydroid.pulse_runtime_path=/run/user/1000/pulse
waydroid.wayland_display=wayland-1
waydroid.background_start=true
waydroid.stub_sensors_hal=1
```
 - Log file, located at `/var/lib/waydroid/waydroid.log`: [gist](https://gist.github.com/giraudan/887f379f35e31526b5cde2ac5282cb60)
 - *Full* (not partial) output of `waydroid logcat` while Waydroid is running: [gist](https://gist.github.com/giraudan/1375a2b6cccd50fb7d5ca90c1859623c)
 - Output of `dmesg`: [gist](https://gist.github.com/giraudan/4f4294e07a51607ed4c1c0f9a490f1a3)

**Comment by priosshrsth** [comment]
I am having exact same issue as well.

**Comment by tomichec** [comment]
I'm having the same issue too. I wouldn't mind not having the lock, but some apps (banking) actually require it to be configured. So, a possible workaround would be to trick those apps into believing that the screen lock is actually enabled.

**Comment by tomichec** [comment]
This issue is likely to be related to https://github.com/waydroid/waydroid/issues/861

**Comment by IslamMohammedSalama** [comment]
[Screencast from 06-16-2024 09:05:30 AM.webm](https://github.com/waydroid/waydroid/assets/138365657/038f82d0-c091-42a9-9b82-583c41036045)
I Have The Same Issue

**Comment by vnaz** [comment]
waydroid:/ # locksettings set-pin 1234                                                                                                                                  
Error while executing command: set-pin
java.lang.IllegalStateException: Fail to enroll user password when creating SP for user 0
	at com.android.server.locksettings.SyntheticPasswordManager.createPasswordBasedSyntheticPassword(SyntheticPasswordManager.java:779)
	at com.android.server.locksettings.LockSettingsService.initializeSyntheticPasswordLocked(LockSettingsService.java:2688)
	at com.android.server.locksettings.LockSettingsService.setLockCredentialInternal(LockSettingsService.java:1741)
	at com.android.server.locksettings.LockSettingsService.setLockCredential(LockSettingsService.java:1663)
	at com.android.internal.widget.LockPatternUtils.setLockCredential(LockPatternUtils.java:660)
	at com.android.server.locksettings.LockSettingsShellCommand.runSetPin(LockSettingsShellCommand.java:258)
	at com.android.server.locksettings.LockSettingsShellCommand.onCommand(LockSettingsShellCommand.java:101)
	at android.os.BasicShellCommandHandler.exec(BasicShellCommandHandler.java:98)
	at android.os.ShellCommand.exec(ShellCommand.java:44)
	at com.android.server.locksettings.LockSettingsService.onShellCommand(LockSettingsService.java:2426)
	at android.os.Binder.shellCommand(Binder.java:929)
	at android.os.Binder.onTransact(Binder.java:813)
	at com.android.internal.widget.ILockSettings$Stub.onTransact(ILockSettings.java:1031)
	at android.os.Binder.execTransactInternal(Binder.java:1154)
	at android.os.Binder.execTransact(Binder.java:1123)

**Comment by gbraad** [comment]
This is necessary to allow passkeys to work.

**Comment by g6094199** [comment]
> This is necessary to allow passkeys to work.

and banking apps

**Comment by DavidFirefox** [comment]
@https://github.com/waydroid/waydroid/issues/861

**Comment by DavidFirefox** [comment]
#861

**Comment by DavidFirefox** [comment]
Hi,
This is link to #861 
Maybe it is disable, by Waydroid. As they have disable Trust : [https://github.com/waydroid/android_vendor_waydroid/commit/9ad786f85f30ffa5286d2d7379052c59be7c3d04](waydroid-patches: Disable trust)
I try to find who, but I don't find.

On Telegram channel Jami say : 
"that's the whole problem, you cannot. any secure option is patched to be broken in waydroid system images somewhere in https://github.com/waydroid/android_vendor_waydroid/tree/lineage-18.1/waydroid-patches/base-patches-30, trying to set one if you find the option just returns it immediately back to None/Swipe whichever you may have selected"

If anybody find more information I'd like to have it :)

**Comment by aleasto** [comment]
Fixed in fe7998d8a57875bdac9ecf763150dba0f831fccb

**Comment by benmahler** [comment]
@aleasto I'm keen to try out this fix but commit https://github.com/waydroid/waydroid/commit/fe7998d8a57875bdac9ecf763150dba0f831fccb does not exist publicly yet. The official repo has no commits since two weeks ago, and you closed this as completed last week.

How do I get access to these commits? Do I have to be an employee of Bliss Labs?

**Comment by aleasto** [comment]
Waydroid will have shown you an Android notification prompting to update. Or you can manually invoke it with `sudo waydroid upgrade`.

Commit https://github.com/waydroid/android_hardware_waydroid/commit/fe7998d8a57875bdac9ecf763150dba0f831fccb belongs to waydroid/android_hardware_waydroid, I hadn't linked it properly.

**Comment by benmahler** [comment]
@aleasto it's amazing how fast your team are bringing out these releases. I see, I had checked a few of the repos in waydroid org, but had not checked android_hardware_waydroid. Confirmed I have this upgrade, works great!
