### ISSUE TITLE
I am unable to run "wydroid init" .. 

### ISSUE THREAD

**Issue by Goblin-me** [waydroid/waydroid#960]
[18:09:26] Failed to load binder driver
[18:09:26] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/6.1.34-1-lts
[18:09:26] ERROR: Binder node "binder" for waydroid not found
[18:09:26] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.

**Comment by cniw** [comment]
**Kernel issue**: your LTS kernel don't have required modules to run Waydroid

Since you didn't share details about your system yet, i just guess you're using archlinux, so just install linux-zen kernel
```bash
sudo pacman -S linux-zen{,-headers}
sudo grub-mkconfig -o /boot/grub/grub.cfg
```
Read more https://wiki.archlinux.org/title/Waydroid#Kernel_Modules

**Comment by thepro-3418** [comment]
a similar issue with me:[11:46:44] Failed to load binder driver
[11:46:44] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.90.1-microsoft-standard-WSL2
[11:46:44] ERROR: Binder node "binder" for waydroid not found
[11:46:44] See also: <https://github.com/waydroid>
Run 'waydroid log' for details.

**Comment by thepro-3418** [comment]
> a similar issue with me:[11:46:44] Failed to load binder driver [11:46:44] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.90.1-microsoft-standard-WSL2 [11:46:44] ERROR: Binder node "binder" for waydroid not found [11:46:44] See also: https://github.com/waydroid Run 'waydroid log' for details.

info
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/lib/systemd/system/waydroid-container.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2023-06-20 12:02:47 IST; 2min 13s ago
   Main PID: 10745 (waydroid)
      Tasks: 1 (limit: 4637)
     Memory: 13.1M
     CGroup: /system.slice/waydroid-container.service
             └─10745 /usr/bin/python3 /usr/bin/waydroid -w container start

Jun 20 12:02:46 HPWindows11Laptop systemd[1]: Starting Waydroid Container...
Jun 20 12:02:47 HPWindows11Laptop systemd[1]: Started Waydroid Container.

(010744) [12:02:52] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.90.1-microsoft-standard-WSL2
(010744) [12:02:52] Failed to load binder driver
(010744) [12:02:52] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.90.1-microsoft-standard-WSL2
(010744) [12:02:52] ERROR: Binder node "binder" for waydroid not found
(010744) [12:02:52] See also: <https://github.com/waydroid>
(010744) [12:02:52] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 97, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(010747) [12:03:08] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.90.1-microsoft-standard-WSL2
(010747) [12:03:08] Failed to load binder driver
(010747) [12:03:08] modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.90.1-microsoft-standard-WSL2
(010747) [12:03:08] ERROR: Binder node "binder" for waydroid not found
(010747) [12:03:08] See also: <https://github.com/waydroid>
(010747) [12:03:09] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 97, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found

(010759) [12:06:24] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(010759) [12:06:24] *** output passed to waydroid stdout, not to this log ***

# Android
# CONFIG_ANDROID is not set
# end of Android
CONFIG_MEMFD_CREATE=y

Linux HPWindows11Laptop 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

**Comment by zyxhere** [comment]
Duplicate of https://github.com/waydroid/waydroid/issues/801
