### ISSUE TITLE
waydroid unable start session.   os: fedora 38

### ISSUE THREAD

**Issue by fyangami** [waydroid/waydroid#970]
^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 20, in get_lxc_version
    return int(version_str[0])
           ^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '['

(026894) [17:01:50] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(026894) [17:01:50] *** output passed to waydroid stdout, not to this log ***
(026975) [17:02:47] org.freedesktop.DBus.Error.UnknownMethod: Method "Start" with signature "a{ss}" on interface "id.waydro.ContainerManager" doesn't exist

(026975) [17:02:47] WayDroid container is not listening
(027022) [17:03:32] Starting waydroid session
(027022) [17:03:32] org.freedesktop.DBus.Error.UnknownMethod: Method "Start" with signature "a{ss}" on interface "id.waydro.ContainerManager" doesn't exist

(027022) [17:03:32] WayDroid container is not listening
(027094) [17:03:47] % lxc-info -P /var/lib/waydroid/lxc -n waydroid -sH
waydroid doesn't exist
(027094) [17:03:47] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(027094) [17:03:47] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(027094) [17:03:47] Couldn't get LXC status. Assuming STOPPED.
(027094) [17:03:47] % modprobe -q ashmem_linux
(027094) [17:03:47] % chmod 666 -R /dev/binder
(027094) [17:03:47] % chmod 666 -R /dev/vndbinder
(027094) [17:03:47] % chmod 666 -R /dev/hwbinder
(027094) [17:04:13] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
awk: fatal: cannot open file `/var/lib/waydroid/lxc/waydroid/config' for reading: No such file or directory
vnic is waydroid0
success
(027094) [17:04:14] % chmod 777 -R /dev/dri
(027094) [17:04:14] % chmod 777 -R /dev/fb0
(027094) [17:04:14] % chmod 777 -R /dev/video3
(027094) [17:04:14] % chmod 777 -R /dev/video2
(027094) [17:04:14] % chmod 777 -R /dev/video1
(027094) [17:04:14] % chmod 777 -R /dev/video0
(027094) [17:04:14] % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
mv: cannot move '/var/lib/waydroid/config_session' to '/var/lib/waydroid/lxc/waydroid': No such file or directory
(027094) [17:04:14] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(027094) [17:04:14] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(027196) [17:04:14] org.freedesktop.DBus.Python.RuntimeError: Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 34, in Start
    do_start(self.args, session)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 165, in do_start
    helpers.lxc.generate_session_lxc_config(args, session)
  File "/usr/lib/waydroid/tools/helpers/lxc.py", line 214, in generate_session_lxc_config
    tools.helpers.run.user(args, command)
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid

(027196) [17:04:14] RuntimeError: Command failed: % mv /var/lib/waydroid/config_session /var/lib/waydroid/lxc/waydroid
(027289) [17:04:23] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(027289) [17:04:23] *** output passed to waydroid stdout, not to this log ***

**Comment by Cpt11** [comment]
ls

**Comment by zyxhere** [comment]
Does this still occur in fedora 39/40?
