### ISSUE TITLE
Container manager is waiting for session to load; container failed to start

### ISSUE THREAD

**Issue by AdnanHodzic** [waydroid/waydroid#99]
I follow [official How to install guide](https://waydro.id/#howto) and although I'm running Ubuntu 21.10 (Impish Indri) I have to use Ubuntu 21.04 codename during (Hirsute Hippo), i.e:

```
export DISTRO="hirsute"
```

since `impish` deb repo doesn't exist yet, i.e:

`deb [signed-by=/usr/share/keyrings/waydroid.gpg] https://repo.waydro.id/ impish main`.

Regardless, rest of the install process goes fine and `waydroid-container` service starts fine:

```
ahodzic@carbon7 ~$ sudo systemctl status waydroid-container
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/lib/systemd/system/waydroid-container.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-09-26 09:09:30 CEST; 50s ago
   Main PID: 68418 (waydroid)
      Tasks: 1 (limit: 18731)
     Memory: 11.6M
     CGroup: /system.slice/waydroid-container.service
             └─68418 /usr/bin/python3 /usr/bin/waydroid container start
```

However after I run: `sudo waydroid container start` log (`waydroid log`) seems to be stuck on:

```
(068732) [09:10:00] % tail -n 60 -F /var/lib/waydroid/waydroid.log
(068732) [09:10:00] *** output passed to waydroid stdout, not to this log ***
(068876) [09:10:25] % chmod 666 -R /dev/anbox-binder
(068876) [09:10:25] % chmod 666 -R /dev/anbox-vndbinder
(068876) [09:10:25] % chmod 666 -R /dev/anbox-hwbinder
(068876) [09:10:25] Container manager is waiting for session to load
```

After I run `waydroid session start` following will happen:

```
071677) [09:18:47] Save session config: /var/lib/waydroid/session.cfg
(071677) [09:18:47] UserMonitor service is not even started
(071677) [09:18:47] Clipboard service is not even started
(068876) [09:18:48] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
waydroid-net is already running
(068876) [09:18:48] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(068876) [09:18:48] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(068876) [09:18:48] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(068876) [09:18:48] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(068876) [09:18:48] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(068876) [09:18:48] % chmod 777 -R /dev/ashmem
(068876) [09:18:48] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
(068876) [09:18:48] % chmod 777 -R /dev/dri
(068876) [09:18:48] % chmod 777 -R /dev/fb0
(068876) [09:18:48] % chmod 777 -R /dev/video3
(068876) [09:18:48] % chmod 777 -R /dev/video2
(068876) [09:18:48] % chmod 777 -R /dev/video1
(068876) [09:18:48] % chmod 777 -R /dev/video0
(068876) [09:18:48] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(068876) [09:18:48] New background process: pid=71714, output=background
(068418) [09:18:48] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
lxc-start: waydroid: conf.c: turn_into_dependent_mounts: 3858 No such file or directory - Failed to recursively turn old root mount tree into dependent mount. Continuing...
waydroid-net is already running
(068418) [09:18:48] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(068418) [09:18:48] % umount /var/lib/waydroid/rootfs/vendor
lxc-start: waydroid: utils.c: safe_mount: 1198 No such file or directory - Failed to mount "/var/lib/waydroid/data" onto "/usr/lib/x86_64-linux-gnu/lxc/data"
lxc-start: waydroid: conf.c: mount_entry: 2379 No such file or directory - Failed to mount "/var/lib/waydroid/data" on "/usr/lib/x86_64-linux-gnu/lxc/data"
lxc-start: waydroid: conf.c: lxc_setup: 4301 Failed to setup mount entries
lxc-start: waydroid: start.c: do_start: 1286 Failed to setup container "waydroid"
lxc-start: waydroid: sync.c: sync_wait: 36 An error occurred in another process (expected sequence number 3)
lxc-start: waydroid: start.c: __lxc_start: 2054 Failed to spawn container "waydroid"
(068418) [09:18:48] % umount /var/lib/waydroid/rootfs
(068418) [09:18:48] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(068876) [09:18:48] waiting 10 seconds for container to start...
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 991 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
(068418) [09:18:48] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(068418) [09:18:48] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(068418) [09:18:48] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(068418) [09:18:48] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(068418) [09:18:48] % chmod 777 -R /dev/ashmem
(068418) [09:18:48] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
(068418) [09:18:48] % chmod 777 -R /dev/dri
(068418) [09:18:48] % chmod 777 -R /dev/fb0
(068418) [09:18:48] % chmod 777 -R /dev/video3
(068418) [09:18:48] % chmod 777 -R /dev/video2
(068418) [09:18:48] % chmod 777 -R /dev/video1
(068418) [09:18:48] % chmod 777 -R /dev/video0
(068418) [09:18:48] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(068418) [09:18:48] New background process: pid=71765, output=background
lxc-start: waydroid: conf.c: turn_into_dependent_mounts: 3858 No such file or directory - Failed to recursively turn old root mount tree into dependent mount. Continuing...
lxc-start: waydroid: utils.c: safe_mount: 1198 No such file or directory - Failed to mount "/var/lib/waydroid/data" onto "/usr/lib/x86_64-linux-gnu/lxc/data"
lxc-start: waydroid: conf.c: mount_entry: 2379 No such file or directory - Failed to mount "/var/lib/waydroid/data" on "/usr/lib/x86_64-linux-gnu/lxc/data"
lxc-start: waydroid: conf.c: lxc_setup: 4301 Failed to setup mount entries
lxc-start: waydroid: start.c: do_start: 1286 Failed to setup container "waydroid"
lxc-start: waydroid: sync.c: sync_wait: 36 An error occurred in another process (expected sequence number 3)
lxc-start: waydroid: start.c: __lxc_start: 2054 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 991 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
(068418) [09:18:49] waiting 10 seconds for container to start...
(068876) [09:18:49] waiting 9 seconds for container to start...
(068418) [09:18:50] waiting 9 seconds for container to start...
(068876) [09:18:50] waiting 8 seconds for container to start...
(068418) [09:18:51] waiting 8 seconds for container to start...
(068876) [09:18:51] waiting 7 seconds for container to start...
(068418) [09:18:52] waiting 7 seconds for container to start...
(068876) [09:18:52] waiting 6 seconds for container to start...
(068418) [09:18:53] waiting 6 seconds for container to start...
(068876) [09:18:53] waiting 5 seconds for container to start...
(068418) [09:18:54] waiting 5 seconds for container to start...
(068876) [09:18:54] waiting 4 seconds for container to start...
(068418) [09:18:55] waiting 4 seconds for container to start...
(068876) [09:18:55] waiting 3 seconds for container to start...
(068418) [09:18:56] waiting 3 seconds for container to start...
(068876) [09:18:56] waiting 2 seconds for container to start...
(068418) [09:18:57] waiting 2 seconds for container to start...
(068876) [09:18:57] waiting 1 seconds for container to start...
(068418) [09:18:58] waiting 1 seconds for container to start...
(068876) [09:18:58] ERROR: container failed to start
(068876) [09:18:58] See also: <https://github.com/waydroid>
(068876) [09:18:58] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 160, in start
    raise OSError("container failed to start")
OSError: container failed to start

(068418) [09:18:59] ERROR: container failed to start
(068418) [09:18:59] See also: <https://github.com/waydroid>
(068418) [09:18:59] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 160, in start
    raise OSError("container failed to start")
OSError: container failed to start

(071852) [09:18:59] UserMonitor service is not even started
(071852) [09:18:59] Clipboard service is not even started
(071677) [09:19:00] UserMonitor service is not even started
(071677) [09:19:00] Clipboard service is not even started
```

Any ideas on what's going wrong here? Thanks!

**Comment by Id2ndR** [comment]
Maybe there was an error an you may unmount everything related to wayland before starting the container again. A reboot may be the easiest way to do that.

What makes me think about that is *lxc-start: waydroid: conf.c: turn_into_dependent_mounts: 3858 No such file or directory - Failed to recursively turn old root mount tree into dependent mount. Continuing...* in the log.

**Comment by AdnanHodzic** [comment]
I reboot but I pretty much ended up having the same problem:

```
(022037) [19:54:22] New background process: pid=22412, output=background
(001902) [19:54:22] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
waydroid-net is already running
(001902) [19:54:22] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(001902) [19:54:22] % umount /var/lib/waydroid/rootfs/vendor
(001902) [19:54:23] % umount /var/lib/waydroid/rootfs
(001902) [19:54:23] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
lxc-start: waydroid: conf.c: mount_entry: 2379 No such file or directory - Failed to mount "tmpfs" on "/usr/lib/x86_64-linux-gnu/lxc/mnt_extra"
lxc-start: waydroid: conf.c: lxc_setup: 4301 Failed to setup mount entries
lxc-start: waydroid: start.c: do_start: 1286 Failed to setup container "waydroid"
lxc-start: waydroid: sync.c: sync_wait: 36 An error occurred in another process (expected sequence number 3)
lxc-start: waydroid: start.c: __lxc_start: 2054 Failed to spawn container "waydroid"
mount: /var/lib/waydroid/rootfs: /dev/loop93 already mounted or mount point busy.
(001902) [19:54:23] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(001902) [19:54:23] NOTE: The failed command's output is above the ^^^ line in the log file: /var/lib/waydroid/waydroid.log
(001902) [19:54:23] ERROR: Command failed: % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(001902) [19:54:23] See also: <https://github.com/waydroid>
(022037) [19:54:23] waiting 10 seconds for container to start...
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 991 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
(001902) [19:54:23] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 130, in start
    helpers.images.mount_rootfs(args, cfg["waydroid"]["images_path"])
  File "/usr/lib/waydroid/tools/helpers/images.py", line 90, in mount_rootfs
    helpers.mount.mount(args, images_dir + "/system.img",
  File "/usr/lib/waydroid/tools/helpers/mount.py", line 131, in mount
    tools.helpers.run.user(args, ["mount", source, destination])
  File "/usr/lib/waydroid/tools/helpers/run.py", line 58, in user
    return tools.helpers.run_core.core(args, msg, cmd, working_dir, output,
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 343, in core
    check_return_code(args, code, log_message)
  File "/usr/lib/waydroid/tools/helpers/run_core.py", line 219, in check_return_code
    raise RuntimeError("Command failed: " + log_message)
RuntimeError: Command failed: % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs

(022444) [19:54:23] UserMonitor service is not even started
(022444) [19:54:23] Clipboard service is not even started
(022333) [19:54:24] UserMonitor service is not even started
(022333) [19:54:24] Clipboard service is not even started
(022037) [19:54:24] waiting 9 seconds for container to start...
(022037) [19:54:25] waiting 8 seconds for container to start...
(022037) [19:54:26] waiting 7 seconds for container to start...
(022037) [19:54:27] waiting 6 seconds for container to start...
(022037) [19:54:28] waiting 5 seconds for container to start...
(022037) [19:54:29] waiting 4 seconds for container to start...
(022037) [19:54:30] waiting 3 seconds for container to start...
(022037) [19:54:31] waiting 2 seconds for container to start...
(022037) [19:54:32] waiting 1 seconds for container to start...
(022037) [19:54:33] ERROR: container failed to start
(022037) [19:54:33] See also: <https://github.com/waydroid>
(022037) [19:54:33] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 160, in start
    raise OSError("container failed to start")
OSError: container failed to start
```

Please let me know if I can give you any additional input from my side.

**Comment by gitati16** [comment]
try `sudo echo "[General]
ApiLevel = 29" > /etc/gbinder.conf`

**Comment by AdnanHodzic** [comment]
> try `sudo echo "[General] ApiLevel = 29" > /etc/gbinder.conf`

Log looks cleaner now, but I still end up with:

```
(1634418) [05:24:03] waiting 10 seconds for container to start...
(1634418) [05:24:04] waiting 9 seconds for container to start...
(1634418) [05:24:05] waiting 8 seconds for container to start...
(1634418) [05:24:06] waiting 7 seconds for container to start...
(1634418) [05:24:07] waiting 6 seconds for container to start...
(1634418) [05:24:08] waiting 5 seconds for container to start...
(1634418) [05:24:09] waiting 4 seconds for container to start...
(1634418) [05:24:10] waiting 3 seconds for container to start...
(1634418) [05:24:11] waiting 2 seconds for container to start...
(1634418) [05:24:12] waiting 1 seconds for container to start...
(1634418) [05:24:13] ERROR: container failed to start
(1634418) [05:24:13] See also: <https://github.com/waydroid>
(1634418) [05:24:13] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 160, in start
    raise OSError("container failed to start")
OSError: container failed to start
```

**Comment by erfanoabdi** [comment]
Apparently something is wrong on mounting waydroid images:
`mount: /var/lib/waydroid/rootfs: /dev/loop93 already mounted or mount point busy.`

**Comment by AdnanHodzic** [comment]
After latest Waydroid update, it still fails but what it seems to be a different issue now:

```
(010735) [08:47:02] UserMonitor service is not even started
(010735) [08:47:02] Clipboard service is not even started
(010477) [08:47:02] UserMonitor service is not even started
(010477) [08:47:02] Clipboard service is not even started
(010914) [08:47:32] % chmod 666 -R /dev/anbox-binder
(010914) [08:47:32] % chmod 666 -R /dev/anbox-vndbinder
(010914) [08:47:32] % chmod 666 -R /dev/anbox-hwbinder
(010914) [08:47:32] Container manager is waiting for session to load
(010951) [08:47:37] Save session config: /var/lib/waydroid/session.cfg
(010951) [08:47:37] UserMonitor service is not even started
(010951) [08:47:37] Clipboard service is not even started
(010914) [08:47:37] % /usr/lib/waydroid/data/scripts/waydroid-net.sh start
waydroid-net is already running
(010914) [08:47:37] % umount /var/lib/waydroid/rootfs/vendor/waydroid.prop
(010914) [08:47:37] % umount /var/lib/waydroid/rootfs/vendor
(010914) [08:47:37] % umount /var/lib/waydroid/rootfs
(010914) [08:47:37] % mount /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(010914) [08:47:37] % mount -o remount,ro /var/lib/waydroid/images/system.img /var/lib/waydroid/rootfs
(010914) [08:47:37] % mount /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(010914) [08:47:37] % mount -o remount,ro /var/lib/waydroid/images/vendor.img /var/lib/waydroid/rootfs/vendor
(010914) [08:47:37] % mount -o bind /var/lib/waydroid/waydroid.prop /var/lib/waydroid/rootfs/vendor/waydroid.prop
(010914) [08:47:37] % chmod 777 -R /dev/ashmem
(010914) [08:47:37] % chmod 777 -R /sys/kernel/debug/sync/sw_sync
(010914) [08:47:37] % chmod 777 -R /dev/dri
(010914) [08:47:37] % chmod 777 -R /dev/fb0
(010914) [08:47:37] % chmod 777 -R /dev/video3
(010914) [08:47:37] % chmod 777 -R /dev/video2
(010914) [08:47:37] % chmod 777 -R /dev/video1
(010914) [08:47:37] % chmod 777 -R /dev/video0
(010914) [08:47:37] % lxc-start -P /var/lib/waydroid/lxc -F -n waydroid -- /init
(010914) [08:47:37] New background process: pid=10989, output=background
lxc-start: waydroid: conf.c: mount_entry: 2379 No such file or directory - Failed to mount "tmpfs" on "/usr/lib/x86_64-linux-gnu/lxc/mnt_extra"
lxc-start: waydroid: conf.c: lxc_setup: 4301 Failed to setup mount entries
lxc-start: waydroid: start.c: do_start: 1286 Failed to setup container "waydroid"
lxc-start: waydroid: sync.c: sync_wait: 36 An error occurred in another process (expected sequence number 3)
lxc-start: waydroid: start.c: __lxc_start: 2054 Failed to spawn container "waydroid"
lxc-start: waydroid: conf.c: run_buffer: 323 Script exited with status 126
lxc-start: waydroid: start.c: lxc_end: 991 Failed to run lxc.hook.post-stop for container "waydroid"
lxc-start: waydroid: tools/lxc_start.c: main: 308 The container failed to start
lxc-start: waydroid: tools/lxc_start.c: main: 313 Additional information can be obtained by setting the --logfile and --logpriority options
(010914) [08:47:37] waiting 10 seconds for container to start...
(010914) [08:47:38] waiting 9 seconds for container to start...
(010914) [08:47:39] waiting 8 seconds for container to start...
(010914) [08:47:40] waiting 7 seconds for container to start...
(010914) [08:47:41] waiting 6 seconds for container to start...
(010914) [08:47:42] waiting 5 seconds for container to start...
(010914) [08:47:43] waiting 4 seconds for container to start...
(010914) [08:47:44] waiting 3 seconds for container to start...
(010914) [08:47:45] waiting 2 seconds for container to start...
(010914) [08:47:46] waiting 1 seconds for container to start...
(010914) [08:47:47] ERROR: container failed to start
(010914) [08:47:47] See also: <https://github.com/waydroid>
(010914) [08:47:47] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 160, in start
    raise OSError("container failed to start")
OSError: container failed to start
```

**Comment by Dani9OO** [comment]
I have this same issue

**Comment by Chiffon-Pudding** [comment]
I had this same problem with an Arch Linux based distribution(Alter Linux), 
File "/usr/lib/waydroid/tools/__init__.py", line 64, in main......
but after trying different methods, it seems to have been solved.
I don't know now what caused the problem, but here is a list of the commands I tried.
1. Install "python-pyclip". I used pamac, but the command "yay -S python-pyclip" should have the same effect.
2. run the command "sudo nmcli device delete anbox0". I was using Anbox, and it seems that the network was conflicting with Waydroid because that setting was still in place.
3. Run the following commands: "sudo systemctl stop waydroid-container", "sudo waydroid upgrade", "sudo waydroid init -f", and "sudo systemctl start waydroid-container". Try to initialize again.

**Comment by Stem-LG** [comment]
same issue here on manjaro

**Comment by rizzini** [comment]
Same on Gento.. I get stuck at `Container manager is waiting for session to load`.

**Comment by aleasto** [comment]
Stale

**Comment by FinnyJokes** [comment]
I ended up using the command `waydroid session start` and it worked! It started right up!

**Comment by eusoubrasileiro** [comment]
same issue hre still
